### ISSUE TITLE
Rename mapStateToProps as mapReduxStoreToReactProps

### ISSUE THREAD

**Issue by Aarbel** [reduxjs/react-redux#1012]
I saw that learning the implementation of Redux inside React architecture is very confusing for junior developers, because it's hard for them to understand that Redux State (Store) is different from React State, and mapStateToProps speaks about "Redux State" and not "React State".

Same for Redux "State", which is often named as "Store". Could be great to clean some namings, and put "store" everywhere in reducers.

What do you think about that ? 
(feedback after hiring and managing 20 interns during 2 years)

@gaearon

**Comment by markerikson** [comment]
Dan isn't an active maintainer any more - please don't ping him.

And no, we have no plans to change the formal names of any of the API parameters at this point.  It's true that the word "state" is used in many different ways in a React+Redux app, but the name is reasonable, and widely used at this point.

Also, "Redux state" and "Redux store" are _not_ the same thing.  "state" is your _data_.  The "store" is the object that _contains_ that data.
