### ISSUE TITLE
Inheritance doesn't work?

### ISSUE THREAD

**Issue by ThomasStubbe** [reduxjs/react-redux#1014]
I know redux is opposed to inheritance. And if you have a clean solution, not using inheritance, I'll gladly accept it.

I've created a base-component: LoggedOutComponent, which checks whether the user is logged in and redirects to the logged-in part of the app (no rendering). This class is implemented by about 10 classes which must share this functionality.

But simply connecting the component doesn't work:

```
LoggedOutComponent extends Component {
  constructor(props) {
    super(props);
  }
}

const mapStateToProps = ({api}) => ({user: api.get('user')});

const mapActionsToProps = dispatch => {
  return {
    ...bindActionCreators({
        setupUser: apiActions.setupUser,
      },
      dispatch),
    dispatch,
  }
};

export default connect(mapStateToProps, mapActionsToProps)(LoggedOutComponent);
```

Any ideas?

**Comment by timdorr** [comment]
You should look into composition instead of inheritance. Render props are a great tool to help with this: https://reactjs.org/docs/render-props.html

**Comment by ThomasStubbe** [comment]
Ok, thanks! MobX it is 👍

**Comment by markerikson** [comment]
I'm rather confused by the discussion here, tbh.

What about connecting that component "doesn't work"?
