### ISSUE TITLE
'storeDidUpdate' callback

### ISSUE THREAD

**Issue by MAKARD** [reduxjs/react-redux#1024]
What about this improvement? It's can be usefull in some cases. 
For some basic example, when component updated without any new props, but with new state, you must detect that (especially using getDerivedStateFromProps instead componentWillReceiveProps, because last is deprecated in newest React):

```tsx
class Component extends React.Component {
      public storeDidUpdate(newState) {
          // Do some stuff, corresponds for new store state
      }
      
     public componentDidUpdate() {
         // Do some stuff, corresponds to new internal state
     }
}
```

instead:
```tsx
class Component extends React.Component {
     // For getDerivedStateFromProps is almost same using
     public componentDidUpdate() {
        if (
          this.props.someStoreField !== "someValue"
          && this.state.someInternalStateValue == "someValue") {
         // Do some stuff, corresponds to new internal state
         } else if (/*Another condition*/) {
            // Do some stuff, corresponds for new store state
        }
     }
}
```

**Comment by markerikson** [comment]
No, we have no plans to add something like this to the React-Redux API, so I'll close this.

Out of curiosity, what specific use cases are you thinking of?

**Comment by MAKARD** [comment]
Just my two cents)
https://github.com/MAKARD/react-redux-lifecycles
