### ISSUE TITLE
Is mapDispatch2Props really necessary?

### ISSUE THREAD

**Issue by SevenOutman** [reduxjs/react-redux#1026]
I've searched for this topic but none result matched the case I'm going to talk about.

In `react-redux`, we use `mapDispatch2Props` to inject access to `dispatch` into components(containers) like:
```jsx
// container.js
onSubmit() {
  this.props.addUser(this.state.formData);
}

function mapDispatch2Props(dispatch) {
  return {
    addUser(data) {
      dispatch({ type: ADD_USER, data });
    }
  }
}
```
However `dispatch` is actually accessible anywhere as long as you import the store, so we don't need this injection.
```jsx
// utils.js
import store from '../store';

export function addUser(data) {
  store.dispatch({ type: ADD_USER, data });
}

// containers.js
import { addUser } from '../utils';

onSubmit() {
  addUser(this.state.formData);
}

```

I know this seems *breaking the "all data should come in as props" rule of React*, but importing and using util functions are very common. Say we need to display a timestamp in some specific format:
```jsx
import { formatTime } from '../utils';

render() {
  return (
    <span>{formatTime(this.props.time)}</span>
  );
}
```

And this approach prevents your component(container) from being aware of redux stuff. So I wonder if it's a good replacement of `mapDispatch2Props`, especially when not taking `ownProps`.

**Comment by kouhin** [comment]
```
import store from '../store';
```

I think you are not using server-side rendering.
When you do server-side rendering, store should be created per request to due with the thread-safe problem.
Thus store(also dispatch() and getState()) should be passed from context.

**Comment by SevenOutman** [comment]
@kouhin No I'm not. That makes sense. 
Then what about none-ssr occasions?

**Comment by timdorr** [comment]
No, mDTP isn't strictly necessary. You're free to get access to `dispatch` or bind it to your action creators by other means, but for most it's a nice convenience. Especially in the object shorthand form.

**Comment by markerikson** [comment]
Also please see the [Redux FAQ entry on why we discourage importing the store directly](https://redux.js.org/faq/storesetup#can-or-should-i-create-multiple-stores-can-i-import-my-store-directly-and-use-it-in-components-myself).
