### ISSUE TITLE
Pure=false results in multiple renders

### ISSUE THREAD

**Issue by madcapnmckay** [reduxjs/react-redux#1028]
I noticed that the behavior of pure=false does not line up with my expectation and wanted to check whether this is a bug or not.

http://jsbin.com/mukuhos/1/edit

If multiple connects are nested and set to pure=false I would expect them to act as if they should always render no matter the change in state/props etc.  i.e. they do not attempt to run their own shouldComponentUpdate logic.

Instead what I see is a multiplying render down the tree. If we connect N layers deep the Nth connect renders N times for each change in state.

**Comment by markerikson** [comment]
That actually sounds like about what I would expect.  Each connected component instance is going to call `setState()` with its updates, so React is probably going to re-render multiple times.

(This is one of the reasons why you _shouldn't_ set `pure=false` unless you have a _very_ good reason to.)

**Comment by madcapnmckay** [comment]
So if you notice in my jsbin I actually pull of the changing state in each of the connected children, so if you set pure=true on each child, it will call setState on each connected component and React will batch them accordingly. I think there's still something wrong here with pure=false.

I understand it's not a recommended pattern, we are using it just in a migration step to get around an issue.

**Comment by madcapnmckay** [comment]
@markerikson @timdorr - here's maybe a clearer example. If we have 3 nested connects that all invalidate every time the store state changes we get the following renders.

```
"render App"
"render child"
"render grandchild"
```

Which corresponds to 3 setState calls in the same tick as we'd expect.

If we instead set each to pure=false, and change nothing else, which should be entirely equivalent. We instead get.

```
"render App"
"render child"
"render grandchild"
"render child"
"render grandchild"
"render grandchild"
```

**Comment by markerikson** [comment]
Yes, and given what I know about both how React and React-Redux work, that's pretty much what I would expect.

By turning off `pure` mode, the components will no longer avoid re-rendering if the incoming data hasn't changed.

What is your use case for setting `pure=false` ?

**Comment by abritinthebay** [comment]
The number of grandchild renders seems... unexpected to me. I get what you're saying but that grandchild render order seems wacky.

**Comment by markerikson** [comment]
It seems very reasonable to me. 

React-Redux v5 enforces top-down subscription behavior. Ancestors notify nested connected components after they've updated. 

That series of statements looks like what I would expect with a cascading series of updates, to to bottom, with each one causing rerenders of that subtree.

**Comment by abritinthebay** [comment]
ah, hmmm 🤔even with React batches though? Or internally is react-redux doing it's own loop on that with the enforcing top-down?

**Comment by markerikson** [comment]
It does its own top-down subscription logic. See the current master branch for the implementation details. 

In v6, we will be switching away from that thanks to createContext.
