### ISSUE TITLE
react-redux provide action functions via context

### ISSUE THREAD

**Issue by haraldrudell** [reduxjs/react-redux#1030]
react-redux distributes the store via React global context

Instead of importing action creators in each component, these could be fished out of the react-redux context as a property of the store. As a hack this is already possible by using dispatch below, but it would be better as part of the public api:

When instantiating the store:

<pre>
export const store = createStore(
  combineReducers({
    jobs,
    area,
    hw,
    sw,
  }),
  {},
  applyMiddleware(thunk)
)

// added action functions:
<strong>function callAbramov() {console.log('RING')}

store.dispatch.actions = {
  callAbramov,
}</strong>
</pre>

Any connected component can then access action creators:

<pre>
import { connect } from 'react-redux'
export default connect()(class TakeAction extends PureComponent {<strong>
  onClick = e => this.props.dispatch.actions.callAbramov(e.target.value)</strong>
</pre>

If this feature does not exist:
* action creators have to be imported creating a hard dependency
* A user has to implement his own React 16 context
* or props drilling 

If this feature is implemented:
* The store creator that collects all reducers can also collect all actions
* inter-component dependency is reduced
* actions can be easily invoked from the lowest possible event-producing component

**Comment by markerikson** [comment]
There's several issues with this:

- We're in the process of switching away from legacy context for version 6
- The store itself is not exposed to connected components
- It's not how the React-Redux API is intended to be used.

Sorry, but no plans to implement anything like this.
