### ISSUE TITLE
Question: Multiple re-render

### ISSUE THREAD

**Issue by snezik** [reduxjs/react-redux#1051]
Sorry, if my question looks stupid.

When function mapStateToProps returns an object, where one keyFiled is empty array or object, my component calls multiple re-render.

Example:

function mapStateToProps(state, props) {
	const selector = formSelector(props.formName);
	return {
		valuesOptions: valueAttrsSelector(state),
		rowsOptions: rowsAttrsSelector(state),
		columnsOptions: columnsAttrsSelector(state),
		rowsValue: selector(state, 'rows'),
		columnsValue: selector(state, 'columns'),
		valuesValue: selector(state, 'values'),
               test: []   // **<= problem here**
	};
}

const ChooseAttributesComposed = compose(
	connect(mapStateToProps,
		dispatch => ({
			openValuePopup: function (valueOptions,  index) {
				dispatch(valuePopupActions.openValuePopup(valueOptions, index));
			}
		})),
	withStyles(styles)
)(ChooseAttributes);

export { ChooseAttributesComposed as ChooseAttributes };

ChooseAttributes.propTypes = {
	classes: PropTypes.object,
	columnsOptions: PropTypes.array.isRequired,
	rowsOptions: PropTypes.array.isRequired,
	valuesOptions: PropTypes.array.isRequired
};

**Comment by markerikson** [comment]
Yes, every time there is a new reference inside of your return value, your component will re-render.  See [this related Redux FAQ entry](https://redux.js.org/faq/reactredux#why-is-my-component-re-rendering-too-often) for an explanation.
