### ISSUE TITLE
Tracing redux dispatch (plain redux and react-redux)

### ISSUE THREAD

**Issue by giorgi-m** [reduxjs/react-redux#1064]
I observed difference on sequence of some actions when using plain redux and react-redux. See this [example ](https://codesandbox.io/s/o7ow661r9)(plain):

    let flag = true;
    let i = 0;
    const render = () => {
      console.log("before", i++);
      if (flag) {
        flag = false;
        store.dispatch({ type: "INCREMENT" });
        console.log("set", i++);
      }
      console.log("proceeding", i++);
    };
    
    store.subscribe(render);
    render();

Output is

    before 0
    before 1
    proceeding 2
    set 3
    proceeding 4

This matched my intuition namely **as soon as first time** dispatch was called inside `if`, you can see new render was **immediately** called: "before 0" followed by "before 1" instead of "before 0" followed by "set 1". Then it printed "proceeding 2" because flag was already reset. And last two lines are from first render which were pending from first render. In total 2 render calls.

My issue is I can't seem to reproduce same sequence of calls when I use redux with react and connected component. I have similar setup like this (in render):

       console.log("before", this.i++)
       if(this.flag){
                
           this.flag=false;
           this.props.dispatch(setDetailsItem(null))
    
           console.log("set", this.i++)
    
        }
        console.log("proceeding", this.i++)

Output

    before 0
    set 1
    proceeding 2
    before 3
    proceeding 4
    before 5
    proceeding 6

Namely in react as soon as first dispatch happened, you can see the code proceeded (instead of immediately calling a new render as in previous case) and printed "set 1" (after "before 0"). Only afterwards new render was called and since flag was already changed now  we never see "set".

Does someone have explanation why this difference with redux when using react and when not using it? Also in react case does it mean, the components get notified about change in state asynchronously? Otherwise how did it manage to update state and then proceed with old render like I showed - and only afterwards call a new render?

**Comment by markerikson** [comment]
Yes, in general, React-Redux asks React to trigger an update (via a `setState()` call).  It's then up to React to decide when to actually execute that re-render and update.  So, components are _notified_ synchronously, but may be _re-rendered_ asynchronously.
