### ISSUE TITLE
Tests not working on Node 10 LTS when using react-redux

### ISSUE THREAD

**Issue by wolfy1339** [reduxjs/react-redux#1070]
`Cannot find module 'react-is' from 'connectAdvanced.js'`
```
at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:221:17)
at Object.<anonymous> (node_modules/react-redux/lib/components/connectAdvanced.js:22:16)
```

I have tried purging the cache on TravisCI to force a refetch of all dependencies, but it still gives me this message.
Relevant TravisCI build output: https://travis-ci.com/hellomouse/GNS/jobs/155896200#L3416

**Comment by wolfy1339** [comment]
It only happens on Node v10 LTS, The previous LTS works fine and v11 is unaffected

**Comment by timdorr** [comment]
You're installing direct from git: https://github.com/hellomouse/GNS/blob/master/dashboard/package.json#L46

You should be installing the published version from npm.

**Comment by wolfy1339** [comment]
Yes. I know, but it shouldn't make that much of a difference right now, as the version on npm and git haven't differed very much.
I will try with the version from npm and get back to you

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
