### ISSUE TITLE
Issue with Typescript and Dispatch

### ISSUE THREAD

**Issue by andrewgrewell** [reduxjs/react-redux#1087]
When passing in anything other than plain actions to dispatch Typescript ends up throwing errors because the value does not contain a 'type' property (which is to be expected).

I got around this by creating an interface that extends `Dispatch` but for `action` it allows `AnyAction` or `ActionCreator<any>`

I'm still getting up to speed with Typescript, so I'm wondering if this solution is acceptable (It allows for errors to be caught when you would expect, e.g. if the action creator is not correct), If it is acceptable, should this be the default definition of `Dispatch`?

the extended dispatch type looks like:
```
export interface ExtendedDispatch extends Dispatch {
    (action: AnyAction | ActionCreator<any>): any
}
```

**Comment by markerikson** [comment]
We don't maintain the React-Redux TS typings, as neither Tim nor I use TS directly.  They're kept over in DefinitelyTyped by the community.

**Comment by andrewgrewell** [comment]
Thanks, I'll move along over there 👍
