### ISSUE TITLE
can I pass ownProps for Defining mapDispatchToProps As An Object

### ISSUE THREAD

**Issue by Nothing-Works** [reduxjs/react-redux#1090]
I am just wondering for `Defining mapDispatchToProps As An Object` how can I pass ownProps to it? like in the function I can pass props as an argument.

`const mapDispatchToProps = (dispatch, ownProps) => {
  toggleTodo: () => dispatch(toggleTodo(ownProps.todoId));
};`
for an object how to pass ownProps?
`const mapDispatchToProps = {
  toggleTodo
};`

**Comment by markerikson** [comment]
You can't. *If* you *need* the ownProps argument, define mapDispatch as a function. Or, have your component methods pass in the right arguments.
