### ISSUE TITLE
Issue with props in React lifecycle functions

### ISSUE THREAD

**Issue by Licen-it** [reduxjs/react-redux#1093]
This issue is similar to #41, but it's happening with a `boolean`.
I noticed implementing the lifecycle method `componentDidUpdate` (and verified it happens in `shouldComponentUpdate` as well) as follow:

```js
componentDidUpdate(prevProps) {
  if (this.props.aBoolean !== prevProps.aBoolean) {
    this.fetchData();
  }
}
```

This component is a connected component, but what i noticed is that when i'm passing a new property from its parent `aBoolean` from `this.props` is the same as the one from `prevProps`. This component is extending `React.Component` and just to be sure it wasn't skipping the update step, i added the following `shouldComponentUpdate`

```js
shouldComponentUpdate(nextProps) {
  console.log(this.props.aBoolean, nextProps.aBoolean);
  return true;
}
```

The result of the log was `true true` or `false false` meaning that this.props has been updated somewhere else getting the new value before `shouldComponentUpdate` being called.

I'm using latest version of react-redux 5.1.1

**Comment by timdorr** [comment]
Can you show a full example of this failing? codesandbox.io works well.

**Comment by Licen-it** [comment]
I tried to replicate on codesandbox.io but i got it working fine. I think this might have something related on how storybook handle updates using knobs combined with react-redux as other non-connected components work fine, i'm seeing this just on connected components.
