### ISSUE TITLE
Link to "Provider" in the API Reference doesn't work

### ISSUE THREAD

**Issue by DominikPalo** [reduxjs/react-redux#1094]
There is a link (button) "PROVIDER" on the bottom of the ["API Reference" page ](https://react-redux.js.org/docs/api) and it points to the unreachable URL https://react-redux.js.org/docs/provider

![image](https://user-images.githubusercontent.com/1623257/49100178-959c2800-f273-11e8-8424-0d7742250806.png)
![image](https://user-images.githubusercontent.com/1623257/49100191-9fbe2680-f273-11e8-91c4-bf2595e4d349.png)

**Comment by timdorr** [comment]
It looks like it's a little wonky because of the file structure. This is probably something Docusaurus wasn't intending to handle. I think it will work if we just move around the api.md file. We should probably rename it to connect.md and make it just for the connect() API.

**Comment by wgao19** [comment]
@timdorr we can go around this by moving `api.md` into the `api/` directory. Would you like me to pull up this fix?
