### ISSUE TITLE
Unable to resolve PropTypes

### ISSUE THREAD

**Issue by niklassaers** [reduxjs/react-redux#1099]
With version 6.0.0 I get:
```
Unable to resolve module `../utils/PropTypes` from `.../node_modules/react-redux/lib/components/Provider.js`: The module `../utils/PropTypes` could not be found from `.../node_modules/react-redux/lib/components/Provider.js`. Indeed, none of these files exist:
```

And indeed, I cannot find that file either. Any suggestions to what could be happening?

**Comment by timdorr** [comment]
You have some sort of bad installation. There is no reference to `../utils/PropTypes` in that file now: https://unpkg.com/react-redux@6.0.0/lib/components/Provider.js

**Comment by njacob1001** [comment]
I have the same problem


Unable to resolve "../utils/PropTypes" from "node_modules\react-redux\lib\components\Provider.js

**Comment by balthazar** [comment]
Assuming you guys experienced the issue like me on react-native, you should re-package the app and launch the packager using `--reset-cache`, which would solve the problem.

**Comment by nico-w** [comment]
@balthazar Thanks. Your way of "resetting" the environment helped us. We rebuilt our environment, so like deleting `node_modules` and just reinstalled everything again.

**Comment by gerohara99** [comment]
I have same problem 

Unable to resolve "../utils/PropTypes" from "/node_modules/react-redux/lib/components/Provider.js

I've followed the step above i.e. reinstall all dependencies manually & reset cache. But continuing to get same error. Any help please?

**Comment by biranchi2018** [comment]
> --reset-cache

how to use it ?

**Comment by Aung-Myint-Thein** [comment]
These commands helped me

https://gist.github.com/jarretmoses/c2e4786fd342b3444f3bc6beff32098d

**Comment by dihan** [comment]
expo start -c fixed it for me

**Comment by dev-ahmed** [comment]
Any updates on this? i have the same issue
