### ISSUE TITLE
Typings dont work for react-redux latest version

### ISSUE THREAD

**Issue by vidhyeshpatil** [reduxjs/react-redux#1100]
ERROR in [at-loader] ./node-modules/@types/react-redux/index.d.ts:49:15, 240:16, 246:16, 313:16
TS2314: Generic type Dispatch<A, D, S> requires 3 type argument(s)

**Comment by timdorr** [comment]
We don't provide types in this library. Please use the appropriate support channels for DefinitelyTyped, which is where you got them from.
