### ISSUE TITLE
Pass result of mapDispatchToProps into mapStateToProps

### ISSUE THREAD

**Issue by travikk** [reduxjs/react-redux#1108]
Hi there!

On a number of occasions, I need some functions generated by mapDispatchToProps to be passed into mapStateToProps, such that they can be leveraged to further generate props.
An example would be, where you generate handlers to be used by a grid in mapDispatchToProps, and then you generate columns in mapStateToProps, thereby requiring all grid action dispatchers there.

Let me know what you think.

**Comment by markerikson** [comment]
That statement doesn't really make sense.  Why would you need action creators that have been wrapped in `dispatch` in order to determine what derived state this component needs?

For a situation like you're describing, I would recommend either creating callbacks in `render` that capture values like the column and row indexes, or passing a callback down to child grid item components and letting them call `this.props.somethingHappened(this.props.row, this.props.column, someValue)`.

**Comment by travikk** [comment]
@markerikson that would be problematic for number of reasons. 

In order for the grid to function, I need to generate the columns for the grid. Column generation is based on redux state, so the ideal place for it is in mapStateToProps.
Additionally, column generation defines renderers for each columns, as well as their props. That mean, column generation code needs to know about the action creators. That potentially could be curried in the following way:

```typescript
gridConfig.js:

export const generateColumns = (dataFromState) => (gridHandlers) => {
  return [
    {id: 'columnA', render: () => <button onClick={gridHandlers.onColumnAClick}>row1</button>},
    {id: 'columnA', render: () => <button onClick={gridHandlers.onColumnAClick}>row2</button>}
   ...
  ]
}

mapStateToProps.js:

export const mapStateToProps = (state) => ({
  columnGenerator: generateColumns(state.something);
})

mapDispatchToProps.js:

export const mapDispatchToProps = (dispatch) => ({
  columnHandler: () => dispatch(...)
})

view.js:

export const MyView = props => {
  const actualColumns({onColumnAClick: props.columnHandler});

  return <Grid
    columns={actualyColumns}
  />
}
```

This however is suboptimal, as:

* now the view is responsible for generating columns
* intermediary curried columnGenerator must exist for now reason other than to pass the action creators

This could easily be simplified if the result of mapToDispatch was passed into mapStateToProps.
Hope this clarifies my ask.

**Comment by markerikson** [comment]
Yeah, I'd say you're going about it the wrong way, for a couple different reasons.

First, while you _can_ technically return anything you want from a `mapState` function, conceptually it should only be about directly deriving data based on the Redux store state.  It shouldn't be used to actually generate JSX or functions.

Second, based on the snippets you're showing, it's likely that your grid component may be re-rendering even if the incoming data hasn't actually changed.

I would suggest that you change your `mapState` function to _only_ extract data from the Redux store state and return that.  Then, map over that data in your component's `render` method to generate the desired UI.

**Comment by travikk** [comment]
`First, while you can technically return anything you want from a mapState function, conceptually it should only be about directly deriving data based on the Redux store state. It shouldn't be used to actually generate JSX or functions.`

But it is. Like I said, the columns are based on the state, in the gist above it might not be as clear (I am passing 1 prop from the state), but one could easily imagine a more involved scenario.

`Second, based on the snippets you're showing, it's likely that your grid component may be re-rendering even if the incoming data hasn't actually changed.`

That really has nothing to do with the problem, as it would exist in either scenario (generate columns in mapStateToProps or in render). Obvious solution is to memoize, but it's outside the scope of this discussion.

`I would suggest that you change your mapState function to only extract data from the Redux store state and return that. Then, map over that data in your component's render method to generate the desired UI.`

This just introduced a middle-man step, that is completely unnecessary. From the POV of the view, it only cares about the columns and that is the primary driver for this request.

**Comment by markerikson** [comment]
My point is that `mapState` is intended to _only_ return data.  No UI, no functions, nothing else.  That's how React-Redux is meant to work, and your current approach is fighting against that.

Generating UI is the job of your React component when it renders.

**Comment by travikk** [comment]
You could easily change the example into this:

```typescript
gridConfig.js:

export const columnGeneratorFactory = (dataFromState) => (gridHandlers) => {
  return [
    {id: 'columnA', rendererProps: {onClickHandler: gridHandlers.onColumnAClick}>row1</button>},
    {id: 'columnA', rendererProps: {onClickHandler: gridHandlers.onColumnAClick}>row2</button>}
   ...
  ]
}
```

At which point there's no UI generation. It was just an example of why it is necessary to have gridHandlers there, instead of how you suggested in https://github.com/reduxjs/react-redux/issues/1108#issuecomment-445553114

Generating a function is a workaround for not being able to reference action creators. What I'm advocating for is, would alleviate the need to generate the function and just pass the JSON object with columns (pure data).

**Comment by markerikson** [comment]
And I'm saying none of that currying is necessary in the first place.

Look, if you can put up a CodeSandbox that does a miniature version of whatever your current grid setup logic is, I'll fork it and show you how I'd do this the "right" way.  But no, passing functions from `mapDispatch` is not how this library is supposed to work, it would require a major redesign of the internals, and we're not going to be doing that.

**Comment by timdorr** [comment]
Just to provide context, Redux itself suggests keeping your store limited to plain data structures (objects and arrays) and primitives (numbers and strings, for the most part). So, in mapping the state out of the store, we expect to maintain some of the same "rules" and not "upgrade" to something more complex. 

More importantly for performance, that kind of mapState output is going to be basically impossible to memoize. You'll run into lots of re-renders, especially with "high traffic" content like a grid of data.

Your best bet is to keep the props you're generating simple and handle the the currying during your render. React can optimize that kind of rendering better and it will have other good benefits later on (refactoring ease, test durability and correctness, code re-use).

**Comment by travikk** [comment]
Like I said, the actual solution does not include currying, it's only to address the comment made here: https://github.com/reduxjs/react-redux/issues/1108#issuecomment-445553114

As for the rest, I disagree about more code re-use, test durability and correctness or refactoring ease, in fact on the contrary. Each time you need a property to be used in any of the grid columns, you'll need to add a prop to the view, to the view's interface as well as pass it down in stories and mapStateToProps. That is not refactoring ease at all.
