### ISSUE TITLE
Connected component type inference

### ISSUE THREAD

**Issue by Voronar** [reduxjs/react-redux#1109]
When we work with TypeScript we have to manually declare prop types injected to connected component. 
In [this article](https://dev.to/voronar/practical-typescript-react--redux-4enh) I described how to do this work automatically with type inference.
Do you think about what? What about providing this utility type to main typings of react-redux library?

**Comment by timdorr** [comment]
We don't maintain the typings for React Redux here. Check with the support resources for DefinitelyTyped, which is where you probably got them from.
