### ISSUE TITLE
How to downgrade react-redux to an earlier version

### ISSUE THREAD

**Issue by bombay21** [reduxjs/react-redux#1112]
I currently have react-redux v6 installed and it doesn't support react-redux-firebase so I want to downgrade it to version 5.x

**Comment by markerikson** [comment]
Run these commands:

```js
npm remove react-redux
npm i react-redux@5
```

**Comment by bombay21** [comment]
Thanks a lot

**Comment by unipavan26** [comment]
I am getting the same issue,please help me out..tried for uninstalling package but it is not happening ,

**Comment by unipavan26** [comment]
![capture](https://user-images.githubusercontent.com/47030478/51746746-27d27800-20cd-11e9-983c-08c9bdf9174f.PNG)
Got this error in my code,please help me out!

**Comment by mirabbos2002** [comment]
> Run these commands:
> 
> ```js
> npm uninstall react-redux
> npm i react-redux@5
> ```

Thanks a lot it worked with me redux is requiring me to downgrade version of tsutil as well can you help with it as well or should i use same code with some changes it is srtange that redux 7.1.1 is requiring elder version of several things like

**Comment by mirabbos2002** [comment]
Thanks a lot it worked with me but redux is requiring me to downgrade version of tsutil as well can you help with it or should i use same code with some changes it is srtange that redux 7.1.1 is requiring elder version of several things like
npm WARN tsutils@3.21.0 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\webpack-dev-server\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\watchpack-chokidar2\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

or is it normal if I should downgrade versions of everthing can you help me with that as well

**Comment by mirabbos2002** [comment]
> Run these commands:
> 
> ```js
> npm uninstall react-redux
> npm i react-redux@5
> ```

Hi it worked with me but it stange that redux 4.1.1 is requiring to downgrade from latest version to elder versions like react react-dom and
npm WARN tsutils@3.21.0 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\webpack-dev-server\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\watchpack-chokidar2\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

should I upradge something or is that a normal if so can you give codes to downgrade all of them
