### ISSUE TITLE
`store` couldn't be found in context with `renderToString`

### ISSUE THREAD

**Issue by cdoublev** [reduxjs/react-redux#1121]
**Do you want to request a _feature_ or report a _bug_?**

A bug (imho).

**What is the current behavior?**

I'm not aware of a service for code demo with SSR. So I'm linking to a [minimal repository](https://github.com/cdoublev/react-redux-v6) to demonstrate the current behavior of a React/Redux app with SSR.

`npm run start` (with SSR)

Visiting http://localhost:8080 (white screen), terminal outputs this error: `{ Invariant Violation: Could not find "store" in the context of "Connect(Component)". [...].`

`npm run start:client`

Normal behavior.

**What is the expected behavior?**

I expected `react-redux` to find `store` with SSR.

**Which versions of Redux, and which browser and OS are affected by this issue? Did this work in previous versions of Redux?**

```json
    "react": "^16.6.3",
    "react-dom": "^16.6.3",
    "react-redux": "^6.0.0",
    "redux": "^4.0.1",
```

Chrome and Debian Stretch as a Vagrant guest inside Windows.

The expected behavior is still obtained with the previous versions of React Redux (5.1.1).

**Additional notes**

It might be related to how `renderToString` works. `renderToStaticMarkup` doesn't work either. I'm not very familiar with the logic of those functions.

I really hope it's not a usage error on my side.

**Comment by timdorr** [comment]
Just looking at things, it's likely something to do with `webpack-hot-server-middleware`. It does weird things around the rendering function and requiring from a string value of the file's contents, not just requiring the file itself. This is likely breaking out the code into a separate VM realm, so the Context instance in the server renderer isn't the same as the client. Looks like a caveat of that package, not React Redux.

**Comment by cdoublev** [comment]
Indeed, it's working with my production build. I will look at what's going on inside `webpack-hot-server-middleware`. Thank you for your help and sorry to not have thought to test it in production before creating this issue.
