### ISSUE TITLE
[RN] Could not find store in the context when using react navigation

### ISSUE THREAD

**Issue by Veikedo** [reduxjs/react-redux#1124]
I have this simple config

```
const HomeStack = createStackNavigator({
  Home: HomeScreen,
  AddEditCategory: AddEditCategoryScreen
});
```

Both `HomeScreen` and `AddEditCategoryScreen` connected to redux using `connect`.

So app opens and while I'm on `Home` it works fine. However, when I try to navigate to `AddEditCategory` this error appears

`Invariant Violation: Could not find "store" in the context of "Connect(AddEditCategoryScreen)". Either wrap the root component in a <Provider>, or pass a custom
React context provider to <Provider> and the corresponding React context consumer to Connect(AddEditCategoryScreen) in connect options.`

I have these versions of packages installed:

```
"expo": "^31.0.4",
"react": "16.5.0",
"react-native": "https://github.com/expo/react-native/archive/sdk-31.0.1.tar.gz",
"react-native-elements": "^1.0.0-beta7",
"react-navigation": "^2.18.2",
"react-redux": "^6.0.0",
"redux": "^4.0.1",
```

I tried rollback to `v5.1.1` of `react-redux` and it worked fine.

Also I tried updating `react-navigation` to "^3.0.8" with `v6` of `react-redux` and there was the same error.

**Comment by markerikson** [comment]
Please provide a project that reproduces this issue.  We've had a few reports of this, but no one has yet shown us a project that we can look at ourselves.

**Comment by Veikedo** [comment]
@markerikson I found the root cause while was preparing a reproducing project :)

The problem was because I imported connect like so:
`import connect from "react-redux/es/connect/connect";`

so need to pay attention hereafter.

Thanks!

**Comment by markerikson** [comment]
Can you tell us why you happened to import `connect` that way?  We've never suggested doing that in the docs.
