### ISSUE TITLE
Component no longer updating with react-redux 6.0.0

### ISSUE THREAD

**Issue by mjhoffm2** [reduxjs/react-redux#1125]
**Do you want to request a _feature_ or report a _bug_?**

Bug

**What is the current behavior?**

The current behavior is that my react component is not getting updated after I update the redux store.  In fact, mapStateToProps is not getting called except for the initial mount.

Here is a fairly minimal repo I set up that reproduces the issue: https://github.com/mjhoffm2/react-demo/tree/react-redux-bug-demo/node

In this demo, the `ChannelList` component dispatches a `LOAD_CHANNELS` action when it mounts, which updates `channels` in the redux store.  However, `mapStateToProps` doesn't get called a second time.  I need to force my component to remount by changing the key from the parent to see the updated data.

**What is the expected behavior?**

The expected behavior is that my component will be updated when the redux store is updated.  This works as intended if I switch to using react-redux 5.1.1, but does not work when I use version 6.0.0.  Even if I call `this.forceUpdate();` in my component, it does not get the new data from the redux store.

**Which versions of Redux, and which browser and OS are affected by this issue? Did this work in previous versions of Redux?**

I am using Redux 4.0.0 and Google Chrome.  I have not tested previous versions of Redux, but this has worked with previous versions of React-Redux.

**Comment by markerikson** [comment]
Hmm.  Code seems reasonable at first glance.  I'll try to take a look at this over the next day or two.

**Comment by maximusnikulin** [comment]
Same here

**Comment by markerikson** [comment]
@agentcoop: please provide a sample project that demonstrates the issue.

**Comment by mjhoffm2** [comment]
I made a demo for the bug that I think @AgentCoop is talking about: https://github.com/mjhoffm2/react-demo/tree/react-redux-bug-demo-2/node

If you run the code in this branch, you can open your browser directly to http://localhost:3000/channels/1/view and you should see the channel list stuck in "loading...".  However, if you click one the close link or one of the close buttons, that will dispatch a route change action through connected-react-router which will cause the channel list to update.

**Comment by markerikson** [comment]
Huh.  I'm looking at this, and I'm pretty confused.

`Provider` is clearly detecting that the state changed between first render and mount, and calling `this.setState({storeState : postMountStoreState})`.  It then re-renders.

But... the context consumer render callbacks in the connected components aren't firing at all when that re-render happens.

checking..


**AHA!**

You have mismatched versions of `react` and `react-dom`.  You're using `react@16.6.3`, but `react-dom@16.5`.  

If I update both to `react@latest react-dom@latest`, then it works correctly.

**ALWAYS KEEP YOUR REACT VERSIONS IN SYNC!

**Comment by mjhoffm2** [comment]
Thanks a ton, I knew it had to be something simple that I overlooked.  I wish React printed a warning in the console if there is a version mismatch.

**Comment by markerikson** [comment]
Agreed. Probably worth filing an issue over there to ask for it.

**Comment by lucastschmidt** [comment]
You are a god @markerikson ... my issue was in a mono repository of both react and native. React web app working fine, then I tried to apply redux in a new native app, not working, same problem as stated above ... for some reason, the repo was updated with latest React version, but the native version was asking for another version 😆 

I even tried subscribing the store, working fine ... I couldnt understand what was going on ...

After a few hours and lots of interwebz searching, I found your answer, thanks a lot dude!

**Comment by pgonzalez-santiago** [comment]
Hey, I had the same problem mapStateToProps doesn't get called a second time on production mode with Expo. This start happening to me with SDK33 having the correct versions of `React` and `React-dom` the problem was `Redux-connect`. I updated the dependency and now it is working :)
