### ISSUE TITLE
mapDispatchToProps shorthand disables currying

### ISSUE THREAD

**Issue by benlime** [reduxjs/react-redux#1138]
There is a similar issue at https://github.com/reduxjs/react-redux/issues/658. I tried using the same technique, but this is not working.

**What is the current behavior?**
Using `mapDispatchToProps` shorthand notation like: `{ setSelected }` returns a function for `setSelected` with a `length` of `0`. This disables the possibility to curry the function in the component after wrapping it with `dispatch`.

You can see an example here: https://codesandbox.io/s/v38z1nopnl

If I bind dispatch manually it works properly.

**What is the expected behavior?**
I would expect the `setSelected` function to be curry-able and the function length to match the arguments of the given function to the `mapDispatchToProps` shorthand.

**Which versions of React, ReactDOM/React Native, Redux, and React-Redux are you using?  Which browser and OS are affected by this issue? Did this work in previous versions of React-Redux?**

see example at https://codesandbox.io/s/v38z1nopnl

**Comment by markerikson** [comment]
The point of the "object shorthand" syntax is to handle the most common use case.  If you want to customize the behavior, use the function form of `mapDispatch`.
