### ISSUE TITLE
Error on build npm package for react redux

### ISSUE THREAD

**Issue by Etto91** [reduxjs/react-redux#1149]
i'm creating an HOC to connect container and representational component.

I'm using webpack for build both on development test and production.

The package exports a function that return the react-redux connect component

On develempent everything works as expected. When i build the package and link to test in production build i got 

> Could not find "store" in the context of "Connect(NameComponentPres)". Either wrap the root component in a `<Provider>`, or pass a custom React context provider to `<Provider>` and the corresponding React context consumer to Connect(NameComponentPres) in connect options.

i don't think that is a problem with react because it works on development, but i had already create a stackoverflow question and post it on reactflux without success

this is my configuration

webpack.config.js

    const path = require("path");

    const outputPath = process.env.BUILD
       ? path.resolve("./build")
       : path.resolve("./test");

    const testConfig = {
       mode: "development",
       entry: "./demo/index.js",
       devtool: "inline-source-map",
       externals: "./build/redux-simple-container.js",
       output: {
           path: outputPath,
           filename: "index.js"
      },
      module: {
        rules: [
            {
                loader: "babel-loader",
                include: [path.resolve("./demo")]
            }
        ]
      }
    };

    const buildConfig = {
      entry: "./src/ReduxSimpleContainer.js",
      mode: "production",
      output: {
          path: outputPath,
          filename: "redux-simple-container.js",
          libraryTarget: "commonjs2"
      },
      externals: ["react", "react-dom"],
      module: {
          rules: [
            {
                test: /\.js?$/,
                use: "babel-loader",
                exclude: /(node_modules)/
            }
        ]
      }
    };

    module.exports = process.env.BUILD ? buildConfig : testConfig;

.babelrc

    {
      "presets": [["airbnb", { "modules": false }]],
      "plugins": ["transform-object-assign"]
    }

./src/ReduxSimpleContainer.js

    import { connect } from "react-redux";
    const ReduxSimpleContainer = (actions, stateRequested, Component) => {
      ....
      ....
      return connect(
        mapStateToProps,
        mapDispatchToProps
      )(Component);
    };

    export default ReduxSimpleContainer;

**Comment by markerikson** [comment]
Please provide a project that reproduces the issue.

**Comment by Etto91** [comment]
i have tried it in two different projects.
this is the shell of both projects.

```
import React from 'react';
import { hydrate } from 'react-dom';
import Loadable from 'react-loadable';
import BrowserRouter from 'react-router-dom/BrowserRouter';
import { renderRoutes } from 'react-router-config';
import { applyMiddleware, createStore, compose } from 'redux';
import { Provider } from 'react-redux';
import logger from 'redux-logger';
import ReduxThunk from 'redux-thunk';
import Parse from 'parse';
import routes from './routes';
import maydayReducers from './reducers';

/* eslint-disable no-unused-vars */
import robots from './robots.txt';
/* eslint-enable */

const preloadedState = window.PRELOADEDSTATE;

delete window.PRELOADEDSTATE;
/* eslint-disable no-underscore-dangle */

let middleware = [ReduxThunk];
let enhancer = applyMiddleware(...middleware);
if (process.env.NODE_ENV !== 'production') {
  middleware = [...middleware, logger];
  const composeEnhancers = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ || compose;
  enhancer = composeEnhancers(applyMiddleware(...middleware));
}
const store = createStore(maydayReducers, preloadedState, enhancer);
/* eslint-enable */

const AppRouter = () => <BrowserRouter>{renderRoutes(routes)}</BrowserRouter>;

Loadable.preloadReady().then(() => {
  hydrate(
    <Provider store={store}>
      <AppRouter />
    </Provider>,
    document.querySelector('#app'),
  );
 });

```
for example i export the component like this

```
export default 
  ReduxSimpleContainer(
    [{ type: INVESTOR.SAVE_EMAIL, params: ['contactId'] }],
    ['investor'],
    FormContact,
  );
```



i have used it in 3/4 projects with copy and paste and now i want to use it via npm

**Comment by markerikson** [comment]
I can't do much to diagnose this without an actual separate project repo I can clone.

**Comment by Etto91** [comment]
@markerikson can i add you to the repo?

**Comment by markerikson** [comment]
If it's public, just give me a link.  If it's private, yeah, add me.

**Comment by markerikson** [comment]
It looks like the repo you've got is just for an NPM package.

It would help if you can put together an entire repo that completely demonstrates the problem, just by cloning it, installing, and running some kind of a "start" command.

Also, does this problem happen if you copy and paste that HOC file into an application, without trying to build it separately?

**Comment by Etto91** [comment]
i'm creating the repo.
I agree with you that isn't a issue with react-redux and i'm sorry for having opened that issue but I'm trying everything to understand what is wrong with the build.

**Comment by markerikson** [comment]
Well, I've cloned both repos, and I've tried building and starting the second one, but I'm not seeing the error you described.  I do see that the second repo has a copy of that HOC file and appears to be using it directly.

I'm sorry, but this is too far off-track for me at this point.  

I'd suggest looking at something like https://www.npmjs.com/package/create-react-library as a starting point for creating a reusable library.

**Comment by Etto91** [comment]
I solved the problem. i have change webpack with babel to build the package. it seems that the problem was from where the package requires the react-redux npm package. if my package require it from his node modules it throws the error otherwise it works. I hope that it can be useful for someone.
