### ISSUE TITLE
connect() - Flow: Missing type annotation for `DP`. `DP`

### ISSUE THREAD

**Issue by crobinson42** [reduxjs/react-redux#1151]
`Flow: Missing type annotation for `DP`. `DP` is a type parameter declared in function type [1] and was implicitly instantiated at call of `connect`

![screenshot 2018-12-31 10 07 41](https://user-images.githubusercontent.com/5973579/50565486-29826900-0ce4-11e9-867a-97735edd0d8b.png)

```
flow-bin@0.89.0
├─ react-redux@6.0.0
└─ redux@4.0.1
```

**Comment by timdorr** [comment]
We don't maintain the Flow types for this library. You should consult the support resources for flow-typed.

**Comment by crobinson42** [comment]
Thanks @ tim - forgot about that :-/ 

FYI for searches - https://github.com/flow-typed/flow-typed
