### ISSUE TITLE
Fix link Advanced Usage: Performance

### ISSUE THREAD

**Issue by wzup** [reduxjs/react-redux#1157]
**What is the current behavior?**

Broken link [Advanced Usage: Performance](https://react-redux.js.org/using-react-redux/connect-mapstate)

Here https://react-redux.js.org/using-react-redux/connect-mapstate#use-selector-functions-to-extract-and-transform-data

**What is the expected behavior?**

Link follows additional description

**Comment by markerikson** [comment]
Yeah, we haven't written that page yet :)  The link is a placeholder.

**Comment by timdorr** [comment]
Closing in favor of #1001
