### ISSUE TITLE
Provider Usage in Redux 6.0.0

### ISSUE THREAD

**Issue by james-novino** [reduxjs/react-redux#1160]
Hi, I just updated to 6.0.0 and have a question. I wrap my main component in a Provider :
```
    public render() {
        return (
            <Provider store={this.store}>
                <MainApp {...this.props} />
            </Provider>
        );
    }
}
```
However, when running the application I get the following error which appears be caused by the usage of the provider : 
```
react-dom.js:17859 Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
    at invariant (react-dom.js:17859)
    at ReactCompositeComponentWrapper.instantiateReactComponent [as _instantiateReactComponent] (react-dom.js:15950)
    at ReactCompositeComponentWrapper.performInitialMount (react-dom.js:4770)
    at ReactCompositeComponentWrapper.mountComponent (react-dom.js:4661)
    at Object.mountComponent (react-dom.js:11409)
    at ReactCompositeComponentWrapper.performInitialMount (react-dom.js:4774)
    at ReactCompositeComponentWrapper.mountComponent (react-dom.js:4661)
    at Object.mountComponent (react-dom.js:11409)
    at ReactCompositeComponentWrapper.performInitialMount (react-dom.js:4774)
    at ReactCompositeComponentWrapper.mountComponent (react-dom.js:4661)
```
We do have some usages of `withRef` but have changed all instances of `withRef` to use `forwardRef`. We do not pass store into any other components in the tree, but are using other redux modules with the following versions : 
```
"react": "16.7.0",
"react-dom": "16.7.0",
"react-redux": "6.0.0",
"redux": "3.7.2",
"redux-observable": "0.19.0",
```

**Comment by markerikson** [comment]
Nothing about the public usage of `<Provider>` has changed in v6.  Can you create a smaller project that reproduces the issue?  

You could also try sticking a breakpoint in the `invariant` function, and checking to see what the actual "object" is that's being received by React.

**Comment by james-novino** [comment]
Yes, we can try to create a small application to reproduce. We were able to debug into the invariant and found that the type that was causing the error was 
```
{$$typeof: Symbol(react.provider), _context: {…}}
```
Which lead us to believe the issue was in our usage of the Provider. The invariant function is called from : 
```
function instantiateReactComponent(node, shouldHaveDebugID) {
  var instance;

  if (node === null || node === false) {
    instance = ReactEmptyComponent.create(instantiateReactComponent);
  } else if (typeof node === 'object') {
    var element = node;
    var type = element.type;
    if (typeof type !== 'function' && typeof type !== 'string') {
      var info = '';
      if ("development" !== 'production') {
        if (type === undefined || typeof type === 'object' && type !== null && Object.keys(type).length === 0) {
          info += ' You likely forgot to export your component from the file ' + "it's defined in.";
        }
      }
      info += getDeclarationErrorAddendum(element._owner);
      !false ? "development" !== 'production' ? invariant(false, 'Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: %s.%s', type == null ? type : typeof type, info) : _prodInvariant('130', type == null ? type : typeof type, info) : void 0;
    }
```

**Comment by markerikson** [comment]
Weird.  Yeah, I don't think there's anything more I can do without a specific project I can get my hands on.

**Comment by timdorr** [comment]
This sounds like a build config problem. A really simple example works just fine: https://codesandbox.io/s/wkpn0o9m4w This doesn't appear to be anything to do with the library itself.

**Comment by landonalder** [comment]
I'm having this issue as well after upgrading to react-redux 6.0.0. I think this shouldn't be closed

**Comment by james-novino** [comment]
@landonalder Do you have a link to your repo? Is the issue your experience similar to the one I described?

**Comment by landonalder** [comment]
@james-novino I believe it is similar to your issue, but sadly I'm not able to provide a link to my repo because it's my employer's private repo
