### ISSUE TITLE
Misleading entry point to import react-redux

### ISSUE THREAD

**Issue by kevroadrunner** [reduxjs/react-redux#1165]
**Do you want to request a _feature_ or report a _bug_?**

Bug

**What is the current behavior?**

The transpiled (babel; to commonjs) `import` of react-redux since version 5.1.0 loads the `.../node_modules/react-redux/es/...` module instead of `.../node_modules/react-redux/lib/...`. I could fix this error by manually edit the react-redux `package.json` key `module` from `es/index.js` to `lib/index.js`.

Stack Trace:
```
 | /user/workspace/project/node_modules/@babel/runtime/helpers/esm/inheritsLoose.js:1
 | (function (exports, require, module, __filename, __dirname) { export default function _inheritsLoose(subClass, superClass) {
 |                                                               ^^^^^^
 |
 | SyntaxError: Unexpected token export
 |     at createScript (vm.js:80:10)
 |     at Object.runInThisContext (vm.js:139:10)
 |     at Module._compile (module.js:617:28)
 |     at Object.Module._extensions..js (module.js:664:10)
 |     at Module.load (module.js:566:32)
 |     at tryModuleLoad (module.js:506:12)
 |     at Function.Module._load (module.js:498:3)
 |     at Module.require (module.js:597:17)
 |     at require packages/search-ui/(internal/module.js:11:18)
 |     at eval (webpack:///external_%22@babel/runtime/helpers/esm/inheritsLoose%22?:1:18)
```

Btw. I cannot explain why our babel transpile process doesn't solve this behavior itself.

**What is the expected behavior?**

I want to use `import` to import react-redux as in version up to `5.0.7`.

**Which versions of React, ReactDOM/React Native, Redux, and React Redux are you using?  Which browser and OS are affected by this issue? Did this work in previous versions of React Redux?**

"react-redux": "6.0.0" (5.0.7 works fine)
"react": "16.7.0"
"redux": "4.0.1"
"@babel/core": "7.2.2"
"@babel/preset-env": "7.2.3"
"@babel/preset-react": "7.0.0"

**Comment by timdorr** [comment]
This isn't an error in React Redux. It's point to a problem in @babel/runtime. It is likely a config issue with webpack.

**Comment by kevroadrunner** [comment]
Thank you for your fast answer. Just to have mentioned it we don't use @babel/runtime (directly) - But `yarn why` says `"react-redux#@babel/runtime@7.2.0"`. That's why i'm rushed in here.

**Comment by timdorr** [comment]
Yes, it's one of our deps. But the fact it's not being transpiled by Babel or properly imported by webpack doesn't have anything to do with our library, unfortunately.
