### ISSUE TITLE
React Native add support react-redux@6.x.x

### ISSUE THREAD

**Issue by retyui** [reduxjs/react-redux#1169]
**What is the current behavior?**
After update react-redux from `5v` to `6v`,  there were problems with connected components. They don't pass new props from the store.

**What is the expected behavior?**
All updates in the store will trigger rerender connected components

```
  React Native Environment Info:
    System:
      OS: Linux 4.15 Linux Mint 18.3 (Sylvia)
      CPU: x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
      Memory: 2.77 GB / 15.55 GB
      Shell: 2.7.1 - /usr/bin/fish
    Binaries:
      Node: 10.15.0 - /usr/bin/node
      Yarn: 1.12.3 - ~/.yarn/bin/yarn
      npm: 6.4.1 - /usr/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    npmPackages:
      react: ^16.7.0 => 16.7.0 
      react-native: ^0.56.0 => 0.56.0
      redux: ^4.0.0 => 4.0.1
      react-redux: ^6.0.0 => 6.0.0
```

**Comment by timdorr** [comment]
We've found there are potentially some issues with older versions of expo, if you are using that. 

But out of the box, we fully support React Native.

**Comment by retyui** [comment]
Woo! 
I don't use expo! 
And your readme file tells me only about 5v.

I will create a demo to reproduce this bag

**Comment by markerikson** [comment]
@retyui : the discussion in #1133 suggests there may also be issues with which version of React Native you're using.  Per https://github.com/reduxjs/react-redux/issues/1133#issuecomment-455789538 : 

> I took a quick look at your project developer239 and noticed you are not using the latest version of react-native. Please try upgrading to 0.57.8 and see if the problem persists.

> I took a very quick look at what happened between expo version 31 and 32, and it seem react-native was upgraded from 0.55 to 0.57 there, so might be that this problem only happens in <0.57.
