### ISSUE TITLE
NPM's README version indicates that version 6.0 is compatible with React 0.14 or later.

### ISSUE THREAD

**Issue by shepmaster** [reduxjs/react-redux#1170]
**What is the current behavior?**

![image](https://user-images.githubusercontent.com/174509/51637885-ea35e980-1f2a-11e9-9fa2-573c6df7e0c3.png)

**What is the expected behavior?**

I'd expect this to match what is in the GitHub README:

![image](https://user-images.githubusercontent.com/174509/51638002-3b45dd80-1f2b-11e9-9545-aadf796e9e5a.png)

**Comment by markerikson** [comment]
Hmm.  Not sure why there's a discrepancy there.

We need to publish a 6.0.1 shortly anyway (@timdorr ).

**Comment by ericdfields** [comment]
Eagerly waiting for 6.0.1 :)

**Comment by sainianubhav** [comment]
It's because at the time of v6.0.0 release, README used to read that. Check here: https://github.com/reduxjs/react-redux/tree/581ece46b8a4179587fe88a6d10000472acffee7

**Comment by markerikson** [comment]
This'll be resolved in the next release.
