### ISSUE TITLE
Proposal: Add an extra argument to mapStateToProps similar to redux-thunk

### ISSUE THREAD

**Issue by perrin4869** [reduxjs/react-redux#1181]
`redux-thunk` supports injecting an extra argument into each thunk, as described [here](https://github.com/reduxjs/redux-thunk#injecting-a-custom-argument):

```javascript
const store = createStore(
  reducer,
  applyMiddleware(thunk.withExtraArgument(api))
)

// later
function fetchUser(id) {
  return (dispatch, getState, api) => {
    // you can use api here
  }
}
```

This is very useful when testing the thunks, by mocking the `api`. It would be helpful to add a similar feature to `react-redux` for mocking out selectors in `mapStateToProps`.

```javascript
import ReactDOM from 'react-dom';
import { Provider, connect } from 'react-redux';
import store from './store';
import * as selectors from './selectors';

ReactDOM.render(
  <Provider store={store} extra={selectors}>
    <MyConnectedComponent />
  </Provider>
);

const MyComponent = ({ user }) => <div>{user.username}</div>;
const MyConnectedComponent = connect(
  (state, props, selectors) => ({ user: selectors.getUser(state) }),
)(MyComponent);
```

Is this feasible?

**Comment by markerikson** [comment]
I don't see how there's anything we need to add for this on our end, and tbh I'm not sure why you would ever need to "mock out selectors".  Not something I see us adding.

**Comment by timdorr** [comment]
I'm not sure this creates any real benefit. You could get rid of the `selectors` argument and your code would still work fine.

If you're looking to get extra runtime data into the mSTP function, you should use props for that. If you're trying to get data deep down the component tree, you should use the context API directly.

**Comment by perrin4869** [comment]
Well, the idea was mostly, same as with `redux-thunk`, for unit testing. 
I don't think there is a way to access context from within connect.
Also, the snippet above works without the select argument just because the component is in the same file :P
An alternative would be to add the extra argument not to mSTP directly, but to the factory function https://react-redux.js.org/api/connect#factory-functions
