### ISSUE TITLE
(typescript) connect has seemingly no type checking

### ISSUE THREAD

**Issue by chriskuech** [reduxjs/react-redux#1185]
**bug**
`connect` has inaccurate type checking.  Consider the following example:

```ts
interface IProps {
  a: Ta;
  b: Tb;
  c: Tc;
}

const mapStateToProps: (state: IState) => Pick<IProps, "a"> = ...
const mapDispatchToProps: (dispatch: Dispatch) => Pick<IProps, "b"> = ...

const MyComponent: (props: IProps) => JSX.Element = ...

export default connect(mapStateToProps, mapDispatchToProps)(MyComponent);
```

**What is the current behavior?**
There is no TypeScript compilation error, so the type system becomes inaccurate.

**What is the expected behavior?**
The last line should throw a typescript compilation error, because `Pick<IProps, "a"> & Pick<IProps, "b">` is incompatible with `IProps`, as it is missing property `c`.

**Which versions of React, ReactDOM/React Native, Redux, and React Redux are you using?  Which browser and OS are affected by this issue? Did this work in previous versions of React Redux?**
`@types/react-redux@7.0.1`
`react-redux@6.0.0`

**Comment by markerikson** [comment]
We don't maintain the TS typings here in the repo - that's handled over in DefinitelyTyped.
