### ISSUE TITLE
some problems with using roadhog 

### ISSUE THREAD

**Issue by WenshyDreamPenta** [reduxjs/react-redux#1188]
Hi,
    when update my version to 6.0.0,  I use roadhog to pack my code , it will be interrupt by errors, as follow:
       
         Can't resolve '@babel/runtime/helpers/esm/objectWithoutPropertiesLoose' in 'd:\myproject\wb-tsnode\build_modules\node_modules\react-redux\es\connect'

but I can see the module exist in node_modules, version 5.0.7 is OK, please give me some help .

**Comment by timdorr** [comment]
This seems like a problem with roadhog, not our project. Please go to them for support.
