### ISSUE TITLE
Incompatibility with React > 16.8.0?

### ISSUE THREAD

**Issue by tstirrat15** [reduxjs/react-redux#1202]
**Do you want to request a _feature_ or report a _bug_?**
Bug

**What is the current behavior?**
On my dev local, with react compiling in a non-production mode, the library works just fine.

However, when I go to run our production build process and then smoketest by running the `server.js` file locally, I get the following error:

https://sentry.io/share/issue/b31d88f4cb34475f95bcdf686064c6ac/

React 16.8.0 works just fine; the patch versions higher than that don't. I'm not sure whether this points to an issue with this library or with React.

**Minimal Repro**
Not quite sure how to go about this. Thoughts? It's failing on the server render, not on the clientside.

**What is the expected behavior?**
No errors; smoketest works.

**Which versions of React, ReactDOM/React Native, Redux, and React Redux are you using?  Which browser and OS are affected by this issue? Did this work in previous versions of React Redux?**

Versions:

* React/DOM: >= 16.8.1
* Redux: 3.6.0
* react-redux: 6.0.1

Platform: Node 8.15.1 on Ubuntu (also appears on CircleCI Node 8 container testbed)

**Comment by markerikson** [comment]
Generally this indicates that your bundler is somehow pulling in two different mismatched instances of React-Redux.  v6+ depends on a singleton instance of React's `createContext()` by default.  Bundling problems can cause more than one instance to get created, and the mismatched instances will cause the connected components to be unable to read the store.

Beyond that, we'd need to see a project that specifically reproduces the issue to know if there's anything else going on.

**Comment by tstirrat15** [comment]
@markerikson thank you - that's a good place to look. I hadn't considered that as a potential problem. Is there troubleshooting documentation to that end somewhere?

**Comment by tstirrat15** [comment]
Hmm... It's definitely a webpack issue of some sort.

We've got our project set up to externalize `node_modules` in the server build, and this is what's coming out in the bundled server code:

```javascript
// ...
/* harmony import */ var react__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(0);
/* harmony import */ var react__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(react__WEBPACK_IMPORTED_MODULE_1__);
// ...
/* WEBPACK VAR INJECTION */(function(module) {/* harmony import */ var react__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(0);
/* harmony import */ var react__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(react__WEBPACK_IMPORTED_MODULE_0__);
// ...
/* harmony import */ var react__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(0);
/* harmony import */ var react__WEBPACK_IMPORTED_MODULE_2___default = /*#__PURE__*/__webpack_require__.n(react__WEBPACK_IMPORTED_MODULE_2__);
// ...
```
Where `__webpack_require__(0)` is:
```javascript
/******/ 	// Load entry module and return exports
/******/ 	return __webpack_require__(__webpack_require__.s = 868);
/******/ })
/************************************************************************/
/******/ ([
/* 0 */
/***/ (function(module, exports) {

module.exports = require("react");

/***/ }),
// ...
```
So for some reason I've got at least three instances of React showing up in my build.

Are there obvious sources of this kind of issue, or is this just going to take some debugging?

**Comment by elmeerr** [comment]
@tstirrat15 any updates on this? I'm facing the same issue :/

**Comment by tstirrat15** [comment]
@elmeerr no - I opened an issue with Webpack here: webpack/webpack#8886 and thus far nobody's responded to it. Could you leave a comment saying that you're seeing the same? Hopefully it'll get a bit of visibility that way.

**Comment by markerikson** [comment]
Yeah, whatever's going on here shouldn't be a React-Redux issue.  Closing this one.

**Comment by elmeerr** [comment]
@tstirrat15 I didn't try the `single` option yet....I'll give a try tomorrow and let you know. Hope that we can solve this 😃
