### ISSUE TITLE
Connecting a component that uses new .contextType API breaks it in React Redux 4.x

### ISSUE THREAD

**Issue by gaearon** [reduxjs/react-redux#1203]
The problem in https://github.com/reduxjs/react-redux/issues/1067 isn't fixed in `react-redux@4` which is pinned to `hoist-non-react-statics@2`. Can we get a fix in there? Since some people can't migrate to 5 due to the perf regressions (for some use cases), and the error is very confusing. Thanks!

**Comment by markerikson** [comment]
@timdorr , you got time to bump deps on v4?

@gaearon : do you have any info on how many people are still on v4, and why?  I remember the one issue filed by Twitter.  Anyone else?

**Comment by timdorr** [comment]
Yeah, I can get to it soon.

**Comment by timdorr** [comment]
Done: https://github.com/reduxjs/react-redux/releases/tag/v4.4.10

**Comment by gaearon** [comment]
Thanks!

**Comment by gaearon** [comment]
> Anyone else?

FB in RN apps, at least. :P

**Comment by markerikson** [comment]
Really.  Do you have any details on why they haven't upgraded to 5.x?

**Comment by gaearon** [comment]
Probably just didn't have any incentives. Migrating from legacy context can be one.
