### ISSUE TITLE
Wrapping a Context Provider throws "Converting circular structure to JSON"

### ISSUE THREAD

**Issue by willcosgrove** [reduxjs/react-redux#1206]
**Do you want to request a _feature_ or report a _bug_?**
 🐛 

**What is the current behavior?**
If I create a react context, and then try to wrap the provider component with `connect`, an error will be thrown: "Converting circular structure to JSON".

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to a CodeSandbox (https://codesandbox.io/s/new) or RN Snack (https://snack.expo.io/) example below:**
https://codesandbox.io/s/8w7j08v10

```js
import React from "react";
import { connect } from "react-redux";

const { Provider, Consumer } = React.createContext(null);

connect()(Provider); // 💥 
```

**What is the expected behavior?**
That it would not throw an error, and connect the component

**Which versions of React, ReactDOM/React Native, Redux, and React Redux are you using?  Which browser and OS are affected by this issue? Did this work in previous versions of React Redux?**
I'm using React 16.8.3, and React Redux 5.1.1.  I'm unaware of when this stopped working.

The Provider component is trying to be JSON serialized right here: https://github.com/reduxjs/react-redux/blob/5cdb83a91ca0ad4414a978f56eb34392a1e3f9df/src/components/connectAdvanced.js#L90-L95

I'm not sure what I would suggest to get around this.  I don't have much experience with `invariant`.  It doesn't appear that there is a way to "lazily evaluate" the error message.

**Comment by markerikson** [comment]
To be honest, the real issue here is that you can't wrap a `Context.Provider` with `connect`.  There's no point to it.  The only prop a `Context.Provider` accepts is `value`.  Any other props you pass down from Redux are going to be ignored.

**Comment by willcosgrove** [comment]
I'm not sure I follow why you couldn't wrap a `Context.Provider` in `connect`.  Sure, it only takes a `value` prop, but I'd use `mapStateToProps` to map some value from redux into the value prop.  In my specific case I'm using `urql` and I need to give it's Provider component an urql client, which I fetch using a selector that grabs the current API key out of Redux.

>But, yeah, the fact that you're even hitting that error message is telling you that it's not a valid component type in the first place. The fact that the stringification is itself failing is simply a symptom, not the problem.

I'm not so sure that it is.  `isValidElementType(WrappedComponent)` returns `true`.  The problem is that the `JSON.stringify` call is happening regardless of what `isValidElementType(WrappedComponent)` returns, because it is an argument to the `invariant` function.

**Comment by willcosgrove** [comment]
@markerikson Would you or another contributor be willing to take another look at this?

You were correct that my provided example was contrived and doesn't make much sense as something that would be desirable to do.  In my actual use case, I'm using `mapStateToProps` to map a specific value to the Provider's `value` prop.  I posted a simple example so you wouldn't need to look through all of my application code to figure out where the problem was, because the problem can be recreated very minimally.

```js
import React from "react"
import { connect } from "react-redux"
const { Provider } = React.createContext(null)
connect()(Provider)
```

And as I mentioned above, I've checked in the debugger and `isValidElementType(Provider)` is true.  So this is not failing because a Provider is not a valid element type.  You can see that Provider is in fact a valid element type by looking at the isValidElementType code here:

https://github.com/facebook/react/blob/5c2b2c0852c715abda7296bd6e7a2e941ca66969/packages/shared/isValidElementType.js#L25-L44

On line 39 the Provider type is checked as a valid type.

I apologize for not making the actual use case of this clear in my original issue.
