### ISSUE TITLE
`isPlainObject()` util returns is still incorrect

### ISSUE THREAD

**Issue by alex89lj** [reduxjs/react-redux#1207]
I am glad that this fix was merged(https://github.com/reduxjs/react-redux/pull/1075), but it seems to be not perfect. 
isPlainObject(Object.create(null))=>true,
isPlainObject(Object.create({}))=>false???. 
![image](https://user-images.githubusercontent.com/8944883/54737361-835f4480-4bea-11e9-8e26-e28492c870e5.png)
This is correct in redux's "isPlainObject" function.
This is my PR:https://github.com/reduxjs/react-redux/pull/1005/files

**Comment by timdorr** [comment]
Please see #1074 for why we accepted that change and Mark's comments here for why we don't need to be exhaustive with our checks: https://github.com/reduxjs/react-redux/pull/1005#issuecomment-416105331
