### ISSUE TITLE
Minor typo in v7 release notes

### ISSUE THREAD

**Issue by baddox** [reduxjs/react-redux#1214]
"The React team encouraged us to us this"

should be

"The React team encouraged us to use this"

**Comment by baddox** [comment]
Apologies if there's a way to make a PR for release notes. I looked for a way but couldn't find one. Release looks great!

**Comment by markerikson** [comment]
Hah, yeah, that's what happens when you write everything up late at night :)  No way to PR release notes as far as I know, but just fixed it.  Thanks!
