### ISSUE TITLE
Not getting updated values from redux store in function components

### ISSUE THREAD

**Issue by vaibhavhrt** [reduxjs/react-redux#1218]
**Do you want to ~~request a _feature_~~ or report a _bug_?**

**What is the current behavior?**
When using Function Component to await for an action to complete then getting the updated store data to do something based on that doesn't works, while in Class based components it works fine. See the attached codesanbox link for demo.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to a CodeSandbox (https://codesandbox.io/s/new) or RN Snack (https://snack.expo.io/) example below:**

**CodeSandbox Link**: https://codesandbox.io/s/z3jp723o0m?fontsize=14
You can see the handle close method runs in function based component but not in class based component(refresh the codesandbox embedded demo to reset the store).

**What is the expected behavior?**
Function based component should also get the lastest store data.

**Which versions of React, ReactDOM/React Native, Redux, and React Redux are you using?**
All latest 
> react16.8.3
> react-dom16.8.3
> react-redux6.0.1
> react-scripts2.1.8
> redux4.0.1
> redux-thunk2.3.0

**Which browser and OS are affected by this issue?**
All browsers/OS
**Did this work in previous versions of React Redux?**
Probably not, but not sure.

**Comment by timdorr** [comment]
This is because you're grabbing props from the render closure, rather than from the class itself during the event handler. I'm not sure of a way around this, as it's just how function components work. But the example does appear to work for me, so I'm not sure where you're seeing the bug.

**Comment by vaibhavhrt** [comment]
Example works for class Component, but not for function component.
Log in the Function Component first, then you will see the alert, after that alert doesn't appears because `error` is `true` because of previous submit, but in my actual project I reset `error` to `false` everytime api request is made so the dialog closes every time but in the demo I created it happens the first time only.
I am trying to implement Function Components everywhere in my project since we have hooks in React now so no need for class component but I am stuck here.
