### ISSUE TITLE
Component unnecessarily updates when using <Link>

### ISSUE THREAD

**Issue by Vodzo** [reduxjs/react-redux#1228]
**Do you want to request a _feature_ or report a _bug_?**

Bug

**What is the current behavior?**

I guess this is kind of a complicated issue but i managed to strip everything and create a minimal reproduction: https://codesandbox.io/s/038x96jpvn

Clicking on "link 1" and watching console output you can see ComponentWithLink being updated and having this as a props: 
```
Object {dispatch: function ()}
```

**What is the expected behavior?**

This is the same code only using react-redux@5.1.0: https://codesandbox.io/s/mmyno8x26p
As you can see with react-redux@5.1.0 component is not being updated which is the desired outcome.

Other component that doesn't have **Link** doesn't update at all which is ok.

Update/re-render also doesn't happen if i don't use **CSSTransition** so the problem is between CSSTransition <-> react-redux <-> Link but only lib that has changed is react-redux.

**Which versions of React, ReactDOM/React Native, Redux, and React Redux are you using?  Which browser and OS are affected by this issue? Did this work in previous versions of React Redux?**

react@16.8.6
redux@4.0.1

**Comment by timdorr** [comment]
This is a React Router change. It re-renders the top level BrowserRouter when pushing the same route now.

**Comment by Vodzo** [comment]
That doesn't explain the change in props and the appearing of dispatch property in a component that doesn't map anything with connect. 

Could you please take another look at this because it breaks only when versions of react-redux are changed.

Thank you

**Comment by timdorr** [comment]
`dispatch` is a default prop you get from `connect()`. You have a cDU, which doesn't fire until the component actually re-renders. That re-render is caused by BrowserRouter.

**Comment by Vodzo** [comment]
But why does it behave differently with only react-redux changed from 7.0.1 to 5.1.0?

**Comment by timdorr** [comment]
Legacy vs new Context API. You'll notice it also reverts behavior if you go back to React Router 4.3.1, which is a legacy context user as well.
