### ISSUE TITLE
React-redux v7.0.0 React.js dependency

### ISSUE THREAD

**Issue by sashberd** [reduxjs/react-redux#1237]
Hey guys,

In your Readme written that v7.0.0 has React.js dependency 16.4 or later. But inside you package.json it is 16.8.6. This makes a warning on packages installation 

> warning " > react-redux@7.0.0" has incorrect peer dependency "react@^16.8.4".

My local version of react as you can see is 16.8.4. So what is right version dependency of v7.0.0
(I can not upgrade today to lates react :( )

Thanks

**Comment by hedgerh** [comment]
Not sure if they want the docs to show the very latest, but I updated them here https://github.com/reduxjs/react-redux/pull/1238

**Comment by sashberd** [comment]
@hedgerh Thanks for clarify
