### ISSUE TITLE
Release notes tab update procedures are resulting in RSS feed spam

### ISSUE THREAD

**Issue by icfantv** [reduxjs/react-redux#1266]
Hey guys, thank you for producing and maintaining a vital piece of the React ecosystem.  Please consider this a friendly request to alter your process for updating the release notes on the Releases tab of GitHub.  GitHub [automatically?] produces an RSS atom feed from a projects Releases page (for react-redux, [it is here](https://github.com/reduxjs/react-redux/releases.atom)) and every time you edit it post release, it effectively produces new entries.  This causes feed subscribers, like the one provided by Slack, to spam channels and produces a LOT of (probably unnecessary) noise.  Noise that we do not see from the Typescript and React releases.

From Slack support:
```
The problem is in the feed itself. What I think is happening is that the Slack RSS
Feed app is posting what appears to be duplicates because the entries
themselves are being updated.

The Slack app isn't smart enough to know the difference between a new posting
and an updated posting. Or, rather, it assumes you want both.

In your screenshot, for example, are two entries, one titled v7.1.0-alpha.0: The
One With Hooks (?) and the other titled simply v7.1.0-alpha.0.

In Github, you only see the one titled v7.1.0-alpha.0, which tells me the original
entry was updated with the more accurate title.

You may not be seeing the same problem in other Github RSS feeds you're
subscribed to because people aren't going back to edit their release notes in
the same way.

If this editing "noise" is too distracting or so noisy that it isn't helpful anymore,
it may be best to unsubscribe this feed.
```

We want to subscribe to the releases feed because we want to be kept abreast of new releases.  Unfortunately, the channel noise has forced us to temporarily unsubscribe from the feed for now.   Thanks again for all you do.

**Comment by timdorr** [comment]
We're not changing titles, so I'm not sure what would be causing this. Regardless, we do make small tweaks to the release notes as typos are noticed. We generally don't change the titles, as they're the version specified on npm and are immutable. If GitHub is creating spurious entries in the Atom feed, that's a GitHub bug and should be reported to them. 

BTW, one newer option for watching a repo is only to get the releases:

![image](https://user-images.githubusercontent.com/17882/56904913-41d57b00-6a6d-11e9-9a67-b5cb45cb9c3d.png)

This may be ideal, as it won't generate duplicate notifications for updates. It's a different channel than Slack, but you may be able to hook that up via email.

**Comment by icfantv** [comment]
@timdorr Ok, thanks.  I'll escalate to GH support.

**Comment by icfantv** [comment]
I've done this and will post their response here.

**Comment by markerikson** [comment]
Yep, I have gone in and made several edits to the release notes as I think of new things that have to be mentioned.

We have no control over the RSS feeds ourselves, so nothing we can do there.

**Comment by icfantv** [comment]
@markerikson, no worries.  I personally didn't care, but given how many folks were in the channel, _some_ did and started to complain.

Looking at the RSS XML, each `<entry>` element has an ID so as long as that doesn't change when the contents are updated, it seems like Slack should be able to detect updates without spitting out another notification.  I'll wait to hear back from GitHub first before pursuing that angle.
