### ISSUE TITLE
Poor performance after updating from version 7.0.1

### ISSUE THREAD

**Issue by TimSusa** [reduxjs/react-redux#1268]
Hi,

at first big thanks for your framework and making things easier since a couple of time. I have the good old approach with mapstateToProps/mapDispatchToProps running in my project and after updating from 7.0.1 to something over that version all my users suffered a big performance lack, so I rolled back to version 7.0.1. 

https://github.com/TimSusa/midi-bricks-mono/commit/9dfcd3d0257541a900d8f2cf863364265bdb49c8

Do we have some kind of breaking change here?

**Comment by markerikson** [comment]
Please provide a sample project that demonstrates the issue.

How are you measuring performance?

**Comment by TimSusa** [comment]
Hey, 

Project with bad performance: https://github.com/TimSusa/midi-bricks-mono/releases/tag/v1.1.66
Project with better performance: https://github.com/TimSusa/midi-bricks-mono/releases/tag/v1.1.69

Performance could percieved, when loading a preset and changing some vertical slider in live mode. That was the reason, users told me about that. I feel that I have no real hard facts for you. So how do your measure performance, by the way? ...closing this issue...

**Comment by markerikson** [comment]
Sorry, just pointing to release tags tells me nothing.  

If you can provide a sample project that specifically demonstrates visible performance issues just by switching versions, _and_ preferably some actual measurable numbers that demonstrate the changes, we can investigate further.

You might want to look at our [React-Redux benchmarks repo](https://github.com/reduxjs/react-redux-benchmarks) to see how we currently measure things.

**Comment by gpfunk** [comment]
@TimSusa did you ever figure out what was going on here? I'm experiencing the same thing, simply updating the version without actually using any of the react-redux hooks is causing major performance issues. Going to dive into deeper but was hoping you potentially had some insights

**Comment by markerikson** [comment]
@gpfunk : as I said earlier, _specific details_ on perf issues would help us analyze what's happening:

- What version of React-Redux were you using previously, and what version are you on now?
- How are you measuring performance?
- What kind of scenarios are affected?
- Can you reproduce the issue with a minimal code sample?

**Comment by gpfunk** [comment]
For sure, sorry, wasn't intending for you to respond to this comment. I'll send more information after I gather it

Just some quick details for you though

Seeing issue on react-redux 7.1.0 / 7.1.1
Performance was fine v7.0.1 (haven't checked any between these versions)
The situation I'm seeing is with our Login screen (simple text input), the input seems to flash as I type into it...It will show the character -> then not -> then show the character again (all rapidly)...almost like the store is not immediately reflecting the changes
I haven't been able to reproduce with minimal code yet

**Comment by gpfunk** [comment]
Really basic measurements, but with v7.0.1 I'm seeing updates in my component within 12ms and with v7.1.0 I'm seeing them within 20+ms...I thru a small setTimeout in v7.0.1 to slow it down and has the same experience
For whatever its worth the project is with react-native and for some reason its more apparent around the 20ms mark then it is when I try to replicate on the browser

**Comment by gpfunk** [comment]
I've tested all the versions and it appears that the issue is introduced in version v7.1.0-rc.1

**Comment by markerikson** [comment]
except that RC was just the hooks branch, retagged, and the hooks branch _shouldn't_ have any real changes to `connect`.

If you're still seeing something, I'd appreciate it if you could look through the diffs there and try to narrow it down.

**Comment by gpfunk** [comment]
Ya I'm just looking thru the commits, that is so strange. I'm definitely seeing the regression at that point though. The only thing I can see is potentially some of the updates to the dependencies? I'll keep looking into it
