### ISSUE TITLE
Hooks minimal example on codepen appreciated

### ISSUE THREAD

**Issue by TimSusa** [reduxjs/react-redux#1269]
Hey, 

I would like to get more information on how I could migrate to your new proposed hooks and yes, I have already read your documentation about that. I mean in most common cases we only have people using mapStateToProps/mapDispatchToProps and a little running example on codepen or jsfiddle would be very very nice.

Thanks in advance.

**Comment by markerikson** [comment]
We'd happily accept a PR to add a CodeSandbox example to the Hooks docs page.

Beyond that, please see these tutorials:

https://itnext.io/introducing-redux-hooks-1bf9c568ecc2

https://www.reddit.com/r/reactjs/comments/bhb3bc/react_redux_with_hooks_using_new_reactredux_71/

https://blog.jakoblind.no/react-redux-hooks/

**Comment by timdorr** [comment]
#1267 is looking to add more examples as well. I think a PR is a better form for this kind of request.
