### ISSUE TITLE
React-devtools not showing Provider storeState in 7.0.3, differs from 6.0.1

### ISSUE THREAD

**Issue by dmeehan1968** [reduxjs/react-redux#1284]
**Bug Report**

**What is the current behavior?**

- react-devtools 3.6.1 (standalone or Chrome ext)
- react-redux 7.0.3

When viewing the DOM in devtools, highlighting the Provider node and looking at the reported state, `storeState` is not shown.

Instead `store` and `subscription` are shown, which appear to be function objects, not the actual store state data.

**What is the expected behavior?**

In react-redux 6.0.1, it was possible to drill into `storeState` and see the current state (array/object depending on what was in state).

**Which versions of React, ReactDOM/React Native, Redux, and React Redux are you using?  Which browser and OS are affected by this issue? Did this work in previous versions of React Redux?**

- react-devtools 3.6.1 (standalone or Chrome ext)
- react-redux 7.0.3
- react 16.8.6
- react-dom 16.8.6

Downgrading to react-redux 6.0.1 restores functionality.

Possibly related to _Direct Component Subscriptions_ introduced in v7?

**Comment by timdorr** [comment]
We have stopped putting the full store state into context because of performance degradation. This isn't an intended feature of the library, so you should use other tools like Redux Devtools.
