### ISSUE TITLE
useSelector does not update when selector returns a map

### ISSUE THREAD

**Issue by iamawebgeek** [reduxjs/react-redux#1286]
**Do you want to request a _feature_ or report a _bug_?**
bug

**What is the current behavior?**
`useSelector` method uses `shallowEqual` util to force update when value is changed and it does not work when I compare 2 es6 maps.
```js
const map = new Map()
const newMap = new Map(map)
newMap.set('key1', 'value1')
console.log(map === newMap) // false
console.log(shallowEqual(map, newMap)) // true
```
Example
https://codesandbox.io/s/charming-jennings-mbfu5?fontsize=14

**What is the expected behavior?**
`shallowEqual` util with 2 different maps should return false

**Which versions of React, ReactDOM/React Native, Redux, and React Redux are you using?  Which browser and OS are affected by this issue? Did this work in previous versions of React Redux?**
React: v16.8.6
Redux: v7.1.0-alpha.4

**Comment by timdorr** [comment]
[We are using](https://github.com/reduxjs/react-redux/blob/master/src/utils/shallowEqual.js) the exact same code as [React uses for shallowEqual](https://github.com/facebook/react/blob/master/packages/shared/shallowEqual.js), which is the same behavior as `connect`. In general, [you shouldn't be storing non-serializable objects in your store](https://redux.js.org/faq/organizing-state#can-i-put-functions-promises-or-other-non-serializable-items-in-my-store-state), nor using them for selecting out data. There are tradeoffs and this is one of them.

**Comment by iamawebgeek** [comment]
With `connect` you can pass manual equality checking function, instead of `shallowEqual`, but there is no way to do it with `useSelector`, there is no way to fix these kind of cases and turns out I need to rewrite lots of my code, because I have different data structures used on my components. Also transforming to other data types may be overhead. I suggest to add some way to support manual comparison of values for `useSelector`
