### ISSUE TITLE
broken link on connect() README

### ISSUE THREAD

**Issue by smcalilly** [reduxjs/react-redux#1289]
There's [a link on the connect.md page](https://github.com/reduxjs/react-redux/blob/master/docs/api/connect.md#connect) that's supposed to go to a page about mapStateToProps, but the [link is broken](https://github.com/reduxjs/react-redux/blob/master/docs/using-react-redux/connect-mapstate).

**Comment by markerikson** [comment]
Erm.... which link, specifically?

Are you browsing the .md file itself, or actually reading the published version of the docs page at https://react-redux.js.org/api/connect ?
