### ISSUE TITLE
eslint(react-hooks/exhaustive-deps) warns on dispatch returned by useDispatch

### ISSUE THREAD

**Issue by dpyzo0o** [reduxjs/react-redux#1292]
**Do you want to request a _feature_ or report a _bug_?**

Bug

**What is the current behavior?**

The docs suggest to memoize `dispatch` with `useCallback`, but the eslint(react-hooks/exhaustive-deps) always gives me warning of missing `dispatch` in the dependency.

<img width="1023" alt="Screen Shot 2019-05-21 at 11 01 41" src="https://user-images.githubusercontent.com/24768249/58082924-41d22200-7bb8-11e9-9804-2680cde9ed29.png">

**What is the expected behavior?**

The demo in the docs does not have `dispatch` in the dependency array. Which behavior is correct?

<img width="811" alt="Screen Shot 2019-05-21 at 11 06 44" src="https://user-images.githubusercontent.com/24768249/58083058-8e1d6200-7bb8-11e9-986c-63f9babbd5d1.png">

**Comment by markerikson** [comment]
Yeah, the example should probably be passing `[dispatch]` as a dependency.  That's what we get for whipping out code examples as we go :)

**Comment by markerikson** [comment]
Updated the docs.

**Comment by polRk** [comment]
Are you planning to write a linter that will fix this problem?
