### ISSUE TITLE
Receiving 'Invalid hook call' when using connect and react-redux 7.0.3 

### ISSUE THREAD

**Issue by scottyj503** [reduxjs/react-redux#1303]
There appears to be an error (Invalid hook call) if I use react-redux version 7.0.3 in conjunction with using the connect object.

If I use version 6.0.1 I don't receive the same error and works as expected.

Expected behavior: No errors. 

Steps to reproduce:

https://github.com/scottyj503/react-redux-error

This is a test project that I created just for this example.  If you clone, npm install and run you will see the specific error.  

If you remove react-redux and add version 6.0.1 the code works as expected.

As a workaround I have downgraded to version 6.0.1.

**Comment by markerikson** [comment]
Well, that's very odd.

The repro project appears fairly minimal, and I can't see anything obviously wrong with it after cloning and running it.

However, if I set up a new Create-React-App project and copy-paste your exact source over to that, then it runs just fine.

We do know the library works just fine in general.  So, I'm going to have to chalk this up to your Webpack build configuration, somehow.  Sorry I can't figure out anything more beyond that.

**Comment by scottyj503** [comment]
Thanks for the quick response.
I looked further into my Webpack config and it appears that the hash option in the HtmlWebpackPlugin is causing the issue...

**Comment by Slapbox** [comment]
@markerikson I'm seeing this in Expo. Any thoughts?

There's also [this issue](https://stackoverflow.com/questions/56111755/reactjs-redux-getting-invalid-hook-call-while-using-only-while-using-connect), so at least 3 people seeing the issue so far. I tried `react-redux@7.0.3` and `react-redux@7.1.0`, but connect always throws the same error.

**Comment by Slapbox** [comment]
Unfortunately `useDispatch()` throws the exact same error.

**Comment by Slapbox** [comment]
I had two versions of React somehow. If you're running into this, it's very likely this is your issue. Use `yarn why react` to determine what versions you have installed and ensure they match.

**Comment by jingnanl** [comment]
I came across the same issue and downgrading to version 6.0.1 works for me. I also tried version 7.0.0, 7.1.0 and 7.2.0, all of them has this problem.

Btw, [similar issue](https://github.com/reduxjs/react-redux/issues/1479) was reported.

**Comment by ryan-sandy** [comment]
If anyone comes across this, you might have named your function starting with `use`. React thinks this is a [custom hook](https://reactjs.org/docs/hooks-custom.html).

**Comment by neerajdixit27** [comment]
@here : was anyone able to solve it, i get the Invalid hook call error with React-redux version 7.X.X but downgrading the version solves the issue. I see only one version of react in my project.

**Comment by Southclaws** [comment]
Getting this too, literally just an empty tutorial electron project and it doesn't work.

**Comment by markerikson** [comment]
As I've already said: we know React-Redux v7 works correctly. This issue means there's some kind of a build setup problem.

**Comment by alexpineda** [comment]
I had this issue as well using webpack electron, downgrading to 6 worked.

**Comment by markerikson** [comment]
My previous comments still stand.  The library works fine. Every single instance of this error has been build-related.

"Downgrading to v6" is not a real solution.  It avoids the error because v6 did not use hooks internally, but v6 is a dead release and is not maintained.  It also has known performance issues.

Please figure out what's wrong with your build setup and use v7 instead.

**Comment by wannymiarelli** [comment]
As a note, I had this issue after upgrading the NodeJS version. Tried everything. Removing all deps from package.json, clearning locks and node_modules. Nothing worked.

Then i tried to use npm install instead of yarn and now everything works fine. Probably something cache related?

**Comment by davidbstein** [comment]
Throwing a note here since this is a top search result for the problem.

If you are using webpack, you may need to set `react` and `react-dom` as external dependencies to avoid duplicating references. This can be done by adding the following settings to webpack config:


```
  externals: {
    "react": "commonjs react",
    "react-dom": "commonjs react-dom",
 }
```
