### ISSUE TITLE
useSelector does not work with Enzyme's context

### ISSUE THREAD

**Issue by PepijnSenders** [reduxjs/react-redux#1305]
**Do you want to request a _feature_ or report a _bug_?**

I would like to post a bug that I found in the new alpha version when used with [`enzyme`](https://airbnb.io/enzyme/).

**What is the current behavior?**

The new react-redux hooks don't pick up the enzyme's context.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to a CodeSandbox (https://codesandbox.io/s/new) or RN Snack (https://snack.expo.io/) example below:**

https://codesandbox.io/s/ecstatic-poincare-7ome2?fontsize=14

**What is the expected behavior?**

The `Component` should pick up on the context from enzyme, but only picks up the context when wrapped inside the `Provider` component.

**Which versions of React, ReactDOM/React Native, Redux, and React Redux are you using?  Which browser and OS are affected by this issue? Did this work in previous versions of React Redux?**

Everything latest and `react-redux@next`.

**Comment by timdorr** [comment]
See airbnb/enzyme#2011. They don't yet support `useContext`, which is critical to making them work.
