### ISSUE TITLE
Feature request: A way to use bindActionCreators with useDispatch hook

### ISSUE THREAD

**Issue by httpiago** [reduxjs/react-redux#1312]
**Do you want to request a _feature_ or report a _bug_?**

Feature

**What is the current behavior?**

The new redux hook api does not allow pre-bind action creators using the useDispatch hook.

**What is the expected behavior?**

It would be interesting if the useDispatch hook allows pre-bind action creators just as it is possible to do with HOC connect:

```jsx
// store/TodoStore.js
const TodoActionCreators = {
  addNewTodo: (payload) => ({ type: 'ADD_TODO', payload })
}

// components/Button.js
function Button() {
  const dispatch = useDispatch(dispatch => bindActionCreators(TodoActionCreators, dispatch))

  function handleAdd() {
    dispatch.addNewTodo({ title: 'New test item.' })
  }

  return <button onClick={handleAdd}>Add new</button>
}

export default Button
```

The same example using HOC connect:

```jsx
// store/TodoStore.js
const TodoActionCreators = {
  addNewTodo: (payload) => ({ type: 'ADD_TODO', payload })
}

// components/Button.js
function Button(props) {

  function handleAdd() {
    props.addNewTodo({ title: 'New test item.' })
  }

  return <button onClick={handleAdd}>Add new</button>
}

const mapDispatchToProps = (dispatch) => bindActionCreators(TodoActionCreators, dispatch)

export default connect(null, mapDispatchToProps)(Button)
```

**Which versions of React, ReactDOM/React Native, Redux, and React Redux are you using?**

- react-dom: 16.8.6
- redux: 4.0.1
- react-redux: 7.1.0

**Comment by timdorr** [comment]
This is already addressed in the docs: https://react-redux.js.org/api/hooks#recipe-useactions
