### ISSUE TITLE
connect breaks in expo 33

### ISSUE THREAD

**Issue by bellini666** [reduxjs/react-redux#1320]
When using `connect` as a decorator in expo SDK 33 the app will break like this:

![56112671-55bdaf00-5f8e-11e9-9f74-73fdd3633238](https://user-images.githubusercontent.com/134025/59464959-301f1b80-8e00-11e9-8419-9b3459c21b08.png)

My code is written like this:

```
@connect(
  mapStateToProps,
  mapActionsToProps,
)
class Foo extends React.Component {
```

If I set pure to `false` it will not break anymore, just like this:

```
@connect(
  mapStateToProps,
  mapActionsToProps,
  null,
  { pure: false },
)
class Foo extends React.Component {
```

This is related to this issue (https://github.com/reduxjs/react-redux/issues/1244) and this one (https://github.com/facebook/react-native/issues/24452).

I didn't have this issue in expo 32 and previous versions.

**Comment by markerikson** [comment]
If it worked fine in prior versions of Expo, then I would expect the issue is on Expo's side somehow.

Actually, yeah, looking at that RN 24452 issue, it seems like it's something to do with a `react-proxy` lib?  So, nothing we can do on our side based on that.
