### ISSUE TITLE
Components using connect will not update in react-native (expo 33) production mode

### ISSUE THREAD

**Issue by bellini666** [reduxjs/react-redux#1321]
My app uses react-redux with expo since version 26 and always worked fine.

After I upgraded it to expo SDK 33, my components are not updating in production mode anymore. In development mode everything works fine though.

I tested it with `6.0.1` (the version I was using with SDK 22), `7.0.1` and the newly released `7.1.0` (which I had to workaround some issues as I described [here](https://github.com/reduxjs/react-redux/issues/1320)). All of them are presenting the same issue.

Since the error only happens in production mode I don't really know how to properly debug it or extract more info.

**Comment by markerikson** [comment]
As per the other issue, the fact that this only occurs in Expo 33 suggests the problem is on their side.

**Comment by bellini666** [comment]
@markerikson hrm, there's something strange now. I just tried to create a snipped of code using expo to open an issue there, but the issue didn't happen.

Not only I didn't have to workaround the `{ pure: false}` as I mentioned in the other issue, but the code worked in both development and production.

So, that doesn't seems to be an issue with expo (and might not be yours also). Do you have any idea of what might be causing that?

**Comment by markerikson** [comment]
Not off the top of my head, unless you happen to be accidentally mutating state somewhere.

**Comment by bellini666** [comment]
@markerikson I just discovered the issue!

I have a component declared as this:

```
@withNavigation
@connect(...)
class Foo extends React.Component {
  ...
}
```

As I said before, this worked until expo 32 in both development and production just fine. In expo 33, it works fine in development mode but not in production.

So, after trying some things, I tried changing the order of the decorators and it worked in production. I changed to something like this:

```
@connect(...)
@withNavigation
class Foo extends React.Component {
  ...
}
```

Does that makes any sense for you?

Since after changing the order the problem resolved itself, I think it is probably an issue here or in `react-navigation`. Just say if that makes sense to you, and if not, I'll open an issue in there

**Comment by bellini666** [comment]
@madbonkey ok, nevermind my last comment. After the issue happened again, I started googling a little more and found this: https://github.com/reduxjs/react-redux/issues/1125#issuecomment-447405203

My issue was exactly that =P

Sorry for bothering you
