### ISSUE TITLE
code comment recommends using useActions hook in most cases where one would want to use the useDispatch hook

### ISSUE THREAD

**Issue by bmwadforth** [reduxjs/react-redux#1322]
There is a comment in the source code within the useDispatch file located under /src/hooks/useDispatch  that recommends instead of using useDispatch, it is recommended to use the useActions hook in most cases. This comment contradicts the documentation found [here](https://react-redux.js.org/next/api/hooks#recipe-useactions). 

Specifically, the documentation mentions the useActions hook has been removed.

Thus, the comment within the useDispatch source code should be updated.

**Comment by timdorr** [comment]
Can you submit a PR?
