### ISSUE TITLE
Propose a shorthand to useSelector

### ISSUE THREAD

**Issue by ZYinMD** [reduxjs/react-redux#1327]
Do you guys think it's a good idea to make `useSelector` take an object as a shorthand?

Basically just destructure the store:
`const foo = useSelector(state => state.foo)`;
 can be written as
`const foo = useSelector({ foo });`

`const bar = useSelector(state => state.foo.bar)`
 can be written as
`const bar = useSelector({ foo: { bar } })` 

It may be a very bad idea, just throwing it out there ~

**Comment by markerikson** [comment]
The idea of an "object shorthand" for `mapState` has been proposed numerous times, and we eventually decided it wasn't worth it.  For `useSelector` particularly, I don't think it's a _bad_ idea, but I don't see much benefit.
