### ISSUE TITLE
areStatesEqual and state comparisons in Provider

### ISSUE THREAD

**Issue by sktw** [reduxjs/react-redux#1328]
**What is the current behavior?**

The `connect` function accepts an option `areStatesEqual`, which is a custom function used by `connect` to compare the current store state to its previous value. However, code inside the `Provider` also performs state comparisons, and these always use strict equality (=== or !==). This inconsistency in how states are compared can lead to unexpected behavior.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to a CodeSandbox (https://codesandbox.io/s/new) or RN Snack (https://snack.expo.io/) example below:**

The following sandbox illustrates a bug that can result from this issue with react-redux v6 in a scenario described in the documentation.

https://codesandbox.io/s/zen-rubin-w3ut5

The second example in the [documentation](https://react-redux.js.org/api/connect#arestatesequal-next-object-prev-object-boolean) for `areStatesEqual` concerns having an impure reducer that mutates the store state. It is recommended to have `areStatesEqual` always return false (i.e. `areStatesEqual = () => false`) to ensure that state mutations still cause re-rendering.

The sandbox example implements a simple counter. The reducer is impure, and mutates the store state. The `areStatesEqual` function described above is provided to `connect`.

With react-redux v6.0.1 clicking the 'Increment x' button does not update the rendered count.

With react-redux v7.1.0 clicking the 'Increment x' button increments the rendered count, as expected.

**What is the expected behavior?**

In the example above, setting `areStatesEqual = () => false` should allow re-rendering when the store state is mutated. More generally, the expected behavior is that all state comparisons should use `areStatesEqual` if provided. 

**Which versions of React, ReactDOM/React Native, Redux, and React Redux are you using?  Which browser and OS are affected by this issue? Did this work in previous versions of React Redux?**

In react-redux v6 the `Provider` makes a number of state comparisions. In particular, the callback provided to the store in the `subscribe` function will only trigger a re-rendering if the current and previous store states fail a strict equality comparison. It is this that causes the counter not to update in the example above.

In react-redux v7 the `Provider` has been substantially re-written. The only state comparision remaining is in `componentDidMount`, presumably to handle state changes that occur between render and mount. The bug therefore also exists in v7, but in a much more restricted way.

**Comment by timdorr** [comment]
Woah, what is this about impure reducers? That is a violation of one of the fundamental rules of Redux. That shouldn't be in there at all. Your reducers have to be pure functions. That reducer should have something like `return { x: state.x + 1, ...state }` in it. 

We're not supporting 6.0 anymore. That implementation was fundamentally flawed. If you need to support an older version of React, you should use a 5.x version. If there's a visible bug in 7.0, we can address it. But if it's caused by an impure reducer, that's a flaw in the reducer, not the library.

**Comment by sktw** [comment]
I completely agree that impure reducers break a fundamental rule of redux, but the [documentation](https://react-redux.js.org/api/connect#arestatesequal-next-object-prev-object-boolean) for `areStatesEqual` specifically mentions this possiblity:

> Example 2
> If you have impure reducers that mutate your store state, you may wish to override areStatesEqual to always return false:
> const areStatesEqual = () => false
> This would likely impact the other equality checks as well, depending on your mapStateToProps function.

This example is present in the documentation at least as far back as v5.

In principle, the method outlined in the documentation would allow react-redux to work with an impure reducer, but only if all state comparisions use the supplied `areStatesEqual` function rather than strict equality.

So I'd suggest that either you:

1. Update the code so that all state comparisons use `areStatesEqual` if supplied.
2. Or, remove the impure reducers example from the documentation.
