### ISSUE TITLE
react-redux v7 useSelector not re-render

### ISSUE THREAD

**Issue by JasonJie** [reduxjs/react-redux#1330]
This code used to work in react-redux v7.1.0
This is my demo.
https://codesandbox.io/s/trusting-sun-07mrh

const todo = useSelector(state => state.todo); not re-render
const todo = useSelector(state => state.todo , () => {}); it's re-render

**Comment by markerikson** [comment]
You're mutating in the reducer:

```js
    case "add":
      const { todo } = state;
      todo.push(action.payload);
      return Object.assign({}, state, { ...state, todo }); 
```

[That is not a proper immutable update](https://redux.js.org/recipes/structuring-reducers/immutable-update-patterns).  Don't do that :)

I'd encourage you to ]use the `configureStore()` function from Redux Starter Kit](https://redux-starter-kit.js.org/api/configureStore), which will throw errors when you mutate.
