### ISSUE TITLE
Rendering connected component with undefined 'mergedProps' parameter throws TSLint error 2739

### ISSUE THREAD

**Issue by StrikeAgainst** [reduxjs/react-redux#1332]
I ran into an issue using React Redux together with TypeScript and TSLint.

I added the option parameter to the connect function for my component, having to put a nullified parameter for mergeProps in between.

```
export default connect<PropsFromState, PropsFromDispatch, OwnProps>(
    mapStateToProps,
    mapDispatchToProps,
    null,
    { forwardRef : true }
)(MyComponent);
```

**What is the current behavior?**

Wanting to render the component throws a TSLint error for me:

`<MyComponent ownProp ref={ref => this.comp = ref}/>`

> Type '{ ownProp: true; ref: (ref: Component<Pick<MyComponent, "ownProp" | "stateProp" | "dispatchProp"> & OwnProps, any, any>) => Component<...>; }' is missing the following properties from type 'Readonly<Pick<MyComponentProps, "ownProp" | "stateProp" | "dispatchProp"> & OwnProps>': stateProp, dispatchProp - ts(2739)

...basically asking for state and dispatch props where it shouldn't ask for them.

Tracing back the type definition of connect (via Visual Studio Code), it refers me to

```
<TStateProps = {}, TDispatchProps = {}, TOwnProps = {}, TMergedProps = {}, State = {}>(
	mapStateToProps: MapStateToPropsParam<TStateProps, TOwnProps, State>,
	mapDispatchToProps: MapDispatchToPropsParam<TDispatchProps, TOwnProps>,
	mergeProps: MergeProps<TStateProps, TDispatchProps, TOwnProps, TMergedProps>,
	options?: Options<State, TStateProps, TOwnProps, TMergedProps>
): InferableComponentEnhancerWithProps<TMergedProps, TOwnProps>;
```

**What is the expected behavior?**

The component should render without any issues, not asking for state and dispatch props.

The type definition of connect should actually refer to

```
<TStateProps = {}, TDispatchProps = {}, TOwnProps = {}, State = {}>(
	mapStateToProps: MapStateToPropsParam<TStateProps, TOwnProps, State>,
	mapDispatchToProps: MapDispatchToPropsNonObject<TDispatchProps, TOwnProps>,
	mergeProps: null | undefined,
	options: Options<State, TStateProps, TOwnProps>
): InferableComponentEnhancerWithProps<TStateProps & TDispatchProps, TOwnProps>;
```

**Which versions of React, ReactDOM/React Native, Redux, and React Redux are you using?  Which browser and OS are affected by this issue? Did this work in previous versions of React Redux?**

React - 16.8.6
ReactDOM - 16.8.6
React Redux - 7.1.0
Redux - 4.0.1
TypeScript - 3.5.2
TSLint - 5.16,0
OS - Win 10 Enterprise x64
I haven't tested this with any previous version of React Redux.

**Comment by timdorr** [comment]
We don't maintain the typings. Please refer to the support resources for DefinitelyTyped.

**Comment by StrikeAgainst** [comment]
Alright, I'll move the issue there, thank you.
