### ISSUE TITLE
react-redux-7.1.0 Provider undefined in tests

### ISSUE THREAD

**Issue by Meemaw** [reduxjs/react-redux#1333]
**What is the current behavior?**
I am trying to write some tests for our custom hooks that use redux. I soon realized that any import from `react-redux` in tests only include the `connect` function. Is this expected? Using Jest as a test runner and CRA to run them.

```js
import { Provider } from "react-redux"

console.log(Provider) // undefined

...
```

**What is the expected behavior?**

Provider to be defined.

**Which versions of React, ReactDOM/React Native, Redux, and React Redux are you using?  Which browser and OS are affected by this issue? Did this work in previous versions of React Redux?**

```sh
react/react-dom: 16.8.2
react-redux: 7.1.0
redux: 4.0.1
```

**Comment by timdorr** [comment]
Nope, that's not normal, but it's not caused by the library. You might have a bad npm install (blow away node_modules and reinstall) or something else is interfering.

**Comment by StKostyantin** [comment]
> Nope, that's not normal, but it's not caused by the library. You might have a bad npm install (blow away node_modules and reinstall) or something else is interfering.

I have the same problem and have checked the modules node. There is a Provider. Even reinstalled packages.

```
import React from 'react';
import { render as rtlRender } from '@testing-library/react';
import { Provider } from 'react-redux'
import { mockStore } from './tests/moksData';

function render(
  ui,
  {
    initialState,
    store = mockStore,
    ...renderOptions
  } = {}
) {
  const Wrapper = (props) => {
    console.log('Provider===', Provider) //undefined
    return <Provider store={store}>{props.children}</Provider>;
  };
  return rtlRender(ui, { wrapper: Wrapper, ...renderOptions });
}

// re-export everything
export * from '@testing-library/react';
// override render method
export { render };
```

**Comment by StKostyantin** [comment]
I found the reason for the error.

```
jest.mock('react-redux', () => ({
  connect: () => jest.fn(),
  useSelector: jest.fn(fn => fn()),
  useDispatch: () => jest.fn()
}));
```

I mocked this library and this led to the fact that I could not use the Provider in tests

**Comment by rampazzo1989** [comment]
> I found the reason for the error.
> 
> ```
> jest.mock('react-redux', () => ({
>   connect: () => jest.fn(),
>   useSelector: jest.fn(fn => fn()),
>   useDispatch: () => jest.fn()
> }));
> ```
> 
> I mocked this library and this led to the fact that I could not use the Provider in tests

Man, you saved my day. I'm maintaining a test file, creating new tests, and that passed unnoticed. Thank you!

**Comment by markerikson** [comment]
Hah, nice :) For the record we would really recommend _against_ trying to mock the `react-redux` lib or any of its APIs.  Instead, we recommend actually creating real Redux stores in tests and rendering a `<Provider store={store}>` around the component tree being tested:

https://redux.js.org/usage/writing-tests#components
