### ISSUE TITLE
react-redux 6.0.1: dispatch() is sending action to wrong store after store change

### ISSUE THREAD

**Issue by compulim** [reduxjs/react-redux#1339]
> I know react-redux@6 may not be supported. Please feel free to close if it is not supported.

## Description

Initially, we assign a store to `<Provider store={ storeA }>`. Then in the logic of a connected component, we call `props.dispatch()`, everything works fine.

Then we create a new store, namely `storeB` and switch to it thru `<Provider store={ storeB }>`. The subsequent `props.dispatch()` does not send actions to `storeB` but keep sending to `storeA`.

It does not repro on `react-redux@^7`.

## Repro steps

You can find the live repro at https://codesandbox.io/embed/brave-leftpad-8bkfs.

1. Create a new React project by `npx create-react-app your-app`
1. `npm install redux react-redux@6 --save`
1. Modified `src/App.js` as in CodeSandbox
1. `npm start`
1. Navigate to http://localhost:3000/
1. Click "Increment", notice the value changed to 1
1. Click "Use store B"
1. Click "Increment" again

### Actual

Notice after clicking "Increment" on step 8, the value did not change to 1.

If you click "Use store A", you will see the value changed to 2. It means the `props.dispatch` is being called on store A instead of B.

### Expected

It should increment the value in store B to 1. The value in store A should still 1.

## Versions

- `react@16.8.6`, `react-dom@16.8.6`
- `redux@4.0.1`
- `react-redux@6.0.1`
   - Also repro on `react-redux@6.0.0`
   - Not repro on `react-redux@7.0.0` and `react-redux@7.1.0`

**Comment by timdorr** [comment]
We're no longer supporting 6.0. You should use either 5.x or 7.x.
