### ISSUE TITLE
usePrevious not working with useSelector

### ISSUE THREAD

**Issue by andreifilip123** [reduxjs/react-redux#1343]
**Do you want to request a _feature_ or report a _bug_?**
Report a _bug_

**What is the current behavior?**
When trying to save a variable from store in a reference for saving the previous state, the reference is set to be `undefined` because on the first render, data from store isn't there yet.
[https://reactjs.org/docs/hooks-faq.html#how-to-get-the-previous-props-or-state](https://reactjs.org/docs/hooks-faq.html#how-to-get-the-previous-props-or-state)

```
function App() {
  const appState = useSelector(state => state.app.state);

  const prevAppState = usePrevious(appState); // prevAppState = undefined

  useEffect(() => {
    if (prevAppState === "background" && appState === "active") {
      console.log("App in foreground");
    }
  }, [appState, prevAppState]);

  return (
    <Text>Whatever</Text>
  );
}
```

**What is the expected behavior?**
The expected behaviour would be to save in `prevAppState` the previous app state. Instead, I get undefined.

**Which versions of React, ReactDOM/React Native, Redux, and React Redux are you using?  Which browser and OS are affected by this issue? Did this work in previous versions of React Redux?**
React: 16.8.6
React Native: 0.59
React Redux: 7.1.0

**Comment by markerikson** [comment]
Um... not sure what you're trying to say here, but this doesn't sound like a bug in React-Redux.

**Comment by jondelga** [comment]
For other people who may encounter this:

If you have multiple routes pointing to the same component, The component will re-render when using the `component` and/or `renter` prop but not the `children` prop. This can explain the `usePrevious` behavior.

**Comment by brayanL** [comment]
This is a real bug, maybe have any solution?

**Comment by markerikson** [comment]
@brayanL That's not a very helpful comment :(

If you think there's an actual bug, please post a CodeSandbox that specifically demonstrates the issue.
