### ISSUE TITLE
Question: Possibly unwanted change in combination with enzyme shallow.

### ISSUE THREAD

**Issue by niels-van-den-broeck** [reduxjs/react-redux#1346]
Since the support for passing the store as a prop has been reimplemented I am trying to upgrade our project to React-Redux v7. 

However I am bumping into something rather peculiar. Between version 5 and 7 something has changed that makes the enzyme shallow renderer not pass the props to the wrapping component anymore.
[Sandbox for reference](https://codesandbox.io/s/react-redux-57-j26b4)
In this sandbox you can alternate between the last v5 release and latest to see the change.

The reason we write these tests is to check if the props are properly wired onto the component.
I wonder if this change is intentional/unavoidable, or if this is an oversight. 

Kind regards.

**Comment by timdorr** [comment]
I'm not sure why that would work before. The wrapper component shouldn't be getting those props, as they're supposed to only be applied to the wrapped component. You should be doing what the v7 test does anyways.
