### ISSUE TITLE
shallowEqual should be generic

### ISSUE THREAD

**Issue by ViktorWb** [reduxjs/react-redux#1348]
When using TypeScript, the return type of useSelector() gets automatically inferred from the arguments passed, which is great. But when using shallowEqual as the equality function, the return type becomes any.

```javascript
import { useSelector } from 'react-redux'
// Here, stateProp correctly gets inferred as string.
const stateProp = useSelector((state: { stateProp: string }) => state.stateProp)

import { useSelector, shallowEqual } from 'react-redux'
// But now, stateProp becomes any.
const stateProp = useSelector((state: { stateProp: string }) => state.stateProp, shallowEqual)
```

The return type should still be string.

This happens because the 'left' and 'right' arguments for the shallowEqual function have type 'any'.

To fix this, shallowEqual should be generic.

```javascript
function shallowEqual<T = any>(left: T, right: T): boolean
```

This would allow TypeScript to infer the types of 'left' and 'right', instead of forcing them to 'any'. This would in turn allow the return value of useSelector to be correctly inferred.

**Comment by markerikson** [comment]
We don't maintain the TS typings ourselves - those are handled in DefinitelyTyped.
