### ISSUE TITLE
[Feature-Request] connect mapStateToProps shallowCompare with array

### ISSUE THREAD

**Issue by WarmVissarutRonaldoDude** [reduxjs/react-redux#1353]
### Descriptions ###

Currently `mapStateToProps` only compare by using `===` which in some case like `[] === []` will return `false` so it might be good to support it from here.

I can help open PR here if you think it's useful.

**Comment by timdorr** [comment]
We provide [an areStatesEqual option](https://react-redux.js.org/api/connect#arestatesequal-next-object-prev-object-boolean) so you can override this behavior.
