### ISSUE TITLE
what is the batch method do for?

### ISSUE THREAD

**Issue by Frank1e0927** [reduxjs/react-redux#1359]
help want.

i dont't understand this method use for some case

https://github.com/reduxjs/react-redux/blob/master/src/index.js#L14

https://github.com/reduxjs/react-redux/blob/master/src/utils/Subscription.js#L11

is there something connection with this one ? https://github.com/acdlite/redux-batched-updates

**Comment by markerikson** [comment]
Please read the API docs:

https://react-redux.js.org/api/batch
