### ISSUE TITLE
v7.1.0 changelogs conflict

### ISSUE THREAD

**Issue by illuminist** [reduxjs/react-redux#1363]
**Do you want to request a _feature_ or report a _bug_?**

Not quite a bug but need some action.

**What is the current behavior?**

Currently in release note of version v7.1.0 there are both
- Add deps argument to useSelector (#1251 by @MrWolfZ)
- Remove deps argument (#1272 by @josepot)

at same time which are conflicting and quite confusing without reading an entire change log and compare which one is actually implemented

**What is the expected behavior?**

"Add deps argument to useSelector" should be removed(or mark it as has been removed). left only "Remove deps argument"

**Which versions of React, ReactDOM/React Native, Redux, and React Redux are you using?  Which browser and OS are affected by this issue? Did this work in previous versions of React Redux?**

React Redux v7.1.0 release notes

**Comment by timdorr** [comment]
This is just to show some of the discussion that happened along the way. We ended up remove a fair number of things in the end, so I think it's important to preserve that knowledge. As always, consult the docs for the most up to date info on the APIs and their usage.
