### ISSUE TITLE
When using the object form of mapDispatchToProps in typescript, type errors are thrown

### ISSUE THREAD

**Issue by zjb19970804** [reduxjs/react-redux#1369]
My async action is similar to this:
`export const changeSearch = (val: string) => (dispatch: Dispatch<any>) => {
  dispatch(searchAction(val));
  getSearchRes().then(res => {
     const { totalNum, data } = res;
     dispatch(saveSearchResAction({ totalNum, data }));
  });
};`

Then I use it in my component:
`export default connect(
  null,
  { changeSearch }
)(Search);`

typeescript gives the error message:
`The type "(val: string) => void" cannot be assigned to the type "(val: string) => (dispatch: Dispatch<any>) => void"`

If mapDispatchToProps uses the form of a return function, it is normal.
`(dispath: Dispatch) => ({ changeSearch: (val: string) => dispath<any>(changeSearch(val)) })`

Is there any problem with the way I use it?

**Comment by timdorr** [comment]
We don't maintain the types for React Redux. Please consult the support resources for DefinitelyTyped.
