### ISSUE TITLE
Connected components are not correctly typed

### ISSUE THREAD

**Issue by JoseCarlosNS** [reduxjs/react-redux#1372]
## The problem

The `connect` function of `react-redux` is not returning a properly typed component, instead seems to be returning a `any` value, which breaks all the type-safety and intellisense of my Typescript code.

## Context

So I'm working on a React-native project on my job and I decided to use Typescript for type-safety and autocomplete/intellisense features on my IDE of choice (Visual Studio Code). So using that I would define a component like this: 

```tsx
interface Props {
  label: string;
}

class CustomComponent extends Component<Props> {
  render(): ReactElement {
    return (
      <View>
        <Text>{this.props.label}</Text>
      </View>
    );
  }
}

export default CustomComponent;
```

And I would get the expected behavior, that is proper type-checking and autocompletion features on VS Code:

![image](https://user-images.githubusercontent.com/28950443/62570072-a91d7b00-b865-11e9-8776-443b7090f484.png)

That error on the component its because its lacking the `label` prop, that I defined in the component's `Props` interface, and since I didn't define any `defaultProps` or marked it with the optional flag (`?`) it makes it a required prop.

But lets say I want to connect that component to my Redux Store, then I would use the `connect` function of `react-redux` and map props and/or action creators to it, like this:

```tsx
// Properties passed from the parent component
interface OwnProps {
  label: string;
}

// Properties passed from the store
interface StoreProps {
  theme: 'light' | 'dark';
}

// Props of the component
type Props = OwnProps & StoreProps;

class CustomComponent extends Component<Props> {
  render(): ReactElement {
    return (
      <View>
        <Text
          style={{ color: this.props.theme === 'light' ? 'white' : 'black' }}
        >
          {this.props.label}
        </Text>
      </View>
    );
  }
}

// The store structure, defined here for the sake of simplicity
interface Store {
  theme: 'light' | 'dark';
}

const mapStateToProps = (state: Store): StoreProps => {
  const { theme } = state;

  return {
    theme
  };
};

export default connect(mapStateToProps)(
  CustomComponent
);
```

But when I do this the component loses all type-safety and autocompletion, where it basically accepts any prop with any value, and the IDE doesn't detect its possible props:

![image](https://user-images.githubusercontent.com/28950443/62571327-75dbeb80-b867-11e9-9cbc-78e027aba546.png)

The code works as expected, but it loses all features that made me use typescript in the first place, so thats a no no.

After searching basically everywhere on the interwebs and asking on 2 slack channels and a discord server, I couldn't find an answer for this riddle. But I found something: **it seems that the `connect` function, even with proper generic type arguments, is returning a `any` value and, obviously, thats not a properly typed React component!**

![image](https://user-images.githubusercontent.com/28950443/62572096-56de5900-b869-11e9-82ff-4cf081f8bbf9.png)

So what am I doing wrong? I've been through basically dozens of articles and guidelines about how to properly type redux-connected components, and it just doesn't work, and I kinda need this to work, because deadlines. Please help, send the eagles.

## Environmnent

**`react-native info`:**

```
System:
    OS: Linux 4.15 Linux Mint 19.1 (Tessa)
    CPU: (4) x64 Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
    Memory: 271.08 MB / 7.71 GB
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 12.4.0 - ~/.nvm/versions/node/v12.4.0/bin/node
    Yarn: 1.17.3 - ~/.nvm/versions/node/v12.4.0/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v12.4.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: ^0.60.4 => 0.60.4 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

**`package.json`:** _(I've ommited some unrelated dependencies for the sake of simplicity)_ 

```json
"dependencies": {
    "react": "16.8.6",
    "react-native": "^0.60.4",
    "react-redux": "^7.1.0",
    "redux": "^4.0.4",
    "redux-thunk": "^2.3.0",
  },
  "devDependencies": {
    "@types/react": "^16.8.23",
    "@types/react-native": "^0.60.1",
    "@types/react-redux": "^7.1.0",
    "@types/redux-thunk": "^2.1.0",
  }
```

**Comment by markerikson** [comment]
We don't maintain the TS typings ourselves.  Those are over in DefinitelyTyped.

**Comment by markerikson** [comment]
Having said that: I myself am still relatively new to using TS, and I'm just starting to try actually using `connect()` in a TS project.  So, A) I don't have any real expertise on this subject, and B) I'm kinda trying to figure out how this works too.

I certainly wouldn't expect `connect()` to be treating things as `any` - that seems broken.  _Why_ it's doing that, I have no idea.

**Comment by JoseCarlosNS** [comment]
@markerikson The thing is, all articles seems to point that the `connect` function should be correctly typed, if you pass the generic type arguments, like so:

```tsx
connect<StoreProps, void, OwnProps, Store>(
  mapStateToProps
)(CustomComponent);
```

But generic type arguments or not, the problem persists. Since you said you guys are not the ones typing the package, I'll just try to open an issue at DefinitelyTyped.

The workaround I found was to use the `typeof` operator in the default export, like this:

```tsx
const connectedComponent: typeof CustomComponent = connect<
  StoreProps,
  {},
  OwnProps,
  Store
>(mapStateToProps)(CustomComponent);

export default connectedComponent;
```

With that typescript works as expected with type-checking and intellisense, but still thats just a workaround and may cause unexpected behavior down the line.

**Comment by abdnaqeeb** [comment]
Try install @types/react-redux
