### ISSUE TITLE
Feature / Discussion : useSaga

### ISSUE THREAD

**Issue by lukebrandonfarrell** [reduxjs/react-redux#1375]
Hey all,

We've converted two applications so far to 'use' the new react-redux API and everything works and looks great! I'm opening this issues to start a discussion on a possible hook for this library.

I'm not even sure if this would belong in this library, maybe it would be beneficial opening this issue in the redux-saga repository (as it is inspired by redux-saga), but since this is `react-redux`, I think its good introducing it here first.

One of the issues we have in our production apps is how can components respond to actions, e.g. CREATE_TODO_SUCCESS should trigger a navigation to next page when we are on that page (at the minute we are using a reducer to keep track of the current page then using sagas to respond to the successful event), but with hooks there seems to be a better way! 

Below is a hook which uses `Redux.subscribe` to listen to the store and trigger a callback when a specific action is dispatched. Components can listen directly to actions dispatched and respond by updating their local state, navigating, etc...

#### Usage
```
useSaga((action) => {
   // Set local state for component / navigate to next screen / show pop-up etc...
}, store, CREATE_TODO_SUCCESS)
```

#### Implementation

```
export function useSaga(effect, store, type) {
  const currentValue = useRef(null);

  const handleChange = () => {
    const state = store.getState();
    const action = state.action;
    let previousValue = currentValue.current;
    currentValue.current = action;

    if (previousValue !== action && action.type === type) {
      effect(action);
    }
  };

  useEffect(() => {
    const unsubscribe = store.subscribe(handleChange);
    return () => unsubscribe;
  }, []);
}
```

This is the current implementation, although there are some caveats with this, so the final solution would probably look much different.

#### Caveats
- We need to create an action reducer to keep track of the last action (currently this is setup as a reduce in our application, but ideally this would need to be kept in the library, using `useReducer` so the consumer does not have to declare an extra reducer in their application)
- We need to pass the store as an argument (I'm not sure if there is any workaround with this using react-redux provider and context? I'm not very familiar with the react-redux internals)
- We need to listen to `store.subscribe` on every `useSaga` (This may have performance costs?)

NOTE: I've debated between calling this: `useListen`, `useSaga` and `useSubscribe` so don't pay too much focus to the name, as it surely will change.

Let me know what you all think

**Comment by markerikson** [comment]
Appreciate the idea, but there's no reason to include this in React-Redux directly.  

Similar to how React provides a bunch of "primitive" hooks like `useState` and `useEffect` and lets you build your own custom hooks on top, we provide `useSelector`, `useDispatch`, and `useStore`.  You should be able to build whatever custom hooks you want on top of those.  (`useStore` specifically answers your question about "how to access the store".)

Also, I also wouldn't suggest calling this `useSaga()`, since this doesn't actually involve the saga middleware.

**Comment by lukebrandonfarrell** [comment]
Hey thanks for the feedback @markerikson, I forgot about `useStore`!
