### ISSUE TITLE
why React-Redux  not use Context.Consumer wrap the wrappedComponent?

### ISSUE THREAD

**Issue by xiaoxiaosaohuo** [reduxjs/react-redux#1376]
in source code I found we use Provider wrap the wrappedComponent,
why React-Redux  not use Context.Consumer wrap the wrappedComponent?
```
<ContextToUse.Provider value={overriddenContextValue}>
        {renderedWrappedComponent}
 </ContextToUse.Provider>
```

**Comment by markerikson** [comment]
Uh... the question doesn't make sense. You _have_ to use a `Context.Provider` to make the value available to nested components.  You use a `Context.Consumer` to _access_ the value inside a nested component.
