### ISSUE TITLE
Request: Provide a hook to fetch an object from state by reference or to make a reference stateful

### ISSUE THREAD

**Issue by shamilovtim** [reduxjs/react-redux#1378]
Let's say from props I have a reference to an object of type `listitem` and my store state looks like this:

props
```
const  MyComponent =  (props:listItem) => {
let myID:number = props.listItem.id;
}
```

store
```
todos:{todos}
whitelist: [ {listitem} ]
blacklist:[ {listitem} ]
```

I could do a `useSelector(state)` get the whole state, `concat` both the whitelist and the blacklist, and then execute a `find(id)` in order to find the right object in both of these arrays by the id that I pulled off the object in my props. But wouldn't it be cool and imperative to be able to find the correct item in the whole store right by the reference to the object? So if I could find it in my store by simple doing `useSelector(state, listItem)` and get back the same object but that the component will know to re-render for. Alternatively, could there be a way of wrapping the reference from props in some sort of hook in order to make the reference stateful again?

**Comment by markerikson** [comment]
I'm not quite sure what you're asking for here, but we don't plan on changing our hooks API at the moment.

That said, you might want to look at https://github.com/dai-shi/reactive-react-redux , which provides some alternative Redux hooks based on proxies.

**Comment by shamilovtim** [comment]
Just was wondering if there could be a hook to make a reference to an object passed from props stateful again. Basically this would prevent having to dig through the state in order to get to the same object using useSelector
