### ISSUE TITLE
Use hooks with haunted library

### ISSUE THREAD

**Issue by askbeka** [reduxjs/react-redux#1384]
Hi,
There is an issue https://github.com/matthewp/haunted/issues/126
Which resulted in this https://next.plnkr.co/edit/8lukaUKTSzv6HOn5, experiment

Looks like react-redux hooks can work not only with React,
Is there any chance that this library good extract hooks outside with loose coupling on react package?

Se plunkr above, for things that are worked around

Thanks

**Comment by timdorr** [comment]
No, since these are the React bindings for Redux. You would write your own bindings for Haunted or other UI libraries.

**Comment by askbeka** [comment]
@timdorr I do understand your point. It can be done, but will result in duplication.
I think everyone appreciates when duplication is avoided;

But anyway can be a separate package for sure:)
