### ISSUE TITLE
Unnecessary import of "useCallback" in "useDispatch" example in "index.d.ts"

### ISSUE THREAD

**Issue by ROiPinheiro** [reduxjs/react-redux#1401]
**Do you want to request a _feature_ or report a _bug_?**

Unnecessary import in _index.d.ts_ doc's

**What is the current behavior?**

In line 498 of "index.d.ts" have a useless import  "useCalback":

```js
import React, { useCallback } from 'react'
import { useDispatch } from 'react-redux'
 
export const CounterComponent = ({ value }) => {
  const dispatch = useDispatch()
    return (
      <div>
        <span>{value}</span>
        <button onClick={() => dispatch({ type: 'increase-counter' })}>
          Increase counter
        </button>
      </div>
    )
  }
```

**What is the expected behavior?**

I think it should be same as [doc's](https://react-redux.js.org/api/hooks#usedispatch)

```js
import React from 'react'
import { useDispatch } from 'react-redux'
 
export const CounterComponent = ({ value }) => {
  const dispatch = useDispatch()
    return (
      <div>
        <span>{value}</span>
        <button onClick={() => dispatch({ type: 'increase-counter' })}>
          Increase counter
        </button>
      </div>
    )
  }
```

React: *16.9.0*
ReactDOM: *16.9.0*
Redux: *4.0.4*,
React-Redux: *7.1.1*

**Comment by timdorr** [comment]
We don't maintain the typings on this library. Please consult the support resources for DefinitivelyTyped.
