### ISSUE TITLE
Component using `ReactReduxContext` is not re-rendered after redux's `injectReducer` call 

### ISSUE THREAD

**Issue by alex-gokkun** [reduxjs/react-redux#1408]
**Do you want to request a _feature_ or report a _bug_?**
Bug

**What is the current behavior?**
The demo is available here: https://codesandbox.io/embed/ecstatic-goodall-dvgq4
The demo is purposely the bare bones so that the issue can be seen more clearly. Later on, I'll try my best to explain how the same issue may reveal itself in a real-life situation.

We've created the app and enhanced the store with `injectReducer` functionality (implementation of `injectReducer` is basically [stolen from Redux official docs](https://redux.js.org/recipes/code-splitting#defining-an-injectreducer-function)). A component, `Indicator` that is, calls `useContext` with `ReactReduxContext` as an argument. `Indicator` returns a green square if the store has a reducer under `xxx` key and a red square otherwise. Another component, `Injector`, also uses `ReactReduxContext` but to provide a user with a button by clicking on which the user can inject the aforementioned `xxx` reducer into the store. So what happens is that when we do indeed inject the reducer none of our components get re-rendered and it happens due to the fact that `ReactReduxContext` isn't updated. 

**What is the expected behavior?**
`Indicator` to be re-rendered after `injectReducer` call due to `ReactReduxContext` change.

**Which versions of React, ReactDOM/React Native, Redux, and React Redux are you using?  Which browser and OS are affected by this issue? Did this work in previous versions of React Redux?**
`react@16.8.4`
`redux@4.0.4`
`react-redux@7.1.1`

**Any real-world examples?**
I encountered this issue while working on the following feature. Let's say we have a route that relies on some dynamic reducer. If the route is the only consumer of that reducer, it makes perfect sense to inject the reducer from within that route. Also, since the reducer is dynamically injected, it makes sense to have a 'guard' component at the top of the route. The guard will allow its children to be rendered only after the reducer has been injected.

```code
export const useDynamicReduxReducer = (key: string, reducer: Reducer): boolean => {
  const storeContext = React.useContext(ReactReduxContext);

  React.useEffect(() => {
    storeContext.store.injectReducer(key, reducer);
  }, []);

  return storeContext.store.isReducerReady(key);
}
```
```
export const Guardian = props => {
  const isDynamicStateReady = useDynamicReduxReducer('reducerKey', reducerItself);

  return isDynamicStateReady ? props.children : null;
}
```
When `Guardian` is called for the first time, it injects the reducer and returns `null`. But since `ReactReduxContext` is not updated after the reducer is injected, `useDynamicReduxReducer` is never called again and `Guardian` is not rendered for the second time.

**Notes**
- While I'm pretty convinced that the described behavior is a bug (it's hard to believe that injecting new reducers should not yield store change), I'm not sure on what side the ball is dropped. If it's not React-Redux's problem, I'd appreciate if you redirected me to a more relevant place.
- My temporary fix for this was to set the timer after `injectReducer` call and perform is-reducer-injected check once again. Doesn't seem to be that much sound 😑

**Comment by timdorr** [comment]
First, you should be using `useStore`, not the context directly.

But nothing about your code subscribes it to updates to the store. `replaceReducer` will dispatch an internal action, but you're not subscribed to it and there won't be any signal to re-render.

**Comment by alex-gokkun** [comment]
@timdorr, thank for your explanation!
