### ISSUE TITLE
useSelector uses equalityFn from the stale closure

### ISSUE THREAD

**Issue by dai-shi** [reduxjs/react-redux#1416]
**Do you want to request a _feature_ or report a _bug_?**

Originally commented https://github.com/reduxjs/react-redux/pull/1412#issuecomment-537546848 to respond @salazarm 's question.

It's a hypothetical bug.

**What is the current behavior?**

checkForUpdates read `equalityFn` from the stale closure, so even if `equalityFn` is changed after the first render, the change doesn't affect.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to a CodeSandbox (https://codesandbox.io/s/new) or RN Snack (https://snack.expo.io/) example below:**

https://codesandbox.io/s/pensive-bhabha-nxt3y
This example is tried to be realistic possible.
The equalityFn is null at the first render and later changed to shallowEqual.
In the result, checkUpdates triggers unnecessary rerenders.

**What is the expected behavior?**

Use `equalityFn` from the latest render.

**Which versions of React, ReactDOM/React Native, Redux, and React Redux are you using?  Which browser and OS are affected by this issue? Did this work in previous versions of React Redux?**

react-redux 7.1.1

**Comment by timdorr** [comment]
Since a compelling use case hasn't come forward, I'm going to close this out. If someone can think of one, we can look into fixing it.
