### ISSUE TITLE
Publish 5.1.2

### ISSUE THREAD

**Issue by mattcrowder** [reduxjs/react-redux#1420]
Hello! I am trying to update my work to React 16.10, and we need to avoid the use of not using UNSAFE on future unsafe component lifecycle methods, I noticed in 5.x that we added the following: https://github.com/mattcrowder/react-redux/blob/41447152f6c6e77763d834fdbfe82fef98e4f46c/src/components/Provider.js#L44

But unfortunately this hasn't been published yet, could I get an ETA on when it will be published, or could you just publish it? thanks!

**Comment by timdorr** [comment]
I'll take a look in a bit. Sorry for the delay!
