### ISSUE TITLE
selector function defined outside useSelector's closure returns always initial state 

### ISSUE THREAD

**Issue by Nomeasmo** [reduxjs/react-redux#1421]
**What is the current behavior?**
I would expect all the following selector function will lead to the same result, which is not true.
``` JS
const outsideSelector = state => state.parameter // Whether imported or declared in same file
const outsideCreator = () => state => state.parameter

export const Component = () => {
  const insideSelector = state => state.parameter
  const inline = useSelector(state => state.parameter) // Re-runs with current state
  const inside = useSelector(insideSelector) // Re-runs with current state
  const outside = useSelector(outsideSelector) // always initial state on re-render
  const outsideC = useSelector(outsideCreator()) // Re-runs with current state
  ...
```
I would define it as bug, if this is not other possible it is minimum counter-intuitive and must be marked as bold in documentation and console out an error.

**What is the expected behavior?**
I would not expect any dependency on where a function is declared. The above functions are all pure.

**Which versions of React, ReactDOM/React Native, Redux, and React Redux are you using?  Which browser and OS are affected by this issue? Did this work in previous versions of React Redux?**
    "react": "16.8.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz",
    "react-redux": "^7.1.1",
    "redux": "^4.0.4",

**Comment by markerikson** [comment]
Can you provide a CodeSandbox that demonstrates the issues you're talking about?  Those _should_ always be returning the same value - why do you say that `outsideSelector` is "returning initial state"?

**Comment by Nomeasmo** [comment]
Hmm I tried with new repo and all works as expected. Strange but so happy all are treat the same.
