### ISSUE TITLE
Missing peer dependency on `react-dom`

### ISSUE THREAD

**Issue by pieh** [reduxjs/react-redux#1424]
This package import some utilities from `react-dom`:
https://github.com/reduxjs/react-redux/blob/2297944eec7009ba9cc2470e1fcc9014fd0771cd/src/utils/reactBatchedUpdates.js#L2

But `react-dom` is not specified as dependency or peerDependency
https://github.com/reduxjs/react-redux/blob/2297944eec7009ba9cc2470e1fcc9014fd0771cd/package.json#L38-L49

This cause `Cannot file module 'react-dom'` errors when using it with [Ink (react for cli/terminal)](https://github.com/vadimdemedes/ink).

Installing `react-dom` does fix the issue (bit weird to install it for terminal app, but what can you do :) ). If `react-dom` is being used, it should be either dependency (probably not the way here) or peerDependency so package managers warn about missing dependency before we run into issues like that.

Issue discovered in https://github.com/gatsbyjs/gatsby/issues/18603

**Comment by timdorr** [comment]
See these PRs:

#1261
#1282
#1371
#1366

**Comment by pieh** [comment]
That's unfortunate :/ but also understandable. Too bad package.json doesn't have some way to conditionally declare dependencies.

Given amount if PRs and issues about this, what do you think about putting some context around that import in source code to guard against PRs and issues about this in the future? :)

In any case - thanks for quick response!

**Comment by markerikson** [comment]
Heh.  Yeah, a "DON'T MESS WITH THIS!" comment might not be a bad idea :)

**Comment by timdorr** [comment]
> Too bad package.json doesn't have some way to conditionally declare dependencies.

They do. It's `peerDependenciesMeta` and it's in all the latest package managers, but is too new to rely on (unlike browsers, we can't polyfill npm 😄).
