### ISSUE TITLE
is it possible to only get hooks in the final bundle?

### ISSUE THREAD

**Issue by gcloeval** [reduxjs/react-redux#1430]
Hello team,
What (is there?) a recommended approach for projects that only use react-redux hooks when it comes to producing final bundle?
When we include react-redux as a dependency, in final production build both connect and connectAdvanced (and all they require) are included even though we never touch them, which results in about 7kb extra. 7kb may not sound much, but if each of our dependency gave us that much extra.....

Here is an example screenshot using CRA and source map explorer.
![react_redux_bundle_using_library](https://user-images.githubusercontent.com/33051249/67055903-31fc4100-f14a-11e9-90c5-78298f6a68e0.jpg)

Here is a codesandbox for this simple project:
https://codesandbox.io/s/bitter-butterfly-exyih

If we just simply manually copy hooks + provider + utils from react-redux source code, we get about exactly expected 7kb less bundle.
Here is a screenshot for that using source-map explorer:
![react_redux_bundle_using_manually_copied_hooks](https://user-images.githubusercontent.com/33051249/67055912-42142080-f14a-11e9-818f-3ba4c3ece6ef.jpg)

Here is codesandox for this project - in folder 
https://codesandbox.io/s/blissful-herschel-slhki

Please let us know if its possible to only get hooks in our final bundle (without manually having to copy source code from react-redux).

**Comment by markerikson** [comment]
To be honest I've never looked into whether you can tree-shake out `connect`.

At this point, the answer is no, you can't.
