### ISSUE TITLE
Do not alter exception thrown from selector

### ISSUE THREAD

**Issue by Dema** [reduxjs/react-redux#1433]
**Do you want to request a _feature_ or report a _bug_?**
bug

**What is the current behavior?**

useSelector extracts `.message` field from thrown exception in https://github.com/reduxjs/react-redux/blob/master/src/hooks/useSelector.js#L60 hiding original exception with stack trace making it hard to pinpoint exact error location.

**What is the expected behavior?**

Is it possible to re-throw original error or, at least print it using console.error?

**Comment by timdorr** [comment]
What about this?
```js
  } catch (err) {
    if (latestSubscriptionCallbackError.current) {
      err.message += `\nThe error may be correlated with this previous error:\n${latestSubscriptionCallbackError.current.stack}\n\n`
    }

    throw err
  }
```
