### ISSUE TITLE
Any reason why checkForUpdates after component first time rendered  in useSelector ?

### ISSUE THREAD

**Issue by malash** [reduxjs/react-redux#1435]
**Do you want to request a _feature_ or report a _bug_?**

Discussion, maybe a bug.

**What is the current behavior?**

In current `useSelector` implement I found this line:

https://github.com/reduxjs/react-redux/blob/4be8b3f09519333e85accb9eea918c014df32f07/src/hooks/useSelector.js#L99

I believe it means when component first rendered the `useIsomorphicLayoutEffect`, as known as `useLayoutEffect` on web or `useEffect` on non-web, will run the callback and `checkForUpdates` is called.

I don't understand why we have to do that check. It seem that even if user changed the state immediately after component mount, `onStateChange` could handle it and let component re-render. Is it right ?

I tried to remove this line and all unit test passed. So if this line is important and cannot be removed may we add some test cases for it ? Otherwise may we remove that line ?

Thanks!

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to a CodeSandbox (https://codesandbox.io/s/new) or RN Snack (https://snack.expo.io/) example below:**

None.

**What is the expected behavior?**

Add some test cases.

**Which versions of React, ReactDOM/React Native, Redux, and React Redux are you using?  Which browser and OS are affected by this issue? Did this work in previous versions of React Redux?**

react-redux@7.1.1

**cc**

@byunicorn

**Comment by malash** [comment]
B.T.W. Is this line used for same purpose ?

https://github.com/reduxjs/react-redux/blob/4be8b3f09519333e85accb9eea918c014df32f07/src/components/connectAdvanced.js#L365

**Comment by markerikson** [comment]
Because it's possible that more actions could have been dispatched between the time the component rendered and the time it subscribes.  This is the pattern shown in Brian Vaughn's `useSubscription` implementation:

https://github.com/facebook/react/blob/0f64703edf5970b12a878ea3b5e1e30ef1d71c74/packages/use-subscription/src/useSubscription.js#L113-L116

**Comment by markerikson** [comment]
And yeah, if our existing tests don't cover it, I'd happily accept a test that shows that.

**Comment by malash** [comment]
Thanks for you reply and your link. 

I'd like to add test cases after thorough understanding that implement.
