### ISSUE TITLE
`useIsomorphicLayoutEffect` cannot pass test cases in non-web environment

### ISSUE THREAD

**Issue by malash** [reduxjs/react-redux#1436]
**Do you want to request a _feature_ or report a _bug_?**

Report a bug.

**What is the current behavior?**

https://github.com/reduxjs/react-redux/blob/2eac86163be2bd5627dab3e33e8b4e0926895442/src/hooks/useSelector.js#L22-L27

https://github.com/reduxjs/react-redux/blob/672540023769845d6d162b382d518945321956ab/src/components/connectAdvanced.js#L40-L45

These two files implement the `useIsomorphicLayoutEffect` hook to [prevent the React warning](https://github.com/reduxjs/react-redux/issues/1402) by using `useEffect` instead of `useLayoutEffect`. But it could break on non-web environment, like React Native, [and etc](https://github.com/chentsulin/awesome-react-renderer).

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to a CodeSandbox (https://codesandbox.io/s/new) or RN Snack (https://snack.expo.io/) example below:**

I tested by these steps:

1. Clone the `react-redux` repo
2. Modify `useIsomorphicLayoutEffect` to `const useIsomorphicLayoutEffect = useEffect`
3. Run `npx jest`

![image](https://user-images.githubusercontent.com/1812118/67777832-47079700-fa9d-11e9-898c-da9a9017bf7a.png)

**What is the expected behavior?**

1. We should add some test cases for non-web environment. For example [@testing-library/react-native](https://testing-library.com/docs/native-testing-library/intro) provides the way to test `react-native` in jest.
2. We should review the implement of `useIsomorphicLayoutEffect` and fix it if there did have some bugs.

**Which versions of React, ReactDOM/React Native, Redux, and React Redux are you using?  Which browser and OS are affected by this issue? Did this work in previous versions of React Redux?**

react-redux@7.1.1

**cc**

@byunicorn

**Comment by markerikson** [comment]
No one has yet filed actual bugs reporting this doesn't work in React Native.  Do you have any actual test cases that show it fails in an RN app?

**Comment by malash** [comment]
😂Bug happened here https://github.com/reduxjs/react-redux/issues/1437

**Comment by markerikson** [comment]
Yep, but I wasn't sure how to try to add RN unit tests at the time.

**Comment by malash** [comment]
How about [@testing-library/react-native](https://testing-library.com/docs/native-testing-library/intro) ?

**Comment by markerikson** [comment]
Fixed by #1444 .
