### ISSUE TITLE
Feature request: Provide a way to access context from mapStateToProps/mapDispatchToProps

### ISSUE THREAD

**Issue by iczero** [reduxjs/react-redux#1443]
**Do you want to request a _feature_ or report a _bug_?**
This is a feature request.

**What is the current behavior?**
The context is not provided to `mapStateToProps` and `mapDispatchToProps`. When using a custom context supplied by options, the context is accessible to the component itself but not those functions.

**What is the expected behavior?**
I request that it be possible to get a specific context in `mapStateToProps` and `mapDispatchToProps`, similar to what can be done with the `useContext` hook. 

**Which versions of React, ReactDOM/React Native, Redux, and React Redux are you using?**
```
├── react@16.11.0 
├── react-dom@16.11.0 
├── react-redux@7.1.1 
└── redux@4.0.4 
```

**Comment by markerikson** [comment]
I don't think this is feasible given our current architecture, and it's definitely not something we plan on implementing.

If you need to do something like this, I'd suggest reading a value from context right above the connected component and passing the value in as a prop, or reading the context value inside a function component and passing it to `useSelector()`.

I'll go ahead and close this, but I am curious: what's your use case for needing to do something like this?

I'm also confused by your mention of "a custom context", as that doesn't have anything to do with accessing a specific context value in a component.  That's overriding a React-Redux internal implementation detail.
