### ISSUE TITLE
Store from props:  undefined

### ISSUE THREAD

**Issue by stevensacks** [reduxjs/react-redux#1448]
**What is the current behavior?**

You guys left a console log in your source. It floods the console with this:

`Store from props:  undefined`

It's here:
`connectAdvanced.js:134`
```javascript
      // We'll check to see if it _looks_ like a Redux store first.
      // This allows us to pass through a `store` prop that is just a plain value.

      console.log('Store from props: ', props.store);
      var didStoreComeFromProps = Boolean(props.store) && Boolean(props.store.getState) && Boolean(props.store.dispatch);
      var didStoreComeFromContext = Boolean(contextValue) && Boolean(contextValue.store);
```

**What is the expected behavior?**
Not to flood the console with logs.

**Which versions of React, ReactDOM/React Native, Redux, and React Redux are you using?  Which browser and OS are affected by this issue? Did this work in previous versions of React Redux?**

react 16.11.0
react-redux 7.1.2
redux 4.0.4

**Comment by markerikson** [comment]
Drat.  I'll fix that momentarily.  Sorry!

**Comment by markerikson** [comment]
Fixed: https://github.com/reduxjs/react-redux/releases/tag/v7.1.3
