### ISSUE TITLE
Missing page

### ISSUE THREAD

**Issue by fosteman** [reduxjs/react-redux#1453]
404 https://react-redux.js.org/next/api/hooks 

https://react-redux.js.org/next/next/using-react-redux/connect-mapstate

**Comment by markerikson** [comment]
Please don't use the `next` version section of the docs.  

(Somehow the `next/hooks` page ended up as the main hit in Google for our hooks API.  Must have been due to the alpha period.)

That said, yes, the `mapState` link should point to the matching version, not the `next` version.

**Comment by thiskevinwang** [comment]
I got a PR to fix this 👆

cc @markerikson, @fosteman
