### ISSUE TITLE
How to read connectAdvanced?

### ISSUE THREAD

**Issue by jituanlin** [reduxjs/react-redux#1460]
I try to read the source code of `connectAdvanced`. 
I think it is the most important thing for really understand the under of hook of `react-redux`.
But it so complicate, so many state need to consider, so many condition logic depend on 
this dynamic state.
It is crazy that simulate the state translate in my little head.
Or, am I wrong? There is any better way to understand it without track the state change
in my head.

**Comment by markerikson** [comment]
Afraid I'm not really sure how to answer your question :(

I'd suggest reading through my post [The History and Implementation of React-Redux](https://blog.isquaredsoftware.com/2018/11/react-redux-history-implementation/) and watching my talk [A Deep Dive into React-Redux](https://blog.isquaredsoftware.com/2019/06/presentation-react-redux-deep-dive/) to get a better understanding of what `connect` does and how it works.

FWIW, you don't need to know how `connect` works inside to be able to use it.  Nothing wrong with reading the code and learning more, but you don't _have_ to.

But yeah, there are a lot of edge cases and things we have to consider.
