### ISSUE TITLE
Add a "DisplayName" on ReactReduxContext for DevTools

### ISSUE THREAD

**Issue by pieplu** [reduxjs/react-redux#1461]
**What is the current behavior?**

ReactReduxContext don't have a DisplayName. It will be usefull on devtools.

Actually it's look's like:

![image](https://user-images.githubusercontent.com/3260285/68772218-6eab4300-05f7-11ea-9d76-00da25639221.png)

**What is the expected behavior?**

Insted of "Context.Provider" in devTools, I expect see "ReactRedux.Provider" or "ReactReduxContext.Provider"

React: 16.8
React-redux: 7.1

I will propose a PR

**Comment by timdorr** [comment]
Thanks, but I don't think we need this.
