### ISSUE TITLE
Property 'defaultProps' does not exist on type ConnectedComponent

### ISSUE THREAD

**Issue by gmukul01** [reduxjs/react-redux#1463]
**What is the current behavior?**

Property 'defaultProps' and children does not exist on type ConnectedComponent.

![image](https://user-images.githubusercontent.com/3636885/68855506-5b39ce00-0704-11ea-83cb-bdf9b7601c1c.png)
![image](https://user-images.githubusercontent.com/3636885/68855519-62f97280-0704-11ea-9ab4-20baebe619b0.png)

**What is the expected behavior?**

It should have expected types.

**Comment by timdorr** [comment]
We don't maintain the types in this repo. Please consult the support resources for DefinitelyTyped
