### ISSUE TITLE
forwardRef in decorator connect Error

### ISSUE THREAD

**Issue by xuanheScript** [reduxjs/react-redux#1469]
version: "react-redux": "6.0.1"
It Error:
`
@connect(mapStateToProps,mapDispatchToProps,null,{ forwardRef: true })
Component
export default Component
`
It Correct:
`
export default connect(mapStateToProps,mapDispatchToProps,null,{ forwardRef: true })(Component)
`

Error Message: `Expected a constructor`

Why?

![image](https://user-images.githubusercontent.com/19216775/69393287-b4f95400-0d13-11ea-84ac-fb0c94425b81.png)

**Comment by markerikson** [comment]
Sorry, we don't support or recommend using `connect` as a decorator.  If it works, that's great, but it's not an intentionally supported use case since the decorator spec and plugins continue to change.
