### ISSUE TITLE
useSelector() unsubscribe

### ISSUE THREAD

**Issue by ashil816** [reduxjs/react-redux#1475]
Is it possible to somehow use rxjs pipe and take1/takeUntil with useSelector()?
In general, is it possible to unsubscribe() from useSelector() manually? ex.

```
useEffect(() => {
  user = useSelector(state => state.auth.user).pipe(take(1))
}, [])
```

**Comment by markerikson** [comment]
No, for two reasons:

- You can't call hooks inside of hooks
- `useSelector` manages its store subscription internally
