### ISSUE TITLE
componentWillReceiveProps dont called after store change, but selector get new correct state

### ISSUE THREAD

**Issue by ladarit** [reduxjs/react-redux#1477]
**Do you want to request a _feature_ or report a _bug_?**

bug

**What is the current behavior?**

**1 case:**
   1. Calling redux action (e.g 'CLOSE_DOCUMENT') -> modify redux store
   2. selector placed in mapStateToProps gets correct data (new modified data)
   3. componentWillReceiveProps and shouldComponentUpdate **don`t called**

**2 case:**
   1. Calling promise -> promise show modal and modify redux store
   2. Closing modal -> promise resloves and modify redux store
   3. After promise resolves (in 'then') calling same redux action (e.g 'CLOSE_DOCUMENT')  -> modify redux store
   4. selector placed in mapStateToProps gets correct data (new modified data)
   3. componentWillReceiveProps and shouldComponentUpdate **called**

**What is the expected behavior?**

in 1 case I expect that componentWillReceiveProps and shouldComponentUpdate will be called

React, ReactDOM = 16.8.4
Redux = ^4.0.1
react-redux = "^7.1.3"

**Comment by markerikson** [comment]
Please provide a CodeSandbox that reproduces the issue.  Also, please check to make sure that you are not mutating state anywhere.

**Comment by ladarit** [comment]
ok, thanks for response, I will try to provide CodeSandbox example tomorrow, because our project is quite big

**Comment by timdorr** [comment]
By default, a connected component is passed through React.memo, so if the props it receives don't change (you get the same result from mapStateToProps), those lifecycle methods will not be called, nor will the component be re-rendered. 

To check for this, you can disable this optimization temporarily with the `{ pure: false }` option on the `connect()` call (4th arg).

**Comment by ladarit** [comment]
thanks to all, it was my mistake, problem was in updated component logic. can beclosed
