### ISSUE TITLE
Curious inconsistent render when using memoized selector direct reference

### ISSUE THREAD

**Issue by exogen** [reduxjs/react-redux#1478]
**What is the current behavior?**

When I have a selector created with `reselect` or `re-reselect`:

```
const getSomething = createSelector(state => state.value, value => value + 1);
```

There is seemingly a difference in re-rendering behavior when passing that selector directly to `useSelector` vs. wrapping it:

```
// What I want to do, seems fine per the docs:
const value = useSelector(getSomething);

// What I have to do instead:
const value = useSelector(state => getSomething(state));
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Demo repo: https://github.com/exogen/test-redux-selector

Run:

```
$ git clone git@github.com:exogen/test-redux-selector.git
$ cd test-redux-selector
$ yarn
$ yarn test
```

All the code lives in this file: https://github.com/exogen/test-redux-selector/blob/master/src/App.test.js

Here's what to look for when running the test:

* The final flushed output of the render (as output using `@testing-library/react`) is consistent.
* However, in the re-render output you'll see `Found inconsistency? true` because an inconsistent render was detected. This shows that you can see inconsistent state in effects, where you might be making decisions based on comparing certain state values etc. (this is why it's a problem in my real code)
* You can also see the actual values during render via the `console.log` output.
* I'm not sure why there are 3 renders in the first place, it seems like there should be two: the initial render, then the render with updated store. Instead, there's a 3rd render with inconsistent state from memoization in between.

<img width="546" alt="Screen Shot 2019-12-02 at 4 34 37 PM" src="https://user-images.githubusercontent.com/53522/70007868-d4b82580-1526-11ea-82e8-db68d8ad9845.png">

I wonder, could it be because of my usage of `redux-mock-store` here? I'm re-rendering with a new store instance, not the same store instance with updated state – a bit weird, but also doesn't seem like it should cause inconsistency.

**What is the expected behavior?**

I would expect `useSelector(selector)` and `useSelector(value => selector(value))` to have equivalent behavior.

**Which versions of React, ReactDOM/React Native, Redux, and React Redux are you using?**

```
├─ react-dom@16.8.6
├─ react-redux@7.1.0
├─ react@16.8.6
└─ redux@4.0.4
```

Thanks! 🙇

**Comment by markerikson** [comment]
Hmm.  For this test at least, I would advise against providing a different `store` entirely.  Instead, try dispatching an action that changes the value, and also wrap that behavior in `act()`, like:

```js
act(() => {
    store.dispatch({type: "INCREMENT"});
});
```

Does that change the rendering results at all?

**Comment by exogen** [comment]
Yes, that works!

I wonder if it's just unsafe to use `redux-mock-store` with rerendering altogether then, as it intentionally doesn't supply any way to update state.

One reason I use it is so that I don't have to specify a reducer or dispatch any actions in my tests, for when I just want to see what a component does with various states as input. What's the recommended pattern for easy testing like this, should I mock `useSelector` instead so I don't need a store at all?

**Comment by markerikson** [comment]
Looking at the `redux-mock-store` docs, it says:

> A mock store for testing Redux async action creators and middleware. The mock store will create an array of dispatched actions which serve as an action log for tests.  Please note that this library is designed to test the action-related logic, not the reducer-related one

I think the answer here is that you really should just create a "real" Redux store, even if it's got a test-only reducer in it, because the point is to have a Redux store that can update its state.  You're not trying to actually check what actions were dispatched and assert on those.

**Comment by exogen** [comment]
I do use that functionality as well and it's nice to just be able to use similar test code everywhere, but it should be just as easy to replicate by doing:

```
store.dispatch = jest.fn();
```

and spying on its calls, so no big loss there.

**Comment by markerikson** [comment]
Right, I'm more saying that _for this particular test_, you'd want a real store instead of a mock one.

**Comment by markerikson** [comment]
Closing as this appears to be resolved.
