### ISSUE TITLE
Invalid hook call when exporting connected component inside lerna

### ISSUE THREAD

**Issue by jdc91** [reduxjs/react-redux#1479]
**Do you want to request a _feature_ or report a _bug_?**
Bug report

**What is the current behavior?**
I am trying to export a connected component as a component lib. However I am getting the invalid hook error.
I have followed all of this https://reactjs.org/warnings/invalid-hook-call-warning.html as well as the related issue mentioned in it.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to a CodeSandbox (https://codesandbox.io/s/new) or RN Snack (https://snack.expo.io/) example below:**

I have created a repo here with a demo example
https://github.com/jdc91/invalid-hook-sample/tree/master
To recreate. Go to the root of the project and run

1. npm install
2. npm run dev:install (lerna bootstrap)
3. npm run build:simple:component:lib
4. npm run build:complex:components
5. npm run app:start

The dependency hierarchy looks like this FYI.
react-app<------react-complex-components<------react-simple-component-lib

**What is the expected behavior?**
The component should be exportable without the invalid hook call error

**Which versions of React, ReactDOM/React Native, Redux, and React Redux are you using?  Which browser and OS are affected by this issue? Did this work in previous versions of React Redux?**
All versions available in repo. Tried this with a react-redux version before hooks was released, but I am getting the same error

Attached error recieved
![image](https://user-images.githubusercontent.com/3422709/70033423-71390100-15d5-11ea-94c4-3a3f43df286b.png)

**Comment by markerikson** [comment]
This almost always means that you have a broken build environment that is resulting in multiple copies of React or React-Redux ending up in your bundle.  That's especially likely in this case due to use of multiple sub-projects.  Please check your build settings and take care of that.

**Comment by jdc91** [comment]
I have actually checked and externalized the React, React DOM dependencies in webpack. And this only occurs when I use react-redux connected components. It works fine exporting normal React components.

**Comment by markerikson** [comment]
The error is occurring when a hook is being called.  That is not a React-Redux specific issue - it's due to the problems that I described.

**Comment by jingnanl** [comment]
I came across the same issue. I believe that @jdc91 is correct, if exporting the react component alone, it's working fine. Only when exporting the connect() HOC would it fail due to "Invalid hook call"

**Comment by pawel2105** [comment]
I'm experiencing the same thing using react-redux 7.1.3 when wrapping a custom `next/app` component, but the error is gone when the tree is not wrapped with a `<Provider />` component, even when leaving the connect() wrapping around the export.

**Comment by markerikson** [comment]
Downgrading to v6 is not the correct answer here, because that version is has performance issues and is not supported going forward.

**Comment by neerajdixit27** [comment]
@markerikson  / @pawel2105  : was anyone able to solve it, i get the Invalid hook call error with React-redux version 7.X.X but downgrading the version solves the issue. I see only one version of react in my project.

@markerikson  : i agree that downgrading is not the solution.

**Comment by markerikson** [comment]
Downgrading "solves" the problem only because v6 wasn't built with hooks.

Every time an issue like this has come up, it's been because there was some kind of a build misconfiguration in a user's project.

**Comment by FurkanSelvi** [comment]
Same issiue, Isn't there any solution other than downgrading?

**Comment by markerikson** [comment]
@FurkanSelvi As I've already said multiple times in this thread: 

**This almost always means that you have a broken build environment that is resulting in multiple copies of React or React-Redux ending up in your bundle. That's especially likely in this case due to use of multiple sub-projects. Please check your build settings and take care of that.**
