### ISSUE TITLE
connect function bug ?

### ISSUE THREAD

**Issue by banli17** [reduxjs/react-redux#1480]
**What is the current behavior?**

i make a Modal，alert:

```js
function alert(options = {}) {
    const div = document.createElement('div')
    div.id = 'modal_' + _uid++
    document.body.appendChild(div)

    if (!store) return

    return ReactDOM.render(
        <Provider store={store}>
            <Modal {...options}/>
        </Provider>
        , div)
}
```

useage is :

```js
Modal.alert({
    content: <ComponentX />
})

// ComponentX
class ComponentX extends Components{
    render(){
       let {title} = this.props
        return <div>{title}</div>
    }
}
export default connect(state=> state.title)(ComponentX);
```

my ComponentX inner use connect(state)。

in react-redux  7.1.0 is ok， bug react-redux 7.1.3 is not ok， error  is follow:

Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Object.da (react-dom.production.min.js:3592)

it likes a bug?

**Comment by markerikson** [comment]
Please provide a CodeSandbox project that reproduces the issue.

Also, if you look at the error message, it says that React is having a problem using hooks.  This usually occurs if you have more than one copy of React or React-Redux bundled into your application.

**Comment by OKNoah** [comment]
> Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

Same here. Seems like `react-redux` might be minified wrong or using hook improperly.

**Comment by markerikson** [comment]
As I said, there's little we can do without a project that demonstrates the problem.  Realistically, it's much more likely that your build setup is wrong.

**Comment by OKNoah** [comment]
> As I said, there's little we can do without a project that demonstrates the problem. Realistically, it's much more likely that your build setup is wrong.

Does this help?

```js
/**
 * @format
 */
import React from 'react'
import { AppRegistry, View, Text } from 'react-native'
import { Provider } from 'react-redux'
import store from 'store'
import App from 'components/App'

const Index = Component => {
  return (
    <Provider store={store}>
      <View>
        <Text>Please</Text>
      </View>
    </Provider>
  )
}

AppRegistry.registerComponent('TiketEventsMerchants', () => Index)
```

**Comment by markerikson** [comment]
Not really, no.  That doesn't tell me anything about your project or build setup, and it's not something I can just run and see the problem in action.

**Comment by banli17** [comment]
it seems version not compatible，i justify version，it's ok

**Comment by timdorr** [comment]
Ok, without any code to actually look through, I'm closing this for now.
