### ISSUE TITLE
Site docs became more outdated in the last couple days?

### ISSUE THREAD

**Issue by abirmingham** [reduxjs/react-redux#1491]
Oddly, it appears that the docs at https://react-redux.js.org/ have become outdated relative to the code in the repository. Just a couple days ago (perhaps yesterday?) I recall looking at a blurb on custom context at https://react-redux.js.org/api/hooks and now it is gone. The same blurb can still be found in the code, however:

```
## Custom context

The `<Provider>` component allows you to specify an alternate context via the `context` prop. This is useful if you're building a complex reusable component, and you don't want your store to collide with any Redux store your consumers' applications might use.

To access an alternate context via the hooks API, use the hook creator functions:

---js
import React from 'react'
import {
  Provider,
  createStoreHook,
  createDispatchHook,
  createSelectorHook
} from 'react-redux'

const MyContext = React.createContext(null)

// Export your custom hooks if you wish to use them in other files.
export const useStore = createStoreHook(MyContext)
export const useDispatch = createDispatchHook(MyContext)
export const useSelector = createSelectorHook(MyContext)

const myStore = createStore(rootReducer)

export function MyProvider({ children }) {
  return (
    <Provider context={MyContext} store={myStore}>
      {children}
    </Provider>
  )
}
---
```

Was that blurb never on the site? Am I going crazy?  :)

**Comment by markerikson** [comment]
This is due to the way our docs are versioned.  You were looking at https://react-redux.js.org/next/api/hooks#custom-context , but the "current" docs at https://react-redux.js.org/api/hooks are showing the content for v7.1.  Unfortunately, there are two different Markdown files for the different versions, and they're kind of out of sync now.

**Comment by abirmingham** [comment]
Thanks for verifying my sanity, @markerikson :)
