### ISSUE TITLE
Redux style guide not discoverable from React Redux docs

### ISSUE THREAD

**Issue by devanfarrell** [reduxjs/react-redux#1495]
Related to #1001 

Potential solutions:
- Link to guide in the list of guides in the side navigation pane
- Duplicate the content of the style guide to both documentation sites
- Migrate the `react-redux` specific guide only

**Comment by timdorr** [comment]
I assume you meant the [Redux style guide](https://github.com/reduxjs/redux/blob/master/docs/style-guide/style-guide.md), as we don't have one specific to React Redux.

I think migrating over the React-specific stuff is probably the correct approach. Redux still needs to maintain a framework-agnostic stance in its docs, IMHO.

**Comment by markerikson** [comment]
But at the same time, the Redux core docs completely assume you're using React in a lot of places (tutorials, etc).

I'd be okay with mirroring the info, or pointing to it, but I'd kinda like to keep the whole page there as-is.
