### ISSUE TITLE
Suggestion to add useParametricSelector hook

### ISSUE THREAD

**Issue by VKobeliatsky** [reduxjs/react-redux#1499]
Since reselect [requires](https://github.com/reduxjs/reselect#sharing-selectors-with-props-across-multiple-component-instances) parametric selectors to have separate instance per component instance they are used in, a `useParametricSelector` hook would be useful.

I hope it would lift some confusion on how to correctly use parametric selectors.

It could look as simple as
```js
import {useMemo, useCallback} from 'react';
import {useSelector} from 'react-redux';

const useParametricSelector = (
  selectorCreator,
  parameter
) => {
  const parametricSelector = useMemo(selectorCreator, []);
  const selector = useCallback(
    state => parametricSelector(state, parameter),
    [parametricSelector, parameter]
  );

  return useSelector(selector);
};
```

**Comment by markerikson** [comment]
I don't see a need to build that in directly, especially since it can be written fairly easily in user-land as you just showed.  Thanks for the suggestion, though!
