### ISSUE TITLE
react-redux in TS 🤔 !!

### ISSUE THREAD

**Issue by 3imed-jaberi** [reduxjs/react-redux#1507]
I think it's time to rewrite react-redux in TS especially after rewriting Redux ..
So, i open this issue to ask about the team approche here!

thanks ❤️ !

**Comment by markerikson** [comment]
We're not currently planning to rewrite React-Redux in TS at this time.  The Redux 5.0 TS rewrite hasn't been released yet, and React-Redux has _much_ more complex typings that have been maintained by the community.

Not saying we won't ever do it, just that it's not anything we're actually planning to do.
