### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by Ildarik** [reduxjs/react-redux#1512]
https://react-redux.js.org/next/api/hooks

_The selector is approximately equivalent to the **_mapStateToProps argument to connect_**_ conceptually.
There are 2 `next` words in a link: https://react-redux.js.org/next/next/using-react-redux/connect-mapstate

Found that in markdown file it is a relative link: https://github.com/reduxjs/react-redux/blob/master/docs/api/hooks.md
How that works?)

**Comment by timdorr** [comment]
Can you submit a PR?
