### ISSUE TITLE
TypeError: (0, _reactRedux.connect) is not a function. (In '(0, _reactRedux.connect)(mapStateToProps, mapDispatchToProps)', '(0, _reactRedux.connect)' is undefined)

### ISSUE THREAD

**Issue by abbasmoosavi** [reduxjs/react-redux#1516]
TypeError: (0, _reactRedux.connect) is not a function. (In '(0, _reactRedux.connect)(mapStateToProps, mapDispatchToProps)', '(0, _reactRedux.connect)' is undefined)

I imported connect from react-redux

![Simulator Screen Shot - iPhone 11 - 2020-02-02 at 12 48 19](https://user-images.githubusercontent.com/15355286/73605970-5295bd00-45ba-11ea-8d56-b14505c7bc60.png)

**Comment by markerikson** [comment]
This is likely a problem with your build environment.  

If you can reproduce the problem with a new project, we might be able to take a look, but we definitely can't do anything with just a screenshot.

**Comment by matinzd** [comment]
> This is likely a problem with your build environment.
> 
> If you can reproduce the problem with a new project, we might be able to take a look, but we definitely can't do anything with just a screenshot.

There wasn't any problem the day before. Project was up and running and we didn't do anything.

**Comment by ShruthiShetty-2218** [comment]
Instead of connect if you are used any other function while exporting . you may get this problem .
