### ISSUE TITLE
Convert `connect` arguments to parametrized arguments.

### ISSUE THREAD

**Issue by jun-sheaf** [reduxjs/react-redux#1521]
**Do you want to request a _feature_ or report a _bug_?**

This is a feature.

**What is the current behavior?**

```connect``` accepts arguments in sequence rather than as an object

**What is the desired behavior?**

```connect``` should accept an object that contains its parameters. E.g.
```ts
connect({
 context: SomeStoreContext,
 mapStateToProps: someMap
})(ToBeConnectedComponent)
```
This would be cleaner and prevent the need to use `null`s to achieve the same result.

**Which versions of React, ReactDOM/React Native, Redux, and React Redux are you using?  Which browser and OS are affected by this issue? Did this work in previous versions of React Redux?**

Redux 4.0.5

**Comment by markerikson** [comment]
Appreciate the suggestion, but we do not plan to change the `connect` API any further.

If we rewrote it, it would be a major breaking change.  If we made that optional, it would make an incredibly overloaded API definition _more_ overloaded, and while we don't maintain the React-Redux typedefs here, they're already insanely complex.

In addition, while `connect` isn't deprecated and we plan to support it indefinitely, we are generally encouraging folks to prefer using our hooks API as the default approach if possible.
