### ISSUE TITLE
[Feature request] Leverage useDebugValue in useSelector

### ISSUE THREAD

**Issue by Finesse** [reduxjs/react-redux#1525]
Debugging components with the `useSelector` hook is more complicated that it could be. In order to see a `useSelector` return value, I have to put `console.log` in my code or dive deep into the hook to find the internal `useState` that stores the current selector value. React has [a browser extension](https://github.com/facebook/react/tree/master/packages/react-devtools) that shows inner state of React tree, components and hooks, and provides [a way to attach a value to a hook](https://reactjs.org/docs/hooks-reference.html#usedebugvalue) in the extension UI:

![image](https://user-images.githubusercontent.com/9006227/75044120-cf0e2280-550c-11ea-9145-e4a06d872d9b.png)

The `useSelector` hook may call `useDebugValue` to show the current selected value next to the hook in the hooks list of the extension UI (like the built-in hooks do). It would be very handy.

I don't know whether using the hook impacts the performance. Using the hook only during development would be sufficient.

**Comment by timdorr** [comment]
This seems like a good idea to me. Can you work up a PR?

**Comment by Finesse** [comment]
@timdorr Yes, I’ll make a PR in a couple days

**Comment by dannyharding10** [comment]
When will this feature be released?

**Comment by markerikson** [comment]
Finally live in https://github.com/reduxjs/react-redux/releases/tag/v7.2.1
