### ISSUE TITLE
In the docs, do you usually keep it all JavaScript?

### ISSUE THREAD

**Issue by KennethKinLum** [reduxjs/react-redux#1529]
**Do you want to request a _feature_ or report a _bug_?**

I was reading https://react-redux.js.org/api/hooks
and all of a sudden, there is this line

`const result : any = useSelector(selector : Function, equalityFn? : Function)`

do you usually keep all code to JavaScript because some React / Redux developers use JavaScript?

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to a CodeSandbox (https://codesandbox.io/s/new) or RN Snack (https://snack.expo.io/) example below:**

**What is the expected behavior?**

**Which versions of React, ReactDOM/React Native, Redux, and React Redux are you using?  Which browser and OS are affected by this issue? Did this work in previous versions of React Redux?**

**Comment by markerikson** [comment]
We've mostly written our docs as just JS, yes, but for the API references, having some form of type definitions is helpful to clarify what the expected arguments are.

**Comment by KennethKinLum** [comment]
> We've mostly written our docs as just JS, yes, but for the API references, having some form of type definitions is helpful to clarify what the expected arguments are.

I think it is good to say what the type is, but having JS and then TS mixed in the docs can be confusing IMO.
