### ISSUE TITLE
useSelector API reference is self-contradictory

### ISSUE THREAD

**Issue by nikparo** [reduxjs/react-redux#1531]
**Do you want to request a _feature_ or report a _bug_?**
bug

The `useSelector` API reference states two things that contradict each other:

- When an action is dispatched, `useSelector()` will do a shallow comparison of the previous selector result value and the current result value. If they are different, the component will be forced to re-render. If they are the same, the component will not re-render.
- `useSelector()` uses strict `===` reference equality checks by default, not shallow equality (see the following section for more details).

**What is the current behavior?**
`useSelector()` uses strict `===` reference equality checks by default, not a shallow comparison.

**What is the expected behavior?**
The docs should probably be amended to say something like this instead:
- When an action is dispatched, `useSelector()` will ~~do a shallow comparison of~~ **compare** the previous selector result value and the current result value. If they are **deemed** different, the component will be forced to re-render. ~~If they are the same~~ **Otherwise**, the component will not re-render.

**Comment by timdorr** [comment]
This was fixed for the primary version in #1326. It looks like, since we now have a 7.2 release, they haven't been updated since that version was generated. I'll get that cut now.
