### ISSUE TITLE
Need definitions for dispatch() that returns Promise

### ISSUE THREAD

**Issue by ORESoftware** [reduxjs/react-redux#1533]
This has been a trouble in our code base for awhile:

-------

![Screenshot from 2020-03-04 15-50-24](https://user-images.githubusercontent.com/11139560/75933995-2e830100-5e30-11ea-9d0a-8140cfcbf09c.png)

-------

![Screenshot from 2020-03-04 15-50-09](https://user-images.githubusercontent.com/11139560/75933999-2f1b9780-5e30-11ea-8d67-b1c5b6a28058.png)

-----

We can't find the definitions for Dispatch where it returns a promise...what do we do?

You can see the red squiggle for .then() in the second screenshot, and the typings for Dispatch in the first screenshot.

**Comment by timdorr** [comment]
This doesn't have anything to do with React Redux

**Comment by ORESoftware** [comment]
I believe it does since react-redux defines dispatch()?

**Comment by dai-shi** [comment]
That's React.useReducer's Dispatch type . You want to use Redux's Dispatch type.

**Comment by ORESoftware** [comment]
I don't see that type tho

![Screenshot from 2020-03-04 18-41-23](https://user-images.githubusercontent.com/11139560/75942647-d526cc00-5e47-11ea-979b-13512726eb1f.png)

**Comment by ORESoftware** [comment]
The above was {ThunkDispatch} from 'redux-thunk'...the below is, `import {Dispatch} from "redux";` and I get:

![Screenshot from 2020-03-04 18-45-18](https://user-images.githubusercontent.com/11139560/75942871-6302b700-5e48-11ea-8d99-6fe61373f90e.png)

**Comment by dai-shi** [comment]
Have you already checked this? https://redux.js.org/recipes/usage-with-typescript#usage-with-redux-thunk

**Comment by ORESoftware** [comment]
@dai-shi  thanks this is the only that's worked so far:

```
export type AppDispatch<T> = typeof store.dispatch
```
