### ISSUE TITLE
Allow users to namespace props from parent using map function

### ISSUE THREAD

**Issue by ORESoftware** [reduxjs/react-redux#1540]
I have this question on StackOverflow:
https://stackoverflow.com/questions/60573849/how-to-namespace-parent-props-using-mapstate

looks like the end user can't control how props are received by the parent - they get namespaced by the parent onto the child as they are declared in the parent. But it would be nice if the child component could control how the parent props get mapped to own props, using a mapping function like this:

```js
function mapEverythingToProps(state: RootState,  dispatch: Dispatch<any>, ownProps: OwnProps) {
  return {
    d: dispatch,
    s:  state,
    o: ownProps
  };
}

export default connect<StateProps, DispatchProps, AllProps, RootState>(
  null,
  null,
  mapEverythingToProps
)(OurComponent);
```

what I am looking for is a good way to namespace props from the parent component, so they don't clash with props from state, and so we can easily determine which props are from state and which are from the parent component.

**Comment by markerikson** [comment]
Sorry, that's just not how React works.  A child has no control over the prop names it receives from the parent, at least in plain JS.

**Comment by ORESoftware** [comment]
yeah mergeProps seems to work for this:

```
const mergeProps = (propsFromState: RootState, propsFromDispatch: AppDispatch<any>, ownProps: OwnProps) => {
  return {
    propsFromDispatch,
    propsFromState,
    ownProps
  };
};

// ...

export default connect<>(null, null, mergeProps)(Home);

```
