### ISSUE TITLE
Website: Invalid SSL Certificate

### ISSUE THREAD

**Issue by jtreminio** [reduxjs/react-redux#1541]
Note: This isn't a bug in `react-redux` library itself.

The SSL certificate issued to https://react-redux.js.org currently shows as invalid in Google Chrome and Firefox.

![image](https://user-images.githubusercontent.com/589398/76145248-94000900-604d-11ea-858b-eee0342d0eb9.png)

I am unsure as to the cause.

**Comment by timdorr** [comment]
We're doing some changes on the backend. It'll be fixed soon. See js-org/js.org#3782

**Comment by timdorr** [comment]
Should be fixed now. Netlify gave it a good whack and the SSL cert is now provisioned.
