### ISSUE TITLE
New Version of React-Redux doesn't work well with my simple 'Redux'.

### ISSUE THREAD

**Issue by elowes** [reduxjs/react-redux#1542]
**What is the current behavior?**

First of all, sorry for my poor English.

I implemented a simple version of Redux with RxJS,then use it with React-Redux.It's works well when the version number of React-Redux less than `7.0.2`(the last available version is 7.0.1).

The demo link is below.

[![Edit admiring-bush-sl25d](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/admiring-bush-sl25d?fontsize=14&hidenavigation=1&theme=dark)

https://github.com/reduxjs/react-redux/blob/7555eaec1103f9244082709b70f5333002e10134/src/components/connectAdvanced.js#L294

And I found if change `useIsomorphicLayoutEffect ` to `useEffect`, it will return to normal.

**What is the expected behavior?**

The demo can work as before.

**Comment by timdorr** [comment]
This probably gets into the specifics of how rxjs subscriptions work, which I'm not a deep expert in.

We only support using an official Redux store. It is already an Observable, so you can use it with rxjs without modification. There is also Redux Observable, which gives you more direct tooling for using rxjs.

**Comment by elowes** [comment]
> This probably gets into the specifics of how rxjs subscriptions work, which I'm not a deep expert in.
> 
> We only support using an official Redux store. It is already an Observable, so you can use it with rxjs without modification. There is also Redux Observable, which gives you more direct tooling for using rxjs.

Fine, thanks
