### ISSUE TITLE
useDispatch typescript example

### ISSUE THREAD

**Issue by bugzpodder** [reduxjs/react-redux#1544]
Thanks Mark for such an awesome package.

I have a question about useDispatch within the typescript world.  (I can open a PR with the updates once I get confirmation).

Normally I just do:
`const dispatch = useDispatch();`
Usually it works very well, except in instances where I want to chain Promises, I get the following error:
```
error TS2339: Property 'then' does not exist on type 'ThunkAction<Promise<KeyValue>, CombinedState<{ appState: ...;  }>, null, Action<...>>'.
```
If I change it to something like this it works fine:
```
  const dispatch = useDispatch<ThunkDispatch<RootState, {}, Action<string>>>();
      
  useEffect(() => {
    dispatch(thunkFunction()).then(result => callback(result));
  }, [dispatch]);
```

I don't see anything in the typescript usage docs that pertains to this:
https://react-redux.js.org/7.1/using-react-redux/static-typing#typing-the-usedispatch-hook

i tried this: `export type AppDispatch = typeof store.dispatch` and didn't work either.

**Comment by markerikson** [comment]
The "use a customized version of `Dispatch` is what's intended to cover this situation, ie:

```ts
const dispatch: MyAppDispatch = useDispatch()
```

So yeah, if you know you need to chain off promises in a thunk, you need to tell TS that your version of dispatch allows that, because the base `Dispatch` type doesn't.
