### ISSUE TITLE
Adding deepEqual in utils to use as equalityFn in useSelector()

### ISSUE THREAD

**Issue by RaulNicoletti** [reduxjs/react-redux#1546]
I needed to use a deep equal comparison in one project Im doing and I wrote it based on the [shallowEqual](https://github.com/reduxjs/react-redux/blob/master/src/utils/shallowEqual.js) from this lib. Just added a recursion to go deep in the nested objects.   
I think it would be helpful to have this built in.   
Here is a sample of the code:

``` js
  for (let i = 0; i < keysA.length; i++) {
    const value = keysA[i]

    if (!Object.prototype.hasOwnProperty.call(objB, value)) return false

    const valueA = objA[value]
    const valueB = objB[value]

    if (typeof valueA === 'object') {
      if (!deepEqual(valueA, valueB)) {
        return false
      }
    } else if (!is(valueA, valueB)) {
      return false
    }
  }
```

Do you guys thinks this is useful for the project?

**Comment by markerikson** [comment]
Appreciate the suggestion, but I don't feel a need to include this.  Part of the reason we exposed `shallowEqual` was that we already had it in the codebase and used it.  Given that there's many other existing equality comparison implementations out there, there's not a good reason to add that when we don't use it ourselves.  Thanks anyway!
