### ISSUE TITLE
Can the Redux docs mention something about code re-use?

### ISSUE THREAD

**Issue by jianlin** [reduxjs/react-redux#1547]
@gaearon 

Usually, the Redux sample code is to wire something up using `connect()` and that's the end of the sample.  Can it state something about code re-use?  That is, component re-use: if the component is used with one Redux state and the component is re-used for another state in the Redux store?

Example:
Let's say, we already have  a `Count` component (counter):

1. what if we need two such components on the same page, one for `countIceCream` and one for `countDrink`?
2. if on the To Go Order page, we need such component but it is for `countSpoon`?

There are two questions, one related to not using React Hooks, and one if using React Hooks:

https://stackoverflow.com/questions/60689844/how-to-re-use-a-component-in-react-and-redux

https://stackoverflow.com/questions/60690050/how-to-we-achieve-code-reuse-if-we-use-react-redux-hooks

If possible, can Dan Abramov @gaearon  give us a definitive answer?

**Comment by timdorr** [comment]
First, Dan doesn't really participate in these projects anymore.

This falls outside the scope of our docs. We're not going to teach you how to implement reusable hooks, or general coding patterns. You should search elsewhere for that.

**Comment by jianlin** [comment]
> First, Dan doesn't really participate in these projects anymore.
> 
> This falls outside the scope of our docs. We're not going to teach you how to implement reusable hooks, or general coding patterns. You should search elsewhere for that.

Code re-use is such an important topic. If the docs can have just a short article about it, millions of developers can benefit from it.

**Comment by markerikson** [comment]
I'm with Tim.  There's nothing specific to the concept of code reuse that we need to document.

**Comment by jianlin** [comment]
> I'm with Tim. There's nothing specific to the concept of code reuse that we need to document.

I think it may be more particular with using Hooks. If the component uses a Redux state, and then spit out 80 lines of JSX.  Now the component needs to be used with a different Redux state, and need to render the same 80 lines of JSX, how could we structure our code, if we don't want to repeat that 80 lines of JSX?

**Comment by markerikson** [comment]
The question is too vague.  It's your app, you're welcome to structure and reuse things however you want.
