### ISSUE TITLE
useSelector uses equalityFn

### ISSUE THREAD

**Issue by coder-jz** [reduxjs/react-redux#1549]
checkForUpdates read equalityFn from the stale closure, so even if equalityFn is changed after the first render, the change doesn't affect

**Comment by dai-shi** [comment]
Yeah, I noticed that too some time ago. Not sure if it's intentional, or a bug which is left for a long time.

**Comment by timdorr** [comment]
Why would you need to change the equality function on a selector hook after it's instantiated?

**Comment by olejorgenb** [comment]
(Duplicate of #1416)
