### ISSUE TITLE
React Experimental: Create Suspense fetch wrapper

### ISSUE THREAD

**Issue by h0tw4t3r** [reduxjs/react-redux#1550]
### What is the new or updated feature that you are suggesting?
When I was playing around with React experimental build I had a component that needed to perform a fetch. Codebox examples provided by https://reactjs.org/docs/concurrent-mode-suspense.html were not connected to Redux so I decided to make a wrapper around it.

```js
const wrapAsyncAction = asyncAction => actionArgs => (dispatch, getState) => {
	const pending = suspender => ({ type: reactConstants.FETCH_PENDING, suspender })
	const success = result => ({ type: reactConstants.FETCH_SUCCESS, result })
	const error = error => ({ type: reactConstants.FETCH_FAILURE, error })

	dispatch(
		pending(
			dispatch(asyncAction(actionArgs)).then(
				r => {
					console.log(r)
					dispatch(success(r))
				},
				e => dispatch(error(e))
			)
		)
	)

	return {
		read() {
			const { react: state } = getState()
			switch (state.status) {
				case reactConstants.FETCH_PENDING:
					throw state.suspender
				case reactConstants.FETCH_SUCCESS:
					return state.result
				case reactConstants.FETCH_FAILURE:
					throw error
				default:
					return state
			}
		}
	}
}
```

As you see here I use `reactConstants` and I have a defined reducer defined in another file:
```js
import { reactConstants } from '../constants/react.constants'

export const react = (state = {}, action) => {
	switch (action.type) {
		case reactConstants.FETCH_PENDING:
			return { status: action.type, suspender: action.suspender }
		case reactConstants.FETCH_SUCCESS:
			return { status: action.type, result: action.result }
		case reactConstants.FETCH_FAILURE:
			return { status: action.type, error: action.error }
		default:
			return state
	}
}
```

### Why should this feature be included?
Concurrent mode in React will definitely become stable one day, and by having this wrapper we could reduce boilerplate code. 
#### I propose the next usage:
1. In reducer file:
```js
import { fetchReducer } from 'react-redux'
import { combineReducers } from 'redux'

...
// consider reducers array defined
...

const rootReducer = combineReducers(...reducers, fetchReduer)
```
2. In action file:
```js
import { wrapAsyncAction } from 'react-redux'
...
// consider an asyncAction as a redux-thunk async action that returns a promise
...

export const loadData = wrapAsyncAction(asyncAction)
```
3. Then in a component file we can call that action when it's wrapped by `<Suspense />`
```js
import React, { Suspense } from 'react'
import { bindActionCreators } from 'redux'
import { connect } from 'react-redux'

const Fetcher = ({resource}) => {
  resource.read()
  return <>read successfully!</>
}

const Component = ({loadData}) => 
  <Suspense fallback={<h1>Loading...</h1>}>
    <Fetcher resource={loadData()} />
  </Suspense>

export default connect(null, dispatch => bindActionCreators({ loadData: actions.loadData }, dispatch)(Component)
```
### What docs changes are needed to explain this?
The only thing that may push you away that it needs a redux-thunk type action.
No changes needed atm, because it could be a new feature.

**Comment by Alishreder** [comment]
needed this for a long time!

**Comment by markerikson** [comment]
I don't think this is anything that belongs in React-Redux atm, if I'm understanding this right.  In particular, I'm not seeing anything that's actually React-related.  In addition, the Suspense APIs aren't stable yet, and the React team has said that the whole Promise-based aspect is likely to change.

However, note that [our Redux Toolkit package will have a new `createAsyncThunk` API in 1.3.0](https://github.com/reduxjs/redux-toolkit/releases/tag/v1.3.0-beta.0) that is somewhat similar to this in terms of abstracting behavior based on fetch logic.

**Comment by sktguha** [comment]
> and the React team has said that the whole Promise-based aspect is likely to change.

Hi Mark @markerikson  , could you point me to where it is being said ? was actually thinking of doing something similar mentioned here , but if the API is changing then it might not be worth it to do it then. Will need to wait until it is stable I guess

Thanks in advance

**Comment by markerikson** [comment]
I know I saw a couple tweets mentioning this a while back, but it's been a while.  Given that the Server Components functionality seems to be based around the same throwing Promises approach, they may have decided to stick with that.

But yes, I'd still consider everything having to do with Suspense as being completely indefinite until it's truly and finally released as a stable production build.

**Comment by sktguha** [comment]
Oh I see. Thanks! . I believe according to the React blog post suspense was released very recently, but I didn't see it mentioned on the blog anywhere when there is going to be a stable rstable production build.

**Comment by markerikson** [comment]
No, Suspense has most definitely _not_ been released for production yet.  

There is a real `<Suspense>` component, but at the moment it's only used for lazy loading in stable builds.

The rest of the Suspense implementation is still very much a work in progress.

**Comment by sktguha** [comment]
Oh I see. yes indeed , it has not been released. Thanks.

Also a bit unrelated , what do you think is the solution to the two problems mentioned in this article ? ( don't agree too much with the rest of the article though) ,
https://codeburst.io/the-ugly-side-of-redux-6591fde68200#fa23:~:text=The%20store%E2%80%99s%20life%20cycle%20is%20different%20from%20the%20components%E2%80%99%20life%20cycle
https://codeburst.io/the-ugly-side-of-redux-6591fde68200#a6cf:~:text=The%20global%20store%20is%20a%20singleton%2C%20but%20a%20component%20may%20have%20many%20instances

I have myself run into both problems personally.

**Comment by sktguha** [comment]
@markerikson

**Comment by markerikson** [comment]
@sktguha off-topic for this thread.  Please find another venue to discuss this :)
