### ISSUE TITLE
update from 5.x to 7.x,  throw an error , can not get  store from context

### ISSUE THREAD

**Issue by 5j2f** [reduxjs/react-redux#1554]
![reducerinjecter](https://user-images.githubusercontent.com/8499421/77820708-25c7d700-711f-11ea-92c6-ef68f08f243c.png)

**Comment by markerikson** [comment]
That code is trying to access the store out of legacy context, which was never part of our public API.

Please see the [Accessing the Store](https://react-redux.js.org/using-react-redux/accessing-store) and [Hooks#`useStore`](https://react-redux.js.org/using-react-redux/accessing-store#using-the-usestore-hook) docs pages for instructions on how to do so safely with v7.
