### ISSUE TITLE
Optional peer dependencies are incorrectly listed in package.json

### ISSUE THREAD

**Issue by mprast** [reduxjs/react-redux#1559]
Currently `react-dom` and `react-native` are listed as optional peer dependencies of react-redux, but they are _only_ listed in `peerDependenciesMeta` and not in `peerDependencies`. Looking at the RFC for optional peer dependencies in Yarn v2, I'm pretty sure the correct way is to list them in both fields: 
https://github.com/yarnpkg/rfcs/pull/105#issuecomment-438474104

Consistent with this, I'm seeing yarn v2 (with pnp) complaining that `A package is trying to access another package without the second one being listed as a dependency of the first one`, even when `react-dom` is a dep of the `react-redux`'s direct ancestor.

Happy to provide a PR and\or a repro if you'd like!

redux: 4.0.5
react-redux: 7.2.0
react-dom: 16.12.0

**Comment by markerikson** [comment]
Yep, I'd fully expect PnP to whine about that.

Also see these previous discussions:

- #1261
- #1282
- #1371
- #1366
- #1424
- #1425
