### ISSUE TITLE
Cannot add property current, object is not extensible useRef

### ISSUE THREAD

**Issue by lianulloa** [reduxjs/react-redux#1564]
Hi, I'm having this issue using *forwardRef*. I'm doing something like this

**What is the current behavior?**
```javascript
function Test(props,ref){
  const a = () =>{
  }

  useImperativeHandle(ref, () => {
    return {
        someFn(){

      }
    }
  })
  return <div>
      test componente
  </div>
}

export default connect(() =>{}, ()=> {},null, {forwardRef:true})(Test)

const App = (props) => {
  const myRef = useRef();
  return   <Testf ref={myRef} />

}
```
and I'm getting this error: **Cannot add property current, object is not extensible useRef**

**What is the expected behavior?**

Why I expect is to have in myRef what I defined using useImperativeHandle hook

I'm using   "react-redux": "^7.1.1"

**Comment by timdorr** [comment]
You only get the ref value if you yourself are using forwardRef. All that option does in React Redux is pass the ref prop through to the connected component.
