### ISSUE TITLE
Link Not Working Properly

### ISSUE THREAD

**Issue by ShrutikaSingh** [reduxjs/react-redux#1580]
Think you found a bug?
   **Yes**

**What is the current behavior?**

When we visit the  API section  under Subscribe to the store and inject action creators on page at https://react-redux.js.org/introduction/basic-tutorial, it leads to status 404, page not found at https://react-redux.js.org/api/connect.md,

![image](https://user-images.githubusercontent.com/42492660/81281022-f0e06580-9076-11ea-93f0-f2b19cb5a6a7.png)

**What is the expected behavior?**
It would need to show some page instead of 404 at https://react-redux.js.org/api/connect.md,

**Comment by timdorr** [comment]
Can you submit a PR to fix this link?
