### ISSUE TITLE
Incorrect/dead links

### ISSUE THREAD

**Issue by jinhale** [reduxjs/react-redux#1583]
From some pages including [accessing the store](https://react-redux.js.org/using-react-redux/accessing-store) there is at least one bad [link](https://react-redux.js.org/api/hooks.md#useStore).  

To correct the link remove the portion of the URL that is '.md'. This may need to be done for multiple pages.

**Comment by timdorr** [comment]
This seems to be a common issue with Docusaurus. They _should_ be converted from the file links to the generated URLs when the site is built. Maybe we have some setting wrong?

**Comment by josephMG** [comment]
https://github.com/facebook/docusaurus/releases/tag/v2.0.0-alpha.64
https://github.com/facebook/docusaurus/pull/3429
upgrade docusaurus should fix it.
