### ISSUE TITLE
Broken link in topic: "Connect: Dispatching Actions with mapDispatchToProps"

### ISSUE THREAD

**Issue by kevgrig** [reduxjs/react-redux#1584]
Broken link in https://react-redux.js.org/using-react-redux/connect-mapdispatch#can-i-call-storedispatch

> It's an anti-pattern to interact with the store directly in a React component, whether it's an explicit import of the store or accessing it via context (see the [Redux FAQ entry on store setup](https://redux.js.org/faq/storesetup#can-or-should-i-create-multiple-stores-can-i-import-my-store-directly-and-use-it-in-components-myself) for more details).

**Comment by timdorr** [comment]
Can you submit a PR to fix this?

**Comment by kevgrig** [comment]
@timdorr It doesn't seem like the referenced FAQ exists any more: https://redux.js.org/faq/store-setup
