### ISSUE TITLE
connect ignores the Types of ownProps

### ISSUE THREAD

**Issue by kiranjd** [reduxjs/react-redux#1587]
**What is the current behavior?**

When using connect function the types of the interface are completely ignored in my `tsx` file. All I see when I import the same component are autocompletes for default JSX only.

I have also tried it using class component as well. The same issue persists.

The following that I have tried is from official docs of [react-redux](https://redux.js.org/recipes/usage-with-typescript#typing-the-connect-higher-order-component)

```
import { connect, ConnectedProps } from 'react-redux'

interface RootState {
  isOn: boolean;
}

const mapState = (state: RootState) => ({
  isOn: state.isOn,
});

const mapDispatch = {
  toggleOn: () => ({ type: 'TOGGLE_IS_ON' }),
};

const connector = connect(
  mapState,
  mapDispatch
);

// The inferred type will look like:
// {isOn: boolean, toggleOn: () => void}
type PropsFromRedux = ConnectedProps<typeof connector>;

type Props = PropsFromRedux & {
  backgroundColor: string;
};

const Text = (props: Props) => {

...

}
export default connector(Text)
```

if I export without using connect, I get all the types intact. i.e.,
```js
// all types are shown
export default Text
```
**What is the expected behavior?**

Versions: 
- react: 16.8.6
- react-redux: 7.2.0

The connect function should preserve the types.

**Comment by kiranjd** [comment]
Solved it.

I didn't install `@types/react-redux`. Works like charm.

**Comment by zero-t4** [comment]
But [docs](https://react-redux.js.org/7.1/using-react-redux/static-typing#typescript) "React-Redux doesn't ship with its own type definitions. If you are using Typescript you should install the @types/react-redux type definitions from npm."

I think here https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-redux/index.d.ts#L299 should be not just 
`? TInjectedProps`
but 
`? TInjectedProps & TNeedsProps`
