### ISSUE TITLE
static typing useSelector requires return type

### ISSUE THREAD

**Issue by zanona** [reduxjs/react-redux#1590]
Following the docs at https://react-redux.js.org/using-react-redux/static-typing#typing-the-useselector-hook it's mentioned that we can type `useSelector` by simply including the RootState as:

```ts
const selectIsOn = (state: RootState) => state.isOn
```

However, I've noticed I could also use a generic type.
The problem I'm facing is that the return type is being set to `unknown` and requires me to also define  a second generic param as a return type:

```ts
const currency = useSelector<{locale:{ccy:'USD'}}>(state => state.locale.ccy); // < unknown
const currency = useSelector<{locale:{ccy:'USD'}},'USD'>(state => state.locale.ccy); // < 'USD'
```

Would there be any way to inherit the return type automatically as it already knows the typing of the root state?

**Comment by markerikson** [comment]
The generic is generally inferred. The simplest approach is to type the `state` arg in the selector as shown, and that way the return type gets inferred as well.
