### ISSUE TITLE
Docs: Links to discord points to a Gist instead

### ISSUE THREAD

**Issue by remram44** [reduxjs/react-redux#1591]
Links to the Discord channel on the website point to [this Gist](https://gist.github.com/gaearon/1d19088790e70ac32ea636c025ba424e) instead ([search this repo for 1d19088790e70ac32ea636c025ba424e](https://github.com/reduxjs/react-redux/search?q=1d19088790e70ac32ea636c025ba424e&unscoped_q=1d19088790e70ac32ea636c025ba424e)).

I'm not sure what the link should be, which is why I opened an issue, not a PR.

**Comment by remram44** [comment]
The "Reactiflux invite link" also seems to not be an invite link.

**Comment by markerikson** [comment]
Yeah, that should point to the Reactiflux Discord instead, same as the Redux core docs.

Can you submit a PR to make the React-Redux links match the ones on the Redux core docs?

**Comment by timdorr** [comment]
@markerikson Looks like you did it :P #1097
