### ISSUE TITLE
Basic Tutorial - Actions and Reducers source code not consistent

### ISSUE THREAD

**Issue by zarasyversen** [reduxjs/react-redux#1594]
Hi! 👋  
I just completed the basic tutorial and got a bit confused as the source code files on the Actions and Reducers steps does not match the final code shown in complete source code. This stops the todo list from working properly (if you only follow the steps) once you reach the end of the tutorial.

https://redux.js.org/basics/basic-tutorial

## Actions
Actions Step: https://redux.js.org/basics/actions#actionsjs
Actions - Complete code: https://redux.js.org/basics/example#actionsindexjs

The step is missing setting the `id` in `addTodo`. 

## Reducers
Reducers Step: https://redux.js.org/basics/reducers#reducersjs
Reducers - Complete (and split up): https://redux.js.org/basics/example#reducerstodosjs

The step is missing `id` as well in `'ADD_TODO'`.

**Comment by markerikson** [comment]
Yeah, the various example pages and snippets have been edited by different people at different times.

I'm planning to rewrite the entire tutorial sequence in the near future, so it's not worth trying to make them consistent at this point.

**Comment by timdorr** [comment]
Yep, follow up in #1574

**Comment by markerikson** [comment]
Actually, the other issue is that this is the React-Redux repo, but the topic is the Redux core tutorial.

**Comment by zarasyversen** [comment]
Ohhhh I am in the completely wrong repo! Don't know how that happened 😂  Sorry about that @markerikson
