### ISSUE TITLE
Upgrade to react 16.13.1 and @types/react 16.9.38 create some console error

### ISSUE THREAD

**Issue by richard-li-next** [reduxjs/react-redux#1595]
I did the following upgrade:
![image](https://user-images.githubusercontent.com/65935211/85394950-f855c280-b581-11ea-8f15-76b27a1e73bb.png)

Then I get some errors in the console:
![image](https://user-images.githubusercontent.com/65935211/85395155-466ac600-b582-11ea-81ec-1019de50957d.png)

**Comment by markerikson** [comment]
This question doesn't appear to be related to React-Redux at all.

**Comment by richard-li-next** [comment]
@markerikson When I rolled back the version of @types/react to 16.9.5 they disappeared

**Comment by markerikson** [comment]
That's the _React_ type.  This is the _React-Redux_ repo.  Totally different library.

And, neither React nor React-Redux maintain their own types. Those live in DefinitelyTyped for both libraries.
