### ISSUE TITLE
useSelector results memory leak in child component

### ISSUE THREAD

**Issue by barron9** [reduxjs/react-redux#1597]
using this in parent component and back-forth to page, left memory uncleaned. without useselector issue is fixed.:
<img width="1155" alt="Screen Shot 2020-06-28 at 14 54 42" src="https://user-images.githubusercontent.com/27488285/85946955-9f56a780-b950-11ea-87a6-5a86ac8284aa.png">
<img width="1155" alt="Screen Shot 2020-06-28 at 14 54 37" src="https://user-images.githubusercontent.com/27488285/85946958-a1b90180-b950-11ea-8058-95d7614b1d4c.png">

```
export function RegisterScreenFooter () {

    let footerState = useSelector((state: registration) => state.registration.footer);
```

https://stackoverflow.com/questions/62622168/useselector-results-memory-leak-in-child-component

**Comment by markerikson** [comment]
The screenshots aren't telling me anything useful.  Please provide a CodeSandbox that reproduces the issue.

**Comment by eddietisma** [comment]
Maybe this is related to Subscription not unsubscribing correctly? 

The useSelector creates a new Subscription, passing ReduxContext in as a parameter. In Subscription.js after trySubscribe there is no unsubscribe happening on parentSub. Hence parentSub.addNestedSub will never unsubscribe.

https://github.com/reduxjs/react-redux/blob/a9235530f4799dd4b2acb3cc65e9caf32efbc44b/src/hooks/useSelector.js#L17
https://github.com/reduxjs/react-redux/blob/a9235530f4799dd4b2acb3cc65e9caf32efbc44b/src/utils/Subscription.js#L106

**Comment by markerikson** [comment]
The unsubscription happens down here:

https://github.com/reduxjs/react-redux/blob/a9235530f4799dd4b2acb3cc65e9caf32efbc44b/src/hooks/useSelector.js#L81

**Comment by eddietisma** [comment]
Hmm.. Where is the unsubscribe from parentSub?  Am I missing something?

```
this.unsubscribe()
this.unsubscribe = null
this.listeners.clear()
this.listeners = nullListeners
```

**Comment by markerikson** [comment]
Yes, `this.unsubscribe()` _is_ the right line.

A `Subscription` instance will be subscribed to either the Redux store directly, or its nearest `Subscription` ancestor.  So, per these lines, `this.unsubscribe` is the subscription cleanup function that was either returned from `store.subscribe()`, or `parentSub.addNestedSub()`:

https://github.com/reduxjs/react-redux/blob/a9235530f4799dd4b2acb3cc65e9caf32efbc44b/src/utils/Subscription.js#L105-L107

**Comment by eddietisma** [comment]
Ah, of course... Thanks!

**Comment by markerikson** [comment]
Never got a reproduction for this, so I'm closing it.

**Comment by LaxmanPache123** [comment]
I am getting memory leak  when I am useSelector
  const { permissions } = useSelector((state) => {
    return state.user;
  });
is there any solution

**Comment by phryneas** [comment]
@LaxmanPache123 you should be doing `const permissions = useSelector((state) => { return state.user.permissions; });` but either way that will just lead to more rerenders, not to a memory leak. It is highly unlikely that that line is causing any kind of leak, but if it does: please read the comment above yours. 

Without any reproduction (a runnable repository where we can see it happening) we cannot do anything about this.
