### ISSUE TITLE
Why can't useSelector exist outside of a function?

### ISSUE THREAD

**Issue by vscing** [reduxjs/react-redux#1600]
### What is the new or updated feature that you are suggesting?
```diff
Why can't useSelector exist outside of a function?
import React from 'react'
import { useSelector } from 'react-redux'

+ const counter = useSelector(state => state.counter)
export const CounterComponent = () => {
- const counter = useSelector(state => state.counter)
  return <div>{counter}</div>
}
```

### Why should this feature be included?
```
There is no explanation for this in the document
Updating the state will result in the state not working
```

### What docs changes are needed to explain this?
```
Indicate scope
```

**Comment by papb** [comment]
This is not specific to `useSelector` from `react-redux`, this is true for any React hook. Take a look at the [react guide on Hooks](https://reactjs.org/docs/hooks-overview.html) and [API reference](https://reactjs.org/docs/hooks-reference.html).
