### ISSUE TITLE
Dark theme for React Redux website.

### ISSUE THREAD

**Issue by KariNarhi** [reduxjs/react-redux#1603]
## Dark Theme for React Redux documents website.

I'd like to suggest implementing a Dark theme toggle switch for https://react-redux.js.org/ , the same way Redux website https://redux.js.org/ and Redux Toolkit website https://redux-toolkit.js.org/ have that small toggle switch at the right upper corner of the top navbar.

React Redux website navbar, with no theme toggle:
![ReactRedux](https://user-images.githubusercontent.com/46904974/86514926-25299580-be1e-11ea-97de-0488d9db37d4.png)

Redux website navbar, with a theme toggle:
![Redux](https://user-images.githubusercontent.com/46904974/86514943-438f9100-be1e-11ea-8989-33a8cba8c7cd.png)

Redux Toolkit navbar, with a theme toggle:
![ReduxToolkit](https://user-images.githubusercontent.com/46904974/86514953-51451680-be1e-11ea-9cbe-5f6dec35a6b5.png)

It really hurts your eyes when you read other Redux documents with dark theme and suddenly React Redux website is bright white.

**Comment by markerikson** [comment]
This is dependent on migrating the React-Redux docs to use Docusaurus v2.  The Redux and RTK sites have been migrated, but we haven't yet done the React-Redux site, largely because the versioning aspect makes it more complex.

If someone would like to tackle doing the migration, that would be appreciated.

**Comment by Reflex-Gravity** [comment]
Can I take this? I'll try to migrate it to v2.

**Comment by Reflex-Gravity** [comment]
Sure, thanks.

**Comment by ruppysuppy** [comment]
I would like to work on this issue, but I have not worked with Docusaurus and am facing a few problems to get it up and running (was unable to trigger onClick event in react and was unable to figure out where to modify the header from). I was planning to add the dark mode using 
```CSS
filter: invert(1) hue-rotate(180deg);
```
Could you help me with the issues @markerikson ?

**Comment by markerikson** [comment]
@ruppysuppy : as I said above, the right answer here is to migrate our docs to Docusaurus v2.  If you'd like to work on that I'd really appreciate it, but no, a CSS hack like that is not the approach we need.

**Comment by ruppysuppy** [comment]
@markerikson, I would like to give it a try, but it might take a couple of days as I would have to go through Docusaurus docs

**Comment by ruppysuppy** [comment]
@markerikson, I am unable to do it. The versioning does complicate it in Docusaurus 2.

**Comment by markerikson** [comment]
We upgraded to DSv2 in #1638 , so this is available now!
