### ISSUE TITLE
Make useSelector value inspectable in dev tools

### ISSUE THREAD

**Issue by dimaqq** [reduxjs/react-redux#1613]
## New Features

I would love it if I could see the values that `useSelector()` returns in the react dev tools, in the hooks section of the component details.

Today I can get to the value, but it requires several clicks, and it's a bit unclear, as it's shown as 1 of 3 `Ref`'s:

<img width="596" alt="Screenshot 2020-07-13 at 17 28 30" src="https://user-images.githubusercontent.com/662249/87281938-b390cc00-c52e-11ea-85ff-2bb5001f5f41.png">

Arguably the returned value could large (hairy nested object, large string), thus, some heuristic is needed to truncate the representation.

Naive implementation is easy with `useDebugValue()` but the above is a concern.

### What is the new or updated feature that you are suggesting?

New

### Why should this feature be included?

* to improve developer experience
* to appear similar to `useState`
* library user cannot do this in their component code

### What docs changes are needed to explain this?

Eh?

**Comment by markerikson** [comment]
Already done in #1525 and #1530 - we just have been very slow in releasing a new build.

I will attempt to get a new build out in the next day or so.

**Comment by markerikson** [comment]
Finally live in https://github.com/reduxjs/react-redux/releases/tag/v7.2.1

**Comment by dimaqq** [comment]
🎉 Fantastic! 🎉 
(`undefined` is expected)
<img width="477" alt="Screenshot 2020-07-27 at 9 31 20" src="https://user-images.githubusercontent.com/662249/88493457-3e240180-cfec-11ea-9d3a-1d732113aad2.png">

P.S. now if there were a babel macro to annotate the purpose of selector, e.g. the variable name from `const token_claims = useSelector(...)` :wishful-thinking:

**Comment by th3fallen** [comment]
@dimaqq if you find such a thing please for the love of everything holy share it
