### ISSUE TITLE
connectAdvanced.js?48b8:191 Uncaught Error: withRef is removed. To access the wrapped instance, use a ref on the connected component

### ISSUE THREAD

**Issue by sumantaparida** [reduxjs/react-redux#1617]
**What is the current behavior?**

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to a CodeSandbox (https://codesandbox.io/s/new) or RN Snack (https://snack.expo.io/) example below:

**What is the expected behavior?**

Which versions of React, ReactDOM/React Native, Redux, and React Redux are you using?  Which browser and OS are affected by this issue? Did this work in previous versions of React Redux?

**Comment by sumantaparida** [comment]
> **What is the current behavior?**
> 
> If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to a CodeSandbox (https://codesandbox.io/s/new) or RN Snack (https://snack.expo.io/) example below:
> 
> **What is the expected behavior?**
> 
> Which versions of React, ReactDOM/React Native, Redux, and React Redux are you using? Which browser and OS are affected by this issue? Did this work in previous versions of React Redux?

Issues not resolved

**Comment by markerikson** [comment]
You haven't answered any of the questions in the issue template, so there's no way to help you here.

As the error message says, React-Redux v7 does not support the `withRef` option.  Use the `forwardRef` option instead:

https://react-redux.js.org/api/connect#forwardref-boolean

**Comment by timdorr** [comment]
If you post nothing, you get nothing.

**Comment by sumantaparida** [comment]
> connectAdvanced.js?48b8:191 Uncaught Error: withRef is removed. To access the wrapped instance, use a ref on the connected component
    at connectAdvanced (connectAdvanced.js?48b8:191)
    at connect (connect.js?3de0:91)
    at createConnectedField (ConnectedField.js?834c:308)
    at createField (createField.js?79cb:22)
    at eval (Field.js?bf70:4)
    at Module../node_modules/redux-form/es/immutable/Field.js (vendors~main.chunk.js:13569)
    at __webpack_require__ (main.js:788)
    at fn (main.js:151)
    at eval (immutable.js?c85a:1)
    at Module../node_modules/redux-form/es/immutable.js (vendors~main.chunk.js:13557)

**Comment by sumantaparida** [comment]
I have to add forwardRef also but still not working 

============
`ProfileAdditionalInformation = connect(
  (state, props) => {
    let { profile } = props;
    profile = profile.toJS();
    const address = profile && profile.address;
    const thirdPartyAssociation = (profile && profile.thirdPartyAssociation) || [];
    const setInitialValue = {};
    thirdPartyAssociation.forEach(ele => {
      setInitialValue[`${ele.type}WithWhom`] = ele.thirdParty;
      setInitialValue[`${ele.type}`] = true;
    });
    return {
      initialValues: {
        ...setInitialValue,
        primarySourceOfIncome: profile.primarySourceOfIncome,
        insuranceExperienceInYears: profile.insuranceExperienceInYears,
        officeSpace: profile.officeSpace,
        monthlyMotorPremium: profile.monthlyMotorPremium,
        monthlyHealthPremium: profile.monthlyHealthPremium,
        monthlyLifePremium: profile.monthlyLifePremium,
        /* dateOfBirth: profile.dateOfBirth ? new Date(profile.dateOfBirth) : new Date(), */
      },
      thirdPartyAssociation: (profile && profile.thirdPartyAssociation) || [],
    };
  },
  undefined,
  undefined,
  { forwardRef: true },
)(ProfileAdditionalInformation);`
============

**Comment by sumantaparida** [comment]
Thing is I'm not using `withRef` anywhere in my codebase.

**Comment by markerikson** [comment]
This appears to be an issue with use of Redux-Form.  Please upgrade the version of Redux-Form you're using, as it's not compatible with React-Redux v7.
