### ISSUE TITLE
 Feature for tracking the parts of state that are actually needed by a component, instead of adding them manually.

### ISSUE THREAD

**Issue by lopeselio** [reduxjs/react-redux#1629]
## New Features
connect and useSelector programming interfaces usually depend on the user manually specifying which state would need to be extracted in order to be rendered

### What is the new or updated feature that you are suggesting?
Would be helpful and easy if there is a feature for tracking the parts of state that are actually needed by a component

### Why should this feature be included?
So that added components do not increase the bundle size

**Comment by timdorr** [comment]
This isn't how Redux works. It only takes a single reducer at its root, so state cannot be broken up into smaller bits. 

If you want to lazy load parts of your app to reduce chunk sizes in your bundle, you are certainly free to do that. But it's not something Redux can help you with.

**Comment by markerikson** [comment]
Also, frankly it's really not clear what you're asking for here, either.

**Comment by dai-shi** [comment]
Not sure, but is it something like #1503?
