### ISSUE TITLE
useState Hook

### ISSUE THREAD

**Issue by myckhel** [reduxjs/react-redux#1630]
## New Features
useState Hook

### What is the new or updated feature that you are suggesting?
- useState Hook for runtime state management
- access a particular component state from another component with hooks 

### Why should this feature be included?
Some times developers would like to create runtime redux states for react components without having to manually create: `reducers` and `actionCreators`.
It would be a good idea if developers can create react component states at runtime in redux store.
similar to react's `useState` hook could be implemented in `react-redux`.

I have implemented a custom hook in my project named `useReduxState`
`useReduxState` allows creating states in redux store without writing the reducer and actions.

`useReduxState` accepts 2 arguments `(uniqueStateName, initialState)` returns object `{selector, setState, getState}`

#### Usage:
```js
// i can create a redux state at runtime
const Component1 = () => {
    const {selector, setState} = useReduxState('component1_state', {count: 1});
    const state = useSelector(selector, (n, p) => n !== p); // {count: 1}

    return <Button onPress={() => setState({count: state.count + 1})} title="Increment" />
}

// i can access Component1 state
const Component2 = () => {
    const {selector} = useReduxState('component1_state');
    const state = useSelector(selector, (n, p) => n !== p); // {count: 2}

    return <Text title={"current component 1 state is: " + state.count} />
}

// i can create a redux state at runtime without depending on the state
const Independent = () => {
    const {selector, setState} = useReduxState('independent_state', {independent: 1, portion: 10});

    return <Button onPress={() => setState({independent: state.independent + 1})} title="Increment independent" />
}

// i can depend on Independent state
const Dependent = () => {
    const {selector} = useReduxState('independent_state');
    const state = useSelector(selector, (n, p) => n !== p); // {independent: 2}

    return <Text title={"i am depending on Independent component state which is: " + state.independent} />
}

// i can depend on a portion of a state
const Dependent2 = () => {
    const {selector} = useReduxState('independent_state');
    const portion = useSelector((state) => selector(state).portion, (n, p) => n !== p); // portion: 10

    return <Text title={"i am depending only on a portion of a state which is: " + portion} />
}
```

### What docs changes are needed to explain this?
New Hook docs has to be added documenting the features.

I have thought of creating a library but i would like to know if this feature would be accepted in react-redux so i can make pull request  with the feature.

**Comment by myckhel** [comment]
I have Created some demonstrations on `codesandbox`: https://codesandbox.io/s/usereduxstate-gdl7g?file=/src/App.js

**Comment by markerikson** [comment]
Appreciate the suggestion, but this doesn't look like something we'd want to add to React-Redux.

You're always welcome to publish your own lib if you find it useful, though!

**Comment by myckhel** [comment]
Okay Great
