### ISSUE TITLE
Docs: accessing store page useStore Hook Link seem to be broken

### ISSUE THREAD

**Issue by makuzaverite** [reduxjs/react-redux#1633]
In docs when you try to go to http://react-redux.js.org/api/hooks.md#useStore nothing works it is 404 page 

this needs to be fixed

**Comment by timdorr** [comment]
File is here: https://github.com/reduxjs/react-redux/blob/master/docs/using-react-redux/accessing-store.md

It appears to be the correct link, so I'm not sure what's going on there.

**Comment by makuzaverite** [comment]
Ok got it

**Comment by spencer741** [comment]
This issue is still persisting in a particular part of the docs.
https://react-redux.js.org/using-react-redux/accessing-store#using-the-usestore-hook

The link in that section is likely incorrect. Showing 404...
https://react-redux.js.org/api/hooks.md#useStore

**Comment by markerikson** [comment]
This may be related to the whole lowercasing of anchors thing that DSv2 fixed at some point.

As I've said numerous times, the docs need to be updated to use DS v2, but I don't have time to do it myself right now.
