### ISSUE TITLE
useSelector is rendering 2 times,

### ISSUE THREAD

**Issue by Taymindis** [reduxjs/react-redux#1634]
useSelector is rendering 2 times when dispatch action, when you click "Increase" Button, the useReduxHook will increase 2 times, instead, using connect HOC is working fine.

Expected useSelector only render 1 at a time

Refs: 
https://codesandbox.io/s/bold-dawn-7yvq4?file=/src/App.js

**Comment by markerikson** [comment]
React re-renders components multiple times in `<StrictMode>`.  If you change that update to be in a `useEffect`, or log inside there, you'll see that only one render is being committed.
