### ISSUE TITLE
[useSelector] throw missing selector error also in production 

### ISSUE THREAD

**Issue by croraf** [reduxjs/react-redux#1635]
https://github.com/reduxjs/react-redux/blob/master/src/hooks/useSelector.js#L99-L101

**What is the current behavior?**

When selector is not provided the error is not thrown in production mode. 

**What is the expected behavior?**

The error should be thrown in production mode also. Not sure why there is an additional production mode check. If it is for performance reasons, checking `!selector` is of the same performance as checking the `"string" !== "string"`.

Perhaps some compilers remove the block completely during compile time?

**Comment by timdorr** [comment]
This is because the error is the result of passing in bad input. This should be caught during development and not make its way to production. Once in production, that error message is not helpful to end users, so we hide it.

**Comment by croraf** [comment]
Just to mention that there might be cases where this is not caught in development, when the selector is dynamically passed from the parent component to the reusable "presentational" component which has `useSelector(selector_passed_from_props)`.
