### ISSUE TITLE
Functionality of 404 page.

### ISSUE THREAD

**Issue by Yashvirani** [reduxjs/react-redux#1636]
Would like to work on improving the functionality of 404 page . I would like to contribute to react-redux.
Thank you for contributing to open source!
### What is the new or updated feature that you are suggesting?
Avoiding the page refresh.
### Why should this feature be included?
Improve unwanted page refresh.
### What docs changes are needed to explain this?
Its a small improvement that could be done.

**Comment by markerikson** [comment]
Sorry, not sure what you're suggesting here. What "page refresh" are you talking about?

What we _do_ need is to [migrate the React-Redux site to Docusaurus v2](https://github.com/reduxjs/react-redux/issues/1603#issuecomment-692784170).

**Comment by Yashvirani** [comment]
In 404.js file in website directory , for the below code:-
(<a href="/">Return to the front page</a>)
We could use react-router-dom <Route> tag instead of using normal <a> tag which I guess could prevent the unwanted page refresh.

**Comment by Yashvirani** [comment]
{<a href="/">Return to the front page</a>}
For the above line of code in 404.js file in website directory we could use react-router-dom <Route> tag instead of using normal <a> tag which I guess could prevent the page from refreshing which it's clicked.

**Comment by Yashvirani** [comment]
{<a href="/">Return to the front page</a>}
For the above line of code in 404.js file in website directory we could use react-router-dom {<Route>} tag instead of using normal {<a>} tag which I guess could prevent the page from refreshing which it's clicked.

**Comment by markerikson** [comment]
This functionality is part of Docusaurus itself. Like I said, the right solution here is to switch to Docusaurus v2.

**Comment by Yashvirani** [comment]
Ok 👍 right.

**Comment by markerikson** [comment]
We've upgraded to Docusaurus v2.  If there's anything else that needs to be done here, please file an additional issue.
