### ISSUE TITLE
Nested connect() child components have stale props with React.Context

### ISSUE THREAD

**Issue by flannanl** [reduxjs/react-redux#1642]
**What is the current behavior?**

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to a CodeSandbox (https://codesandbox.io/s/new) or RN Snack (https://snack.expo.io/) example below:

I have created a small example at https://codesandbox.io/s/react-redux-sample-d442e.
- Go to the above example link.
- Open the Console tab in the Preview pane. Alternatively, run my example in a new window and open the Console tab in the DevTool.
- Click either the "Increment" or "Decrement" button.
- Inspect the logs in the Console.

You will see something like below:

```
from AppContainer: mapStateToProps
index.js:27 counter in AppContainer.js render: 1
index.js:27 counter in Component.js render: 0
index.js:27 Component.js: mapStateToProps
index.js:27 counter in Component.js render: 1
```

My `Component.js` is re-rendered twice. It seems one is triggered by the React Context.Provider and the other one is triggered by the redux store update. And you can see that the counter value in the first re-render is stale. However if I remove line 8 in Component.js (i.e. the line that use the `useContext` callback), `Component.js` is only re-rendered once and the props are updated properly at re-render time.

**What is the expected behavior?**

- I will expect my Component should only be re-rendered once with the props being updated properly. Please note that if I don't use React.Context, the store update and the re-render works as expected. It is only an issue if I use React.Context in my component.

Which versions of React, ReactDOM/React Native, Redux, and React Redux are you using?  Which browser and OS are affected by this issue? Did this work in previous versions of React Redux?

- This issue is seen in Chrome and Safari. Also this issue is not seen in `react-redux` v6 or earlier.

- Dependencies:

<img width="374" alt="image" src="https://user-images.githubusercontent.com/12156672/95896578-70770c80-0d5a-11eb-846d-1f94e55eee24.png">

**Comment by markerikson** [comment]
The first issue with this is, don't try to count renders by logging directly in the component's render logic.  Do it in a `useLayoutEffect()` afterwards.  React will double-render components in `<StrictMode>` in development to help flush out bugs.

It _is_ possible that there's some subtle timing back and forth between context and React-Redux, especially with nested `connect` components.  In particular, `connect` relies on cascading subscriptions that are triggered in the commit phase.

**Comment by flannanl** [comment]
My real application is more complicated. I have an input field in my application and the validation state is stored in redux. The problem is that my app can have external actions that can be triggered to override the props and that could trigger subsequent validation actions. Since the prop has a stale value during re-render, my child component thinks there is an updated value (in fact, it is the old value) needs to be processed and so it triggers the unintentional validation action and that screws my store and the value I entered is actually reverted.

**Comment by markerikson** [comment]
I'm going to close this as a WONTFIX for now, largely because we're encouraging folks to stop using `connect` (even though it'll be fully supported in v8).  This is a real bit of behavior that I can understand is annoying, but I don't think there's a meaningful change we can make at this point, and I don't intend to spend time fixing it myself.

If someone still feels strongly about this please comment, or even better file a PR to improve behavior here.
