### ISSUE TITLE
InferableComponentEnhancerWithProps does not correctly infer class-based (React.Component flavor) component properties

### ISSUE THREAD

**Issue by yurigenin** [reduxjs/react-redux#1644]
**What is the current behavior?**

When using a component class extending **React.Component** to connect to Redux store with **connect()** HOC the returned component is of an **InferableComponentEnhancerWithProps** type. But this type does not correctly derive the properties of the component because internally it relies on the component to extend **React.ComponentType**. But **React.Component** does not extend it, thus, the property inferring fails.

The definition of the **InferableComponentEnhancerWithProps** is here:

```
export type InferableComponentEnhancerWithProps<TInjectedProps, TNeedsProps> =
    <C extends ComponentType<Matching<TInjectedProps, GetProps<C>>>>(
        component: C
    ) => ConnectedComponent<C, Omit<GetProps<C>, keyof Shared<TInjectedProps, GetProps<C>>> & TNeedsProps>;
```
It uses **GetProps** type to match injected properties with **propTypes** properties:

```
export type GetProps<C> = C extends ComponentType<infer P> ? P : never;
```

It will always return **never** since **React.ComponentType** is defined as:

```
type ComponentType<P = {}> = ComponentClass<P> | FunctionComponent<P>;
```

But any component that is defined as:

```
class MyComponent extends React.Component<MyProps> {}
```

does not extend from either **ComponentClass** or **FunctionComponent**.

It results in all injected properties not getting omitted as intended because **GetProps** type is **never**:

```
ConnectedComponent<C, Omit<GetProps<C>, keyof Shared<TInjectedProps, GetProps<C>>> & TNeedsProps>;
```

**What is the expected behavior?**

All injected properties that match **propTypes** should be omitted.

Which versions of React, ReactDOM/React Native, Redux, and React Redux are you using?  Which browser and OS are affected by this issue? Did this work in previous versions of React Redux?

7.x

**Comment by markerikson** [comment]
We don't maintain the React-Redux TS typings here - they're over in DefinitelyTyped.

**Comment by markerikson** [comment]
Does that still happen with the latest version of `@types/react`?  We're not generally targeting React 16.x at this point, and `@types/react` _mostly_ stays in sync with the current React version.

**Comment by noahnu** [comment]
It works with @types/redux and react-redux v7. Haven't tried using @types/redux with v8 since v8 ships with types. I'll give this a try this week, thanks for the quick reply.

When you say you're not targeting v16 anymore, are you referring to not testing against v16? There's still "official" support for v16 right? I'm going off of the package.json peer requirements. Perfectly understandable if official v16 support is dropped, it's 2 versions behind at this point :smile:

**Comment by markerikson** [comment]
@noahnu : I'm asking about `@types/react`, not `@types/redux` - both v7 and v8 rely on having React's types available.

And yeah, we're not doing any testing against React 16 in general today.  I expect that React-Redux _will_ work with React 16 in terms of both runtime behavior and types, but we're not explicitly testing that.

**Comment by noahnu** [comment]
Ah sorry, I misread your message. I haven't tested with the latest react types since there are substantial breaking changes that would prevent updating those types in my codebase (v16) without substantial work.
