### ISSUE TITLE
Update React version in peerDependencies to meet React 17

### ISSUE THREAD

**Issue by Constantiner** [reduxjs/react-redux#1646]
## New Features

Update React version in peerDependencies to meet React 17

### What is the new or updated feature that you are suggesting?

React 17 support.

### Why should this feature be included?

To support the latest stable version of React.

### What docs changes are needed to explain this?

I suppose docs won't change.

**Comment by markerikson** [comment]
Yep - can you file a PR to add that?

**Comment by victoriafrench** [comment]
any timeline when this will be released?

**Comment by timdorr** [comment]
I'm upgrading some build tools and dependencies. I'll try to do a release afterwards, but Travis is being very slow the last few days.
