### ISSUE TITLE
Updating of flow types

### ISSUE THREAD

**Issue by darthzeran** [reduxjs/react-redux#1649]
#New Features
The flow typed files show this warning
`Deprecated utility. Using `$Supertype` types is not recommended! (`deprecated-utility`) `

### What is the new or updated feature that you are suggesting?
Removing Supertype from react redux flow

### Why should this feature be included?
So that flow is up to date

**Comment by markerikson** [comment]
We don't maintain the Flow types here - they're over in the Flow-Typed repo:

https://github.com/flow-typed/flow-typed/blob/master/definitions/npm/react-redux_v7.x.x/flow_v0.104.x-/react-redux_v7.x.x.js

That, I honestly would advise _against_ using Flow at this point. A poll of Reddit /r/reactjs users a year ago showed that 50% were using plain JS, 48% TS, and only 2% Flow, and I would assume that TS usage is _over_ 50% in the React community at this point.
