### ISSUE TITLE
Add TypedUseDispatchHook interface for typing and using with middlewares like redux thunk

### ISSUE THREAD

**Issue by IVIosi** [reduxjs/react-redux#1650]
**Do you want to request a feature or report a bug?**

Feature

**What is the expected behavior?**

add an interface like TypedUseSelectorHook for useDispatch hook

**Details**

I think an interface for typing `useDispatch` hook like what `useSelector` hook has could be useful for many users who uses redux middlewares for async actions (e.g. redux thunk and etc.)

**Comment by IVIosi** [comment]
@markerikson  I'd gladly open a PR to update React-Redux page with `useAppDispatch` information.

Also I think something like what I'd say before could be useful specially for apps migrating from JS to TS. For example:

```javascript
import { Action } from 'redux';
import {
  useDispatch as useReactReduxDispatch,
  useSelector as useReactReduxSelector,
  TypedUseSelectorHook,
} from 'react-redux';
import { ThunkDispatch } from 'redux-thunk';

import { AppState } from 'path/to/app/root/state';

export type TypedDispatch = ThunkDispatch<AppState, unknown, Action>;
export interface TypedUseDispatchHook<TState> {
  (): TState;
}

export const useSelector: TypedUseSelectorHook<AppState> = useReactReduxSelector;
export const useDispatch: TypedUseDispatchHook<TypedDispatch> = useReactReduxDispatch;
```

So after using these interfaces, there is no need to change any other part of codebase.

**Comment by markerikson** [comment]
Still not sure what you're asking us to actually _add_ beyond what that `useAppDispatch` example shows doing.  The idea is that you'd import and use `useAppDispatch` everywhere.

Copying @phryneas , our resident TS expert.

**Comment by phryneas** [comment]
I'd say what you are describing there pretty much matches what we already have in the docs that Mark linked to above.
With the caveat that `typeof store.dispatch` in normal redux does not include middlewares. You'd have to use redux toolkit for that - which generally is the official recommendation, *especially* when you're using TypeScript.

**Comment by dai-shi** [comment]
@IVIosi 
FWIW, for typed selector, there's another option for experts: `DefaultRootState`
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/2a43fe2f451a26f47c1360fb4d90d77a5b9046ee/types/react-redux/index.d.ts#L49

**Comment by IVIosi** [comment]
@phryneas @markerikson @dai-shi  Thanks for your comments. I found out there are different approaches for static typing. So no need for helper type I mentioned in the beginning.
