### ISSUE TITLE
Allow passing a default equality function to `createSelectorHook`

### ISSUE THREAD

**Issue by Veramone** [reduxjs/react-redux#1656]
## New Features

Allow passing a default equality function to [`createSelectorHook`][cshCode]

### What is the new or updated feature that you are suggesting?

I'd like to suggest adding a second argument to [`createSelectorHook`][cshCode] to overwrite the default equality function.

### Why should this feature be included?

My redux store consists for the most part out of custom classes from a functional programming library. This library, [prelude-ts], relies on hash codes and an internal `.equals()` function on its objects to check equality between objects that do not share a reference:

```typescript
const a = Vector.of(1, 2, 3);
const b = Vector.of(1, 2, 3);

console.log(a === b) // False
console.log(a.equals(b)) // True
```

I assume other functional programming languages do something similar, and even outside of an FP context, this seems like a moderately frequent use-case to me in a language that does not support operator overloading.

To ensure I don't rerender my components unnecessarily, I pass my own equality function for now:

```typescript
// helpers.ts
const preludeEq = (a: HasEquals, b: any): boolean => a.equals(b);

// In some component:
import { useSelector } from 'react-redux';
import { preludeEq } from '../helpers';

const ProjectList = () => {
  const projects: Vector<string> = useSelector(store => store.project, preludeEq);

  return (
    <ul>
      {projects.map((name) => <li>{name}</li>)}
    </ul>
  );
}
```

I would like to instead be able to create my own useSelector hook and pass preludeEq as a default equality function. Something like:

```typescript
// helpers.ts
const preludeEq = (a: HasEquals, b: any): boolean => a.equals(b);

// store.ts
import { preludeEq } from '../helpers';

export const useSelector = createSelectorHook(null, preludeEq);

// In some component:
import { useSelector } from "../store";

const ProjectList = () => {
  const projects: Vector<string> = useSelector(store => store.project);

  return (
    <ul>
      {projects.map((name) => <li>{name}</li>)}
    </ul>
  );
}
```

### What docs changes are needed to explain this?

`createSelectorHook` actually doesn't seem to be referenced in the docs, but this might touch upon:
  - #1575
  - #1574
  - #1504

I'm more than willing to submit a pull request for this :) Since the first argument to `createReactHook` is optional, this change could be fully backward compatible.

[cshCode]: https://github.com/reduxjs/react-redux/blob/754c1059ded0c1ea3a9b6dc1d870e31c22d8c3b7/src/hooks/useSelector.js#L93
[prelude-ts]: https://www.npmjs.com/package/prelude-ts

**Comment by Veramone** [comment]
Awesome, I'll get on it somewhere soon. As for the docs, could you outline the use case for having your own `Context`? I don't immediately see it myself.

**Comment by markerikson** [comment]
@Veramone the only real use case for that is if you want to use multiple Redux stores within a single React component tree, so you need sections of the component tree to use store B instead of store A.  Both `connect` and `useSelector` rely on accessing the Redux store instance via context, and the default behavior is to use the singleton `ReactReduxContext` instance we create internally.  You _could_ actually render `<Provider store={storeB}>` for a particular subtree and override the default context value for that section, but if you want to intermingle them or something, you'd have to mix contexts.

**Comment by antonobergklarna** [comment]
I think createUseSelector should take an object as a second param and not only the eqFunction. This will make it possible to add other options without breaking the api. 

The reason I raise this now is that I will quite likely open a new issue in the coming days and pitch allowing passing i custom areStatesEqual function to createUseSelector.

**Comment by timdorr** [comment]
@antonobergklarna No need. That's exactly what this issue is discussing.

**Comment by antonobergklarna** [comment]
@timdorr - My interpretation of this discussion is that we are talking about the equalityFn that is used to compare the result returned by the selector (i guess analog to areStatePropsEqual in connect). I want an areStatesEqual that will replace storeState !== latestStoreState.current and default to refEquality. 

The second argument to createUseSelector could be an optional object where you could provide both 
{ areStatesEqual, equalityFn }.  

If an object notation feels like a good idea I think that it will also make sense to challenge the name equalityFn and use something like areSelectedPropsEqual or areDerivedDataEqual

**Comment by williamisnotdefined** [comment]
Sorry for my ignorance but..

`
const MySelector = (selector) => {
    return useSelector(selector, yourOwnEqualityFn)
}
`

That hook doenst solve the problem?

**Comment by timdorr** [comment]
Actually, yeah, that would be much easier than changing our API. You need to create a hook anyways, and it doesn't have to come from the factory function.
