### ISSUE TITLE
useBoundAction hook

### ISSUE THREAD

**Issue by ericp96** [reduxjs/react-redux#1662]
### What is the new or updated feature that you are suggesting?
It would be nice to incorporate the `mapDispatchToProps` functionality into a new hook/hooks

For example, current functionality:
```js
import { useCallback } from 'react';
import { useDispatch } from 'react-redux';

const incrementActionCreator = ...;

const MyComponent = () => {
  const dispatch = useDispatch();
  const increment = useCallback(() => dispatch(incrementActionCreator()), []);
}
```

This could be condensed to:

```js
import { useBoundAction } from 'react-redux';

const incrementActionCreator = ...;

const MyComponent = () => {
  const increment = useBoundAction(incrementActionCreator);
}
```

### Why should this feature be included?
This feature is offered with the current `connect` HOC when you provide an object to the `mapDispatchToProps` argument.  Increasing parity between hooks and hocs increases the versatility of the library.  

It also is convenient because it removes a lot of boilerplate making the code more terse and increasing readability.

### What docs changes are needed to explain this?
A new documentation section describing the new hook and its usage.

### Suggested implementation
Looking at `useDispatch`, it seems like a simple implementation could be done like this:

```js
import { ReactReduxContext } from '../components/Context'
import { useDispatch as useDefaultDispatch, createDispatchHook } from './useDispatch'

/**
 * Hook factory, which creates bound actions to the dispatch bound by a given context.
 *
 * @param {Function} [actionCreator] Action creator to wrap with dispatch`<Provider>`.
 * @param {React.Context} [context=ReactReduxContext] Context passed to your `<Provider>`.
 * @returns {Function} A `useBoundAction` hook bound to the specified context.
 */
export function createBoundActionHook(actionCreator, context = ReactReduxContext) {
  const useDispatch =
    context === ReactReduxContext ? useDefaultDispatch : createDispatchHook(context)

  return function boundAction() {
    const dispatch = useDispatch()
    const action = actionCreator.call(this, arguments)
    return dispatch(action)
  }
}

/**
 * A hook to bind an action creator to the dispatch function.
 *
 * @returns {function} action bound to redux store's `dispatch` function
 *
 * @example
 *
 * import React, { useCallback } from 'react'
 * import { useBoundAction } from 'react-redux'
 *
 * const setCounterActionCreator = count => ({
 *   type: 'set-counter',
 *   payload: {
 *     count
 *   }
 * })
 * 
 * export const CounterComponent = ({ value }) => {
 *   const setCounter = useBoundAction(setCounterActionCreator);
 *   return (
 *     <div>
 *       <span>{value}</span>
 *       <button onClick={() => setCounter(0)}>Reset counter</button>
 *     </div>
 *   )
 * }
 */
export const useBoundAction = /*#__PURE__*/ createBoundActionHook()
```

**Comment by timdorr** [comment]
We've already decided against including this kind of hook before. Here's Dan's comment that sums it up pretty well: https://github.com/reduxjs/react-redux/issues/1252#issuecomment-488160930

If you want it, we have a recipe for an equivalent in the docs, but it is not recommended: https://react-redux.js.org/api/hooks#recipe-useactions

**Comment by markerikson** [comment]
We had this as a `useActions` hook in our original alphas, but Dan strongly argued that we should drop the notion of "binding action creators" and not ship it.  After consideration, we agreed, and dropped it.

Not something we're planning to do at this point.

See https://blog.isquaredsoftware.com/2018/11/react-redux-history-implementation/#v7-1-hooks for recap and links.

**Comment by ericp96** [comment]
Hmmmm.... hard to want to disagree with a genius here, especially with one so paramount in bringing forth such an awesome set of tools for working on the front end.  Unfortunately, it's not what I was hoping for.

I see a lot of the reasoning being done around `useActions` which accepted an object and returned an object and I can get on board with those decisions.  Is there any chance future consideration might be given to a singular version of the function (e.g. `useAction`)?  It might seem like semantics, but the change does reconcile several of the concerns mentioned by Dan Abramov in his advocacy for its removal.

Also, if Dan happens to read this, sorry for being contrarian and "overly fixat(ing) on these one-line "shorter" changes and miss(ing) the bigger picture."  However, I do appreciate the abstraction. :D

I understand creating and maintaining a package like this is not easy.  Thanks for your work on redux and in taking the time to review my feature request.

**Comment by markerikson** [comment]
Yeah, really not something we're planning to offer officially, but there's nothing stopping you from writing and using your own (per the recipe in the docs).
