### ISSUE TITLE
Return of the Hook useActions

### ISSUE THREAD

**Issue by vstatsura** [reduxjs/react-redux#1665]
[doc useActions](https://react-redux.js.org/api/hooks#removed-useactions)

Enough time has passed since the introduction of hooks. It might be worth reconsidering the hook useActions?
I propose to vote again to include it in the react-redux. According to my observations among colleagues, everyone continues to use connect because of the more convenient work with dispatch actions. Or use the sample useActions code from the documentation.

**Comment by markerikson** [comment]
Sorry, no plans to add this - it just doesn't provide enough benefit.
