### ISSUE TITLE
Cant Connect to 'a' store

### ISSUE THREAD

**Issue by drfbwilliams** [reduxjs/react-redux#1681]
Hello,

I have read countless layers of documentation and still can't get this to work - I am assuming it is either a bug or a complete misunderstanding on my part (probably the later)

**The scenario:**
I have an asp.net core 3.1 mvc app.

I write a component in React - let's call it **Component A** - it is running inside an HTML page with a container div as host

Component A has a correctly implemented store - it is written using typescript - I can dispatch actions and all is good.

Now I write a totally separate React component - **Component B** - not in the same project, not related or connected in any way to **Component A**

I now add **Component B** to the same HTML page with a separate div container host.

Everything works - both React components render, the store is created in **Component A** and actions are dispatched correctly.

Now I want **Component B** to connect to the **SAME** store as **Component A** has created. I want to listen and potentially also dispatch actions.

The documentation and everything I read tells me that the connect() method is used to connect to '**a**' store - and that there should only be a single store created for any given application.

I realise that the documentation here may actually mean - a single store per connected component? - my thinking is that there is only a single DOM running on the resulting page - so why wouldn't any component be able to connect to it?

If this is a bug - fair enough.

If this is my misunderstanding, please point me to resources that consider the "application" to be the actual DOM running in the page, not just a single or connected sibling components.

If this is not something that Redux can handle at the moment, please consider this as a feature request.

Many thanks for any help on this issue.

**Comment by markerikson** [comment]
Yes, you can share the same Redux store instance across multiple React component trees.  Just do:

```js
const store = configureStore();

ReactDOM.render(
  <Provider store={store}>
    <Component1 />
  </Provider>,
  document.getElementById("root1")
);

ReactDOM.render(
  <Provider store={store}>
    <Component2 />
  </Provider>,
  document.getElementById("root2")
);
```

**Comment by drfbwilliams** [comment]
@markerikson thank you for your response. 

Having now chassed down configureStore() - (I assume that is the only one inside the reduxjs/toolkit?) - I do not see how that can actually work?

The configureStore method still requires a reference to a reducer.

There simply is no point to this if one must duplicate all the code for reducers, actions etc into multiple components, just to get a connection and listen for state changes.

The example you provide shows a single instance of a store object being referenced by two DOM renderers in the same context - not two separate renderers in two separate contexts, with a single reference each to a single Redux store.

Perhaps you were just writing that short hand to give the hint - I appreciate that - but I don't see how that applied to a Typescript based implementation where reducers and actions etc need the same type structures.

I appreciate any further pointers yourself or anyone else can provide on this.

Many thanks

**Comment by markerikson** [comment]
@drfbwilliams I don't think I actually understand what the use case is you're describing here, tbh.

The example I showed was a complete example of using the same Redux store for two different React component trees in the same page.

If that's not what you're trying to do, you're going to need to describe your situation in more detail, preferably with sufficient example code to show what you're actually trying to do.  Ideally, it would help to see the actual code, either in a CodeSandbox or at least a Github repo link.

It sounds as if you're trying to put together some very unusual application architecture, but I can't tell for sure based on the description so far.
