### ISSUE TITLE
the website is horizontally scrollable

### ISSUE THREAD

**Issue by gurrrung** [reduxjs/react-redux#1687]
**What is the current behavior?**

Website is being scrollable horizontally for pages like: 
https://v2.docusaurus.io/docs/api/themes/configuration
https://v2.docusaurus.io/docs/markdown-features

![Screenshot from 2021-02-16 20-10-38](https://user-images.githubusercontent.com/30543444/108077947-1cc35980-7093-11eb-91ff-e2d4846579cb.png)

**What is the expected behavior?**

It should not be horizontally scrollable.

**Comment by markerikson** [comment]
You seem to have filed a bug about Docusaurus on the React-Redux repo.
