### ISSUE TITLE
[Feature Request]Support imperative useSelector

### ISSUE THREAD

**Issue by NE-SmallTown** [reduxjs/react-redux#1689]
### What is the new or updated feature that you are suggesting?

Currently, we don't have a api to call a selector imperatively. Think about this situation.

The server returns some data, and we need to `setState` part of it with a selector, like :

```javascript
// a-3rd-party-library.js
async function useMyRequest({ selector }) {
  const [ res, setRes ] = useState({})
  const selectorResult = useSelector(selector)

  useEffect(() => {
     setRes(prev => ({
       ...prev,
       data: selectorResult ,
     }))
   }, [ selectorResult ])

  const res = await getServerData()

  setRes(prev => ({
      ...prev,
      status: 'xxx',
  }))
}

// Component.js
function Component() {
  const res = useMyRequest({
    selector: store => store.foo + store.bar,
  })

  // ... render something with `res.data`
}
```

Because there is no **imperative** `useSelector`, we must use the `useSelector` **hook**. So, it will cause **2** times re-render, one by the **first** `setRes`, one by the **second** `setRes`.

If we have a **imperative** `useSelector`, we can reduce the re-render times to **just 1**. Like:

```javascript
// a-3rd-party-library.js
async function useMyRequest({ selector }) {
  const [ res, setRes ] = useState({})

  const res = await getServerData()

  const selectorResult  = imperativeSelector(selector)

  // there is just 1 `setRes` calling
  setRes(prev => ({
      ...prev,
      status: 'xxx',
      data: selectorResult ,
  }))
}
```

### Why should this feature be included?

To reduce re-render times.

### What docs changes are needed to explain this?

Haven't think about yet.

**Comment by timdorr** [comment]
I'm not sure what you're asking for because hooks _must_ be imperative. Your example has an async function for the hook, which is not possible with how hooks function (this is essentially a side effect during rendering). Similarly, on your 2nd example, you are calling a setState directly inside of the render, which is also a side effect. 

There is nothing for us to do here. This is simply how hooks work.

**Comment by NE-SmallTown** [comment]
@timdorr 

I'm sorry I use the word 'imperative' here. Let me clarify it more clear.

>  Your example has an async function for the hook

I'm sorry, I just wanted to simply it and put the most important code. But sure it should be something like 

```javascript 
function useMyRequest({ selector }) {
  const [ res, setRes ] = useState({})


  useEffect(() => {
    getServerData().then(res => {
      const selectorResult  = imperativeSelector(selector)

      // there is just 1 `setRes` calling
      setRes(prev => ({
        ...prev,
        status: 'xxx',
        data: selectorResult ,
      }))
    })
  }, []
}
```

---

> imilarly, on your 2nd example, you are calling a setState directly inside of the render,

Same, I just simply the logic. It was like 

```javascript
useEffect(() => {
  setRes(prev => ({
      ...prev,
      status: 'xxx',
      data: selectorResult ,
  }))
}, [])
```

---

The key point I wanted to say is, we need a non-hook way to call selector(I called this as 'imperative' before), instead of `useSelector` hook(I called this as 'non-imperative' before).

Technically, this can be done because `selector` is just a pure function, we even can implement it like 

```javascript
funcrtion imperativeSelector(selector) {
  return selector(store.getState())
}
```

But this is  a very rough implementation. So, that's why I post this feature request.

**Comment by NE-SmallTown** [comment]
> What you're really asking for here is access to the store's getState() method and then calling it as needed.

No, as I said, "this is a very rough implementation", because `useSelector` itself has many [other logic](https://github.com/reduxjs/react-redux/blob/45dfd45ac8ccb9a67701364c998e0eb097d9bdb7/src/hooks/useSelector.js#L9)

This is why I post this issue and want it be builted-in

**Comment by markerikson** [comment]
Then I'm afraid I still really don't understand what you're asking for here.

You said you want to run a selector, but without subscribing to the store, right?  That's just `selector(store.getState())`, as you showed in that example.  We already have `const store = useStore()`, so there's nothing else we need to build into React-Redux itself here.

**Comment by NE-SmallTown** [comment]
> because that logic is only relevant for actually dealing with subscriptions.

Not totally right, it will process the error when call the selector [here](https://github.com/reduxjs/react-redux/blob/45dfd45ac8ccb9a67701364c998e0eb097d9bdb7/src/hooks/useSelector.js#L40) , and will check the equality [here](https://github.com/reduxjs/react-redux/blob/45dfd45ac8ccb9a67701364c998e0eb097d9bdb7/src/hooks/useSelector.js#L60) , and will add some debug info [here](https://github.com/reduxjs/react-redux/blob/45dfd45ac8ccb9a67701364c998e0eb097d9bdb7/src/hooks/useSelector.js#L111), and will check the argument type [here](https://github.com/reduxjs/react-redux/blob/45dfd45ac8ccb9a67701364c998e0eb097d9bdb7/src/hooks/useSelector.js#L99) , and may has something else I don't or can't list here(sorry I'm not very familiar with the source code)

That's why I called the `selector(store.getState())` as the 'very rough implementation' and wanted it to be builted-in. It's not appropriate to do this by me from my personal perspective

**Comment by markerikson** [comment]
@NE-SmallTown All of that logic is _only_ relevant when we're subscribing.  If you just want to run the selector, right now, and get the state, none of that matters.

For example, if you manually call `selector(store.getState())` while rendering, and that throws an error, then React's normal "explode and catch fire unless caught by an error boundary" behavior kicks in.

That clause that you pointed to is only for the case of an error thrown by a selector inside of the subscription, which we then need to re-propagate during the rendering phase with the correct stack info.

So, again, as far as I can tell, the `useStore()` hook _is_ the answer here for what you want to do.

**Comment by NE-SmallTown** [comment]
Thanks Mark! If so, can I ask for bringing it into react-redux? Like providing a method such as `executeSelector`:

```javascript
// react-redux.index.js
import store from '......'

export const executeSelector = selector => selector(store.getState())
```

There are 2 reasons to do this :

1. The selector term is a part of react-redux just like the `interceptor` in `axios`. So, it would be more appropriate to do this by react-redux library.

2. And then, if the api(even react-redux itself) changes since now, like selector can receive a second argument, the upgrade path will be smooth

**Comment by markerikson** [comment]
@NE-SmallTown : I've stated this several times already, and I'm not sure how much clearer I can be.

**What you're asking for can already be accomplished by calling the `useStore()` hook and running the selector yourself - NO NEW APIS NEED TO BE ADDED.**

```js
function MyComponent() {
  // will automatically re-render component any time `item` changes reference
  const item = useSelector(selectSomeItem);

  const store = useStore();
  // Will imperatively run the selector, whenever this component re-renders,
  // but without subscribing to the store and forcing updates when state changes
  const otherThing = selectOtherThing(store.getState());
}

**Comment by NE-SmallTown** [comment]
@markerikson Sorry, I was not intended to spam here(though I don't know why you think so). Given that the discussion is becoming chaotic, please let me do a brief summary.

I post a situation which need imperatively run the selector. **We has agreed about that this is a reasonable situtation.**, right?

So, the question **becomes** that **who** is **responsible** to implment this. (Technically **both we** can implement this, but how to implment it is not the key point we are arguing)

**I** think it should be implmented by **react-redux** due to 3 reasons:

1. 'this is a very rough implementation, it will process the error when call the selector [here](https://github.com/reduxjs/react-redux/blob/45dfd45ac8ccb9a67701364c998e0eb097d9bdb7/src/hooks/useSelector.js#L40) , and will check the equality [here](https://github.com/reduxjs/react-redux/blob/45dfd45ac8ccb9a67701364c998e0eb097d9bdb7/src/hooks/useSelector.js#L60) , and will add some debug info [here](https://github.com/reduxjs/react-redux/blob/45dfd45ac8ccb9a67701364c998e0eb097d9bdb7/src/hooks/useSelector.js#L111), and will check the argument type [here](https://github.com/reduxjs/react-redux/blob/45dfd45ac8ccb9a67701364c998e0eb097d9bdb7/src/hooks/useSelector.js#L99) , and may has something else I don't or can't list here(sorry I'm not very familiar with the source code)'
2. 'The selector term is a part of react-redux just like the interceptor in axios. So, it would be more appropriate to do this by react-redux library.'
3. 'And then, if the api(even react-redux itself) changes since now, like selector can receive a second argument, the upgrade path will be smooth'

And **you** think it should be implmented **by myself** due to 2 reasons:

1. 'All of that logic is only relevant when we're subscribing. If you just want to run the selector, right now, and get the state, none of that matters.'
2. 'What you're asking for can already be accomplished by calling the useStore() hook and running the selector yourself - NO NEW APIS NEED TO BE ADDED.'


So, if we can't reach a consensus. I can accept that to implement it by myself **at now**, and then if someone post the same or slimilar feature request or issue **in the future**, I think we can **continute** to **review** this feature request I posted. Just  like many ideas was posted/implemented by ourselves at first and finally be adopted by the library/framework.

What do you think?

**Comment by markerikson** [comment]
I think you're ignoring what I'm saying :(

**There is nothing that needs to be implemented, by either of us.**  No new APIs need to be added.  No functionality needs to be changed. No subscription logic needs to be reused.

**Please** try out the `useStore()` example I showed in your own app.

If that doesn't do what you need we can discuss things further, but as far as I can see, you're misunderstanding what the bulk of the code in `useSelector` does, and you're ignoring the solution I've already provided.
