### ISSUE TITLE
useSelector doesn't rerun if state updates with async function

### ISSUE THREAD

**Issue by muazazhar** [reduxjs/react-redux#1695]
**What is the current behavior?**

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to a CodeSandbox (https://codesandbox.io/s/new) or RN Snack (https://snack.expo.io/) example below:

**What is the expected behavior?**

Which versions of React, ReactDOM/React Native, Redux, and React Redux are you using?  Which browser and OS are affected by this issue? Did this work in previous versions of React Redux?

**Comment by markerikson** [comment]
I don't see any actual problem description here, just the default issue template text, so I'm going to close this.

If you have an actual issue, please reply with the details we've asked for.
