### ISSUE TITLE
selector in useSelector called one more time after forceUpdate inside hook

### ISSUE THREAD

**Issue by oleggrishechkin** [reduxjs/react-redux#1697]
**What is the current behavior?**

When state changed, selector recomputes, and value sets into latestSelectedState. Component will re-render, and selector recomputes again, but its value already in latestSelectedState.current

(selector is arrow function - `const data = useSelector((state) => state.data);`)

**What is the expected behavior?**

Selector recomputes once

I can open PR to fix this, but I don't know, may be selector specially calls twice for some reasons

**Comment by markerikson** [comment]
Can you put together a CodeSandbox that reproduces the issue?

**Comment by oleggrishechkin** [comment]
Yes, try this https://codesandbox.io/s/react-redux-twice-selector-r43fy

I think calling selector twice may prevent stale selectedState if selector use data from other useSelector in the same component

**Comment by oleggrishechkin** [comment]
@markerikson please, check CodeSandbox above
 
You can close this issue if it's correct behavior
I solve my own problem by memoize selector

 ```
const selector = useCallback((state) => some expensive selector, [some selector deps]);
const data = useSelector(selector);
 ```

It prevents selector call on re-render

**Comment by timdorr** [comment]
@markerikson Do you happen to remember why it's implemented this way? We do two calls because one is run on the subscription callback to check if we need to re-render:

https://github.com/reduxjs/react-redux/blob/010c3eeab4ac4d2a0f48b94f9e668a7e0ffff322/src/hooks/useSelector.js#L65-L83

If that's the case, then we re-render and the selector fires again to provide the value back to the component: 

https://github.com/reduxjs/react-redux/blob/010c3eeab4ac4d2a0f48b94f9e668a7e0ffff322/src/hooks/useSelector.js#L36

We could probably avoid that by also setting `latestStoreState.current` when running `checkForUpdates`. Was there any reason for not doing that? Some Suspense magic perhaps?

**Comment by markerikson** [comment]
Yeah, I glanced at the repro briefly, and saw that the reason for the duplicate selector call is that `latestStoreState.current` is not being updated by the subscriber logic and is therefore failing the "has state changed" check when we re-render.

I'm not sure if it's an oversight, or a concern about mutating `latestStoreState` and ending up with weird CM-related shenanigans.

FWIW, I had a conversation with Dan yesterday where he suggested that "in practice most stuff 'just works' with CM" - ie, yes all the concerns about "tearing" that they've warned about are valid, but in practice it's not actually all that big of an impact.

Given that we _are_ trying to track `latestSelectedState`, I can't immediately see why it would be bad for us to set `latestStoreState` too at the same time, which ought to resolve this.

**Comment by oleggrishechkin** [comment]
I miss `latestStoreState` change check, sorry, my "solution" above shouldn't work.
I updated CodeSandbox, now selector moved out of component

**Comment by markerikson** [comment]
I can try to put out a 7.2.4 in the next couple days.

**Comment by phantomcosmonaut** [comment]
Hey, I was using Suspense and a custom hook to render components asynchronously with async data fetching redux actions and I seem to have run into an issue directly related to this thread. I get the error `Cannot update a component ('IdentityVerificationScreen') while rendering a different component ('RenderSuspender'). To locate the bad setState() call inside 'RenderSuspender'` which takes me to the `forceRender` call from `useSelector` hook. Do you think the update in 7.2.4 will solve this issue and when can I expect to see the new version released? Thanks!

**Comment by markerikson** [comment]
@phantomcosmonaut no, that shouldn't have anything to do with this issue. This is about a selector re-running when the component is already rendering. What you're describing is a store subscription causing a component to render in the first place.

If you're seeing problems with React-Redux and Suspense, please file a new issue with a reproduction so we can look into it.
