### ISSUE TITLE
equalityF is not a function

### ISSUE THREAD

**Issue by gshilin** [reduxjs/react-redux#1704]
After release 7.2.3 I got error "equalityFn is not a function" in a component that beforehand worked perfect. In debugger I see that in useSelector.js in function checkForUpdates value of equalityFn is Array with one element "null":
equalityFn: Array(1)
0: null

I don't know how to reproduce it in a short example.

React: 17.0.2
ReactDOM: 17.0.2
Redux: 4.0.5
React Redux: 7.2.3

**Comment by markerikson** [comment]
Hmm. The code passes tests and looks valid when I glance at it again. It's going to be hard to investigate this without a reproduction example.

**Comment by gshilin** [comment]
Found it: for some reason I supplied an array as an equalityFn, probably that was an attempt for some optimization. And it didn't crash in 7.2.2.

**Comment by gshilin** [comment]
Its call was inside of try-catch:
try {
        var newSelectedState = latestSelector.current(store.getState());

        if (equalityFn(newSelectedState, latestSelectedState.current)) {
          return;

**Comment by markerikson** [comment]
I suppose we could add a couple dev-only checks to `useSelector` to verify that both `selector` and `equalityFn` are functions :)

**Comment by gshilin** [comment]
It would be nice to raise an exception when a `useSelector` is created with wrong properties. At least it would be easy to find it.

**Comment by gshilin** [comment]
This is the comment from prev version:
```
// we ignore all errors here, since when the component
// is re-rendered, the selectors are called again, and
// will throw again, if neither props nor store state
// changed
```

**Comment by markerikson** [comment]
Yep, agreed. If you've got some time, could you try filing a PR that would throw an error if either `selector` or `equalityFn` are not actually functions, in dev mode only?

**Comment by gshilin** [comment]
Yep, will try tomorrow
