### ISSUE TITLE
CRA typescript template with react-redux

### ISSUE THREAD

**Issue by Onlylonger** [reduxjs/react-redux#1707]
**What is the current behavior?**

![image](https://user-images.githubusercontent.com/19505200/113254801-a05ea000-92f9-11eb-9013-633373889e78.png)

![image](https://user-images.githubusercontent.com/19505200/113260787-41048e00-9301-11eb-9fa8-0aa6ba7200ae.png)

repo: https://github.com/Onlylonger/cra-redux-ts

Layout component used by App; but show above TypeScript error;

*_* need help

**Comment by phryneas** [comment]
You need to add `children: React.ReactNode;` to your LayoutProps if you want to pass children into them.
But this REALLY is not a react-redux question and this is a bug tracker, not a help forum. Please use more appropriate channels next time.

Also see https://github.com/typescript-cheatsheets/react

**Comment by Onlylonger** [comment]
got it
