### ISSUE TITLE
A proposal for a possible hook: "useDispatcher"

### ISSUE THREAD

**Issue by maziart** [reduxjs/react-redux#1716]
## useDispatcher hook 
As described and implemented [here](https://github.com/maziart/use-dispatcher), I suggest that `useDispatcher` hook which is easier to use, can be integrated within `react-redux` package itself.

**Comment by markerikson** [comment]
This is basically the `useActions` hook that was proposed and then removed during our alpha process, so this is not something we want to do:

https://react-redux.js.org/api/hooks#recipe-useactions
