### ISSUE TITLE
Test cases failed

### ISSUE THREAD

**Issue by Rajshah1897** [reduxjs/react-redux#1720]
I have 12 test cases failed in my project. here is the error. Not sure how to fix this?

could not find react-redux context value; please ensure the component is wrapped in a <Provider>

24 |   const handleImport = () => pushStep('importContact');
      25 |
    > 26 |   const globalStoreData = useSelector(dataSelector);
         |                           ^
      27 |   const {
      28 |     roles,
      29 |   } = globalStoreData;

Test Suites: 1 failed, 1 skipped, 30 passed, 31 of 32 total
Tests:       12 failed, 1 skipped, 133 passed, 146 total
Snapshots:   0 total
Time:        19 s

**Comment by markerikson** [comment]
This is a problem in your application, not with React-Redux.  The issues list here is reserved for actual bugs and feature requests with the library.

You should make sure you're rendering a `<Provider store={store}>` around your component even in tests.
