### ISSUE TITLE
Problem with docs in /getting-started section .

### ISSUE THREAD

**Issue by SiddheshKukade** [reduxjs/react-redux#1727]
URL : [https://react-redux.js.org/introduction/getting-started#hooks](https://react-redux.js.org/introduction/getting-started#hooks)

On this URL  Hooks Section you can see this following code  :arrow_down: 

![temp](https://user-images.githubusercontent.com/65951872/120583068-2b1f6080-c44b-11eb-9c8e-9cb696ce1920.JPG)

:red_circle:  Problem : 
 You can see in the above code that we are importing some functions from ./userSlice

``import {
  decrement,
  increment,
  incrementByAmount,
  incrementAsync,
  selectCount,
} from './counterSlice'``

And if you checked the entire page there is no information [or even hint ] aboout what does this ``./counterSlice`` contains

:large_blue_circle:  My Suggestion : 
Please add the documentation about what actually the page contains  or share the contents of that file so that there will be no confusion for beginners. 

Thank you for Reading this. :handshake:

**Comment by markerikson** [comment]
A couple quick thoughts:

- The focus of the React-Redux docs site is to teach how to use the React-Redux library. React-Redux is used with Redux itself, either Redux Toolkit or the original Redux core. The React-Redux docs assume you already know Redux.
- This is just a "Getting Started" page, and that snippet is just trying to illustrate what some basic usage code looks like.

If you aren't comfortable with Redux already, please see the Redux core docs tutorials. They cover fundamental Redux concepts, Redux Toolkit, and React-Redux:

https://redux.js.org/tutorials/index

**Comment by SiddheshKukade** [comment]
> A couple quick thoughts:
> 
> * The focus of the React-Redux docs site is to teach how to use the React-Redux library. React-Redux is used with Redux itself, either Redux Toolkit or the original Redux core. The React-Redux docs assume you already know Redux.
> * This is just a "Getting Started" page, and that snippet is just trying to illustrate what some basic usage code looks like.
> 
> If you aren't comfortable with Redux already, please see the Redux core docs tutorials. They cover fundamental Redux concepts, Redux Toolkit, and React-Redux:
> 
> https://redux.js.org/tutorials/index

Thank you Sir . :+1:
