### ISSUE TITLE
We should add a hooks bound to actions,such as useBindDispatch.make dispatch easier

### ISSUE THREAD

**Issue by xiyunanhai1028** [reduxjs/react-redux#1729]
import React from 'react';
import bindActionCreators from '../utils/bindActionCreators';
import { ReactReduxContext } from '../components/Context'

function useBindDispatch(actionsCreators) {
    const { store: { dispatch } } = React.useContext(ReactReduxContext);
    return bindActionCreators(actionsCreators, dispatch);
}
export default useBindDispatch;

**Comment by markerikson** [comment]
We tried this in the hook alphas, and removed that because it didn't provide enough benefit. 

See https://react-redux.js.org/api/hooks#recipe-useactions
