### ISSUE TITLE
SSR not working

### ISSUE THREAD

**Issue by cheehau** [reduxjs/react-redux#1777]
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

- React: 
- ReactDOM/React Native: 
- Redux:
- React Redux:

### What is the current behavior?

Hi SSR is not working when I enable the redux in gatsby-config

    {
      resolve: `gatsby-plugin-react-redux-persist`,
      options: {
        // [required] - path to your createStore module
        pathToCreateStoreModule: "./src/state/createStore",
        // [optional] - options passed to `serialize-javascript`
        // info: https://github.com/yahoo/serialize-javascript#options
        // will be merged with these defaults:
        serialize: {
          space: 0,
          // if `isJSON` is set to `false`, `eval` is used to deserialize redux state,
          // otherwise `JSON.parse` is used
          isJSON: true,
          unsafe: false,
          ignoreFunction: true,
        },
        // [optional] - if true will clean up after itself on the client, default:
        cleanupOnClient: true,
        // [optional] - name of key on `window` where serialized state will be stored, default:
        windowKey: "__PRELOADED_STATE__",
      },
    },

### What is the expected behavior?

SSR should work

### Did this work in previous versions of React Redux?

- [ ] Yes

**Comment by timdorr** [comment]
This isn't a React Redux bug.
