### ISSUE TITLE
Link visibility issue in dark mode

### ISSUE THREAD

**Issue by NegiAkash890** [reduxjs/react-redux#1782]
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

- React Redux:
In the docs

### What is the current behavior?

1. Go to the React-Redux doc
2. Switch the dark mode on.
3.  Open any section in tutorial

### What is the expected behavior?

The links in the  "Tutorial" section of the left sidebar.
Contains three subsections each one of these contains a "tip", "prerequisites" block.
On turning the dark mode on some links in this block lose visibility.

Screenshot 1 : 

![image](https://user-images.githubusercontent.com/55234838/127490838-440ffe50-dd2e-443c-a73d-e5db2bb5e984.png)

Screenshot 2 :

![image](https://user-images.githubusercontent.com/55234838/127490565-2fad7f51-c13a-41b9-90d2-2f8b073c34e6.png)

Screenshot 3 : 

![image](https://user-images.githubusercontent.com/55234838/127490644-fee44a1a-ed2f-4f31-819e-60b4abe8d783.png)

I am interested in fixing this where should I start ?

### Which browser and OS are affected by this issue?

I checked on edge and firefox

### Did this work in previous versions of React Redux?

- [ ] Yes

**Comment by timdorr** [comment]
> I am interested in fixing this where should I start ?

All of the doc site stuff is in the `website` folder. You can find our CSS customizations here: https://github.com/reduxjs/react-redux/blob/master/website/static/css/custom.css

**Comment by NegiAkash890** [comment]
Hi on skimming through the  stylesheet I found that its the CSS rule marked in the screenshot that is introducing the bug 

![react-redux](https://user-images.githubusercontent.com/55234838/127648780-c46d9309-d263-4363-8ce5-f06817c55012.PNG)

Toggling the property fixes the issue : 

![react-redux-final](https://user-images.githubusercontent.com/55234838/127649165-3d0acab2-934c-47c9-97d3-ae9f57d7ff48.PNG)


But on hovering the link , the link again becomes invisible. I think that the property mentioned above should be removed and for the hovering issue I think we can use 
```CSS
/* Something like this so anchor tag do not lose its visibility on hover  */
a:hover{
  color : red ;
}
```

**Comment by AnirudhPanda** [comment]
#1783 Review Please!
