### ISSUE TITLE
setBatch should be exported to allow custom react backend

### ISSUE THREAD

**Issue by maxired** [reduxjs/react-redux#1790]
### What is the new or updated feature that you are suggesting?

As a user of redux, I want to benefits from the use of `batch`, whatever react backend I am using.
In my case, I am using React-konva, which use react-reconciler from React fiber.
I whish I could call redux `setBatch` to provide the `batchedUpdates` function from the reconciler

### Why should this feature be included?

Exporting the `setBatch` is easy to do, and would help lot of user of redux who care about performance.

Since react-redux is not supposed. to work only for react-dom and react-native, it make sense to open this benefits to all.

### What docs changes are needed to explain this?

We would need to explain how setBatch works, and provide some example of using it

**Comment by markerikson** [comment]
We do already have an `alternate-renderers` entry point that avoids importing batching from ReactDOM or React Native, specifically for use with other renderers.  However, I don't think we actually export `setBatch` atm.

Seems reasonably doable in 7.2.x as well as 8.x.

**Comment by maxired** [comment]
thanks @markerikson for your answer.

In my case, I am also using react-dom for part of my app, so the import is not really an issue here.  But thanks for pointing it, as I was not aware of it.

**Comment by markerikson** [comment]
Given that React 18 now batches by default, I think this is OBE.
