### ISSUE TITLE
Don't omit render logic from the example in the TypeScript Quick Start docs

### ISSUE THREAD

**Issue by DanielFlaum** [reduxjs/react-redux#1791]
### What is the new or updated feature that you are suggesting?

This is in reference to https://react-redux.js.org/tutorials/typescript-quick-start#use-typed-hooks-in-components

The docs there include the following code snippet for `features/counter/Counter.tsx`:

```typescript
import React, { useState } from 'react'

import { useAppSelector, useAppDispatch } from 'app/hooks'

import { decrement, increment } from './counterSlice'

export function Counter() {
  // The `state` arg is correctly typed as `RootState` already
  const count = useAppSelector((state) => state.counter.value)
  const dispatch = useAppDispatch()

  // omit rendering logic
}
```

The rendering logic at the end of the code snippet should not be omitted.

### Why should this feature be included?

If the rendering logic is not omitted then the example demonstrates how the typed `dispatch` gets used in a TypeScript project. This provides two benefits:

First, it makes the example more complete, and therefore more useful to people who want to adapt the example in their own projects.

Second, it provides useful information for people who are trying to build a conceptual understanding of how React Redux works. Seeing how `dispatch` gets used may help them confirm or invalidate their understanding.

### What docs changes are needed to explain this?

The rendering logic for the code snippet merely needs to be included.

**Comment by timdorr** [comment]
This example isn't meant to explain how React Redux works. It's meant to demonstrate how to use hooks in components. Other code is just a distraction, so it's intentionally omitted. Thanks, but we're going to keep it brief.
