### ISSUE TITLE
useSelector's provided selector function is called twice on mount

### ISSUE THREAD

**Issue by sufian-slack** [reduxjs/react-redux#1801]
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

- React: 17.0.2
- ReactDOM/React Native: 17.0.2
- Redux: 4.1.1
- React Redux: 7.2.

### What is the current behavior?

While refactoring some `connect()`-based components to be functional hook-based components using `useSelector()`, I noticed some degraded performance.

It looks like on initial mount, selectors passed to `useSelector()` are called twice when they only need to be called once.

A test case demonstrating the calls and call counts can be shown here: https://codesandbox.io/s/use-selector-twice-lgovv?file=/src/index.js

Upon loading, the console log shows:

```
1. useSelector: render 
1. useSelector: useSelector 
2. useSelector+useCallback: render 
2. useSelector+useCallback: useSelector 
3. mapStateToProps: mapStateToProps 
3. mapStateToProps: render 
1. useSelector: useSelector 
2. useSelector+useCallback: useSelector
```

The last two `useSelector` calls are surprising, as they occur *after* their corresponding components have rendered, but themselves do not trigger a call to the functional component.

---

As an aside, I don't believe this is an issue, but did notice some undocumented/surprising behavior:

If you pass an inline function to `useSelector`, like:

```
function MyComponent({ myValue }) {
    const myResult = useSelector((state) => getMyResult(state, myValue));
    // ...
}
```

`getMyResult` will be called twice for each redux subscriber notification, this is due to `useSelector` seeing that the selector function passed has differed, and as a result will call the selector function. To avoid this, the selector passed to `useSelector` can be memoized:

```
function MyComponent({ myValue }) {
    const getMyResultMemo = useCallback((state) => getMyResult(state, myValue), [myValue]);
    const myResult = useSelector(getMyResultMemo);
    // ...
}
```

You can see this difference when interacting with the +1 buttons in the linked demo.

### What is the expected behavior?

I would expect mounting a component to only call each selector passed to `useSelector` once, similar to how on mount `connect()` calls the `mapStateToProps` function only once.

In the linked demo, I would have expected the console output on load to read:

```
1. useSelector: render 
1. useSelector: useSelector 
2. useSelector+useCallback: render 
2. useSelector+useCallback: useSelector 
3. mapStateToProps: mapStateToProps 
3. mapStateToProps: render 
```

### Which browser and OS are affected by this issue?

all

### Did this work in previous versions of React Redux?

- [ ] Yes

**Comment by markerikson** [comment]
Purely off the top of my head, the two calls on mount are most likely due to needing to read the state from the store _during_ the initial render, and then again after it's finished mounting and we have to double-check to see if any state changed while the rest of the rendering process occurred.  

The need to re-call the selector with a new reference while rendering is indeed because a new selector reference _could_ return an entirely different result, such as if it captured `props.someValue` and props value is now changing due to the parent re-rendering and passing down something different.

I can try to take a look later, but both of these sound like expected behavior given our current implementation.

**Comment by sufian-slack** [comment]
Oh, thanks for the quick reply! I was looking in a bit deeper into the behavior, and I think it may be possible to avoid? 

It looks like the first call happens here, as a result of the `selector`/`storeState` refs being initialized from `undefined`: https://github.com/reduxjs/react-redux/blob/master/src/hooks/useSelector.ts#L40

And the second call happens within the `useIsomorphicLayoutEffect` hook after the component is rendered: https://github.com/reduxjs/react-redux/blob/master/src/hooks/useSelector.ts#L74

I took a stab at special-casing the first mounting in this PR from my recent fork: https://github.com/sufian-slack/react-redux/pull/1

I _think_ this is a workable approach, and does not appear to cause any issues in the Slack client when used locally, but I'm not certain: are there cases where between the first render and the first triggering of `useIsomorphicLayoutEffect` we would need to recalculate the selected state even if the store's state did not change?

**Comment by markerikson** [comment]
> are there cases where between the first render and the first triggering of useIsomorphicLayoutEffect we would need to recalculate the selected state even if the store's state did not change?

Yes, that's exactly the scenario that I'm talking about.

The `checkForUpdates` function will run on all future dispatched actions, but we _also_ have to run it once _right away after mount_, just in case there were any further updates in between the initial render and the time this component has mounted.  That's the second call that you're seeing, and it _is_ necessary.

This is the same pattern shown in the official `useSubscription` hook:

https://github.com/facebook/react/blob/main/packages/use-subscription/src/useSubscription.js#L112-L115

**Comment by sufian-slack** [comment]
Ah, thank you, I think I see why this second check is present.

However, just to confirm an assumption I'm making: could you please take a look at the change to `checkForUpdates` here in my referenced PR? https://github.com/sufian-slack/react-redux/pull/1/files#diff-19c189d7f6bf5e0a2646567980762c0b615e6cdeee0079ca781bb10c5cb92198R72-R87

> The problem is we don't know whether the state has changed or not until we actually run the selector again and diff the results

The referenced code is making the assumption that if there was a subscription notification triggered after the initial call to `useSelector` but before the `useIsomorphicLayoutEffect` call, then the store's state would have changed references (since the purpose of the notification is to inform subscribers of state changes).

So if the store's state hasn't changed references between those events, we can assume there were no notifications between those events. I think this means we can avoid running the selector again, since selectors should be pure and the return value should be the same.

However, I may be missing something though, perhaps we can't make that assumption?

**Comment by markerikson** [comment]
Hmm, yeah, that's a good point.

Glancing at the linked PR, I don't think we need to keep track of "is this the first render".  We already assume immutable updates, so a check if the root state has changed ought to work, and we're already assigning the latest state in a ref.

We do a "are states equal" check in `connect` already, it's just buried in the maze of selector logic for `mapState`:

https://github.com/reduxjs/react-redux/blob/v7.2.4/src/connect/selectorFactory.js#L76

Not sure why I never added that at the start here, but yeah, doing that first and bailing out if equal seems reasonable.  This is something we could also apply to the 7.x branch as well.

**Comment by sufian-slack** [comment]
Oh right, because we should just be able to compare states and if equal avoid the recalculation in all cases?

Cool, let me see if I can adjust this PR accordingly, I'll first target 7.x since that's what we're on, but I could also try and get the same approach working on `master`?

**Comment by markerikson** [comment]
Yep! 

I can always put out new 7.x patch releases - we're still maintaining the 7.x line, we're just starting to work towards an 8.0 on `master`.  (For that matter, I figured out a way to shave some bytes from our `Subscription` implementation during the TS conversion process that I need to apply to 7.x as well.)

**Comment by sufian-slack** [comment]
Thanks, just added two pull requests, one for the `7.x` line and the other for `master`.

And thanks for the feedback on not needing to keep track of the first render, the change is much simpler!
