### ISSUE TITLE
React-redux is throwing error:  exports is not defined for react-native-web.

### ISSUE THREAD

**Issue by dwipalp97** [reduxjs/react-redux#1805]
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

- React: 16.13.1
- ReactDOM/React Native: ^0.65.1
- Redux:^4.0.5
- React Redux:^7.2.4

### What is the current behavior?
I have initially integrated reat-redux for mobile platform , and it is working fine. But then i have integrated react-native-web in my existing project so now it is throwing error at runtime. 

Throwing following error: Uncaught ReferenceError: exports is not defined
    at eval (extends.js:2)
    at Module../node_modules/react-redux/node_modules/@babel/runtime/helpers/esm/extends.js 

### What is the expected behavior?

It should support react-native-web

### Which browser and OS are affected by this issue?

browser: Chrome
 "react-redux": "^7.2.4",
"react-native": "^0.65.1",

### Did this work in previous versions of React Redux?

- [x] I have checked on mobile platform it was working but in react-native-web it is throwing error

**Comment by timdorr** [comment]
This looks to either be a Babel or other build tool problem. It's not something wrong with the library.
