### ISSUE TITLE
Error: Could not find "store" in the context (7.2.5)

### ISSUE THREAD

**Issue by BarishSarac** [reduxjs/react-redux#1816]
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

- React: 16.14.0
- ReactDOM/React Native: 16.14.0
- Redux: 7.2.5
- React Redux: 7.2.5

### What is the current behavior?

Installing version 7.2.5 caused below error messages to be thrown on my app. If I go back to 7.2.4 I get no error message everything works fine. I updated only this package in the whole app and run it, still got the error so it's not related to any other package updates I've done.

```
Error: Could not find "store" in the context of "Connect(MenuUser)". Either wrap the root component in a <Provider>, or pass a custom React context provider to <Provider> and the corresponding React context consumer to Connect(MenuUser) in connect options.

Error: Could not find "store" in the context of "Connect(index)". Either wrap the root component in a <Provider>, or pass a custom React context provider to <Provider> and the corresponding React context consumer to Connect(index) in connect options.
```

### What is the expected behavior?

The error not to show up

### Which browser and OS are affected by this issue?

Google Chrome  Version 93.0.4577.63 (Official Build) (64-bit)

### Did this work in previous versions of React Redux?

- [X] Yes

**Comment by markerikson** [comment]
I'll be honest and say that this seems rather unlikely to be a real bug in React-Redux. If you diff the two package versions, you can see that only a couple lines of code changed, and they have nothing to do with the use of context for passing down the store.

My first suggestion would be to check your project and see if you accidentally have multiple versions of React-Redux or React installed.  That would potentially cause mismatched context instances to exist.

Beyond that, you'd need to create a project that reproduces this issue for us to take a look at it.

**Comment by timdorr** [comment]
Yeah, this is a common context problem with duplicate installs of different package versions. Use `npm ls react-redux` to find mismatched versions. This isn't a React Redux bug.

**Comment by yoyo837** [comment]
When i updated webpack 5.70.0 to 5.71.0 i got the same error, back webpack to 5.70.0  the error disappeared.
