### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Jeggery** [reduxjs/react-redux#1819]
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

- React: 16.14.0
- ReactDOM/React Native: 
- Redux:4.0.5
- React Redux:

### What is the current behavior?

View the react Redux source code through the warehouse.
An error is reported when installing the official master warehouse
![redux安装bug](https://user-images.githubusercontent.com/39072827/133917925-37e96a8f-abed-406e-ac71-461818ff8363.png)

### What is the expected behavior?

normal setup

### Did this work in previous versions of React Redux?

- [ ] Yes

**Comment by timdorr** [comment]
This isn't an issue with React Redux.
