### ISSUE TITLE
Attempted import error: 'Provider' is not exported from 'react-redux'.

### ISSUE THREAD

**Issue by bipindubey-technoark** [reduxjs/react-redux#1826]
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

"react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-redux": "^7.2.5",
    "react-router-dom": "^5.3.0",
    "react-scripts": "4.0.3",
    "redux": "^4.1.1",

### What is the current behavior?

import { Provider } from 'react-redux';

i have imported provider from react-redux but it is showing error not exported from react-redux

### What is the expected behavior?

it should work

### Did this work in previous versions of React Redux?

- [X] Dont know using this first time

**Comment by timdorr** [comment]
We definitely do: https://unpkg.com/browse/react-redux@7.2.5/es/exports.js

Something is wrong with your build tooling. This isn't a bug on our end.

**Comment by bipindubey-technoark** [comment]
let me re build and run the project

**Comment by Doaa-Mamdouh** [comment]
I faced this problem because I wrote {provider} with small case of "p" but when I wrote 
import { Provider} from "react-redux" it works fine !
