### ISSUE TITLE
Unable to access library store inside another react application

### ISSUE THREAD

**Issue by anj-kr** [reduxjs/react-redux#1839]
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

- React: 16.13.1
- ReactDOM: 17.0.2
- Redux:4.0.5
- React Redux: 7.2.0

### What is the current behavior?

Hello, 

There is a react library with its own store where the user authenticated token is available. Now when i try to use library store i'm getting the below error when adding the store to the provider

Here store is from react library 
ex:  import store from 'example-library'
   ```
 <Provider store={store}>
      <Router {...props} history={HistoryService}>
        <AppContainer />
            <Route path="/tab1" component={Tab1Component} /> 
      </Router>
     </Provider>
```
 
Provider.js:25 Uncaught TypeError: store.getState is not a function

### What is the expected behavior?

Able to use the same store from react library and use it with another react application for fetching the user data

### Did this work in previous versions of React Redux?

- [ ] Yes

**Comment by timdorr** [comment]
You don't appear to be exporting the correct thing from your other module. This isn't a React Redux bug.
