### ISSUE TITLE
Error: Not initialize! on react 18 beta and react-redux v8 beta

### ISSUE THREAD

**Issue by kYem** [reduxjs/react-redux#1844]
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

    "@reduxjs/toolkit": "^1.7.0-beta.1",
    "react": "^18.0.0-beta-fdc1d617a-20211118",
    "react-dom": "^18.0.0-beta-fdc1d617a-20211118",
    "react-redux": "8.0.0-beta.0",
    "react-scripts": "^5.0.0-next.47"

### What is the current behavior?

I decide to try out the React 18 and with recent announcement of  react-redux  `v8 beta`, I though it would be possible to get everything up running. 

Now there is a question mark if this is caused by RTK not yet supporting react 18 and is conflicting with `react-redux` and if that is the case here, that just mean I will need to wait until it is ready and this can be closed.

Now the error I'm receiving on component load receiving `Error Not initialize!`

Here is simplified example that produce the error in CodeSandbox: https://codesandbox.io/s/nostalgic-raman-bizfl?file=/src/App.tsx

### What is the expected behavior?

Components render without error and selector provider the slice value.

### Which browser and OS are affected by this issue?

Ubuntu 20.10

### Did this work in previous versions of React Redux?

- [X] Yes

**Comment by markerikson** [comment]
Well, that's definitely due to the changes I made last night :)  Question is _why_ that's happening.

What's _supposed_ to happen is that dummy function gets replaced before any other startup code runs.  But, it does rely on some module initialization order behavior.

Let me play around with things and see if things are initializing in a different order than I expect them to.

**Comment by kYem** [comment]
From my quick debugging on the task it seems like useSelector.ts was initialized 

```
import { useContext, useDebugValue } from 'react'

import { useReduxContext as useDefaultReduxContext } from './useReduxContext'
import { ReactReduxContext } from '../components/Context'
import { getSyncFunctions } from '../utils/useSyncExternalStore'
import type { DefaultRootState, EqualityFn } from '../types'

const [, useSyncExternalStoreWithSelector] = getSyncFunctions()
```
At this point `useSyncExternalStoreWithSelector` is not yet initalized, then something calls `setSyncFunctions` and update the references, however as `useSyncExternalStoreWithSelector` was resolved before that, it still have a reference to `notInitialized` function.

At least that how it looked like based on debug statements, but I could not figure out exactly why it was doing it (or where useSelector load was initiated).That's why I though maybe it's the RTK somehow causing it

![2021-11-19_20-53-47](https://user-images.githubusercontent.com/3390897/142706644-696521e7-0a71-43fd-92ba-35fa3d630c63.png)

**Comment by markerikson** [comment]
Nah, this has nothing to do with RTK :)

This worked fine in local testing, but it seems like the built artifacts are behaving different. I can work around it, just a question of how best to do that.

**Comment by markerikson** [comment]
Okay, should be fixed in https://github.com/reduxjs/react-redux/releases/tag/v8.0.0-beta.1 . Sorry about that!  Please try that out and let me know if it works.

**Comment by kYem** [comment]
Thanks, that was fast, working as expected.

**Comment by markerikson** [comment]
Sweet! I'd appreciate any other feedback you can offer after you've played around with it some more, even if it's just "still working as expected".
