### ISSUE TITLE
react-redux dispatch action does not work on android but works on ios

### ISSUE THREAD

**Issue by hugoh59** [reduxjs/react-redux#1864]
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

- React: 17.0.2
- ReactDOM/React Native: 0.66.4
- Redux:^4.0.5
- React Redux:^7.2.1

### What is the current behavior?

I have set up my store correctly and everything works perfectly fine on ios. But on android with the exact same code, the dispatch action has no effect, it does not populate my context with the value returned from my APi.

Since it is exactly the same code, I have been struggling to figure out what the issue could be.

I am using

    "react-redux": "^7.2.1",
    "redux": "^4.0.5",
    "redux-thunk": "^2.3.0",
    "react-native": "0.66.4",
```
const dispatch = useDispatch()
const trans = useSelector(state => state.translation);
useEffect(() => {
    fetchTranslations(dispatch)
  }, [])

import React from "react";

const initState = {};

const TranslationReducer = (state = initState, action) => {
  switch (action.type) {
    case 'FETCH_TRANSLATIONS':
      return action.payload.data
    default:
      return state;
  }
};

export default TranslationReducer

import { get } from '../api/query';

export function fetchTranslations(dispatch) {
  try {
    return (
      get('/api/v3/labels/mobile_app/')
      .then(res => {
        console.log('res', res)
        return res.json()
      })
      .then(response => {
        console.log('response', response)
        dispatch({
          type: 'FETCH_TRANSLATIONS',
          payload: response
        })
      })
    )
  } catch (e) {
    console.log('error', e)
  }
}
```

### What is the expected behavior?

everything is correctly returned from the api, but dispatching the action does nothing to the state, it stays empty on android, but works fine on ios.

I am working on Android studio 11.0.11 on a Pixel 4 API 32 emulator.

### Did this work in previous versions of React Redux?

- [ ] Yes

**Comment by markerikson** [comment]
There is nothing that is specific to any OS in React-Redux. The only platform-specific implementation we have is checking whether we're running with ReactDOM or React Native.

Given that, I'm going to go ahead and close this because it can't be a bug in React-Redux.

I would suggest using the Redux DevTools to see if the action truly is being dispatched and if state is being updated, and where the update sequence may be getting interrupted.
