### ISSUE TITLE
Inconsistent docs around static typing reducer config

### ISSUE THREAD

**Issue by hebronwatson** [reduxjs/react-redux#1876]
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

- React: 
- ReactDOM/React Native: 
- Redux:
- React Redux:

### What is the current behavior?

This issue targets the docs in the website. [This doc](https://github.com/reduxjs/react-redux/blob/master/website/versioned_docs/version-7.2/using-react-redux/static-types.md) contains code for configuring a redux store suitable for a blog, rather than one suitable for the example that is used throughout the rest of the guide. It also lacks guidance on how to write the reducer.

### What is the expected behavior?

 I understand that this can likely be gleaned from the redux docs, but bearing in mind that many of the TypeScript focussed sources (and even examples from the same source) tend to have slight or significant differences between them, it would save considerable time to have one consistent tutorial showing the code to go from redux store config all the way to working React component.

### Did this work in previous versions of React Redux?

- [ ] Yes

**Comment by markerikson** [comment]
I'm sorry, I'm really not sure I understand what specific concern you're describing here.

Can you give specific examples of what you feel is either A) wrong, or B) missing?
