### ISSUE TITLE
@types/react-redux is incorrect for mergeProps when mapDispatchToProps is null/undefined

### ISSUE THREAD

**Issue by saraid** [reduxjs/react-redux#1877]
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

- React: 
- ReactDOM/React Native: 
- Redux:
- React Redux:

### What is the current behavior?

Discussed here: https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/59297

The error is that the types do not consider a code-supported case where mergeProps is defined, but mapDispatchToProps is not. The types expect that the passed value will be `undefined`, whereas [the code](https://github.com/reduxjs/react-redux/blob/4d384029e3fa0355e762f40409a5dac4358a3de3/src/connect/mapDispatchToProps.ts#L14-L20) actually passes `{ dispatch: Dispatch }`.

This means that, when the Typescript option `strictFunctionTypes` is set to `true`, correctly typed usages of this pattern will fail.

### What is the expected behavior?

When turning `strictFunctionTypes` on, the types should still compile for this specific use case. [A PR has been opened](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/59310) to fix the issue.

I was asked to file this issue to make sure it gets tracked for v8 development.

### Did this work in previous versions of React Redux?

- [ ] Yes

**Comment by markerikson** [comment]
This got merged in DT, and also added to v8.
