### ISSUE TITLE
Consider removing `DefaultRootState` type

### ISSUE THREAD

**Issue by markerikson** [reduxjs/react-redux#1879]
React-Redux v8 currently has a `DefaultRootState` type defined:

https://github.com/reduxjs/react-redux/blob/4d384029e3fa0355e762f40409a5dac4358a3de3/src/types.ts#L13-L23

This was copy-pasted directly from the `@types/react-redux` types in DefinitelyTyped, which have had that for a while.

We Redux maintainers were not involved in that type being added originally, and [specifically think it's a bad practice](https://dev.to/phryneas/comment/1mp3l):

> Or to say it bluntly: If at that point in time, we as Redux maintainers would have known about what was going on in DefinitelyTyped, we would have prevented `DefaultRootState` from ever being added. Unfortunately, at that point we were not aware.
> 
> It is a global enhancement of the state, no matter if the reducer was actually added to your store.
> 
> At one point in time, some library will go ahead and pollute that interface and suddenly every project using that library will have an extra property in their Redux store - without any reducer for it being present.
> 
> There is a good reason we don't recommend doing this anywhere in the docs.

Given that, I'd like to propose removing it from the v8 typings before this gets released.

I'm assuming we'd want to replace that with `unknown` instead.

I did a couple code searches, and I see maybe 1000-1500 usages in the wild:

- https://sourcegraph.com/search?q=context:global+lang:typescript+DefaultRootState+count:2000&patternType=literal
- https://github.com/search?l=TypeScript&q=DefaultRootState&type=Code
- https://cs.github.com/?q=DefaultRootState

So that's not _zero_, but it isn't a thing that would completely break the ecosystem in the upgrade process.

Lenz also said that this is a pattern that _could_ get replicated in userspace if desired, although I'm not sure what the details are on that.

**Comment by phryneas** [comment]
The benefits of the pattern are not to be overlooked - you don't need to have all reducers meet in one place, which would be especially desirable in a situation where reducers are injected after the fact.

It could, however, easily be recreated in userland:
```ts
// store/state.ts
export inferface MyOwnRootState {}

// store/hooks.ts
import { MyOwnRootState } from './state'
import { TypedUseSelectorHook, useSelector  } from 'react-redux'
export const useAppSelector: TypedUseSelectorHook<MyOwnRootState > = useSelector

// feature/something/slice.ts
declare module 'store/state' {
  inferface MyOwnRootState {
    foo: MyFeatureState
  }
}
```

=> this does not necessarily need to be shipped with the react-redux types and can be imitated in userland. That way, it's also impossible for random depencies to poison that type.

**Comment by phryneas** [comment]
One point where my previous statement would not hold true: 
Afaik, there is no way to create a `connect` type that has a fixed `State` type at the moment.

But in that light I would suggest we add another type
```ts
export type TypedConnect<State, Dispatch> = { /* all the current signatures with fixed state and dispatch types */ }
export const connect: TypedConnect<unknown, Dispatch>
```

that `TypedConnect` type will probably end up being more useful than the `DefaultRootState` in the first place.

**Comment by josh-degraw** [comment]
Makes total sense, even if for no other reason than consistency with how the other redux codebases do things.

**Comment by dai-shi** [comment]
Module Augmentation should be useful in case we want a TS-only solution for typing state. This sounds reasonable because 99% usage of redux would be single store. I kind of [liked the solution](https://twitter.com/dai_shi/status/1224256734128037888), but can understand that it may lead to a bad practice.

Just my two cents.

**Comment by markerikson** [comment]
Just did this in #1887 . There was also already a `Connect<State = DefaultRootState>` type being exported, so that just defaults to `unknown` now.

**Comment by adamaveray** [comment]
In case anyone is looking to replicate augmenting the `DefaultRootState` type (to avoid having to explicitly declare the state's type in every call to `useSelector()`) the following module augmentation file should work:

```ts
// react-redux.d.ts
import type { EqualityFn } from 'react-redux/es/types';
import type { GlobalState } from '...'; // Your root store type

declare module 'react-redux' {
  export declare const useSelector: <T>(selector: (state: GlobalState) => T, equalityFn?: EqualityFn<T>) => T;
}
```

_(The file should be placed in a directory listed in the project's `tsconfig.json`'s `typeRoots` array – [see the docs](https://www.typescriptlang.org/docs/handbook/declaration-merging.html#module-augmentation))_

Now calls such as `useSelector(state => ...)` will automatically treat the `state` parameter as having the above `GlobalState` type.

**Comment by longb1997** [comment]
> In case anyone is looking to replicate augmenting the `DefaultRootState` type (to avoid having to explicitly declare the state's type in every call to `useSelector()`) the following module augmentation file should work:
> 
> ```ts
> // react-redux.d.ts
> import type { EqualityFn } from 'react-redux/es/types';
> import type { GlobalState } from '...'; // Your root store type
> 
> declare module 'react-redux' {
>   export declare const useSelector: <T>(selector: (state: GlobalState) => T, equalityFn?: EqualityFn<T>) => T;
> }
> ```
> 
> _(The file should be placed in a directory listed in the project's `tsconfig.json`'s `typeRoots` array – [see the docs](https://www.typescriptlang.org/docs/handbook/declaration-merging.html#module-augmentation))_
> 
> Now calls such as `useSelector(state => ...)` will automatically treat the `state` parameter as having the above `GlobalState` type.

i got TS error when using this

**Comment by adamaveray** [comment]
> i got TS error when using this

@longb1997 Do you have any further details about the error?

**Comment by longb1997** [comment]
> > i got TS error when using this
> 
> @longb1997 Do you have any further details about the error?

thanks for the reply, this is error:
hover on useSelector: `Subsequent variable declarations must have the same type.  Variable 'useSelector' must be of type '<TState = unknown, Selected = unknown>(selector: (state: TState) => Selected, equalityFn?: EqualityFn<Selected> | undefined) => Selected', but here has type '<T>(selector: (state: GlobalState) => T, equalityFn?: EqualityFn<T> | undefined) => T'.
`
and hover on `declare`: `A 'declare' modifier cannot be used in an already ambient context.`

**Comment by markerikson** [comment]
@longb1997 : note that we specifically advise _against_ trying to do this!

Instead, follow our docs guidelines for creating "pre-typed" versions of the hooks:

https://redux.js.org/tutorials/typescript-quick-start#define-typed-hooks

**Comment by VladimirTi** [comment]
In case someone is looking for a way how to upgrade big projects to react-redux@8 without changing every useSelector/useDispatch import and usage accross all the project to typed version of it (useAppSelector, useAppDispatch), there is my solution (works on typescript project):

In your tsconfig.json, add next block:

```
//tsconfig.json
"paths": {
  "react-redux-default": [
    "./node_modules/react-redux"
  ],
  "react-redux": [
    "./src/react-redux-typed"
  ]
},
```
In react-redux-typed.ts:
```
//react-redux-typed.ts
import { TypedUseSelectorHook, useDispatch as useDefaultDispatch, useSelector as useDefaultSelector } from 'react-redux-default';

import type { AppDispatch } from './YOUR_PATH';
import type { ApplicationState } from './YOUR_PATH';

export * from 'react-redux-default';

export const useDispatch: () => AppDispatch = useDefaultDispatch;
export const useSelector: TypedUseSelectorHook<ApplicationState> = useDefaultSelector;
```

That's all. After that, you are able to leave all useSelector/useDispatch imports and usage as it is, but now it is typed as should be
