### ISSUE TITLE
React 18 release broke create-react-app appname --template redux

### ISSUE THREAD

**Issue by minaelee** [reduxjs/react-redux#1881]
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

- create-react-app@5.0.0

### What is the current behavior?

When I use the command:

`npx create-react-app someappname --template redux
`

Since yesterday when React 18 was released as production, I now get this error every time:

![image](https://user-images.githubusercontent.com/4936954/160773152-d73e334e-a594-4b0d-b029-5b447252fcdc.png)

Here it is again in text:

Installing template dependencies using npm...
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: noversionplusredux@0.1.0
npm ERR! Found: react@18.0.0
npm ERR! node_modules/react
npm ERR!   react@"^18.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.3 || ^17" from react-redux@7.2.6
npm ERR! node_modules/react-redux
npm ERR!   react-redux@"^7.2.3" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\minae\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\minae\AppData\Local\npm-cache\_logs\2022-03-30T07_04_35_242Z-debug.log
`npm install --no-audit --save @reduxjs/toolkit@^1.5.1 @testing-library/jest-dom@^4.2.4 @testing-library/react@^9.3.2 @testing-library/user-event@^7.1.2 react-redux@^7.2.3` failed

### What is the expected behavior?

It creates a react-redux app as normal. 

### Which browser and OS are affected by this issue?

n/a

### Did this work in previous versions of React Redux?

- [ ] Yes

**Comment by markerikson** [comment]
Yeah, this is an unfortunate consequence of both CRA and NPM default behavior:

- CRA apparently always installs the latest React by default
- NPM now always installs peer deps, and errors if it can't find a match.

I may have to put out a React-Redux v7.2.x emergency patch that bumps the peer dep to accept React 18 just to work around this, although I don't like that.

The real solution is that we need to finish up React-Redux v8 and release it, but that'll be at least a couple weeks.

See https://github.com/reduxjs/react-redux/issues/1740#issuecomment-1083184887 for some additional thoughts.

**Comment by compulim** [comment]
Agree on NPM default behavior. But I think an emergency patch makes sense.

I have a non-CRA project. It is a React UI component library:

- Uses `react-redux@7.2.6`
- Has peer deps of `react@>=16.8.3`
- No dev/deps to `react` or `react-dom`

After `react@18` is released, the CI pipeline of the project suddenly broke with zero code change.

NPM try to install `react@18` because the project says it wants `react@>=16.8.3`. Then it conflicted.

On the other side, if the project doesn't have peer deps set, it is fine.

**Comment by markerikson** [comment]
I've put out React-Redux 7.2.7 as a stopgap, but the real answer is we need to get v8 out the door.
