### ISSUE TITLE
Replace reducer incorrect store state

### ISSUE THREAD

**Issue by ghost** [reduxjs/react-redux#1882]
### Description

Case: replace reducer when specific props changes.

Case description:
- Parent component pass props to child
- Child attach reducer (with props from parent) into store in `useLayoutEffect`

### What is the current behavior?

When child receives a new prop from parent a new reducer attached to store but store has previous state.

### Steps to Reproduce

I've created example to demonstrate behaviour (https://codesandbox.io/s/priceless-rgb-c9hdw8).

### What is the expected behavior?

In this case I expect to see a new `value` rendered on screen when user changes value in dropdown.

**Comment by mnajjarian** [comment]
I have seen this issue with react 18 and I see here is the same thing.

**Comment by markerikson** [comment]
Closing due to lack of response.
