### ISSUE TITLE
add createConnectHook factory.

### ISSUE THREAD

**Issue by geekact** [reduxjs/react-redux#1901]
### What is the new or updated feature that you are suggesting?

React-Redux has provided `createSelectorHook` and `createStoreHook`, and what I want is `createConnectHook`.

### Why should this feature be included?

When I provide my own ReactReduxContext, I have to inject to connect every time I use it:
```typescript
export default connect(_, _, _, { context: MyOwnReactReduxContext })(App);
```

Maybe createConnectHook can help me
```typescript
export const myConnect = createConnectHook({ context: MyOwnReactReduxContext, store: MyStore });
```
And I can import it from every files:
```typescript
import { myConnect } from './myConnect';
export default myConnect(mapState)(App);
```

### What docs changes are needed to explain this?

No.

**Comment by markerikson** [comment]
Sorry, but we have no plans to add any further features around `connect`. It's there and is supported as-is, but we're not adding anything more to it.
