### ISSUE TITLE
unused import

### ISSUE THREAD

**Issue by phapdinh** [reduxjs/react-redux#1906]
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

- React: 
- ReactDOM/React Native: 
- Redux:
- React Redux:

### What is the current behavior?

There is an unused import for resolve inside website docusaurus.config.js on line 1

### What is the expected behavior?

there should be no unused imports

### Did this work in previous versions of React Redux?

- [ ] Yes

**Comment by timdorr** [comment]
Thanks, but not really a big deal. It's just an internal tool we use.
