### ISSUE TITLE
Add a type definition that accepts ThunkAction provided redux-thunk to useDispatch

### ISSUE THREAD

**Issue by yamachu** [reduxjs/react-redux#1911]
### What is the new or updated feature that you are suggesting?

From react-redux v8, it provides own type definitions.
Along with that, a difference arose from the type definitions that were provided by volunteers in TypesDefinitions.

What I am having trouble with is the type definition of `useDispatch`.

https://github.com/reduxjs/react-redux/blob/26ddc6a6fc1238408ae5a0cbc18f15be225786dc/src/hooks/useDispatch.ts#L25-L31

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/b153e7ef5fb60b1a20dc5120c55058fd24c2cc39/types/react-redux/index.d.ts#L538-L540

The current react-redux type definition only allows pure actions to be passed to dispatch.

### Why should this feature be included?

It is helpful to maintain an ecosystem with third-party libraries surrounding react-redux.

### What docs changes are needed to explain this?

Maybe nothing.

**Comment by markerikson** [comment]
Hiya.  The issue here is that there's no guarantee that the actual Redux store being used was configured to have the thunk middleware.  So, if we just automatically have the types include support for thunks, we're actually lying to our users about how the runtime behavior will work.

Because of that, we specifically teach and show how to infer the final _real_ type from `store.dispatch`, and create a "pre-typed" hook that captures that for use within the rest of the app:

https://react-redux.js.org/using-react-redux/usage-with-typescript#standard-redux-toolkit-project-setup-with-typescript

**Comment by stevebeauge** [comment]
Sorry, but this is very confusing. I was not able to find an end to end typescript guide that works with thunks.

Trying to decrypt the documentation you linked :

> For useDispatch, the default Dispatch type does not know about thunks or other middleware. In order to correctly dispatch thunks, you need to use the specific **customized AppDispatch type from the store that includes the thunk middleware types**, and use that with useDispatch. Adding a pre-typed useDispatch hook keeps you from forgetting to import AppDispatch where it's needed.

Can you clarify the bold part?

**Comment by phryneas** [comment]
Take a look at one of the two TypeScript "Quick Start"s at https://redux-toolkit.js.org/tutorials/typescript or https://redux.js.org/tutorials/typescript-quick-start

**Comment by stevebeauge** [comment]
I've already read carefully these articles, without matching the missing piece.

The [CRA template](https://github.com/reduxjs/cra-template-redux-typescript/blob/master/template/src/app/store.ts) is using the same setup than mine, but is working perfectly.

I narrowed my issue to AppDispatch typing. At right, it seems ok :
![image](https://user-images.githubusercontent.com/184604/164306354-651c5fd3-b029-4215-811f-f9fe86b407d8.png)

At left, however, I "lost" part of the expected type:
![image](https://user-images.githubusercontent.com/184604/164306722-4c50f13b-df85-4d8e-9bc8-0264010844c8.png)

Comparing the CRA template : 
Right is :
![image](https://user-images.githubusercontent.com/184604/164307161-84b2fc38-3df6-44ad-99e3-4951b859bdf1.png)
While left is :
![image](https://user-images.githubusercontent.com/184604/164307241-406f998a-d005-4f4d-b06c-febe4dac4ffb.png)

Still looking for the difference :(

**Comment by stevebeauge** [comment]
Found the difference I guess. My thunk was named `UploadFilesStep` while my slice was `uploadFilesStep`.
Seems it matters homehow. 
thx for the help
