### ISSUE TITLE
Impossible to create a lib compatible with version 7 and 8

### ISSUE THREAD

**Issue by paztis** [reduxjs/react-redux#1914]
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

- React: 18
- ReactDOM: 18
- Redux: 4.2
- React Redux: 7 or 8

### What is the current behavior?

When we want to create a lib with a peer dependency to react-redux we face a problem.
People that use react 18 will provide react-redux 8. People that work with react 17 will provide react-redux 7.

The lib is doing basic things, but it uses the connect with pure option to true.
In v8, pure option is no more necessary but it throws an error to say the option is not necessary.
This exception makes the full app crash.
It is not possible to remove the option to let v7 correctly works.

We have this case in an unmaintained lib react-beautifull-dnd that blocks the migration of apps to react 18.

### What is the expected behavior?

A console warning can be displayed but not a blocking error, mostly if this parameter is not used at all.

### Which browser and OS are affected by this issue?

All

### Did this work in previous versions of React Redux?

- [X] Yes

**Comment by markerikson** [comment]
Hmm. My first answer here is that you shouldn't have to be passing in `pure: true` in the first place even in v7, because that's already the default and has been for years.

**Comment by paztis** [comment]
The problem is react-beautifull-dnd is unmaintained since 1 year but still really used. This one is blocking our migration to react 18 / react-redux 8.
Changing from error to warning will unlock the problem.

More the error is only thrown in dev mode. So it can be good to only warn not ?

**Comment by leosuncin** [comment]
@paztis there's a fork of `react-beautiful-dnd` with [fix in progress](https://github.com/react-forked/dnd/pull/345), maybe the fork is an more likely alternative

**Comment by paztis** [comment]
I've take a look to this fork. It only tries to update react 18 dependency.
I don't know how it can work. Only version 8 of react-redux can support react 18 ?

**Comment by markerikson** [comment]
Just published https://github.com/reduxjs/react-redux/releases/tag/v8.0.2 , which should fix this.
