### ISSUE TITLE
export 'unstable_batchedUpdates' (reexported as 'unstable_batchedUpdates') was not found in 'react-dom' (module has no exports)

### ISSUE THREAD

**Issue by aammlj2002** [reduxjs/react-redux#1915]
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

- React: 18.0.0
- ReactDOM/React Native: 18.0.0
- Redux: 4.1.2
- React Redux: 7.2.7

### What is the current behavior?

As soon as I imports react-redux, it shows the following error.

```
Compiled with problems:

ERROR in ./node_modules/react-redux/es/utils/reactBatchedUpdates.js 2:0-52

export 'unstable_batchedUpdates' (reexported as 'unstable_batchedUpdates') was not found in 'react-dom' (module has no exports)
```

### What is the expected behavior?

Redux is working very well in previous day. And I didn't change any verion of react and redux and suddenly got this errors. I tried by reseting to previous commits, but error is still showing.

### Which browser and OS are affected by this issue?

MacOS, Chrome

### Did this work in previous versions of React Redux?

- [ ] Yes

**Comment by timdorr** [comment]
You should upgrade to React Redux 8 if you want to use React 18.

**Comment by markerikson** [comment]
That said, I actually don't know why this error is happening, because ReactDOM 18 still exports `unstable_batchedUpdates`.
