### ISSUE TITLE
When react-redux@8 is installed, type is not normally found in dispatch.

### ISSUE THREAD

**Issue by Kir93** [reduxjs/react-redux#1918]
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

- React: 17.0.2
- ReactDOM/React Native: 17.0.2 / 0.68.1
- Redux: 4.2.0
- React Redux: 8.0.1

### What is the current behavior?

TS2345: Argument of type 'AsyncThunkAction<TicketEntity[], void, {}>' is not assignable to parameter of type 'AnyAction'. Property 'type' is missing in type 'AsyncThunkAction<TicketEntity[], void, {}>' but required in type 'AnyAction'.

```
const dispatch = useDispatch();
...
useEffect(()=>{
  dispatch(anyAction()) ; // error
},[dispatch])


### What is the expected behavior?

dispatch type changed before version

// v7
const dispatch: Dispatch
<AsyncThunkAction<ILoadNoticeListReturn, boolean | QueryDocumentSnapshot<INotice> | undefined, {}>>(action: AsyncThunkAction<...>) => AsyncThunkAction<...>

// v8
const dispatch: Dispatch
<AnyAction>(action: AnyAction) => AnyAction

### Which browser and OS are affected by this issue?

_No response_

### Did this work in previous versions of React Redux?

- [X] Yes

**Comment by phryneas** [comment]
This was actually a bug in the past. since the default `dispatch` type does not take the `redux-thunk` middleware into consideration and so always returned a wrong return value from the `dispatch` call. In short, it was possible to `dispatch` anything that was not a valid action.

To have redux-thunk's typings for a store with thunk, you need to set up [correctly typed hooks](https://redux.js.org/tutorials/typescript-quick-start#define-typed-hooks):

```ts
// store.ts

import { configureStore } from '@reduxjs/toolkit'
// ...

const store = configureStore({
  reducer: {
    posts: postsReducer,
    comments: commentsReducer,
    users: usersReducer
  }
})

// Infer the `RootState` and `AppDispatch` types from the store itself
export type RootState = ReturnType<typeof store.getState>
// Inferred type: {posts: PostsState, comments: CommentsState, users: UsersState}
export type AppDispatch = typeof store.dispatch


// hooks.ts

import { TypedUseSelectorHook, useDispatch, useSelector } from 'react-redux'
import type { RootState, AppDispatch } from './store'

// Use throughout your app instead of plain `useDispatch` and `useSelector`
export const useAppDispatch = () => useDispatch<AppDispatch>()
export const useAppSelector: TypedUseSelectorHook<RootState> = useSelector
```

**Comment by Kir93** [comment]
@phryneas In version 7, dispatch took care of the type inference, so is there no way to update it?

**Comment by phryneas** [comment]
No, in version 7 that was a bug. The dispatch just accepted whatever you put in there and returned exactly that.

```js
dispatch(validAction) // returns valid action <- this is correct
dispatch(thunk) // returns the return value of the thunk, but the type said it would return the thunk instead
dispatch(5) // this should have never been possible, but the types allowed it and said it returns 5
```

**Comment by Kir93** [comment]
@phryneas oh! Thank you for the reply. Hope you have a nice day :)

**Comment by phryneas** [comment]
You too!
