### ISSUE TITLE
Type missing from a single var in file.

### ISSUE THREAD

**Issue by stathis1998** [reduxjs/react-redux#1923]
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

- React: `^18.1.0`
- ReactDOM/React Native: `^18.1.0`
- React Redux: `^8.0.0-beta.1`
- @reduxjs/toolkit: `^1.8.0`

### What is the current behavior?

After upgrading to React@next, ReactDOM@next and Typescript@next I got a typescript error about an array never[] that was being pushed Listener type values.

I fixed it by adding the type Listener[] but it will get erased next update.

from
`let listeners = []`
to
`let listeners: Listener[] = []`

Line 37 at node_modules/react-redux/src/utils/Subscription.ts function createListenerCollection > get.

### What is the expected behavior?

Type is missing so typescript is whining.

### Which browser and OS are affected by this issue?

Firefox latest & Windows 10

### Did this work in previous versions of React Redux?

- [x] Yes

**Comment by markerikson** [comment]
You _shouldn't_ be compiling files in `node_modules`.

If someone wants to file a PR that improves this we'll merge it, but this is not a bug - this is a wrong setting in your application's `tsconfig.json`.
