### ISSUE TITLE
Nullish mapDispatchToProps causes Typescript Issues

### ISSUE THREAD

**Issue by marconi1992** [reduxjs/react-redux#1927]
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

- React: 18.2.0
- ReactDOM: 18.2.0 
- Redux: 4.2.0
- React Redux: 8.0.2

### What is the current behavior?

The `connect` HoC returns incorrect wrapped component prop types when passing `null` or `undefined`  as `mapDispatchToProps` argument.

```tsx
  class TestComponent extends React.Component<OwnProps & StateProps> {}

  const TestDispatchPropsNull = connect(mapStateToProps, null)(TestComponent)

  const verifyNull = <TestDispatchPropsNull foo="bar" />

  const TestDispatchPropsUndefined = connect(
    mapStateToProps,
    undefined
  )(TestComponent)

  const verifyNonUn = <TestDispatchPropsUndefined foo="bar" />
```

<img width="1038" alt="image" src="https://user-images.githubusercontent.com/11670923/175205993-f048db82-b555-4eac-ae07-d134b6d5d138.png">

**Codesandbox:** https://codesandbox.io/s/nullish-mapdispatchtoprops-q0eolm

### What is the expected behavior?

If the `connect` HoC accepts `null` or `undefined` then it should infer the wrapped component props correctly

### Did this work in previous versions of React Redux?

- [X] Yes

**Comment by marconi1992** [comment]
I think passing a nullish value in `mapDispatchToProps` is not recommended 

`connect(mapStateToProps, null)` or `connect(mapDispatchToProps, null)` 

We should only use `mapStateToProps` alone `connect(mapStateToProps)`. However, it's a common pattern I've seen in production code and there is no warning or TS definition preventing us to do that.

I created a PR adding a new type into the `Connect` type but let me know if we want to improve the types for preventing it rather than allowing it.

**Comment by markerikson** [comment]
Hmm. Passing a null value for `mapDispatch` is entirely legal :)  For example, say you want to pass in either `mergeProps` or `options` and the component doesn't need to dispatch:

`connect(mapState, null, null, {whateverOptionHere})`

I'm actually curious about how the `@types/react-redux` types for v7 handle this.  What does the TS behavior look like there?

**Comment by marconi1992** [comment]
> Hmm. Passing a null value for `mapDispatch` is entirely legal :) For example, say you want to pass in either `mergeProps` or `options` and the component doesn't need to dispatch:
> 
> `connect(mapState, null, null, {whateverOptionHere})`
> 
> I'm actually curious about how the `@types/react-redux` types for v7 handle this. What does the TS behavior look like there?

We have the same result using `@types/react-redux` types. I think v7 is using types for v6

Codesandbox: https://codesandbox.io/s/nullish-mapdispatchtoprops-v7-34psnf?file=/src/App.tsx

The [type](https://github.com/reduxjs/react-redux/pull/1928/files#diff-d35c5513c9b94df76b0abdfa0a2d1a75c953e8910fec0da7918dcff2cbead857R304) I included in the PR  is missing in `v7` and `v6`

FWIW I found that issue upgrading from v5 to v8

**Comment by markerikson** [comment]
Not sure what you mean by "v7 is using the types for v6".

In general our public API for `connect` has stayed almost identical across multiple major versions, with the only differences being a couple tweaks to what options are accepted:

https://blog.isquaredsoftware.com/2018/11/react-redux-history-implementation/

But yeah, seems very possible that this combination of arguments just wasn't being handled right in the  community types, and that carried over to v8 when we migrated the lib to TS.

**Comment by marconi1992** [comment]
> Not sure what you mean by "v7 is using the types for v6".

Nevermind, I thought we didn't have `v7` types because the folder is missing but the latest version of `@types/react-redux` is pointing to the [index.d.ts ](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-redux/index.d.ts)😅 rather than a version folder, there we have the `v7` types.

**Comment by marconi1992** [comment]
@markerikson just to confirm. Is the change from my PR suitable for this? or should we proceed differently?

I included a custom eslint rule in my codebase to prevent developers to use that pattern while we stay in v5 to avoid introducing more TS issues before jumping to v8.

<img width="1073" alt="image" src="https://user-images.githubusercontent.com/11670923/175354410-67a18aa3-15d0-47aa-8886-31c2da0809a7.png">

**Comment by phryneas** [comment]
Just to be sure: when working with v8, you have *deinstalled* `@types/react-redux`, right? That package is not required any more and would cause all kinds of conflicts.

As for the underlying problem: your example is honestly not complete enough to even find out if there is a problem in the first place. `OwnProps & StateProps` as well as `mapStateToProps` could be pretty much anything. Can you please provide a full example that shows the types are misbehaving?

**Comment by phryneas** [comment]
By the way, I'm saying this because when I just hand-write some minimal interfaces, everything works just fine:

[TypeScript playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wFgAoUSWOAbzQgDtGkMBfObXAo9GAWiIATAK4APMuQrBGMJFEzokcAPIB3RgAUcYAM51MECAC44umFBkBzNtNnzFaZQGUYKOdoh66cW1PKYIowYwExwIChgru5IACoQnnoAFACUtHBEMCJQjHB0HH4UFHloADYouvqxSOYAwriQLLJwSGJyjEL6yHwAdPXgTEiyADzqWjr6AGRw0R4TAHz5ReQlTOZw1eYAIsC6YO5oABaJugByIqWlcAC8cAzMrDBJEVFucvEnADRwjBelKUlNjB+o0hjAUstVox1gA3eTATAAT3OlxucGGQJ2ewOxwmKKuhgg1wARAAjFBQYlwAD080hdzW8Exu32MCOJwAqh0kJgZEghGj7iwMElinlwpFZnEEhNPmK8kEhDy+UIxQCgSDBrIIf4obD4UjTkwuWiMTUYFjWeyJlylbyWALCSTyZSafMgA)

**Comment by marconi1992** [comment]
> Just to be sure: when working with v8, you have _deinstalled_ `@types/react-redux`, right? That package is not required any more and would cause all kinds of conflicts.
> 
> As for the underlying problem: your example is honestly not complete enough to even find out if there is a problem in the first place. `OwnProps & StateProps` as well as `mapStateToProps` could be pretty much anything. Can you please provide a full example that shows the types are misbehaving?

@phryneas Yeah, I removed the `@types/react-redux`. You can notice from the codesanbox example are not using them.

I'm not sure what you mean by "full example". I was able to reproduce the issue on the example I provided with a simple setup.

Also, it's clear in the example the types are not correct. Notice it's using the `mapState and mapDispatch (as an object)` type here 
https://github.com/reduxjs/react-redux/blob/master/src/components/connect.tsx#L306

<img width="710" alt="image" src="https://user-images.githubusercontent.com/11670923/175363814-63c5cb62-1a4b-4eb8-a49a-1832713ce26f.png">

This is the type mess up things
```ts
   /** mapState and mapDispatch (as an object) */
  <TStateProps = {}, TDispatchProps = {}, TOwnProps = {}, State = DefaultState>(
    mapStateToProps: MapStateToPropsParam<TStateProps, TOwnProps, State>,
    mapDispatchToProps: MapDispatchToPropsParam<TDispatchProps, TOwnProps>
  ): InferableComponentEnhancerWithProps<
    TStateProps & ResolveThunks<TDispatchProps>,
    TOwnProps
  >
 ```

In this case the `mapDispatchToProps` could null or undefined, then `ResolveThunks<TDispatchProps>` returns `never` when passing a nullish value

**Comment by phryneas** [comment]
I'm sorry, I missed the CodeSandbox and was trying just with the code you had posted into this issue.
