### ISSUE TITLE
Docs: i18n

### ISSUE THREAD

**Issue by mskKote** [reduxjs/react-redux#1930]
### What is the new or updated feature that you are suggesting?

Internalization for react-redux docs

### Why should this feature be included?

**Props**
++ It would be easier to understand all the concepts.
++ Inclusiveness.

**Cons**
-- Docs for new features should be translated.

Mobx documentation already has maintenance of other languages

### What docs changes are needed to explain this?

Exist docs will not be changed

**Comment by markerikson** [comment]
To be honest this is really low priority, and we have no plans to do this ourselves.  Plus, we maintainers don't know any other languages and can't do any of the translation.

This would have to be a fairly large effort, driven by the community, and I don't think there's going to be a lot of enthusiasm or contributors to do that.

**Comment by mskKote** [comment]
Well, i've seen that docs are implement by docusaurus with build in i18n. So, i can translate it on russian

There are 16 pages. If it wont be a problem i could do that

**Comment by timdorr** [comment]
It's better if we leave this to separate communities to maintain (e.g., http://cn.redux.js.org/). While you may translate it correctly now, there's no way for us to know if a translation is out of date. Nor is there a way to ensure new pages are created in the future.

**Comment by mskKote** [comment]
Hello again!

I've translated the library
https://630cb8518dc0eb395a6d6436--lively-gelato-ac8199.netlify.app/

Pls, register to us sub-domain ru.react-redux.js.org

And also i've created a solution problem of actualization of that translation. If you connect a webhook, i would receive notification + message in telegram chat about any changes in folder /docs
http://185.209.31.11:5000/api/react-redux-webhook

<img width="1173" alt="Снимок экрана 2022-08-29 в 19 09 17" src="https://user-images.githubusercontent.com/52584520/187246442-aee541d3-40d0-4c23-86d0-c416e5240949.png">

**Comment by markerikson** [comment]
FWIW I'm not sure we can do anything about that domain name.

We use https://js.org/ , and I'm not sure if we have any control that can manage sub-sub-domains.

**Comment by mskKote** [comment]
Sorry for deleting previous message

Currently we obtained a domain: https://ru.react-redux.js.org. We will be glad if you include our link in [translations section](https://react-redux.js.org/introduction/getting-started#docs-translations)

Also we've created a partial solution of actualization problem of that translation ([timdorr's comment](https://github.com/reduxjs/react-redux/issues/1930#issuecomment-1170235894)). If you connect a webhook, we would receive notification + message in telegram chat about any changes in folder `/docs`
http://185.209.31.11:5000/api/react-redux-webhook

![photo_2022-08-29_19-36-46](https://user-images.githubusercontent.com/52584520/188245667-2c0a3e48-efe7-4f2b-aeb1-2d5358a38f53.jpg)
