### ISSUE TITLE
useSyncExternalStore/shim and vitejs

### ISSUE THREAD

**Issue by vidarc** [reduxjs/react-redux#1932]
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

- React: 18.2.0
- ReactDOM/React Native: 18.2.0
- Redux: 4.2.0
- React Redux: 8.0.2

### What is the current behavior?

On load, throws an error about unable to read `exports` property on `undefined`. Seems exact same as this issue: https://github.com/apollographql/apollo-client/issues/9670

### What is the expected behavior?

Should be able to handle build tools that prefer ESM

### Did this work in previous versions of React Redux?

- [ ] Yes

**Comment by timdorr** [comment]
This isn't a problem with our library, but with `use-sync-external-store`. You should file a bug on that project, which is under the `react` repo: https://github.com/facebook/react/
