### ISSUE TITLE
Feature Request: Dependency Injection via react context

### ISSUE THREAD

**Issue by IMalyugin** [reduxjs/react-redux#1934]
### What is the new or updated feature that you are suggesting?
Allow selectors and actions to access specific DI context provided by `react-redux`;

There are two ways of doing this:

**Straight solution:**
Adding 3rd argument to `mapDispatchToProps`, `mapStateToProps`, and selectors used by `useSelector` to provide unitifed React DI context.

**Hacky solution:**
Instead of adding more arguments, we could monkey-patch state during `mapStateToProps/useSelector` call, to inject hidden keys into state. This way it would be possible to keep selectors as simple as they are now, functions that may accept 1 argument. Selectors can then be enhanced to extract these context values back.

We used that approach in our practice, creating custom connectors, that monkey-patch state in `mapStateToProps`, injecting context values, and restoring it back after the call is finished. Overall solution is pretty neat, but unless it is first-class citizen of `react-redux`, there are a lot of inconveniences - such as having to create custom connectors and not getting errors when a wrong connector is used.

To demonstrate the use case for hacky solution:
```jsx
// page
const Catalog = ({ productIds }) => (
  {(productIds.map((id) => (
    <ProvideReduxContext name="pid" value={id} key={id}>
       <ProductHeading />
       <ProductDescription />
    </ProvideReduxContext>
  )}
);

export default connect((state) => ({
  productIds: selectProductIds(state),
})(Catalog);
```

```jsx
// heading
const ProductHeading = ({ children }) => (
  <h1>{children}</h1>
);

export default connect((state) => ({
  children: selectProductTitle(state),
}))(ProductHeading);
```

```jsx
// selectors
// supporting contextId would obviously require advanced memoization
// state schema is the following: { products: [{ id, title }] }

const selectProductIds = createSelector(
  (state) => state.products,
  (products) => products.map((item) => item.id),
);

const selectProduct = createContextSelector([
    (state) => state.products,
    (, , { pid }) => pid,
  ], (products, pid) => products.find((item) => item.id === pid)
);

const selectProductTitle = createContextSelector(
  selectProduct,
  (product) => product.title
);
```

I could participate in feature development if this idea would be considered promising.

### Why should this feature be included?

One of the most blamed features of redux for the past decade is that it does not allow for dependency injection. All the selectors are always bound to exact piece of the state tree, e.g. `state.homePage.productCards`. This limitation is the worst pain of redux as the global state manager.

The only way to "overcome" this, is actually passing some distinct value over `ownProps` of every single selector call, but that adds a huge overhead, so nobody does this.

As another case that appears to be a pain of redux is array mapping. When using `react-redux` with arrays, we can only connect the arrays as a full instance, so the whole concept of using redux for managing small pieces of application  breaks apart when we use it on catalog pages.

That is where the feature request comes to mind. React Context is the recommended approach of introducing dependency injection for react applications, and it actually scales pretty well to redux. If we allow passing extra parameters to redux context and then passing it down to selectors and actions, it would be possible to keep selectors while mounting the reducers to other state pieces without modifying the codebase.

On top of that a new breed of selectors would be born - contextSelectors, allowing to access elements within arrays, for example we can make a selector: selectTariffCardTitle, that would return different primitive values within array based on the call location. If it is called on a card used inside first element of array, it will return the heading of the first element, etc.

### What docs changes are needed to explain this?

The feature would require a new major release with a lot of new docs / modifications to existing docs.

**Comment by markerikson** [comment]
I'm not sure I understand the requested use case here. Can you give some concrete code samples of what you're trying to accomplish?  Is the primary goal to handle lazy-loading reducers into the store?

I can tell you that we're absolutely _not_ adding any new functionality to `connect` at this point - it's there, it works, but it's purely in maintenance mode, and we _want_ people using the hooks API instead.

**Comment by IMalyugin** [comment]
Not lazy loading reducers, more like decoupling selectors from store schema via react context. And for that, we need to pass context down into selectors.

Two concrete examples would be:
1. Imagine a shop catalog page, 80% of all the data on the page is mapping a huge array of data into different product cards. I would like to allow `react-redux` to write selectors, that get data from current product element. So that redux would be allowed inside arrays - `selectingProductName` into `<ProductTitle />` component.

2. Imagine a reusable widget, like popup, currently nobody would consider using redux to implement it, because we would have to create root selector bound to fixed state branch, e.g. `state.popups.myWidget`, and force end-user to insert that reducer to this very spot. But what if we want to use it in a differently structured store? Or that widget needs to be used in 2 spots. but our root selector would still select data from `state.popups.myWidget`;

To fix both these problems we need to use React Context along with selectors, as it would allow us to pass the data needed for examples to work:
1. Pass productId into selectors over context, so that each selector can get data for currently rendered `productCard`;
2. Pass rootSelectorPath into selector over context, so that widget selects data based on the currently mounted location;

Whole configuration in both cases would take 1 react-context usage. The first example is explained above in the initial comment.

One could argue that you could achieve the same by using hooks, and replacing useSelector with custom hook like useProductSelector or useWidgetSelector, that uses both useContext with useSelector under the hood. But firstly, it does not work with connect. And secondly, it would probably force us to rewrite all the selectors to manually pass down the context value.

As for the so hated "`connect`": `mapStateToProp` uses same mechanics as `useSelector`, so it makes sense upgrading both with the same functionality to keep consistency.

And as an off-topic: It's a shame, an approach with clean interfaces, black-box external connection and greatly decoupled store is being replaced by casual hooks approach. But I guess that's life, there's no point arguing about it, but I'm pretty sure there will always be people choosing `connect` :)

**Comment by markerikson** [comment]
I don't see the connection with React Context and Redux here, and I also don't understand the "genuine DI" label either.

Can you please show some _actual code examples_ of what you want to accomplish, not just descriptions?  Even if the code isn't real working code.

I'll also note that the "selectors" API is actually part of Reselect, not React-Redux, and Reselect has no knowledge of React all.  So, the notion of a `createContextSelector` doesn't make sense a conceptually. A selector is a function that accepts some arguments and returns a result, regardless of where those arguments came from.

**Comment by IMalyugin** [comment]
Was just updating the comment with this.

If by code samples you mean a working repo, then it sounds more of a pull request. Seems a bit too early for that. If just "how i would like to use that feature code-wise" is enough, then code above is exactly about that. I could add some explaining to the code example above, or add another example, if that could help.

By Geniune DI, I mean adding Dependency Injection capabilities. Since context is considered implementation of IoC by react team. Basically integrating react-redux with context would mean making react-redux DI-capable.

As for selectors, i was going to say that too. Yes I understand that selectors are actually not part of react-redux, they are more like an external feature and have no knowledge of react, but for DI to work with selectors we would first have to pass context down to these selectors. they can use it as a ordinary params, or we could hide these params as dynamic part of the state, that is part of an implementation. If done right, we don't even need new kind of selectors, just new kind of connection that generates a dynamic state piece.

Currently the state is passed down into selectors unchanged, and considering example above, for a shop card, we have same entire state for all 10 shop products. But If react-redux could split state based on context and memoize it would not break compatibility and still allow the feature to work.

At the end of the day what a feature request is about - is dependency injection. Reusability for redux over different parts of the state and selecting elements of array.

**Comment by IMalyugin** [comment]
An example of what state could be passed down to selector calls:
```
For selector called within first product context, pass following state:
{
  products: [{
    id: 1,
    title: "My first product",
  }, {
   id: 2, 
   title: "My second product",
  }],
  __reactReduxContexts: { pid: 1 }
}

For the same selector called within second product context, pass following state:
{
  products: [{
    id: 1,
    title: "My first product",
  }, {
   id: 2, 
   title: "My second product",
  }],
  __reactReduxContexts: { pid: 2 }
}
```

where __reactReduxContexts are values stored in ProvideReduxContext

**Comment by IMalyugin** [comment]
To do this, connect and useSelector, could memoize calculate new state as memoize of state and all the shallow keys of ProvideReduxContext.

**Comment by IMalyugin** [comment]
If what I mean is still not clean, I could try making a full example of what I want to achieve, or even a code sample that creates "custom" connect, to show it.

**Comment by markerikson** [comment]
I think we're still talking past each other.  To set some ground expectations:

- We are _not_ modifying `connect`.  It's frozen.
- `createSelector` has no knowledge of "context", so that's irrelevant here. Only components know anything about React context.  So, any description of "adding a new argument to `createSelector`" isn't going to happen either.

I need a better explanation of what you're trying to "inject" via DI here, and how. Typically, "DI" is used for injecting something like an API call service. That clearly isn't relevant for the use case of "selecting data from a Redux store".

There isn't any notion of "splitting state via context".  `useSelector` and `mapState` both receive the _entire_ Redux root `state` object.  So I'm still very confused what you're asking for and what you're trying to accomplish here.

The general approach for customizing what a component reads from state has always been to pass data via props, and use that to help determine what is selected from the store. With `connect`, the `mapState` function does get `ownProps` as an argument:

```js
const mapState = (state, ownProps) => {
  const todo = selectTodoById(state, ownProps.todoId);
  return { todo };
}

export default connect(mapState)(TodoListItem);
```

With `useSelector`, you use closures:

```js
function TodoListItem({todoId}) {
  // `todoId` could also have come from a `useContext` as well here
  const todo = useSelector(state => selectTodoById(state, todoId));
}
```

Given that, I'm not clear what additional functionality you're asking for above and beyond those existing capabilities.

So, I'm asking for some "realistic" code examples.  It doesn't have to _run_, given that you're asking for a new feature of some kind, but enough code (a few components, a store setup so I can see the reducers, etc), to get a sense of what you're actually trying to accomplish that's not possible with the current API.

**Comment by IMalyugin** [comment]
Okay, let's not jump to conclusions, I've heard all your points and I see that you are trying to understand.

I guess it would be much clearer and easier to understand if i just made a simple working codesandbox with a monkey patched solution, shouldn't take too long to do.

As for ownProps and extra useContext call for every single place. That is clearly not DI and has nothing in common with DI. It's almost as saying - why use react context at all if we can pass the same value down to every component :)

The DI I mean is not the "real" interface-based dependency injection. I just mean react context, as it IS considered a special implementation of DI for react. It allows overriding some data from outside without explicitly passing anything straight into the components.

**Comment by phryneas** [comment]
Let's look at the different parts: `connect` is a legacy api that still exists to support class components (which most apps are phasing out nowadays if they haven't already, but it's not getting any new features. We are pretty set on that. There will not be any new `connect` features.

Taken that as a given, all changes could be made to `useDispatch` and `useSelector`.

`useDispatch` only returns `dispatch`, so there would not be anything to do regarding action creators here.

`useSelector` can already be used with values from context:
```js
const valueFromContext = useContext(MyContext)
const valueFromSelector = useSelector(state => mySelector(state, valueFromContext ))
```

Doing it this way also works nicely with values from props:
```js
function MyComponent(props) {
  const valueFromSelector = useSelector(state => mySelector(state, props.someValue))
}
```
is also works nicely with local state:

```js
  const [stateValue, setStateValue] = useState("initialValue")
  const valueFromSelector = useSelector(state => mySelector(state, props.someValue))
```

Now, the main question is: is it worth adding another api to this mix that could only be used with context, but not with props and not with state?

My gut feeling would be "no". Especially as I'd say that such an api might be a bit weird to use with a third argument:

```js
  const valueFromSelector = useSelector(mySelector, equalityFunctionIdidntNeedToSpecifyBefore, MyContext)
```
also, that brings up the question "what if I need mutliple contexts?"
```js
  const valueFromSelector = useSelector(mySelector, equalityFunctionIdidntNeedToSpecifyBefore, { valueA: MyContextA, valueB: MyContextB })
```
would come to mind, but that would introduce a subtle way of breaking the rules of hooks:

Internally, `useSelector` would now need to call `useContext(MyContextA); useContext(MyContextB);`

So what if on a future render, the user decided to pass in `{ valueA: MyContextA, valueB: MyContextB, valueC: myContextC }`? `useSelector` would need to execute 3 `useContext` calls instead of two - and that would break the rules of hooks.


I'm sorry, but so far I don't see a way of doing it that is sufficiently "more ergonomic" than what was possible before - and even possible to implement.

**Comment by IMalyugin** [comment]
Well your position on connect could be fatal to the feature request. Because if you will go as far as making the library inconsistent in the way it works over different selector types just to avoid implementing feature to both connect and useSelector. Funny enough connect has nothing to do with class components and can be used with function components just as good, but everybody only looks at at as part of the legacy react class api. 

Putting that aside. Yes adding 3rd argument to useSelector is a bad idea, it would still cause lot of issues and the whole point of the feature request would be lost. So I should have only suggested splitting state with the context during useSelector call (as explained in this comment: https://github.com/reduxjs/react-redux/issues/1934#issuecomment-1204143442)

As for having multiple contexts that is not a problem - this is why I suggested using one custom context provided by react-redux, if you want to use multiple values, just inject more different values into the same context using the advanced provider. Using user-defined react contexts was never the idea, as just as you mentioned it breaks rules of hooks and would also break the value of the feature - it would just add more boilerplate then there is at the moment.

With current state of things, almost nobody uses second argument to selectors. It doesn't scale, it doesn't work with memoization, and it forces developers to write all the selectors with two arguments, explicitly passing props. You do have a point that useSelector can be combined with useContext into a higher order hook - and that would partially fix the issue. One would have to replace all the useSelector call with the new useContextSelector custom hook and it would partially solve the problem. Except for the part with having to make all the selectors more complicated. So splitting the state and passing a new synthetic state that has context data in it could make the things much cleaner.

I still insist on showing an example, so that we could all be tuned to the same concept.

**Comment by phryneas** [comment]
> Funny enough connect has nothing to do with class components and can be used with function components just as good, but everybody only looks at at as part of the legacy react class api.

`connect` is much harder to use for most people and the hooks also have much better TypeScript support. Consequently we have always been recommending the hooks for any use with function components. If we would have started off in a world where hooks existed and class components would not exist, `connect` would never have been added. Hence, `connect` is a legacy api to support class components.

> With current state of things, almost nobody uses second argument to selectors. 

Most people do this, if they ever followed the official Redux tutorials.

> It doesn't scale, it doesn't work with memoization, and 

A second argument that changes does not break memoization more or less than passing in a first argument that changes

> it forces developers to write all the selectors with two arguments, explicitly passing props. 

Yes, that's what people are doing. Functions can take multiple arguments.


Let me showcase the difference between a memoized selector taking one argument and consuming two parts of state and a memoized selector taking two arguments:

```js
const selectorWithOneArgument = createSelector(
  state => state.someSlice,
  state => state.someValueFromContextThatWasAddedOntoState,
  (someSlice, someValueFromContextThatWasAddedOntoState) => /* some calculation here */
)
// opposed to
const selectorWithOneArgument = createSelector(
  state => state.someSlice,
  (state, secondArgument) => secondArgument,
  (someSlice, secondArgument) => /* some calculation here */
)
```

Also, here are approaches of non-memoized selectors:

```js
const selectorWithOneArgument = ({ someSlice,  someValueFromContextThatWasAddedOntoState }) => /* some calculation here */
// opposed to
const selectorWithOneArgument = ({ someSlice }, secondArgument) => /* some calculation here */
```

As you see, from the side of defining a selector there is literally no difference between both approaches.

**Comment by IMalyugin** [comment]
> A second argument that changes does not break memoization more or less than passing in a first argument that changes
That's true, even if we did pass a hidden value inside first argument it wouldn't matter much, as reselect memoization would still only cache result based on the single cache.
 
> Yes, that's what people are doing. Functions can take multiple arguments.
> 
> Let me showcase the difference between a memoized selector taking one argument and consuming two parts of state and a memoized selector taking two arguments:

That's not the point, it doesn't matter how to pass the argument, but with this, you can no longer use selectors freely. What if your root selector has to change based on some own prop? You would have to apply that schema in every single one of the selectors, overcomplicating things

```js
// not even using reselect for simplicity
const selectFifthLevelData(state, ownProps) => selectFouthLevelData(state, ownProps).fifth;
const selectFourthLevelData = (state, ownProps) => selectThirdLevelData(state, ownProps).fourth;
const selectThirdLevelData = (state, ownProps) => selectThirdLevelData(state, ownProps).third;
const selectSecondLevelData = (state, ownProps) => selectThirdLevelData(state, ownProps).second;
const selectFirstLevelData = (state, ownProps) => state[ownProps.rootKey];
```
If somebody is this in their code and they don't feel this is wrong then i give up.

What i wanted to do is keep the boilerplate at bay. All you need to do:
1. <ProvideReduxDIContext rootKey={customKey}> somewhere in react
2. In the very selector, that requires context value do this:
```
const { selectStateContext } from 'react-redux';
const selectFirstLevelData = createSelector(
  state => state,
  state => selectStateContext(state).rootKey
);
```

That's it, DI at work, provider is used somewhere above the application just once. Nobody has to write tons of extra code just to pass that data down.

**Comment by IMalyugin** [comment]
Just give me an honest answer, I'm sure all of us did a lot of array mappings in react/redux applications. Did you still use redux inside these array react elements or did you just connect the container and switch to react props drilling, because redux doesn't work well with arrays? And if you still did use redux, didn't you feel like you write too much boilerplate and overcomplicate selectors?

**Comment by markerikson** [comment]
I've said this a few times already, but I don't understand the original use case you're trying to address here.

When and why would you need to swap what section of state a component is reading from? I genuinely don't understand the intent here, which is why I keep asking for a realistic example.

**Comment by phryneas** [comment]
> because redux doesn't work well with arrays

I really have **no** idea what you mean by this, Redux works perfectly fine with arrays. Could you give some kind of code example what *you* mean when you say that?

**Comment by phryneas** [comment]
As for the "having one singular context", that would just cause a very real problem: every component subscribing to a context change always rerenders - no matter if it was interested in that specific context change.

So assume you have one single selector that even takes the context into account and 200 other selectors spread over components. Now you change the context value. All of those components will rerender - no matter if the selector return value changed. We simply cannot prevent that.

**Comment by IMalyugin** [comment]
Ye, I've heard both of you, I'll try to provide an example that shows the entire thing. 

@phryneas
The original example in the first comment showed the problem with elements:

```jsx
// page
const Catalog = ({ productIds }) => (
  {(productIds.map((id) => (
    <ProvideReduxContext name="pid" value={id} key={id}>
       <ProductHeading />
       <ProductDescription />
    </ProvideReduxContext>
  )}
);

export default connect((state) => ({
  productIds: selectProductIds(state),
})(Catalog);
```

```jsx
// heading
const ProductHeading = ({ children }) => (
  <h1>{children}</h1>
);

export default connect((state) => ({
  children: selectCurrentProductTitle(state),
}))(ProductHeading);
```

```jsx
const selectProductIds = createSelector(
  (state) => state.products,
  (products) => products.map((item) => item.id),
);

const selectCurrentProduct = createSelector([
    (state) => state.products,
    (state) => selectStateContext(state).pid,
  ], (products, pid) => products.find((item) => item.id === pid)
);

const selectCurrentProductTitle = (state) => selectCurrentProduct(state).title;
```

Modified it a little to remove complexity.

**Comment by IMalyugin** [comment]
> As for the "having one singular context", that would just cause a very real problem: every component subscribing to a context change always rerenders - no matter if it was interested in that specific context change.
> 
> So assume you have one single selector that even takes the context into account and 200 other selectors spread over components. Now you change the context value. All of those components will rerender - no matter if the selector return value changed. We simply cannot prevent that.

It IS the same with redux state, isn't it? If  you change the state, all the selectors trigger. Most use cases for context selectors would be keeping the value static, why changing both state and redux? And even if we did change the value once, ye, act the same as if redux value changed.

All the examples i brought before were having static context - having different productIds for array elements? 100% static, having different mount roots? Static.

**Comment by IMalyugin** [comment]
> I've said this a few times already, but I don't understand the original use case you're trying to address here.
> 
> When and why would you need to swap what section of state a component is reading from? I genuinely don't understand the intent here, which is why I keep asking for a realistic example.
> 
> And how do arrays relate to any of this?
> 
> We're talking past each other here, and it's getting frustrating for me because I _don't understand what the goals are_ and thus I can't provide a meaningful answer. It feels like you're describing a problem space that I've never seen myself or never seen anyone else run into, and you're assuming that we're already familiar with this problem.

And yet again, I already agreed with you, I'll make an example :) But it would take a few hours, not minutes. I'm not confident that more "non real" examples that just show the concept would change anything at this point, so I'm going to make a real one.

**Comment by phryneas** [comment]
@IMalyugin in a situation like that I would depending on the situation either pass down the id or the product itself as a prop (probably the id though) - and I can't remember when I last encountered a situation where I had to pass it down further than 2 or 3 levels, using component composition.

> It IS the same with redux state, isn't it? If you change the state, all the selectors trigger. Most use cases for context selectors would be keeping the value static, why changing both state and redux? And even if we did change the value once, ye, act the same as if redux value changed.

No. With Redux state, the selector re-executes - and then react-redux decides if the component needs a rerender. If context changes, the component will rerender, no matter what. There is no way around it.

> All the examples i brought before were having static context - having different productIds for array elements? 100% static, having different mount roots? Static.

Now have 5 different values in there and not just that one id. Maybe an id and four dropdowns. Change one dropdown. Everything unrelated will rerender, just as if another dropdown or the id would have changed.

**Comment by IMalyugin** [comment]
> No. With Redux state, the selector re-executes - and then react-redux decides if the component needs a rerender. If context changes, the component will rerender, no matter what. There is no way around it.
Now that sounds like a flaw of hooks :)

I was still thinking in terms of connect, you're right, selectors don't have to trigger if value didn't change. But I did mention react-redux specific context, right? who said it has to be a changing context, I'm sure there is a workaround, make it a ref, change the value and poke selectors, check if value changed. We're all developers here, we should discuss the details after we're all on the same page including markerikson, and after we all see a value in this.

**Comment by IMalyugin** [comment]
> @IMalyugin in a situation like that I would depending on the situation either pass down the id or the product itself as a prop (probably the id though) - and I can't remember when I last encountered a situation where I had to pass it down further than 2 or 3 levels, using component composition.

Well when I had such a situation i passed id to every element of my react tree, I got rid of every other props, and just pushed lot of ids down (before hooks were added). Nowadays if i wasn't so positive towards connect, I guess I could write my own useSelector using context and then would pass values down, since there are no other choice. Although I'm just switching to render props for arrays and then inside high level components i have to spread all the keys down to components, because it feels less boilerplate'ish for average-size arrays of data.

**Comment by phryneas** [comment]
> I was still thinking in terms of connect, you're right, selectors don't have to trigger if value didn't change. But I did mention react-redux specific context, right? who said it has to be a changing context, I'm sure there is a workaround, make it a ref, change the value and poke selectors, check if value changed. We're all developers here, we should discuss the details after we're all on the same page including markerikson, and after we all see a value in this.

That really would make us reimplement what Redux does (again) on top of reimplementing what React does... I'm still not convinced any of this makes any sense to be honest, seeing that it would add a very different concept of dealing with external values, compared to what is already standard in nowadays code bases (see the three different useSelector usages above that are all very alike).

Taking up on your "second argument is problematic"... I still feel that is very much only a problem the way you specifically are using selectors here? Funny enough, the complexity in your example would even completely disappear using reselect composition.

**Comment by IMalyugin** [comment]
Took some time to make a working prototype in codesandbox just to figure out codesandbox is broken and one can no longer update dependencies in it :)

Will move it to another tool when I can, for now, heres the code:
https://codesandbox.io/s/react-redux-forked-n8y5kt


> Taking up on your "second argument is problematic"... I still feel that is very much only a problem the way you specifically are using selectors here? Funny enough, the complexity in your example would even completely disappear using reselect composition.
I'm usually using selectors with reselect, composing them the right way, and usually I don't pass data in. And yes I never use redux for dependency injection tasks, I always assume that redux is just not made for arrays and dynamic state mounting widgets. If such a task arises, I have to write my own redux on top of plain react context, which is kinda shame.

On top of that, ye, there is no viable solution for connect-based code, and I understand all your point on that subject, but that doesn't make me agree on it.

**Comment by phryneas** [comment]
Generally, have you ever read the [Redux Essentials, Part 6: Performance and Normalizing Data](https://redux.js.org/tutorials/essentials/part-6-performance-normalization) tutorial? It seems that even with this example you are reinventing a lot of wheels.

**Comment by IMalyugin** [comment]
Okay, moved it to the new working codesandbox:
https://codesandbox.io/s/react-redux-di-0ofqyy

@phryneas
As for the @redux/toolkit docs, no you got me there I haven't read the entire doc edge-to-edge, I've read a lot of it. looked up entity adapters, don't see them helping more than joining together 3 functions doing essentially the same we always do, when working with entities. Basically we've been using that approach for a few years now, but with an internal tool.

It wouldn't change much if i added entity adapter to the example, we still have to pass all the id-data manually. The point is in making scoped selector usage as simple as possible. I'm not sure that pointing towards the fact that we can always do the same manually by adding a lot more code covers the feature request as inappropriate.

The todo example is kept as simple as possible just to show context of the solution. Of course at such scale it would make no sense to go on and implement something like that. But imagine thousands of selectors, huge applications using that mechanic, nobody wants to pass second parameter to all these selectors. It's the same as choosing between connecting redux in container and connecting redux in the final component. I'm glad community choosed the latter to reduce props drilling. But now we have ownProps drilling in selectors, joined by unnecessary explicit context usage in every connected component.

**Comment by phryneas** [comment]
> nobody wants to pass second parameter to all these selectors.

What do you mean by that? If it's a `createSelector` use, that explicitly isn't the case.

Taking your own argument:
```js
const firstSelector = (state, arg) => something
const secondSelector = createSelector(firstSelector, result => something)
const thirdSelector = createSelector(secondSelector , result => something)
const fourthSelector = createSelector(thirdSelector , result => something)
const fifthSelector = createSelector(fourthSelector, result => something)
```

Putting aside that this is a level of reducer composition I would not expect in a big number of apps in the first place, you don't have to pass any second argument through every of the intermediate levels here.

**Comment by IMalyugin** [comment]
> > nobody wants to pass second parameter to all these selectors.
> 
> What do you mean by that? If it's a `createSelector` use, that explicitly isn't the case.
> 
> Taking your own argument:
> 
> ```js
> const firstSelector = (state, arg) => somethingBasedOnArg
> const secondSelector = createSelector(firstSelector, result => somethingBasedOnResult)
> const thirdSelector = createSelector(secondSelector , result => somethingBasedOnResult)
> const fourthSelector = createSelector(thirdSelector , result => somethingBasedOnResult)
> const fifthSelector = createSelector(fourthSelector, result => somethingBasedOnResult)
> ```
> 
> Putting aside that this is a level of reducer composition I would not expect in a big number of apps in the first place, you don't have to pass any second argument through every of the intermediate levels here.
> 
> This whole scenario still seems like overengineering a very specific problem only very few applications ever have.

Well, you have a good point here, just putting createSelectors would fix some issues, but there is a catch with createSelectors, we don't always wrap simple functions with createSelectors, so it's very error prone, one standard selector and it is ruined. And there is still parts about passing props to selectors and no decent support for connect (and yes I've got your point about it not being supported anymore)

**Comment by IMalyugin** [comment]
Anyways the sandbox is working now, feel free:
https://codesandbox.io/s/react-redux-di-0ofqyy

**Comment by markerikson** [comment]
> And i don't trust second createSelector argument, because it doesn't bode well with memoizing

Note that as of Reselect 4.1, you can create selectors with a cache size > 1:

https://github.com/reduxjs/reselect/releases/tag/v4.1.0

Alternately, you could create a unique selector instance per component instance, if there are many components that would want to call the "same" selector with different arguments.

That said, if the selector is just _returning_ a valid (like `return state.items[id]` or `state.items.find(item => item.id === id)`, then memoization is irrelevant anyway because you're not _deriving_ data.

**Comment by IMalyugin** [comment]
Good to know that memoization is fixed. As for the second argument, ye, i know, thats why i said we don't usually use createSelectors for the sake of destructuring a value. And if we are forced to createSelectors for the whole cascade because of some deep prop, thats violating dijkstra's principle as well as SRP.

**Comment by markerikson** [comment]
I have no idea what that last statement means, tbh :(

Per https://redux.js.org/usage/deriving-data-selectors , selectors have two main purposes:

- encapsulating looking up a given value from the Redux state
- Memoizing expensive transformations or cases where derived data needs a consistent reference that shouldn't be recalculated every time

I don't know how `createSelector` accepting an argument has anything to do with "Dijkstra's Principle" or SRP.

> Just hope you're not trying to be offensive in this comment by trying to pick me up on just about anything :) I've been doing frontend for 15 years, last 7 years in react/redux stack. And for about 6 last years I've been waiting for somebody to invent a way to marry DI with redux. about 4 years ago I made a solution similar to the suggested one, but even thought it fixed the problem, it added a lot more complexity, being an external tool. Unfortunately, the only way to fix that is making it a first citizen for react-redux.

I feel like there's a bit of a language barrier here somehow :(  I'm genuinely not sure what this statement is even trying to say.

You keep repeating "DI" and "Redux".  I know what Dependency Injection is. I know what Redux is. I just don't understand what _you_ seem to think these words mean together.

Honestly, the last suggestion I can offer here is to dynamically generate selectors by passing in some kind of an input selector, like:

```ts
export const createModuleXSelectors = (
  inputSelector: (state: any) => ModuleXState
) => {
  return {
    selectSomeData: createSelector(inputSelector, (moduleXState) => {
      return //derive more data here
    })
  }
}
```

This is a pattern we use with RTK's `entityAdapter.getSelectors`, which can return either "localized" selectors that need just the slice state, or "globalized" selectors that expect the root state.

You could maybe create those selectors in a parent component, pass the selector functions themselves down via context, and then do:

```ts
function ModuleXChildComponent() {
  const moduleXSelectors = useContext(ModuleXSelectorsContext);
  const someData = useSelector(moduleXSelectors.selectSomeData);
}
```

and at that point you truly are injecting the method of selecting the proper data into the component.

To be honest I still don't fully understand what you're asking for here, but based on the general flow of the conversation so far, I don't think we're going to add or change anything that matches what you seem to want.  We're not modifying `connect`, and we're not making changes to Reselect.

We've tried to offer some suggestions based on what we _think_ the problem space is that you're describing, but somehow the way you're describing it just quite isn't coming across clearly as we try to read this.  It also seems like you also want to use React-Redux with patterns that you prefer but that we no longer recommend, and also are trying to solve problems that feel out of the normal usage flow (like the possibility of state lookups needing to be completely dynamically computed at runtime).

Unfortunately I don't think this conversation is going anywhere useful, so I'm going to go ahead and close this issue.

**Comment by IMalyugin** [comment]
Unfortunately I have to agree that this conversation is not going anywhere, so it was probably the right choice to do. The conversation however was still rather useful, so thank you. I figured out that this whole thing can still be achieved without creating custom selectors, actions, or anything. Monkey-patching ReactReduxContext, carefully injecting context values inside of the returned state achieves all the same without forcing extra code. The "context values" will most likely need to be fixed forever (without allowing to change them on the fly) to prevent re-rendering. But in most cases, that's not required.

Thank you for your time either way.
