### ISSUE TITLE
React 18 Automatic Batching SUPPORT?

### ISSUE THREAD

**Issue by stormdotcom** [reduxjs/react-redux#1938]
### What is the new or updated feature that you are suggesting?

React 18 introduced batching[fine tuned] with additional features, which helps our react app in lot performance improvement, I would like to suggest redux team to add handle those changes in redux for fullest comparability with react 18 in upcoming release  If possible how, when will be the release

### Why should this feature be included?

Lot more performance improvement

### What docs changes are needed to explain this?

https://react-redux.js.org/using-react-redux/connect-mapstate

**Comment by phryneas** [comment]
There should be nothing on our end to be done - if React automatic batching is active for you, it should do that with Redux updates as well.

**Comment by markerikson** [comment]
Yeah, this is inherent in React 18 (and we also already used batching internally anyway with earlier React versions).
