### ISSUE TITLE
ConnectedProps: dispatch prop expected even if there is no mapDispatchToProps 

### ISSUE THREAD

**Issue by TheHaff** [reduxjs/react-redux#1944]
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

- React: 
- ReactDOM/React Native: 
- Redux:
- React Redux:

### What is the current behavior?

i use ConnectedProps to infer my component props instead of manual typings, but i noticed when reusing the result in a different component where i manually piped down the same props that it expects dispatch.

### What is the expected behavior?

Should'nt need dispatch in these cases

### Did this work in previous versions of React Redux?

- [ ] Yes

**Comment by markerikson** [comment]
What do you mean by "expects `dispatch`"?  What error message are you seeing?

Can you put together a sandbox or repo that shows the actual problem?

The PR you filed doesn't look correct.  If you don't provide a `mapDispatch` argument, React-Redux _will_ pass in `props.dispatch` automatically.
