### ISSUE TITLE
Can't use a npm library, which depends on react-redux, on different library versions among repositories

### ISSUE THREAD

**Issue by icaldana-daitan** [reduxjs/react-redux#1949]
## The versions
* `"react": "17.0.2"`
* `"react-dom": "17.0.2"`
* `"redux": "4.2.0"`
* `"react-redux": "8.0.2"`

## Context
I'm working on a multi-frontend environment with `Webpack` module federation + `react` + `redux` + a NPM library for shared components, which uses `react-redux` to compose the shared store.

![003](https://user-images.githubusercontent.com/30550706/186940465-4aec90bc-5023-4c9c-961e-6e4acf03afaa.png)

## The issue
All repositories (aka micro-frontends - MFE), must use the SAME SDK library version. When we don't, `react-redux` breaks weirdly. Even when publishing two versions with the same code, it doesn't run. 

![002](https://user-images.githubusercontent.com/30550706/186940952-0ff64bf2-d413-48b4-9888-7707b06000aa.png)
![01](https://user-images.githubusercontent.com/30550706/186940960-3b489c4a-0b0b-4eb1-aa6a-ef7faf0164eb.png)

### What is the expected behavior?

It should work properly since there wasn't code changes, only the package version is different.

### Which browser and OS are affected by this issue?

Chrome  104

### Did this work in previous versions of React Redux?

- [ ] Yes

**Comment by markerikson** [comment]
This seems like expected behavior.

React-Redux relies on React context to pull out the current `Subscription` instance. That means that it _must_ be the _exact same `ReactReduxContext` reference_ to work right.

React-Redux uses a singleton `ReactReduxContext` instance.  If you have multiple versions of React-Redux installed, there are multiple different copies of `React-ReduxContext`.

So, in the same way that you _must_ have one copy of React in the app, you _must_ have one copy of React-Redux.

**Comment by icaldana-daitan** [comment]
@markerikson what I don't get is that, besides having one or many instances of `ReactReduxContext`, why does the mere fact of chancing the package version would cause this error? It works perfectly when using the same version, regardless of the code itself being the same or not.

**Comment by phryneas** [comment]
Every of those packages calls `const ReactReduxContext = React.createContext()`.

So `useContext(ReactReduxContextFromPackage1)` will only retrieve the value by `ReactReduxContextFromPackage1.Provider` and `useContext(ReactReduxContextFromPackage2)` will only retrieve the value by `ReactReduxContextFromPackage2.Provider`.

They cannot see each other.

**Comment by icaldana-daitan** [comment]
Got it, but, Is changing the **version itself** affecting the context/singleton?

**Comment by phryneas** [comment]
Yes, because if you have two different versions of the library bundled up in your code (and that's what is probably happening), they won't be able to see each other.

**Comment by markerikson** [comment]
Yeah, what's probably happening is that each distinct build of your own app's base package is bundling in a copy of React-Redux. Thus, when the app loads, there are _multiple_ copies of React-Redux, each with its own entirely separate `const ReactReduxContext = React.createContext()` call inside. Thus, there are totally separate `ReactReduxContext` instances, React _sees_ them as being `!==`, and they are treated as being different and things don't line up right.

**Comment by icaldana-daitan** [comment]
> Yes, because if you have two different versions of the library bundled up in your code (and that's what is probably happening), they won't be able to see each other. You might be using the Provider from one version with the useContext call from the other.

WOW I see, thank you!
