### ISSUE TITLE
Type error when use bindActionCreators with async thunk action

### ISSUE THREAD

**Issue by zation** [reduxjs/react-redux#1954]
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

- React: 18.2.0
- ReactDOM/React Native:  18.2.0
- @reduxjs/toolkit: 1.8.4
- React Redux: 8.0.2

### What is the current behavior?

call binded async thunk action will return AsyncThunkAction, not the return of AsyncThunkAction. Please check this [code](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbwFBzgYygUwIY0wQQGcBPAOzQBUALAV1IGsAaFdLXTAJUwBMa1MozVGgikAZsADmNLAGUY0TELgAjYKW740MYKIDCbBVELMAvnDFQIIOAHIAAll4APAFaEA9AogAbesBhbJFBIWEQWGkJMABFgQjBcNCozCysbWzZtAFonGmdbAG4kJBFSQnhsEnJqOno4AF5WHDwiMkpaBgAKW0q2moZbRjhOgEoGgD5EUxGS0XK4XP4oBqb2Ll4lzoRTIc6VGmAfbgEx+snkVH3D46gAOmxubj1KzE7e6o76W7EaHwkfHw8XbcKDYMQwU7nFioEFg+CNbYsaZIZGleblRQrUoSaRyIyvBALHh8ARwaZFJAwYhgTBwfBgMCxeKJKgrKk0iBiOAYrC3bhxBIwJJFNHwSIEBlMwVJABcw0hdMlApZK3FUpZFJ+5B0ojgAAlrK8xhd0HN4PzmULWY1xfTGcqraMWKLVOpjpoqu1ais1BotDrSAZmtBCG9Pf0mHALdKqCMisIzUTCL94a6NDxWh9ak7UFhkz4YLc6AB3UFgUYUhNleB5lMARhW0ZZYb6n1GcZYtYLdaLpFL2HLHdMxSAA):
<img width="632" alt="image" src="https://user-images.githubusercontent.com/1049425/188260217-372c5205-a028-42ac-866e-dac53ddcb1f3.png">
<img width="497" alt="image" src="https://user-images.githubusercontent.com/1049425/188260234-411b845a-811d-4b9d-a8d1-32ba25c3ffc8.png">

### What is the expected behavior?

call binded async thunk action should return the result of AsyncThunkAction

### Did this work in previous versions of React Redux?

- [ ] Yes

**Comment by phryneas** [comment]
BindActionCreators does not know of any Middleware you are using, so it acts as if you are not using any. It can also not take those from `dispatch`, as those are overloads that even include generics - and typescript has no tools for us to map over these.

Bottom line: please just don't use bindActionCreators if avoidable in any way. There are multiple reasons we are not showing that anywhere in the docs, this being one of them.

If you are dead-set on it, you will have to cast those types manually.

**Comment by zation** [comment]
Thanks for the explanation. I'll try to cast it or wrap the bind function myself.

**Comment by phryneas** [comment]
Is there any specific reason why you want to go against all recommended best practices and use this in the first place? This is a very old api and afaik we explicitly do not document it for hook usage, as we want to encourage people to actually actively use dispatch.

**Comment by zation** [comment]
I want to extract a function to include the logic of `useDispatch`, `useCallback`, `unwrap`. They are common in our project. There is an [example](https://www.typescriptlang.org/play?ssl=40&ssc=1&pln=41&pc=1#code/JYWwDg9gTgLgBAbwFBzgYygUwIY0wQQGcBPAOzQBUALAV1IGsAaFdLXTAJUwBMa1MozVGgikAZsADmNLAGUY0TELhEylWg2UARYITC40VZgF84YqBBBwA5AAEsvAB4ArQgHoFEADb1gMa0igkLCILDSEmDp6BkZIpuaWNmxoMAC0DjSO1gDcgeDQ8FzYKYyhqOGYAMLYXl4ARsVMcWYWVtbJ-rlIIqSE8Ngk5NR09HAAvKw4eKpDGvQAFNYDasMM1qXz2FCShABccNikxACU4wB8B9uEx92ifXAZ-FDjk+xcvE-zCMYbdTTAXm4AlOYwuyFQfwBQKgADpsNxuNUIptBuoRjCxDQvBJajwNtwoNgxDAQWCWKgCUT4BNvixjDd6bdevA+ooXj0JNI5AosF8Hjw+AI4PSujBiGBMCowGAovoYIYXmKJRAxHBWVgYdxdHLDLkevcKvhpbKYvt5qSpTLtTEXhUTfKqKLxZKZmiGJVRJyXuC1TB2AB+fYjUgQADupBYWuiDsDcHthhYmEcMEJseDYYjqCwzkwKQAajUaJg0wwQ+GWBEoMAasAAF48ACiUAsUAozpL9DLmbgEtIWtIkgAspg-R2uyxMdiAV4eMPR0HSxmWNnc3huHPsGOl8YukngvB9fBDaj8ClgKIXgAefClABCpUqcCTeD7hBUqNW9A94ikZ02Z9ESo2B5fZXU-a87wfM4LR9Q84CjHUqFtCJ4yoc1cizEcZFIOAKmqWoGjQBZyTgTYrn2W9jn2AAFVpdEwa8LlBeDrQdS9DmIP9ihgc9SCAqZoDInZjmOGE6FDQkwHNZRUAAbQQmJSm43j+NwaAAF1lGOXIdyQJBMXIHiLwACUsTBzTKdA7ngQCvGAIjkIIE8ANIFEVjmbSWGXLCoBwy8-hgBQcNs+z6DGBAQqI4wzkqOyiMvNwAqCs44j0oA). The logic in `useAsyncAction` function are duplicated many times in our project. When I tried to extract it, I want to refer to the implementation of `bindActionCreators` and make the type as strong as possible.

**Comment by phryneas** [comment]
Yeah, that's a bit too generic that TS could ever infer that - you'll have to write quite a bit of types by hand - like this:

```ts
import {
  createAsyncThunk,
  createReducer,
  configureStore,
  AsyncThunk,
  Dispatch,
} from '@reduxjs/toolkit'
import {
  useDispatch,
} from 'react-redux';
import React, {
  useCallback,
} from 'react';

const asyncThunk = createAsyncThunk('asyncThunk', (args: { foo: string}) => args)
const reducer = createReducer({}, (builder) => {
  builder.addCase(asyncThunk.fulfilled, (draft) => {
    draft = {}
  })
})
const store = configureStore({ reducer });

type AppDispatch = typeof store.dispatch;
const useAppDispatch: () => AppDispatch = useDispatch;

type AsyncThunkConfig = {
  state?: unknown
  dispatch?: Dispatch
  extra?: unknown
  rejectValue?: unknown
  serializedErrorType?: unknown
  pendingMeta?: unknown
  fulfilledMeta?: unknown
  rejectedMeta?: unknown
};

export const useAsyncAction = <T extends AsyncThunk<any, any, any>>(actionCreator: T)=> {
  const dispatch = useAppDispatch();
  return useCallback(
    (args: Parameters<T>[0]): Promise<T extends AsyncThunk<infer R, any, any> ? R : never>  => {
      return dispatch(actionCreator(args)).unwrap()
    },
    [dispatch, actionCreator],
  );
};

function Home() {
  const onClick = useAsyncAction(asyncThunk);
  
  return <button onClick={onClick}>Click</button>
}


```

**Playground Link:** [Provided](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbwFBzgYygUwIY0wQQGcBPAOzQBUALAV1IGsAaFdLXTAJUwBMa1MozVGgikAZsADmNLAGUY0TELhEylWg2UARYITC40VZgF84YqBBBwA5AAEsvAB4ArQgHoFEADb1gMa0igkLCILDSEmDp6BkZIpuaWNmxoMAC0DjSO1gDcgeDQ8FzYKYyhqOGYAMLYXl4ARsVMcWYWVtbJ-rlIIqSE8Ngk5NR09HAAvKw4eKpDGvQAFNYDasMM1qXz2FCShABciGYQEPt9UMCkksYAlOMAfHBbO1fdon1wGfxQ45PsXLyf8wQxg2dRowC83AENzG92QqFB4MhUAAdNhuNxqhFNoN1CNkWIaF4JLUeBtuFBsGIYNDYSxUOTKfAJkCWNc4s8em8+opvj0JNI5AosID3jw+AI4NcujBiGBMCowGAovoYIZvjK5RAxHBuVhkdxdCrDLlOfAKvhFcqYvt5jSFUrDTFvhUraqqNLZfKZriGJVRPzvnCdTB2AB+fYjUgQADupBYBuibvDcFdhhYmEcMApycjMbjqCwzkwKQAajUaJgcwwo7GWBEzjVgAAvHgAUSgFigFE9VfoNfzcDlpANFwAspgQ73+ywCUTwV4eOPJxHq3mWIXi3huEvsFO18YuhngvBTXBzTj8ClgKJvgAeChwDN4YeEFQ41b0W-YUjEUrf38PD+ty3JsV6iJUbBCvsFBXDCZToK88AJkaVDOhEFoOomhi2rkBYTjIpBnhE1S1A0aALHScCbNsexwAACls2AgBOAiEPetwANoAAwALpXPsdGtLomD3o+maYC+b4rHMt7nGIEocH+P5KcQ9yhnAHBwPspCYAAbgI9x3PBqB4TABFwMhMSgTA16kBBUzQNRTxXMidDRhSYC2pRwKURxllun+YF2ZB0A8coVy5AeSBIAS5A2TeAASliYLa8GnuBXjAORaEEBeQXYtJIwRSw674VAhG3qCMAKIRGVZfQYwIHV5HGLclSZeRt5uFVNW3HE0VAA)
      

Usually I'd probably avoid it though - writing

`const x = () => dispatch(myThunk()).unwrap()` is pretty straightforward and a lot more telling what is actually happening.

**Comment by zation** [comment]
Thanks for your great suggestion and improvement! Could you please have a look the one last question when I want to implement the `useAsyncActions` just like what [redux does](https://github.com/reduxjs/redux/blob/master/src/bindActionCreators.ts#L53)?

This is my current (implementation)[https://www.typescriptlang.org/play?ssl=48&ssc=1&pln=49&pc=1#code/JYWwDg9gTgLgBAbwFBzgYygUwIY0wQQGcBPAOzQBUALAV1IGsAaFdLXTAJUwBMa1MozVGgikAZsADmNLAGUY0TELhEylWg2YBfOGKgQQcAOQABLLwAeAK0IB6BRAA29YDCNJQkWIhY1CmABFgQjBcNCptXX1DIzY0GABacxoLIwBuD3BoeC5seMYfVD9MAGFsR0cAIzymX38AWUwQCEi9A2M4twykEVJCeGwScmo6ejgAXlYcPFVhjXoACiNBtRGGIwKF7ChJQgAuOGxSYgBKCYA+Q53CE57Rfrhk-igJqfYuXmeFhC1NyppgI5uAIzuNLshUP9AcCoAA6bDcbhlfxbIbqUawsQ0RwSCo8TbcKDYMQwUHglioQnE+CTH4sLS3Bl3PrwfqKV69CTSOQKLDfR48PgCOAM7owYhgTAqMBgIIhMJUV7iyUQMRwNlYWHcYKhGDhDK9B7FfAyuW68IHBZk6WynUK17FM0KsUSqUAcUwMC4MBkpB4AB4KJdJhQ4JgLHhSNxCCo0Wt6P7gOJhd7ffjDscCkdiJcAPxwVNQP3cOAHP0ANwEGWV7s98fwO0DwbgofDkejsdW8392YKSbEwvrOyzxzzLfmDckpbgFarSGZD0qSe4szQ+HiwFEr0DYYjmCjMdX8Z7mYzxBHOfOWw3ohKbF5BwoBW18r1VAOJttr-C1qQWx2BwejAQ6SE2JwHAACtEwSYP6QGFsWTbBpcL7mlQ14wJupB3tM0D-pIJwnLCdAAO5EmAVrdIa8DGmi66YVukw7m2+4dke3a9meF7nFeeQMdh97QI+1oQug9zwKh9qTMapp2m+lEsFgPpFnAxRlBU1RoIsFJwEuUarvRWEYVhOG4NAz5yT+yioAA2pJb5ZjeAm4VAAC6ygnBkWgupKcAQds2AgDGtIsDZ9CYMQBz9FASaSK5H5xhxp6cdm5xIN5841gWmCENiNKFHAYURVFMAxaQcWWtsuwHNm1pQQYMEnjm6XdOGXjwNRqn+AZTnBXA-oQbu7Yxv5RJBQUHBDaxMZcLljgwLxTmmby+x+eBBYXAVnX2eEDrdbJ37oZ5imer6XWYI0zQLDpVqbaJqDCOJApzTAByzXlrw-BkD0PWI0BwAsnXhcQcBJocS2CVANwFT9j0suD-HLf9kx8SZkOEEVxCud9sOoFgL2Y65rx6SudFOcZt6QxZh3HbjWg6Xjp0qfjeU46gvw6XZllUO5LDHRlSBYuQ-FwAAEgYmC3aJnW3o4wBaXtBBk-xqJdqMtNwCdymkP1-wwAoOuy-L9DjAgRtaVo5wlHLWn+rYesG2lWhAA]:

```ts
import {
  createAsyncThunk,
  createReducer,
  configureStore,
  AsyncThunk,
} from '@reduxjs/toolkit'
import {
  useDispatch,
} from 'react-redux';
import React, {
  useCallback,
  useMemo,
} from 'react';

const asyncThunk = createAsyncThunk('asyncThunk', (args: any) => args)
const reducer = createReducer({}, (builder) => {
  builder.addCase(asyncThunk.fulfilled, (draft) => {
    draft = {}
  })
})
const store = configureStore({ reducer });

type AppDispatch = typeof store.dispatch;
const useAppDispatch: () => AppDispatch = useDispatch;

type GetReturned<T> = T extends AsyncThunk<infer Returned, any, any> ? Returned : never;
type GetThunkArg<T> = T extends AsyncThunk<any, infer ThunkArg, any> ? ThunkArg : never;

const bindAsyncAction = <T extends AsyncThunk<any, any, any>>(actionCreator: T, dispatch: AppDispatch) => 
(arg: GetThunkArg<T>): Promise<GetReturned<T>> => dispatch(actionCreator(arg)).unwrap();

const useAsyncAction = <T extends AsyncThunk<any, any, any>>(actionCreator: T) => {
  const dispatch = useAppDispatch();
  return useCallback(
    bindAsyncAction(actionCreator, dispatch),
    [dispatch, actionCreator],
  );
};

type Params = {
  [key: string]: AsyncThunk<any, any, any>
};

type Result = {
  [key: string]: (args: any) => Promise<any>
};

export const useAsyncActions = <P extends Params, R extends Result>(actionCreators: P): R => {
  const dispatch = useAppDispatch();
  return useMemo(
    () => {
      const result: Result = {};
      for (const key in actionCreators) {
        const actionCreator = actionCreators[key];
        result[key] = bindAsyncAction(actionCreator, dispatch);
      }
      return result;
    },
    [dispatch],
  );
};

function Home() {
  const onClick = useAsyncAction(asyncThunk);
  
  return <button onClick={onClick}>Click</button>
}
```

But I got type error:
<img width="704" alt="image" src="https://user-images.githubusercontent.com/1049425/188494926-16a2dd77-6bff-474a-baca-cbdf3c886bab.png">

I wandering how redux can pass the type check but I got the error? Is there a way to make the similar implementation?

Thanks again!

**Comment by phryneas** [comment]
You are working with yet-to-be-resolved generics in TS at that point - everything there are placeholders to be filled in on usage.
At some point you will have to cast a few things.

That said, your code is not possibly inferrable - how would TS ever find out what R is based on P? Those are completely decoupled. See my example where I derived the output type from the input type on the type level. TS can't analyze that for you.

**Comment by zation** [comment]
I tried Object.entities and upgrade the ts version, target to resolve the problem. Here is the [code](https://www.typescriptlang.org/play?target=6&ts=4.8.0-beta#code/JYWwDg9gTgLgBAbwFBzgYygUwIY0wQQGcBPAOzQBUALAV1IGsAaFdLXTAJUwBMa1MozVGgikAZsADmNLAGUY0TELhEylWg2YBfOGKgQQcAOQABLLwAeAK0IB6BRAA29YDCNJQkWIhY1CmABFgQjBcNCptXX1DIzY0GABacxoLIwBuD3BoeC5seMYfVD9MAGFsR0cAIzymX38AWUwQCEi9A2M4twykEVJCeGwScmo6ejgAXlYcPFVhjXoACiNBtRGGIwKF7ChJQgAuOGxSYgBKCYA+Q53CE57RfsOh9VGKAHcICan2WeeGJZW5i93hs4FtrgdSDQQJUBGdxpdtrtbr0Hsl+FBPhhppweHwBAsEFpNpUaMBHNxYRdCnASWSKVAAHTYbjcMr+LZPNb0BliGiOCQVHibbhQbBiGBwy7IVCoEVi+CTQksLS3FV3PrwfqKTGiCTSOQKLAEuBogRwFXdGDEMCYFRgMBBEJhKifK02iBiOBarAM7jBUIwcIZFHwYr4e2OgPhA4LSV2h3+52fYqR52W622gDimBgXBgMlIPAAPBRLpMKHBMBY8KRuIQVJz5kXgOIzXmC0LDscCkdiJcAPxwdtQQvcOAQzAANwEGTdWZzXPwOxLZbgFarNbrDdWTd7BRbYjNi52PeOA7X8yXknHcEL06g3RDNJb3B++HiwFEnxLlermFr9Y-FyRZ7l2xCnn25xbB+oglGwhoHBQBR+k6gZUAc4YJqh4RxgsLCIgc2YwMekgrswJwHAACtEwSYEWRHDqOK5lpcKFRlQ0EwJ+pBwdM0BgpIJwnAydCvKKYCxt0VZePAT5hk875cV+kw-hu-5bkBu7dmBEHnFBeRKTx8HQIhcbSug9zwGxSaTGGEaJmhkksFg+YjnAxRlBU1RoIsLCoJUL5vjBpCcdxvG4NAyEOThyioAA2tZaEALrKCcGRaOmNpwJR2zYCA9aKiwcX0JgxAHP0UAtpISUYY2owgdpoG9ucSAZUgSBzkOmCEHyMBFpRv6bvWOWivlq7mXFADScAtnAJXEB62U1aCiL7HAREkf1U1JeccbUQYtH0TmjHFpR216a1UkWDJFkau5-hBYZBVwP1g3qcNuX5QUHBvQBXU9Y4fWUXpoWwcZUBrZRFFDlS5lPol4TJg99nYRxaXOTmBb3ZgjTNHhMqgmZfkyk+2yisQnwAPKVFYmDxAy-4wJV3Wg0ZfEQ8JIDYBJxMEwsxWlT2dUMElcYC+Bz61o93EcjuoxRajJwpbzcDowTqAuVj1O0-TbQgAAoqQTPACzZPYKcGQE0SxMJdFVDK6g6NtUgvLkIZcAABIGJgsbUk+sGOMAPlIwQCnBbLgIMGrt0POZqCiEoxMwO8yg6LZD1h09BLEwnBwAr8tQE8nEB58L9BvC0yrRxjrmkC9JIwAodcB0H9DjAgLc+Vo5wlIHPlFrYDdNy1WhAA) if anyone want to refer:
```ts
import {
  createAsyncThunk,
  createReducer,
  configureStore,
  AsyncThunk,
} from '@reduxjs/toolkit'
import {
  useDispatch,
} from 'react-redux';
import React, {
  useCallback,
  useMemo,
} from 'react';

const asyncThunk = createAsyncThunk('asyncThunk', (args: any) => args)
const asyncThunkTwo = createAsyncThunk('asyncThunkTwo', (args: number) => args)
const reducer = createReducer({}, (builder) => {
  builder.addCase(asyncThunk.fulfilled, (draft) => {
    draft = {}
  })
})
const store = configureStore({ reducer });

type AppDispatch = typeof store.dispatch;
const useAppDispatch: () => AppDispatch = useDispatch;

type GetReturned<T> = T extends AsyncThunk<infer Returned, any, any> ? Returned : never;
type GetThunkArg<T> = T extends AsyncThunk<any, infer ThunkArg, any> ? ThunkArg : never;

const bindAsyncAction = <T extends AsyncThunk<any, any, any>>(actionCreator: T, dispatch: AppDispatch) => (
  arg: GetThunkArg<T>,
): Promise<GetReturned<T>> => dispatch(actionCreator(arg)).unwrap();

export const useAsyncAction = <T extends AsyncThunk<any, any, any>>(actionCreator: T) => {
  const dispatch = useAppDispatch();
  return useCallback(
    bindAsyncAction(actionCreator, dispatch),
    [dispatch],
  );
};

type Params = {
  [key: string]: AsyncThunk<any, any, any>
};

type Result<P extends Params> = {
  [K in keyof P]: (args: GetThunkArg<P[K]>) => Promise<GetReturned<P[K]>>
};

export const useAsyncActions = <P extends Params, R extends Result<P>>(actionCreators: P): R => {
  const dispatch = useAppDispatch();
  return useMemo(
    () => {
      const array = Object.entries(actionCreators).map(
        ([key, asyncThunk]) => [key, bindAsyncAction(asyncThunk, dispatch)],
      );
      return Object.fromEntries(array);
    },
    [dispatch],
  );
};

function Home() {
  const onClick = useAsyncAction(asyncThunk);
  const {
    one,
    two,
  } = useAsyncActions({
    one: asyncThunk,
    two: asyncThunkTwo,
  });
  
  return <button onClick={onClick}>Click</button>
}
```
The function `one` and `two` can infer it's original args.

**Comment by phryneas** [comment]
You don't need that `R` generic.

```ts
export const useAsyncActions = <P extends Params>(actionCreators: P): Result<P> => {
```
