### ISSUE TITLE
shallowEqual breaks typed selector return type

### ISSUE THREAD

**Issue by justgowa** [reduxjs/react-redux#1964]
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

- React: 18.2.0
- ReactDOM/React Native: 18.2.0
- Redux: 4.2.0
- React Redux: 8.0.4

### What is the current behavior?

without `shallowEqual` type inferred correctly
![image](https://user-images.githubusercontent.com/46902316/197757651-d79e172f-d1aa-4037-930d-d0be034adca2.png)

otherwise it breaks
![image](https://user-images.githubusercontent.com/46902316/197758105-466f37c8-6a68-4032-9c44-bbaf46ef5db2.png)

### What is the expected behavior?

types infer correctly with `shallowEqual`

### Did this work in previous versions of React Redux?

- [ ] Yes

**Comment by justgowa** [comment]
#1348 found related issue

**Comment by phryneas** [comment]
Could you try installing the CodeSandbox preview build from https://github.com/reduxjs/react-redux/pull/1965 and see if that fixes it for you?

**Comment by justgowa** [comment]
Unfortunally no but `useSelector` still has same type
![image](https://user-images.githubusercontent.com/46902316/197856222-a39aac6f-a34b-433b-b4a6-db62dbfa1689.png)

**Comment by phryneas** [comment]
Ah, very good catch, that one needs it too!

**Comment by justgowa** [comment]
Yes

**Comment by justgowa** [comment]
@phryneas  will you release these changes?

**Comment by phryneas** [comment]
We'll need a few type tests for that before @markerikson pulls the lever on that - I'll try to get to that in the next few days. Meanwhile, that CI build should work nicely I hope?

**Comment by markerikson** [comment]
Hmm. Fwiw I just tried setting up a typetest based on this and #1348 , and it seems to be working correctly _without_ `NoInfer`.

@justgowa by any chance do you have any of TS's "strict" settings turned off?

I'm okay with shipping the change because I don't think it will _hurt_, but after a quick try I can't repro the original issue.

**Comment by markerikson** [comment]
Fixed by #1965 .

**Comment by justgowa** [comment]
@markerikson  yep, ts strict is off

**Comment by phryneas** [comment]
@justgowa we cannot make any guarantees for any TypeScript configuration other than `strict: true`. We already support the last 5 TypeScript releases.  
With all the flags that could be enabled or disabled on top of that, there would be tens of thousands of configuration combinations we have to check.  
Also: TypeScript is meant to be used with `strict`. The fact that you can turn that off is pretty much a backwards compatibility stunt or for during a migration to TS, but you should always aim for enabling `strict`.

**Comment by justgowa** [comment]
@phryneas  i get it, i'm working on pretty old project and unfortunatly it started with non strict rules.
Anyway, thank you a lot!
