### ISSUE TITLE
Error: Unable to resolve module react-redux

### ISSUE THREAD

**Issue by marceloch2** [reduxjs/react-redux#1972]
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

- React: 18.2.0
- React Native: 0.70.5
- Redux: 4.2.0
- React Redux: 8.0.5

### What is the current behavior?

Unable to run a React Native app, IOS version with Hermes and Fabric enabled.
react-redux could not be found within the project or in these directories: node_modules.

I've already deleted node_modules, Pods, watchman watch-del-all, arch -x86_64 pod install, but nothing seems to make it to work, unfortunately.

### What is the expected behavior?

Be able to run with Hermes and Fabric enabled.

### Which browser and OS are affected by this issue?

Mac Apple M1 chip - OSX 13.0 Ventura

### Did this work in previous versions of React Redux?

- [X] Yes

**Comment by markerikson** [comment]
Unfortunately this sounds like an issue with your package manager, and there's nothing we can do about that on our end.  We know the `react-redux` package itself works correctly in multiple environments.

**Comment by Jeffrey-Hull** [comment]
Please clone last data. JSON.parse(JSON.stringify(data));
