### ISSUE TITLE
createSelectorHook at 8 version miss the generic type conversion, all states are unknown

### ISSUE THREAD

**Issue by AuthorProxy** [reduxjs/react-redux#1973]
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

- React: "^17.0.2",
- ReactDOM/React Native: "^17.0.2",
- Redux: "@reduxjs/toolkit": "^1.9.0",
- React Redux: "^8.0.5",

### What is the current behavior?

After upgrading from "react-redux": "^7.2.5" I cannot use anymore this code: `createSelectorHook<T>();`

My current not working code:
```
import { createSelectorHook, useDispatch, shallowEqual } from "react-redux";

import type { RootState, RootDispatch } from "@ds/store/bootstrap";

export const useRootDispatch = () => useDispatch<RootDispatch>();
export const useRootSelector = createSelectorHook();
```

Now all states in selectors are unknown

### What is the expected behavior?

Plz return how it was before:
```
import { createSelectorHook, useDispatch, shallowEqual } from "react-redux";

import type { RootState, RootDispatch } from "@ds/store/bootstrap";

export const useRootDispatch = () => useDispatch<RootDispatch>();
export const useRootSelector = createSelectorHook<RootState>();
```

### Did this work in previous versions of React Redux?

- [X] Yes

**Comment by phryneas** [comment]
Generally, you should not be using `createSelectorHook` for this - that was an external suggestion that made it into the types but was never approved by one of the core maintainers. 

Please go by the [documented approach](https://redux-toolkit.js.org/tutorials/typescript#define-typed-hooks)

```ts


// Use throughout your app instead of plain `useDispatch` and `useSelector`
export const useAppDispatch: () => AppDispatch = useDispatch
export const useAppSelector: TypedUseSelectorHook<RootState> = useSelector
```
