### ISSUE TITLE
react-redux Provider error

### ISSUE THREAD

**Issue by ShatadalDas** [reduxjs/react-redux#1979]
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

- React: 18.2.0
- ReactDOM/React Native: 18.2.0
- Redux: using redux toolkit
- React Redux: 8.0.5
- @reduxjs/toolkit: 1.9.1

### What is the current behavior?

I'm using Next.js, Redux-toolkits, React-redux all are in the latest versions.

After importing Provider from react-redux
`import { Provider } from "react-redux";`

it gives this error in my VS Code terminal (I'm using SSR)-
```
error - C:\Users\Shatadal Das\Desktop\My All Program Files\NEXT\my-blog-website\node_modules\react-redux\es\exports.js:1
import Provider from './components/Provider';
^^^^^^

SyntaxError: Cannot use import statement outside a module
```
I've the default tsconfig file, generated by `create-next-app`

### What is the expected behavior?

Didn't expected any like that to happen.

### Did this work in previous versions of React Redux?

- [ ] Yes

**Comment by markerikson** [comment]
This appears to be some kind of an issue with Next and its build/import configuration somehow.  I don't know _why_ it would be having a problem, but we know that the current published package  configuration works correctly.  So, I'd recommend filing an issue with the Next repo.
