### ISSUE TITLE
[TypeError] Object is not a constructor

### ISSUE THREAD

**Issue by saulojoab** [reduxjs/react-redux#1980]
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

- React: 18.0.0
- ReactDOM/React Native: ^0.70.1
- Redux-Toolkit: ^1.9.1
- React Redux: ^8.0.5

### What is the current behavior?

Whenever I create my store on the App entry point, I get this error: 
```
Error loading story index:
[TypeError] Object is not a constructor
``` 
![image](https://user-images.githubusercontent.com/37988252/210213507-04005138-6f0f-4123-90ed-e688697a42f8.png)

This error does not spawn a Logbox with errors, but it breaks some of my app's libraries. As an example, Apollo requests always return undefined, and `react-native-image-crop-picker` does not work correctly.

This is my entry point stack: 
![image](https://user-images.githubusercontent.com/37988252/210213275-be2ae039-f463-41b8-ba9b-20b0b74ba9f3.png)

I think its probably something to do with a library conflict or something, but it's making my head burn trying to solve it. I've tried everything: moving the provider location, adding it onto the index.js file, with no success.

This is my store configuration: 
![image](https://user-images.githubusercontent.com/37988252/210213715-98ccc55b-7e86-4e84-b69b-14720465b69a.png)

This is one of my reducers:
![image](https://user-images.githubusercontent.com/37988252/210213774-23529116-98c9-401f-89eb-227c79786271.png)

### What is the expected behavior?

Everything should work without breaking the app.

### Which browser and OS are affected by this issue?

Android - API Level 33

### Did this work in previous versions of React Redux?

- [ ] Yes

**Comment by phryneas** [comment]
Maybe wrap a

```js
try {
  //...
} catch (e) {
  console.log(e.toString(), e.stack.toString());
}
```
around it. With the given information it's pretty impossible to say anything.

**Comment by saulojoab** [comment]
@phryneas where should I put the try-catch? 

That's what confused me the most, since the error doesn't show where the root cause is, not on the Logbox, RN dev tools and Flipper.

**Comment by phryneas** [comment]
Around the place that you assume causes the error. If you say it happens when creating the store, wrap it around `configureStore`.

**Comment by saulojoab** [comment]
@phryneas I did this, and it didn't throw any errors:
![image](https://user-images.githubusercontent.com/37988252/210216548-ec1e084a-a237-4303-8f19-cf8f938d050e.png)

It's very hard to find the cause since the error does not specify where it comes from. Maybe it is something with redux-toolkit?

**Comment by timdorr** [comment]
This doesn't appear to be a bug with Redux or RTK. 

Like Lenz said, you can do that wrapping to track down the source of the error. The storybook one is probably a good place to start. Go into your node_modules folder and find [this code](https://github.com/storybookjs/storybook/blob/d531341c9ac015b2143b72baab6ccccf55480302/code/lib/preview-api/src/modules/preview-web/Preview.tsx#L155) (after transpilation) to add the more descriptive error handling there (particularly `e.stack`).

**Comment by saulojoab** [comment]
just in case anyone stumbles upon this: it was Storybook.

I don't know why it breaks, but removing the Storybook imports solved the problem. Really weird.
