### ISSUE TITLE
Could not find "store" in either the context or props of "Connect(i)". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(i)".

### ISSUE THREAD

**Issue by saisandeep1** [reduxjs/react-redux#1982]
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

- React: 17.0.2
- ReactDOM/React Native: 17.0.2
- Redux: 4.1.0
- React Redux: 7.2.4

### What is the current behavior?

We have a large react project with different functionalities. We are using redux to maintain the state across the whole project. But as we kept adding new functionalities, it became very complex to manage the project. So, we moved each functionality to a separate library module and added the library module inside the root project. 

It works fine for the react-redux with version: 5.0.7 and redux with version: 3.7.2. But when I upgraded the react-redux to 7.2.4 and redux to 4.1.0, I am unable to access the store inside the library module.

Below is the error I got when accessing the store inside the library module.

`Could not find "store" in either the context or props of "Connect(i)". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(i)".`

To reproduce the error, I have created a simple TODO application in stackblitz. Here is the URL: [https://stackblitz.com/edit/node-brmydx?file=README.md.](https://stackblitz.com/edit/node-brmydx?file=README.md.) this project, I have created a module called component-library, published it, and used it in the root project. And I have moved the component named FilterLink, which uses redux state and used it in the footer component in the components package in the root folder.

### What is the expected behavior?

To be able to use the store inside the library.

### Did this work in previous versions of React Redux?

- [X] Yes

**Comment by phryneas** [comment]
Those will probably end up with two different copies of the same version (or different versions) or `react-redux`. Your library should have `react-redux` as a `peerDependency`, not a `dependency` to prevent that.

**Comment by markerikson** [comment]
Yep. This is a common issue with modern React Context.  Each context instance is effectively a singleton, so if you have multiple copies of React (or React-Redux) in the final bundle, those are separate context instances and React will not be able to link them together correctly at runtime.
