### ISSUE TITLE
Clean up documentation

### ISSUE THREAD

**Issue by samilieberman** [reduxjs/react-redux#1986]
### What is the new or updated feature that you are suggesting?

In some of the documentation markdown files, there is markdown that is not getting rendered properly. For example, in the [hooks](https://github.com/reduxjs/react-redux/blob/master/docs/api/hooks.md) documentation, `:::tip` and `:::info` are not getting rendered properly.

### Why should this feature be included?

It is important to maintain technical documentation and make sure it is as clear, understandable, and readable as possible for the users.

### What docs changes are needed to explain this?

This change is a doc change only. I can work on it if this gets approved as a valid issue!

**Comment by phryneas** [comment]
That's the source code of the docs. The real docs are over at https://react-redux.js.org/api/hooks

**Comment by samilieberman** [comment]
> That's the source code of the docs. The real docs are over at https://react-redux.js.org/api/hooks

Thank you! Makes sense and closed the issue.

**Comment by markerikson** [comment]
Appreciate you trying to notify us!

(btw, out of curiosity: how did you end up browsing those Markdown files to start with, rather than looking at the published docs site? Just wondering if there's something we can do to make the link to the docs site more obvious)

**Comment by samilieberman** [comment]
@markerikson The [Higher-Order Components React documentation](https://reactjs.org/docs/higher-order-components.html) links to the [connect documentation here](https://github.com/reduxjs/react-redux/blob/master/docs/api/connect.md#connect), which should be updated to point to the docs site instead. 

I didn't realize the `connect.md` was for the docusaurus site, assumed that was coming from another markdown repository and not within the main codebase itself

**Comment by markerikson** [comment]
Huh, yeah, had no idea the React docs linked there!

That's presumably been there for a _looooong_ time :)  Once upon a time, the React-Redux docs _were_ just "the Markdown files in the repo". But we set up an actual published docs site in... 2018? 2019?

I know the new React beta docs are almost ready to become the real docs site, and that the beta docs don't talk about Higher Order Components. But we ought to file a PR against the existing React docs repo to go update that link anyway.

**Comment by samilieberman** [comment]
@markerikson if you can help by pointing me in the direction of where the React docs live, i would love to make the change!

**Comment by markerikson** [comment]
@samilieberman Sure, I can even do a quick search and point you to the exact file :)

It'd be here:

https://github.com/reactjs/reactjs.org/blob/b0ccb47f33e52315b0ec65edb9a49dc4910dd99c/content/docs/higher-order-components.md?plain=1#L17

Appreciate you helping out with that!

(Also: not sure if you actually have any intent to learn Redux atm or were just browsing the React docs, but: we Redux maintainers hang out in the `#redux` channel in the Reactiflux Discord ( https://www.reactiflux.com ) and are happy to answer questions, and Reactiflux in general is a great place to chat and get help with React.)

**Comment by samilieberman** [comment]
@markerikson Thank you! I will make the change shortly.

and thank you for sharing! That sounds awesome, I will definitely take a look.

**Comment by samilieberman** [comment]
@markerikson here is the [PR](https://github.com/reactjs/reactjs.org/pull/5624) for reference. I am just waiting on approvals
