### ISSUE TITLE
forwardRef  wrapped by connect will cause white screen in IE browser

### ISSUE THREAD

**Issue by longxin-vico** [reduxjs/react-redux#1987]
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

- React: 
- ReactDOM/React Native: 
- Redux:
- React Redux:

### What is the current behavior?

connect(forwardRef((props, ref)=>)(Component) will cause white screen in IE browser, however there is ok in chrome and edge

### What is the expected behavior?

expect to be ok IE browser same as chrome and edge

### Which browser and OS are affected by this issue?

IE11

### Did this work in previous versions of React Redux?

- [ ] Yes

**Comment by timdorr** [comment]
We don't support IE at all anymore. That is an outdated and unsupported browser that Microsoft has completely discontinued.
