### ISSUE TITLE
v8.x re-render lazy component if dispatch was made during it

### ISSUE THREAD

**Issue by MikeYermolayev** [reduxjs/react-redux#1988]
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

- React: 18.2.0
- ReactDOM/React Native: 18.2.0
- Redux: 4.2.1
- React Redux: 8.0.5

### What is the current behavior?

So I was migrating our codebase from react-redux 7.x to react-redux 8.x when I faced the issue. We have some legacy components which use Classes and/or redux-form. In our case the issue led to infinite render loop, the behavior was pretty much the same as when you accidentally put `setState()` inside render;

We have a component like this:
```
class ObjectEditor() {
 constructor(props) {
   super(props);
   
   props.dispatch(initObjectEditor({id: props.id}))
 }
}
```
where `props.id` is generated by `useId()` in the upper component.

So code like this worked well on react-redux 7.x but began to cause infinite loop after upgrading to 8.x

Here is a small re-pro sandbox https://codesandbox.io/s/sweet-franklin-8uujc3?file=/src/Counter.js . While it doesn't cause infinite loop you can observe in logs that it renders two different Counter components with different 'id' props. 
If you change react-redux to 7.x the issue is completely gone.

### What is the expected behavior?

I'm not sure which behaviour is correct one but the fact that it has changed took 1.5 working days of mine to fully identify the problem.

Would be awesome if react-redux could print some warning to console in such case because it's very hard to find the reason of bailed-out renders

### Did this work in previous versions of React Redux?

- [X] Yes

**Comment by markerikson** [comment]
At first glance, I'm not sure if there's anything we can _do_ about this.

React-Redux v8 uses React's new `useSyncExternalStore` hook.  Part of the point of that hook is that React is now responsible for managing the re-renders when the external store (such as Redux) updates.  As I understand it, that can include throwing away an in-progress render if an external update happens in the middle.

Generally, dispatching in a class component constructor is not a good idea to begin with, so I'm not surprised that's causing an issue here.

**Comment by MikeYermolayev** [comment]
> Generally, dispatching in a class component constructor is not a good idea to begin with, so I'm not surprised that's causing an issue here.

Yeah, agree with that. Just was a little bit surprised when some legacy components went to infinite loop after update. Also we have some of them using redux-form and it was causing infinite render too (as I can see they make dispatches in `componentWillReceiveProps`)

One last question from me:

Is it ok now to do something like this inside render?:

```
const Component = () => {
  const dispatch = useDispatch();
  const isInitialised = useSelector(getIsInitialised);

  if (!isInitialised) {
    dispatch(initStore);
  }
}
```

As I remember there was an error in console previously when you tried to do dispatch outside an effect

**Comment by markerikson** [comment]
No, definitely not.  You _should not_ trigger updates while rendering.

**Comment by MikeYermolayev** [comment]
Thank you for clarifications!
