### ISSUE TITLE
Cannot read properties of undefined (reading 'useSyncExternalStoreWithSelector')

### ISSUE THREAD

**Issue by esraahusamia** [reduxjs/react-redux#1995]
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

- React: 
- React Redux:

### What is the current behavior?

hello ,i created npm package with react , react-redux and redux-toolkit , and i'm trying to bundle this app using rollup with umd format , to use it as cdn , when i'm trying to use the cdn it gave me this error 

**`Cannot read properties of undefined (reading 'useSyncExternalStoreWithSelector')`**

note ** it's working fine locally 

![image](https://user-images.githubusercontent.com/30745980/230882255-88204dd3-880e-4826-ba3b-aebbc4db546d.png)

### What is the expected behavior?

use bundled react app with react redux and redux toolkit with format umd without errors 

### Which browser and OS are affected by this issue?

chrome , windows 10

### Did this work in previous versions of React Redux?

- no

**Comment by phryneas** [comment]
That's a React-internal error - probably a problem with your bundling setup or you are running with an old, or multiple, versions of React.
