### ISSUE TITLE
Why is useDispath not promise?

### ISSUE THREAD

**Issue by yakiler** [reduxjs/react-redux#2012]
### What is the new or updated feature that you are suggesting?

"After a component state update, it is common to trigger another state update. Initially, people used to use firstUpdateState(); secondUpdateState() to achieve this. However, with the introduction of React, we have to use useEffect to handle the second state update caused by the first one. Having a lot of useEffect calls scatters the component logic across different places, rather than decoupling it.

In Redux, we use dispatch to notify state changes, but even after one state change, we still need to use useEffect to handle other states. This is not aesthetically pleasing. People have spent a lot of time perfecting Promises to solve callback hell and maintain the coherence of logic. However, useEffect disrupts this beauty. Even though Redux can use asynchronous middleware to handle multiple state updates, the code structure becomes complex. So why not set dispatch to a promise mode from the beginning? Specifying that one state update triggers the synchronous behavior of other states is very common."

### Why should this feature be included?

Just a doubt

### What docs changes are needed to explain this?

I‘m not sure

**Comment by markerikson** [comment]
I'm not sure what the actual suggestion is here.  This feels like a general misunderstanding of how both React and Redux work.
