### ISSUE TITLE
`v8.0.6` cannot be installed due to peer dependency issue

### ISSUE THREAD

**Issue by xsjcTony** [reduxjs/react-redux#2018]
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

- React: 18.2.0
- ReactDOM: 18.2.0
- Redux: 4.2.1
- React Redux: 8.0.5 (8.0.6 not able to install)

### What is the current behavior?

npm WARN Could not resolve dependency:
npm WARN peerOptional @reduxjs/toolkit@"^5.0.0-beta.0" from react-redux@8.0.6
npm WARN node_modules/react-redux
npm WARN   react-redux@"^8.0.6" from the root project
npm WARN   1 more (@reduxjs/toolkit)
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-redux@8.0.6
npm WARN Found: @reduxjs/toolkit@1.9.5
npm WARN node_modules/@reduxjs/toolkit
npm WARN   @reduxjs/toolkit@"^1.9.5" from the root project

---

npm ERR! notarget No matching version found for @reduxjs/toolkit@^5.0.0-beta.0.

### What is the expected behavior?

Should be able to run `npm install`

---

It's definitely a typo that it should be `v2.0.0-beta.0` instead of `v5.0.0-beta.0` (THIS IS CRITICAL TO FIX)

But I think it should allow `v1.9.5` as well at this stage, since it doesn't make sense to force a beta version here

### Which browser and OS are affected by this issue?

Irrelavent

### Did this work in previous versions of React Redux?

- [X] Yes

**Comment by xsjcTony** [comment]
![image](https://github.com/reduxjs/react-redux/assets/45784210/632f9fd8-5a97-487d-ba69-68a87bc7b44d)

**Comment by markerikson** [comment]
Whoops, yep, I'm an idiot :)  Fixing!

**Comment by markerikson** [comment]
okay, v8.0.7 is out - please let me know if that fixes the issue!

**Comment by xsjcTony** [comment]
Everything works well now. Thanks!

**Comment by markerikson** [comment]
Yep, thanks for reporting, and sorry about that!  (my fault - publishing a whole bunch of package beta versions today, while sitting in an airport waiting for a delayed flight, and simply wrote that wrong!)
