### ISSUE TITLE
setub babel with pnpm

### ISSUE THREAD

**Issue by abderrahmane-arache-nw** [reduxjs/react-redux#2032]
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

i cloned this repository , hoping to bundle my custom react library using this babel config, 
the difference is that iam using pnpm and am getting this error

```bash
Error: Cannot find package '@babel/plugin-proposal-private-methods' imported from C:\Users\ssss\tests\react-redux\babel-virtual-resolve-base.js
``` 

### What is the current behavior?

-

### What is the expected behavior?

-

### Did this work in previous versions of React Redux?

- [ ] Yes

**Comment by markerikson** [comment]
I'm confused what you're trying to do. What "custom React library"?  Why are you cloning the React-Redux library?  Why are you trying to use PNPM?

FWIW we specifically use `yarn` v3 to install packages for this repo.
