### ISSUE TITLE
A documented utility to access store in plain js functions in React

### ISSUE THREAD

**Issue by tapansharma** [reduxjs/react-redux#2036]
### What is the new or updated feature that you are suggesting?

We should have a utility where we can connect to provider store in plain js functions instead of need to directly import the store in plain js files in a react app. I understand this will not bring rerenders and that totally fine. 

Example would be, I have an axios file where I need to read token from store. Passing token/ store from useStore hook everywhere is troublesome. Only way I am left with is importing store directly which does not seems right

### Why should this feature be included?

Currently if we need to get some value from store, we need to import store and then use getState method is not right. Using useStore is not possible everywhere.

### What docs changes are needed to explain this?

In section how to connect to store, this new feature should be added as below
To connect to provider store directly in plain js use [new] utility.

**Comment by EskiMojo14** [comment]
Functions that need access to dispatch or getState should usually be [thunks](https://redux.js.org/usage/writing-logic-thunks).

**Comment by markerikson** [comment]
Already covered here:

- https://redux.js.org/faq/code-structure#how-can-i-use-the-redux-store-in-non-component-files
