### ISSUE TITLE
Error: (0 , _useIsomorphicLayoutEffect.useIsomorphicLayoutEffect) is not a function

### ISSUE THREAD

**Issue by xybl3** [reduxjs/react-redux#2046]
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

- React: 18.2.0
- ReactDOM/React Native: ReactDOM 18.2.0
- Redux:4.2.1
- React Redux: 8.1.1

### What is the current behavior?

I am trying to dispatch interface 
```ts
export interface AccountDiscord {
  accent_color: string | null;
  avatar: string | null;
  avatar_decoration: string | null;
  banner: string | null;
  banner_color: string | null;
  discriminator: string;
  email: string | null;
  flags: number | null;
  global_name: string | null;
  id: string;
  locale: string;
  mfa_enabled: boolean;
  premium_type: number;
  public_flags: number | null;
  username: string;
  verified: boolean;
}
```

and it throws me an error
Unhandled Runtime Error
Error: (0 , _useIsomorphicLayoutEffect.useIsomorphicLayoutEffect) is not a function

### What is the expected behavior?

It should dispatch that object to state and render normal react view

### Did this work in previous versions of React Redux?

- [X] Yes

**Comment by markerikson** [comment]
Where and how are you trying to use React-Redux?  Is this by any chance inside of the new Next.js 13 `app` directory?

**Comment by xybl3** [comment]
Yes, thats correct

**Comment by markerikson** [comment]
@xybl3 @phryneas knows more about this than I do, but in general you can't use anything with React hooks directly inside of a server component.  You'll need to change the `<Provider>` or `useSelector` usages into client components.

**Comment by phryneas** [comment]
Yeah, generally my first question would be if you are in a client component.

**Comment by xybl3** [comment]
My bad, I did it and it worked. Thanks for help.
