### ISSUE TITLE
The version >8.1.0 doesn't work in browsers that don't support Proxy

### ISSUE THREAD

**Issue by git-decadent** [reduxjs/react-redux#2048]
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

- React: 18.2.0
- ReactDOM: 18.2.0
- Redux: 4.2.1
- React Redux: 8.1.0

### What is the current behavior?

An update of the React Redux to version 8.1.0 made the usage of the package impossible on TVs that uses web view applications. LG (WebOS) and Samsung (Tizen) older than 2018 model years:

Tizen 2017: Chromium 47
WebOS 2017: Chromium 38

[Proxy()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) support was added to Chromium in version 49.

The code throws the following Error:
`Uncaught ReferenceError: Proxy is not defined`
 in this part of the code:

```
var ReactReduxContext = /*#__PURE__*/new Proxy({}, /*#__PURE__*/new Proxy({}, {
  get: function get(_, handler) {
    var target = getContext(); // @ts-ignore

    return function (_target) {
      for (var _len = arguments.length, args = new Array(_len > 1 ? _len - 1 : 0), _key = 1; _key < _len; _key++) {
        args[_key - 1] = arguments[_key];
      }
      return Reflect[handler].apply(Reflect, [target].concat(args));
    };
  }
}));
``` 

### What is the expected behavior?

React Redux can be used in older browsers without issues.

Probably [ProxyPolyfill](https://github.com/GoogleChrome/proxy-polyfill) can be used? 

### Which browser and OS are affected by this issue?

>Chromium 49. WebOS, Tizen

### Did this work in previous versions of React Redux?

- [X] Yes

**Comment by EskiMojo14** [comment]
according to [caniuse](https://caniuse.com/proxy), Proxy has been supported in all major browsers since 2016. If you want to support 9+ year old browsers, then you can include a polyfill in your build as you've linked there. 

ultimately I don't think it's within the scope of the library to include a polyfill for Proxy.

**Comment by markerikson** [comment]
Yep. We modernized the JS output as of 8.0, and we aren't going to include polyfills for things that have been in the standard library for years.  That's up to app teams to handle themselves based on their own deployment targets.
