### ISSUE TITLE
TypeError: (0 , _useIsomorphicLayoutEffect.useIsomorphicLayoutEffect) is not a function

### ISSUE THREAD

**Issue by sundaram2021** [reduxjs/react-redux#2049]
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

- React:  18.2.0
- ReactDOM/React Native:  18.2.0
- Redux:  4.2.1
- React Redux:  8.1.0

### What is the current behavior?

 error node_modules\react-redux\lib\components\Provider.js (37:60) @ Provider
- error TypeError: (0 , _useIsomorphicLayoutEffect.useIsomorphicLayoutEffect) is not a function
    at stringify (<anonymous>)
null

not able to run my next.js app (13.4.6)

### What is the expected behavior?

should run without error 

### Which browser and OS are affected by this issue?

Windows 11

### Did this work in previous versions of React Redux?

- [ ] Yes

**Comment by markerikson** [comment]
We can't do anything just based on a single error message. Please provide a CodeSandbox or a Replay ( https://replay.io/record-bugs ) that shows this error happening.

**Comment by sundaram2021** [comment]
this is the repo [https://github.com/sundaram2021/ecommerce-next](url)

just fork and run it using `npm run dev` and you will get the exact same error

**Comment by markerikson** [comment]
Most likely you're trying to use React-Redux in an app directory layout file that's getting SSRed.  The hooks like `useEffect` only exist in client components / layouts.

**Comment by markerikson** [comment]
Also see the guidance here:

- https://nextjs.org/docs/getting-started/react-essentials#rendering-third-party-context-providers-in-server-components

**Comment by sundaram2021** [comment]
yes I got the point , I just moved out the redux provider in another file and I made that file a client component
and then in wrap up the Layout with this new Provider

and it works fine

**Comment by IyadSaadeh** [comment]
> For me, what fixed this error (using next "13.4.19" and react-redux "8.1.2"): I needed to add
> 
> ```
> "use client" 
> ```
> 
> to the top of my page which had the `<Provider store={store}>`

Yes This is aa best soultion

**Comment by Iamhazard** [comment]
In next 13 ,create new Provider components   and exports as "export function Providers({ children }) {
  return <Provider store={store}>{children}</Provider>; using  "use client"  and import it to App component ..this will works

}:

**Comment by BismarkCodes** [comment]
This worked for me.
Follow this link on how to manage states in nextjs "server" modes app, especially third-party providers like redux etc:
https://vercel.com/guides/react-context-state-management-nextjs#rendering-third-party-context-providers-in-server-components

Steps to fix error:

1. Create a providers.tsx file in your `src/app` folder
2. Inside your providers.tsx file, Import all your providers here eg. for redux you can do
`     "use client";
        import store from "@/redux/store";
        import React, { PropsWithChildren } from "react";
        import { Provider } from "react-redux";

        export default function Providers({ children }: PropsWithChildren) {
              return <Provider store={store}>{children}</Provider>;
        }
`
**NB: It's important to add the `"use client"` statement at the top to let next js know that it should render on client side and not from server.** 
4. Now in your `layout.tsx` file import `Providers` component and use it like so;
`
//import statement
import Providers from "./providers";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        //usage
        <Providers>
          <SidebarAndNavWrapper>{children}</SidebarAndNavWrapper>
        </Providers>
      </body>
    </html>
  );
}

`

**Comment by milindgoel15** [comment]
Adding use client to providers.tsx results in this error for me:

```console
Warning: Only createServerContext is supported in Server Components.
 ⨯ node_modules\react-redux\es\hooks\useReduxContext.js (16:12) @ useReduxContext
 ⨯ Error: could not find react-redux context value; please ensure the component is wrapped in a <Provider>
    at useAppCart (./src/redux/CartStore.ts:70:23)
    at Cart (./src/app/cart/page.tsx:24:97)
    at stringify (<anonymous>)
```

<details>
<summary>my code</summary>

```ts
const cartStore = configureStore({
	reducer: persistedCartReducer,
	middleware: (getDefaultMiddleware) =>
		getDefaultMiddleware({
			serializableCheck: {
				ignoredActions: [FLUSH, REHYDRATE, PAUSE, PERSIST, PURGE, REGISTER],
			},
		}),
});

export const cartPersistor = persistStore(cartStore);

export type AppDispatch = typeof cartStore.dispatch;

export const useAppDispatch: () => AppDispatch = useDispatch;

export type RootState = ReturnType<typeof cartStore.getState>;
export const useAppSelector: TypedUseSelectorHook<RootState> = useSelector;

export const useAppState = () => useAppSelector((state) => state);

export const useAppCart = () => {
	// const state = useAppSelector((state) => state);
	const cart = (state: RootState) => state.cart;
	const totalPrice = (state: RootState) => state.totalPrice;
	const cartState = useAppSelector(cart);
	const totalPriceState = useAppSelector(totalPrice);

	const dispatch = useAppDispatch();
	return { cartState, totalPriceState, dispatch };
};

export default cartStore;
```

</details>

**Comment by kasir-barati** [comment]
One question though, why we cannot pass store to the component in root layout?

Read here for more info: https://github.com/vercel/next.js/discussions/59090
