### ISSUE TITLE
`shallowEqual` has a false-positive when comparing differing dates

### ISSUE THREAD

**Issue by Annoiiyed** [reduxjs/react-redux#2058]
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

- React Redux: v1.8.2

### What is the current behavior?

```javascript
const a = new Date("2023-08-03T14:18:05.320Z");
const b = new Date("2023-08-03T14:19:05.320Z")
console.log(shallowEqual(a, b)); // true
```

### What is the expected behavior?

It should return `false` instead. I would personally also say false negatives are preferable to false positives, given the `shallow` part.

The issue is caused because Object.keys returns an empty array on dates here:
https://github.com/reduxjs/react-redux/blob/master/src/utils/shallowEqual.ts#L21C17-L21C28

**Comment by Annoiiyed** [comment]
I'm not sure what would be preferable; returning false if either value is a date, or casting both to string before comparison if a/b are dates. Happily to submit a PR though, given input on your preferences :)

**Comment by phryneas** [comment]
Tbh., the only behaviour we would add to that would probably to return `false` if we detect a non-serializable object and there is no object reference identity, but I'm not sure if that is better than the current behaviour - this function is not really made for the purpose of comparing anything that cannot really be compared shallowly.

**Comment by markerikson** [comment]
Yep. This would be expected behavior for any class instance with private fields or similar behavior. Working as intended.

**Comment by markerikson** [comment]
This is a good example of why we specifically tell users to only put non-serializable values into the state. React-Redux has _always_ relied on reference comparisons to determine if extracted values have changed and the UI should re-render:

- https://redux.js.org/style-guide/#do-not-put-non-serializable-values-in-state-or-actions

**Comment by Annoiiyed** [comment]
Would you not consider a date serialisable, then?

**Comment by markerikson** [comment]
Not a `Date` _instance_, no. Loosely put, if it's not a plain JS object/array or primitive, as returned by `JSON.parse(someString)`, it's not considered directly "serializable".

**Comment by EskiMojo14** [comment]
![image](https://github.com/reduxjs/react-redux/assets/18308300/d45516fe-7a17-4db0-ad84-2bbe81894afd)
