### ISSUE TITLE
    Could not find react-redux context value; please ensure the component is wrapped in a <Provider>

### ISSUE THREAD

**Issue by ArtemFedorchuk** [reduxjs/react-redux#2084]
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

- React: "^18.2.0"
- ReactDOM: "^18.2.0" 
- "@reduxjs/toolkit": "^1.9.7"
- React Redux: "^8.1.3"

### What is the current behavior?

I have the issue with the react-redux context value. But my app and `customRender` function are wrapped with the Provider. This issue relates only for testing files
```
const RouterAndStoreWrapper: FC<RouterAndStoreWrapperProps> = ({
  children,
  route = '/'
}): ReactElement => {
  window.history.pushState({}, 'Test page', route);
  return (
    <MemoryRouter initialEntries={[route]}>
      <Provider store={store}>{children}</Provider>
    </MemoryRouter>
  );
};

export const customRender = (
  ui: ReactElement,
  { route, ...renderOptions }: ExtendedRenderOptions = {}
): RenderResult => {
  try {
    return render(ui, {
      wrapper: ({ children }) => (
        <RouterAndStoreWrapper route={route}>{children}</RouterAndStoreWrapper>
      ),
      ...renderOptions
    });
  } catch (error) {
    console.error('customRender helper', error);
    return render(ui);
  }
};
```

And one more strange thing is one of the tested components works well but other component get such error.
I've tried everything and I have no idea what to do and how it solve(
Could you help me with this?
Have you ideas?

<img width="584" alt="Screenshot 2023-11-13 at 17 55 13" src="https://github.com/reduxjs/react-redux/assets/43110065/23d35478-4296-4123-8d68-239db687f138">
<img width="806" alt="Screenshot 2023-11-13 at 17 51 48" src="https://github.com/reduxjs/react-redux/assets/43110065/9f098aad-d0bf-4b27-a589-77702de48a54">
<img width="680" alt="Screenshot 2023-11-13 at 17 54 20" src="https://github.com/reduxjs/react-redux/assets/43110065/370443ba-b612-470d-a1e7-8c6932c82d62">
<img width="699" alt="Screenshot 2023-11-13 at 18 59 02" src="https://github.com/reduxjs/react-redux/assets/43110065/4fd5ffcb-9616-4db2-88ae-77e37d7d1907">
<img width="625" alt="Screenshot 2023-11-13 at 18 04 38" src="https://github.com/reduxjs/react-redux/assets/43110065/d5faaf1e-5611-4b14-89a6-f5437075d5d0">

### What is the expected behavior?

Have no issues with the react-redux context value.

### Did this work in previous versions of React Redux?

- [ ] Yes

**Comment by ArtemFedorchuk** [comment]
I've tried to add this in the `index.test.tsx`
```
jest.mock('react-redux', () => ({
  useDispatch: jest.fn(),
  useSelector: jest.fn()
}));
```
Than I've got this error:
<img width="821" alt="Screenshot 2023-11-13 at 19 08 36" src="https://github.com/reduxjs/react-redux/assets/43110065/bd0aec61-d8e3-4dde-9cb2-6515e19f8cd2">
It's so crazy and looks like infinite issues fix 😢

**Comment by markerikson** [comment]
You definitely _should not_ be trying to mock the React-Redux hooks.

Unfortunately I don't have an immediate answer for why the context provider isn't working correctly.  It _looks_ like your `customRender` function setup is reasonable.

Are there possibly multiple copies of React or React-Redux getting pulled into that project somehow?

**Comment by markerikson** [comment]
Closing due to lack of further info.
