### ISSUE TITLE
Rename `noopCheck` to `identityFunctionCheck`

### ISSUE THREAD

**Issue by aryaemami59** [reduxjs/react-redux#2090]
### What is the new or updated feature that you are suggesting?

Rename `noopCheck` to `identityFunctionCheck`

### Why should this feature be included?

- To provide a more accurate description since a no-op function is more like `() => {}`, an identity function is like `x => x`.
- It would also be more consistent with the definitions defined in Reselect.

### What docs changes are needed to explain this?

The [No-op selector check section](#https://react-redux.js.org/api/hooks#no-op-selector-check) will have to be slightly tweaked. 

https://react-redux.js.org/api/hooks#no-op-selector-check

**Comment by EskiMojo14** [comment]
adding the 9.0 milestone as this would be a breaking change :)

I personally don't have any objections to the change though - we'd have to add it to the migration guide, but I suspect the amount of people impacted would be low
