### ISSUE TITLE
Color visibility of some note

### ISSUE THREAD

**Issue by edcheyjr** [reduxjs/react-redux#2093]
## What docs page needs to be fixed?
Not a big problem but the color of the links under "Defining the mapDispatchToProps Function with bindActionCreators" does not seem visible  will reading 
- **Section**: [Defining the mapDispatchToProps Function with bindActionCreators](https://react-redux.js.org/using-react-redux/connect-mapdispatch#defining-the-mapdispatchtoprops-function-with-bindactioncreators)
- **Page**:Connect: [Dispatching Actions with mapDispatchToProps](https://react-redux.js.org/using-react-redux/connect-mapdispatch)

## What is the problem?
The color of the links note under [Defining the mapDispatchToProps Function with bindActionCreators](https://react-redux.js.org/using-react-redux/connect-mapdispatch#defining-the-mapdispatchtoprops-function-with-bindactioncreators)
## What should be changed to fix the problem?
the purple and grey color don't seem to make it visible while reading i would recommend changing the colors a bit

**Comment by EskiMojo14** [comment]
raised #2094 which fixes the background colour for codeblocks inside blockquotes

![image](https://github.com/reduxjs/react-redux/assets/18308300/3543d937-50ed-4b92-85ec-bf5826c23608)

it's a little odd that blockquotes are light even during dark theme but this is at least consistent with that
