### ISSUE TITLE
Unable to resolve module react-dom

### ISSUE THREAD

**Issue by talaikis** [reduxjs/react-redux#2099]
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

- React: 18.2.0
- React Native: 0.72.6
- Redux: 5.0.0
- React Redux: 9.0.0

### What is the current behavior?

Unable to resolve module react-dom

### What is the expected behavior?

No react-dom in react-native

### Did this work in previous versions of React Redux?

- [X] Yes

**Comment by markerikson** [comment]
This is probably a result of the ESM packaging updates. We used to have separate `batchedUpdates.js` and `batchedUpdates.native.js` files, and now that we pre-bundle those aren't there.

Looking into this, but I don't use RN myself - may need some help testing out fixes!

**Comment by markerikson** [comment]
@talaikis can you provide a repo project that reproduces this issue?

**Comment by markerikson** [comment]
I was able to repro the issue and the (hopeful) fix is live in 9.0.1.

Can you let us know if that works?

- https://github.com/reduxjs/react-redux/releases/tag/v9.0.1

**Comment by TheWirv** [comment]
Hi @markerikson, this issue occurs for me when testing (my React Native project) via jest. Since jest needs CJS, it ignores `react-redux.react-native.js` and rather uses `crs/react-redux.development.cjs`. Do you have any idea how to solve this?

**Comment by markerikson** [comment]
@TheWirv : not immediately. Going to need some time to think through the possible ramifications here, unfortunately :(

**Comment by TheWirv** [comment]
No problem at all, I didn't really expect you to automagically come up with a solution. Thank you very much for reopening.

**Comment by TheWirv** [comment]
That PR actually fixes my issues completely. The app works perfectly fine, and the tests are all green. 👌🏼

**Comment by TheWirv** [comment]
Good morning. I got confirmation that this problem has been solved by newly released v9.0.3. Thanks so much for the fix on such short notice. :)
