### ISSUE TITLE
Getting issue in middleware of configureStore when update redux-toolkit to 2.0.1

### ISSUE THREAD

**Issue by abhishekantala24** [reduxjs/react-redux#2128]
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

- React: 
- ReactDOM/React Native: 
- Redux:
- React Redux:

### What is the current behavior?

https://stackoverflow.com/q/77952583/23185273

### What is the expected behavior?

https://stackoverflow.com/q/77952583/23185273

### Which browser and OS are affected by this issue?

all

### Did this work in previous versions of React Redux?

- [ ] Yes

**Comment by markerikson** [comment]
Please don't just link to external posts.  If you're having a problem, we need a CodeSandbox or a Github repo that shows this happening (and especially if you're using something like a custom middleware).
