### ISSUE TITLE
Test fail with provider in react-native

### ISSUE THREAD

**Issue by salarmiirzaeie** [reduxjs/react-redux#2137]
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

- React: 18.2.0
- ReactDOM/React Native: 0.73.4
- Redux:
- React Redux:9.1.0

### What is the current behavior?

When we was trying test components using jest and redux in react-native, it said "SyntaxError: Cannot use import statemen outside a module" where we used Provider from react-redux in version 9.1.0 but in react-redux version 8.1.3 it was passed in jest 

### What is the expected behavior?

It should pass in version 9.1.0 like other version like v 8.13

### Did this work in previous versions of React Redux?

- [X] Yes

**Comment by markerikson** [comment]
We updated React-Redux's packaging in v9, and it should be using ESM modules by default. Our tests show it _should_ work with Jest. If you have a specific issue, please provide a repo that shows this error happening so we can investigate.

**Comment by salarmiirzaeie** [comment]
I created a repo : https://github.com/salarmiirzaeie/react-redux-jest/tree/main 
![image](https://github.com/reduxjs/react-redux/assets/97589643/24139bcc-6eeb-4465-a5fb-69555bc79aac)

**Comment by timdorr** [comment]
You don't have `babel-jest` hooked up correctly. Add this to your jest.config.js:
```
"transform": {
  "\\.[jt]sx?$": "babel-jest"
},
```

**Comment by gavrilikhin-d** [comment]
> You don't have `babel-jest` hooked up correctly. Add this to your jest.config.js:
> 
> ```
> "transform": {
>   "\\.[jt]sx?$": "babel-jest"
> },
> ```

I have the same problem. Adding this to config doesn't help

**Comment by gavrilikhin-d** [comment]
This has helped https://github.com/reduxjs/react-redux/issues/2103#issuecomment-1870389783
