### ISSUE TITLE
useSelector hook seems to break hook parsing in React Developer Tools

### ISSUE THREAD

**Issue by kenlyon** [reduxjs/react-redux#2142]
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

- React: 18.2.0
- ReactDOM/React Native: 18.2.0
- Redux: 4.2.1
- React Redux: 8.0.1

### What is the current behavior?

When I use the `useSelector` hook in my component, the _Components_ tab of the React Developer Tools fails to parse the hooks:
![image](https://github.com/reduxjs/react-redux/assets/10090224/7dc478b6-6209-4559-93e2-bd770fa94a20)

Steps to reproduce:
1. Install the React Developer Tools extension in Firefox.
2. Open an app that contains a component that uses the `useSelector` hook.
3. Open the Developer Tools and click on the "Components" tab.
4. Select the component in the tree and look at the "hooks" section of the right panel.

### What is the expected behavior?

I expect the React Developer Tools to be able to parse the hooks without error and show the names of the variables:

![image](https://github.com/reduxjs/react-redux/assets/10090224/69db09e1-aa46-4755-8d0f-df597e975be0)

### Which browser and OS are affected by this issue?

Firefox 123.0.1, WIndows 10 Pro

### Did this work in previous versions of React Redux?

- [ ] Yes

**Comment by timdorr** [comment]
Looks like this is an upstream bug: facebook/react#27889

It may be fixed by React Dev Tools 5.0.1 or 5.0.2, either that or a uSES fix. Either way, it's not something we can fix ourselves.

**Comment by kenlyon** [comment]
@timdorr Thanks for the link to the relevant issue! I'm glad to see it's been fixed. Hopefully there will be a new release of the extension soon.
