### ISSUE TITLE
docs: v9.0.0 release missing information

### ISSUE THREAD

**Issue by Matthew-Mallimo** [reduxjs/react-redux#2148]
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

- React Redux: v9.0.0

### What is the current behavior?

The [release notes for v9.0.0](https://github.com/reduxjs/react-redux/releases/tag/v9.0.0) seem to be missing some information under the "Modernized Build Output" section.

> Modernized Build Output
We now publish modern JS syntax targeting ES2020, including optional chaining, object spread, and other modern syntax. If you need to

That is the end. It seems like there was intention to provide some instruction since it just ends with "If you need to"

### What is the expected behavior?

Either finish the sentence or remove to avoid confusion

### Did this work in previous versions of React Redux?

- [ ] Yes

**Comment by markerikson** [comment]
Heh, that should have been "if you need to . If you need to target older browsers, please transpile the packages yourself (or use the `legacy-esm` build artifact for ES2017)."

and I managed to copy-paste the same issue across different repo release notes :)

Fixed!
