### ISSUE TITLE
Hooks API Reference uses misnamed type in the useSelector() example

### ISSUE THREAD

**Issue by MayCXC** [reduxjs/react-redux#2152]
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

- React: 
- ReactDOM/React Native: 
- Redux:
- React Redux:

### What is the current behavior?

[The `useSelector()` example in the API Reference](https://react-redux.js.org/api/hooks#useselector) defines a type alias for `SelectorFn`, but then uses an undefined `SelectorFunction` type in place of `SelectorFn`.

### What is the expected behavior?

The example should use the `SelectorFn` type that it defines.

### Did this work in previous versions of React Redux?

- [ ] Yes

**Comment by EskiMojo14** [comment]
it's worth noting the example is "pseudo-Typescript", as are a lot of our API references. It's enough to get the point across, while not being actual functional Typescript. 

making sure that a name used is consistent across the example makes sense, but don't expect the full example to match our actual types :)
