### ISSUE TITLE
Include UMD build artifacts for latest release

### ISSUE THREAD

**Issue by AjeshM** [reduxjs/react-redux#2159]
### What is the new or updated feature that you are suggesting?

Include UMD build artifacts for latest release 

### Why should this feature be included?

Include UMD build artifacts for latest release

### What docs changes are needed to explain this?

Include UMD build artifacts for latest release

**Comment by phryneas** [comment]
React [just removed UMD](https://github.com/facebook/react/pull/28735) for their upcoming version.

UMD is essentially dead, and three issues with just a single sentence over three repos won't change that.

If you can give us more context on your use case we could try and help you to work with a modern alternative. Why do you think you need an UMD build?

**Comment by markerikson** [comment]
Closing due to lack of response.

**Comment by avtarnanrey** [comment]
In React 19, they have removed UMD, but they are not shipping ESM either. Rather they are recommending using esm.sh
Now in situations where your client/company does not allow us to use third party CDNs, you're stuck.
Now either we stop externalizing dependencies and bundle it all together, or try to convert these packages to UMD ourselves.
