### ISSUE TITLE
Can't NPM Install Redux with Vite React + Typescript

### ISSUE THREAD

**Issue by luthfikamalananda** [reduxjs/react-redux#2161]
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

- React: 18.2.0
- ReactDOM/React Native: 18.2.0
- Redux: 2.2.3
- React Redux: 9.1.1
-- dev depedencies --
- "@types/react": 18.2.66
- "@types/react-dom": 18.2.22

### What is the current behavior?

Couldn't install the redux toolkit and react redux. With this error
"npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution."
![Screenshot 2024-04-26 151431](https://github.com/reduxjs/react-redux/assets/113531863/afaed6a8-a4bf-4ab4-87f7-a4751427db4b)

I tried to use --force to bypass the installation, but i couldn't use some of the RTK Query Hooks

### What is the expected behavior?

Should be installable

### Which browser and OS are affected by this issue?

All Browser

### Did this work in previous versions of React Redux?

- [ ] Yes

**Comment by luthfikamalananda** [comment]
Here's the log report
[2024-04-26T08_08_58_365Z-eresolve-report.txt](https://github.com/reduxjs/react-redux/files/15127495/2024-04-26T08_08_58_365Z-eresolve-report.txt)

**Comment by markerikson** [comment]
This looks like an issue with React Native 0.74 needing React 18.2, and your app also trying to install React 18.3.  Either way this doesn't have anything to do with React-Redux.
