### ISSUE TITLE
Compatibility with React 19 types

### ISSUE THREAD

**Issue by eps1lon** [reduxjs/react-redux#2162]
### What is the new or updated feature that you are suggesting?

Compatibility with React 19 types.

I used `npx types-react-codemod@latest` that solved most of the issues. All necessary changes can be cherry-picked from https://github.com/eps1lon/react-redux/pull/1. You can also check out https://github.com/users/eps1lon/projects/3/views/9 to get an overview what other apps/libraries need to do for migration.

### Why should this feature be included?

To allow seamless migration to React 19.

### What docs changes are needed to explain this?

None

**Comment by markerikson** [comment]
Can you clarify what actual changes are needed?

**Comment by eps1lon** [comment]
https://github.com/eps1lon/react-redux/pull/1/files

**Comment by markerikson** [comment]
@eps1lon can you clarify how we have an implicit transitive dependency on `@types/prop-types`?
