### ISSUE TITLE
Unable to install @reduxjs/toolkit on Next.js project

### ISSUE THREAD

**Issue by DGamer007** [reduxjs/react-redux#2166]
I was creating a new Next.js application with `redux` example; and I encountered this issue.

![image](https://github.com/reduxjs/redux-toolkit/assets/72591998/a3489f46-b432-4d9e-8b94-e662c3436e3f)

This issue arises even when I am trying to install `@reduxjs/toolkit` in existing Next.js project with `npm install --save @reduxjs/toolkit`.

I am currently trying on Kali Linux. But I replicated this issue on Ubuntu as well. Somehow, it seems to work on Windows.

**Comment by markerikson** [comment]
This should be fixed now that React-Redux 9.1.2 is out.
