### ISSUE TITLE
Your Docusaurus site did not load properly.

### ISSUE THREAD

**Issue by AshishZiniya** [reduxjs/react-redux#2187]
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

- React: latest
- ReactDOM/React Native: latest
- Redux: latest
- React Redux: latest

### What is the current behavior?

![Screenshot (45)](https://github.com/reduxjs/react-redux/assets/98575396/e1168c81-2913-4f19-877e-159c0b882803)

### What is the expected behavior?

fix this site like it always look like

### Which browser and OS are affected by this issue?

chrome browser and windows 11

### Did this work in previous versions of React Redux?

- [ ] Yes

**Comment by markerikson** [comment]
The site is working fine for us atm - this may be an issue with your internet provider somehow?

**Comment by AshishZiniya** [comment]
Can you explain what the problem is?

**Comment by markerikson** [comment]
I don't know, because the site is working fine for me and other users atm.  So, it's most likely something with your network trying to load it.

**Comment by AshishZiniya** [comment]
Ok, thanks for your time.
