### ISSUE TITLE
Maximum update depth exceeded

### ISSUE THREAD

**Issue by dekim1028** [reduxjs/react-redux#2189]
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

- React: 18.2.0
- ReactDOM/React Native: RN 0.73.8
- Redux: 5.0.1
- React Redux: 9.1.2

### What is the current behavior?

```
function ReduxTestContent() {
    const data = useSelector(TestSelector.selectTest(1));
    const [state, setState] = useState(0);

    useEffect(() => {
        setState(data.test);
    }, [data]);

    return (
        <View>
            <Text>{state}</Text>
        </View>
    );
}
```

```
static readonly selectTest = (data: number) =>
    createSelector(RootSelector.selectTest, (state) => {
        return { test: 1 };
});
```

'A Maximum update depth exceeded.' error occurs in the code above.
It seems that the selectTest function always determines that a new object is returned, but there was no problem before upgrading. (before: 7.2.9)

### What is the expected behavior?

'A Maximum update depth exceeded.' No errors should occur

### Which browser and OS are affected by this issue?

Android, iOS

### Did this work in previous versions of React Redux?

- [X] Yes

**Comment by markerikson** [comment]
Yes, your `selectTest` function is _calling_ `createSelector` every time, which is both a wrong use of `createSelector`, and _will_ return a new object every time because no memoization is happening.  Please don't do that :)
