### ISSUE TITLE
useSelector giving  TypeError: Cannot read properties of undefined (reading 'hasValue') after running jest test cases

### ISSUE THREAD

**Issue by raoehtesham03** [reduxjs/react-redux#2190]
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

- React: 18.3.1
- ReactDOM/React Native: 18.3.1
- Redux: 5.0.1
- React Redux: 9.1.2
- @testing-library/jest-dom: 6.4.6

### What is the current behavior?

When I am running the jest test cases I am getting this error ; 

 **TypeError: Cannot read properties of undefined (reading 'hasValue')**

### What is the expected behavior?

It should run the test cases successfully.

### Which browser and OS are affected by this issue?

Chrome, Mac

### Did this work in previous versions of React Redux?

- [X] Yes

This might be becaues of use-sync-external-store. Please fix

**Comment by markerikson** [comment]
There's absolutely no useful information here that we could even _begin_ to offer help with.
