### ISSUE TITLE
bump react-redux to v8.1.2: Super expression must either be null or a function

### ISSUE THREAD

**Issue by witlploe** [reduxjs/react-redux#2194]
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

- React: 18.2.0
- ReactDOM: 18.2.0
- Redux:5.0.1
- React Redux:8.1.3

### What is the current behavior?

My current project needs to upgrade react-redux to 8.1.3.But after the upgrade, my app is inaccessible, and an error occurs: **Super expression must either be null or a function**. My previous version is 5.1.2, and it loads normally in 5.1.2. 
But in the official documentation, I see that connect still works and is supported in React-Redux 8.x.But I got the error.

**class Connector**
```
export default class Connector {
	constructor(TheComponent) {
		bindThis(this);
		const that = this;
		this.name = TheComponent.name || TheComponent.displayName;

		const WrappedComponent = connect(
			this.mapStateToProps,
			this.mapDispatchToProps,
			this.mergeProps,
		)(TheComponent);

		class Wrapped extends WrappedComponent {
			constructor(props, context) {
				that.store = props.store;
				super(props, context);
			}
			UNSAFE_componentWillMount() {
			 	// adding resources and reducers used in a component to StoreService
			}
			componentWillUnmount() {
			 	super.componentWillUnmount();
			}

			componentDidMount() {
			 	super.componentDidMount();
			}
		}
		return Wrapped;
	}
}
```
**class ActionsAsideConnector**
```
export class ActionsAsideConnector extends Connector {
	mapStateToProps(state) {
		return {
			actions,
			documentId,
			userToMatching,
			userIdSuggestions,
		};
	}
	mapDispatchToProps(dispatch) {
		return {
			closeInfoHandler: () =>dispatch(asidesInstance.triggerAction(xxxxxxxxxx, CLOSE)),
		};
	}
	mergeProps(stateProps, dispatchProps, ownProps) {
		return {
			...stateProps,
			...ownProps,
		};
	}
}

export default new ActionsAsideConnector(ActionsAside)
```
**ActionsAside**
```
const ActionsAside = ({
	closeInfoHandler,
}) =>
		<div>
			<InfoAside
				title={infoTitle}
				isOpen={isInfoOpen}
				closeHandler={closeInfoHandler}
			/>
		</div>
	) 

ActionsAside.propTypes = {
	infoTitle: PropTypes.string,
};
ActionsAside.defaultProps = {
	isInfoOpen: false,
};
export default ActionsAside;
```

### What is the expected behavior?

The app can be loaded normally on the v8.1.2

### Which browser and OS are affected by this issue?

chrome/macos

### Did this work in previous versions of React Redux?

- [ ] Yes

**Comment by EskiMojo14** [comment]
From 5.1.2 to 8.1.2 is three major versions - have you checked the release notes for each major release to make sure there's no breaking changes you've missed?

**Comment by phryneas** [comment]
Yeah, extending other components has always been an anti-pattern - see https://legacy.reactjs.org/docs/composition-vs-inheritance.html#so-what-about-inheritance
