### ISSUE TITLE
[Performance] Domain contexts & selectors

### ISSUE THREAD

**Issue by gentlee** [reduxjs/react-redux#2202]
### What is the new or updated feature that you are suggesting?

**Problem:**

One of the slowest parts of redux is that there can be a lot of subscribers to the store with their custom state comparers. If we have 1000 subscribers and 100 actions are triggered per second (like on startup of the chatting app), 100 000 comparisons are made per second.

One possible solution is to use multiple stores, but this can lead to various issues.

**Suggestion:**

The same performance of having multiple stores can be achieved with single store. There is already an ability to make custom contexts and hooks, but currently it makes sense only for multiple stores. 

Ability to provide the same store but with domain selector should be added:

```typescript
const store = createStore(reducer);

const SomeDomainContext = React.createContext(null);
const someDomiainSelector = (state) => state.someDomain

// custom hook for a specific domain
export const useSomeDomainSelector = createSelectorHook(MyContext, someDomainSelector)

const App = () => {
  return (
    <Provider store={store} />
      <Provider store={store} selector={someDomainSelector} context={SomeDomainContext}>
        <RootModule />
      </Provider>
    </Provider>
  );
}

const RootModule = () => {
  // here we got the state of the selected domain, not the whole redux state
  // this selector should not be executed and compared on redux state updates when domain does not change
  const someDomainState = useSomeDomainSelector(domainState => domainState, customEqualityFn) 

return null
}
```

### Why should this feature be included?

This will make using multiple stores totally obsolete, but will fix performance issues caused by single store.

### What docs changes are needed to explain this?

https://react-redux.js.org/using-react-redux/accessing-store

Add recommended practise here:
https://redux.js.org/style-guide/

**Comment by markerikson** [comment]
Agreed that the `O(n)` behavior of Redux's subscription model is both a strength (simplicity) and a weakness (perf at very large scales).

That said, if I'm understanding this proposal right, the approach here isn't viable. There's no guarantee that a given subtree will _only_ ever access a specific slice of state.  The whole point of `useSelector` is that _any_ component can read from _any_ part of the state at _any_ time.

**Comment by gentlee** [comment]
@markerikson you can see that `someDomiainSelector` is passed to `createSelectorHook` too, and that makes the hook provide only domain state, not the whole.

So yes, it will access only a specific slice.

**Comment by gentlee** [comment]
@markerikson OK, I updated header a bit with idea to create a `createSliceWithContext`, for future if someone decides to do that.

**Comment by gentlee** [comment]
Other possible ways to reach that:
1. `combineStores` into single same as `combineReducers` / `combineSlices` - that way we also separate action handling by reducers for multiple stores if dispatched not by the main store, but by the child store. Which is a nice feature to have.
2. Some wrapper (e.g. `createDomain(reducer)`) around reducer (including combined reducers) that returns context, hooks (useSelector, useDispatch can also be returned to separate actions only for that domain, if it is possible) and mb even selectors (if coming from combined slices) for the new context.

**Comment by phryneas** [comment]
Just to throw the idea out - with something like `proxy-memoize`, there could be a new version of `useSelector` that shared a single store subscription and then would trigger subscribers much more granularly, but transparently to the user.

**Comment by markerikson** [comment]
Yeah, that's roughly similar to what I was playing around with in this PR:

- #2047

but A) I haven't ever had time to go back and play with that idea again, B) I'm pretty sure there's a ton of edge cases this would have issues with, and C) it requires an up-front fixed set of work (reconciling the immutably updated state tree into the proxy wrapper) _and_ the cost of reading from proxies (which I recently found out can be relatively expensive), and it's very questionable if the amount of time saved from skipping subscribers and selectors would actually be a net improvement in perf.

I can say that apparently Slack did do something similar to this "domains" proposal in terms of watching for top-level slice changes, but it sounds like they did it by wrapping the store subscription process itself and providing methods for consumers to subscribe to just those keys, thus providing some fan-out behavior.  (Also, evidence that this can be done in userland, and thus not something I would want to build in to the lib itself any time soon.)
