### ISSUE TITLE
node_modules\react-redux\dist\react-redux.legacy-esm.js with code Cannot read property 'getState' of undefined

### ISSUE THREAD

**Issue by lalithasj** [reduxjs/react-redux#2204]
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

- React: 18.2.0
- ReactDOM/React Native: 0.74.6
- Redux: 5.0.1
- React Redux: 9.1.2

### What is the current behavior?

<Provider store={store}>
    <AppNavigator />
</Provider>

//store.js
export const store = configureStore({
    reducer: {
        auth: authSlice,
        cart: cartSlice,
    },
});

This error is located at:
    in Provider (created by App)
    in App
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in Client(RootComponent), js engine: hermes
 ERROR  TypeError: Cannot read property 'getState' of undefined

### What is the expected behavior?

I didn't expect this error in react-redux and @reduxjs/toolkit configureStore and Provider.

Appreciate any suggestion

### Which browser and OS are affected by this issue?

windows 11, chrome browser, android emulator

### Did this work in previous versions of React Redux?

- [x] Yes

**Comment by markerikson** [comment]
That error says to me that you aren't actually passing `<Provider store={store}>` correctly. Please check the code that passes the store to the provider and make sure it's a valid store reference.

**Comment by lalithasj** [comment]
Hi @markerikson ,
Thank you for your suggestion. I will check that.
