### ISSUE TITLE
Cannot read properties of null (reading 'useMemo')

### ISSUE THREAD

**Issue by Hishammpsnhn** [reduxjs/react-redux#2209]
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

 Uncaught TypeError: Cannot read properties of null (reading 'useMemo')
The above error occurred in the <Provider> component
 react-redux:9.1.2

### What is the current behavior?

downgrade the version 

### What is the expected behavior?

error or bug

### Which browser and OS are affected by this issue?

brave

### Did this work in previous versions of React Redux?

- [x] Yes

**Comment by timdorr** [comment]
This is coming from lines like this: 
https://github.com/reduxjs/react-redux/blob/560ac02a4cb531ce97889114e0e9dabd12ce91ce/src/components/Provider.tsx#L65

This likely means something is up with your build system for the `react` module to return `null`. This isn't a problem with the library.

**Comment by tnguyen14** [comment]
I think I am running into a similar problem to this when using ESM version of this library. Here's the minimal code I have to reproduce it

```js
import React from 'https://esm.sh/react@18.2.0';
import { render } from 'https://esm.sh/react-dom@18.2.0';
import { Provider } from 'https://esm.sh/react-redux@9.1.2';

function App() {
   return (
      <div>Hello, world</div>
  );
}

render(
  <Provider>
    <App />
  </Provider>,
  document.querySelector('#app')
);
```

with a simple 
```html
<div id="app"></div>
```

The error is

```
Uncaught TypeError: l.current is null
    useMemo React
    ht Redux
    React 11
        Hi
        sa
        ia
        df
        Ir
        ao
        on
        wn
        Cf
        qr
        render
    <anonymous> pen.js:12
react.production.min.js:26:30
    useMemo React
    ht Redux
    React 11
    <anonymous> pen.js:12
```
