### ISSUE TITLE
Giving warning in next.js 15

### ISSUE THREAD

**Issue by anishkumar127** [reduxjs/react-redux#2212]
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

- React: 19.0.0-rc-66855b96-20241106
- ReactDOM/React Native: 19.0.0-rc-66855b96-20241106
- Redux:  "@reduxjs/toolkit": "^2.3.0",
- React Redux:^9.1.2

### What is the current behavior?

 WARN  Issues with peer dependencies found
.
├─┬ react-redux 9.1.2
│ ├── ✕ unmet peer react@^18.0: found 19.0.0-rc-66855b96-20241106
│ └─┬ use-sync-external-store 1.2.2
│   └── ✕ unmet peer react@"^16.8.0 || ^17.0.0 || ^18.0.0": found 19.0.0-rc-66855b96-20241106
├─┬ @reduxjs/toolkit 2.3.0
│ └── ✕ unmet peer react@"^16.9.0 || ^17.0.0 || ^18": found 19.0.0-rc-66855b96-20241106
└─┬ @fluentui/react-components 9.56.1
  └─┬ @fluentui/react-alert 9.0.0-beta.124
    └─┬ @fluentui/react-avatar 9.6.42
      └─┬ @fluentui/react-popover 9.9.24
        └─┬ @fluentui/react-context-selector 9.1.69
          └── ✕ unmet peer scheduler@">=0.19.0 <=0.23.0": found 0.25.0-rc-66855b96-20241106

Done in 11s

### What is the expected behavior?

should not give the warning

### Which browser and OS are affected by this issue?

All

### Did this work in previous versions of React Redux?

- [ ] Yes

**Comment by markerikson** [comment]
Per the sibling issue in the RTK repo:

We don't currently explicitly list React 19 in our peer dependencies because it's not final yet. We'll update that when React 19 officially comes out. That said, it should _work_ fine at runtime.

**Comment by anishkumar127** [comment]
@markerikson React 19.0.0 Officially stable now.

**Comment by markerikson** [comment]
Yes, and I just released https://github.com/reduxjs/react-redux/releases/tag/v9.2.0 last night with the update :)
