### ISSUE TITLE
react-redux 9.x 版本编译产物存在较新的语法 ?? 存在兼容性问题

### ISSUE THREAD

**Issue by xinglai-zxl** [reduxjs/react-redux#2213]
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

- React:  18.x
- ReactDOM/React Native: 
- Redux: 5.x
- React Redux: 9.x

### What is the current behavior?

![Image](https://github.com/user-attachments/assets/b2004edb-ccd6-4e5c-ad5c-858c17aa4c7e)
es6 语法在某些场景下不支持

### What is the expected behavior?

预期产物是es5语法的产物，不包含较新语法

### Which browser and OS are affected by this issue?

wechat

### Did this work in previous versions of React Redux?

- [ ] Yes

**Comment by timdorr** [comment]
The library requires modern browsers. If you need older browser support, you should either transpile the code with a tool like Babel or use an older version (as many other libraries do this too).
