### ISSUE TITLE
`connect()` no longer pass through generic type arguments for components

### ISSUE THREAD

**Issue by ehellman** [reduxjs/react-redux#2218]
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

- React: 19.0.0
- ReactDOM: 19.0.0
- Redux: 5.0.1
- React Redux: 9.2.0
- TypeScript: 4+

### What is the current behavior?

We've got a lib containing a data loader module that uses `connect()` to consume the redux store. Today we tried to upgrade from:

- React: 17.0.2
- ReactDOM: 17.0.2
- Redux: 4.1.0
- React Redux: 7.2.4

And we ran into a typing issue. I've made a demo showcasing both the type of component we are using and a super simplified way of how it's used: [See demo](https://codesandbox.io/p/devbox/react-redux-connect-generic-props-r9khv5)

We're declaring the PropType for the DataLoader component to use a type argument `<T>`, which up to today has worked fantastically using the exact same code as in the demo. As you can see, the `user` object that gets returned in the render props get an `unknown` type which previously wasn't the case, instead it got `T` as expected.

To showcase the main difference I can spot, I added a `types` script that spits out `.d.ts` files in `dist/types/`. If we take a look at `DataLoader.d.ts` and compare it to what a working version used to look like:

### Current (not working):

```ts
// DataLoader.ts
type DataLoaderProps<T> = {
  data: Promise<T>;
  children: (data: T) => React.ReactNode;
  fallback?: React.ReactNode;
  fallbackData?: T;
} & ConnectedProps;

type ConnectedProps = {
  currentTheme: SiteTheme;
};

// DataLoader.d.ts
. . .

declare class DataLoader<T> extends React.Component<DataLoaderProps<T>, DataLoaderState<T>> {
    state: DataLoaderState<T>;
    constructor(props: DataLoaderProps<T>);
    . . .
}

declare const _default: import('react-redux').ConnectedComponent<
  typeof DataLoader,
  {
    data: Promise<unknown>;
    children: (data: unknown) => React.ReactNode;
    fallback?: React.ReactNode;
    fallbackData?: unknown;
    . . .
  }
>;
export default _default;
```

### Previous (working):

```ts
// DataLoader.ts
type DataLoaderProps<T> = {
  data: Promise<T>;
  children: (data: T) => React.ReactNode;
  fallback?: React.ReactNode;
  fallbackData?: T;
} & ConnectedProps;

type ConnectedProps = {
  currentTheme: SiteTheme;
};

// DataLoader.d.ts
. . .
declare class DataLoader<T> extends React.Component<
  DataLoaderProps<T>,
  DataLoaderState<T>
> {
  . . .
}
declare const _default: typeof DataLoader;
export default _default;
```

The main difference I can see is the `import("react-redux").ConnectedComponent` parts that weren't there before. I'm not sure if the updated type declaration for the `connect` function has done something to disable this from being possible.

### What is the expected behavior?

As you can see in the demo, `user` inside `<DataLoader>` in `App.tsx` gets the `unknown`type, which matches with what we can see in the `.d.ts` typedefs. I expected the same behavior as we had before where `user` was typed as `T` instead, (`User` in this case).

Please let me know if I can update my demo with something specific that might help out.

### Which browser and OS are affected by this issue?

All

### Did this work in previous versions of React Redux?

- [x] Yes

**Comment by markerikson** [comment]
We did move the `connect` typings directly into our own codebase as part of the TS migration with React-Redux v8. We made _some_ changes at the time, but tried to keep the types the same as what was in `@types/react-redux` as much as possible, including the existing type tests.

So, it's _possible_ that we broke something, but if so it certainly wasn't intentional.

That said: at this point, `connect` is not actively being worked on, and we strongly recommend you use the hooks API instead.

If anything, I'd recommend looking at using our RTK Query data fetching and caching layer if possible:

- https://redux-toolkit.js.org/rtk-query/overview

**Comment by ehellman** [comment]
Thank you for such a quick reply!

Yeah, I kind of expected that this was the case. It's sad that it's regressed but at the same time, I agree with you that the hooks API is the future. We just wanted to offer an easier upgrade path for some of our projects that hasn't refactored their class components yet - but this is a good excuse to find time to actually do that refactoring :)

It seems to be working alright with components that do not have this specific setup with a generic type argument though, so the initial scope of the refactor wouldn't be enormous.

We can mark this as resolved!
