### ISSUE TITLE
Error handling in connectAdvanced can swallow errors

### ISSUE THREAD

**Issue by markerikson** [reduxjs/react-redux#802]
Reported in Reactiflux chat by user "Bahamut", who was not in a position to file a report himself.

Description:

There was a function being defined inside of a `mapDispatch` function, like:

```js
function mapDispatch(dispatch) {
    return {
        someFunction: () => dispatch({type : "SOME_ACTION", string : `some template literal`})
    };
}
```

There was an error in the template literal, and that threw an error when the `mapDispatch` function was checked by `connectAdvanced()` at [connectAdvanced.js#L15-25](https://github.com/reactjs/react-redux/blob/f1367df6de7fc5aed4e2434d68038a517208f6da/src/components/connectAdvanced.js#L15-L25).  

However, the error was swallowed by the `try/catch` block there, and no visible error was reported in the console.

So, the important issue here appears to be that we have a `try/catch` that swallows errors, and doesn't report them in any way.

Would it be a good idea to use the `warning()` util to log errors here?

**Comment by hoschi** [comment]
We found the same problem with when our selector function had an error (accessing prop 'x' from undefined) which was swallowed.

**Comment by rick-li** [comment]
Same here, it swallows all the run time errors in render, it can waste days debugging it.... :(

**Comment by markerikson** [comment]
@rick-li : I wouldn't expect this to swallow errors from _rendering_, just errors that occur inside of a `mapState` or `mapDispatch` function.

**Comment by mjniday** [comment]
I just had this happen with `mapState` where errors were not surfaced. I was trying to access a property on something inside its `ownProps` which was temporarily undefined. Less certain still about this part, but the browser kept crashing when trying to render that component. Fixing the error in the `mapState` function resolved that issue for me.

Something like...
```js
const mapState = (state, ownProps) => {
  const itemId = ownProps.collection.first().itemId // ownProps.collection.first() was initially undefined
  return {
    itemId
  }
}
```

Seems possible that the error handling here was blowing up the call stack which resulted in the browser dying.

**Comment by jimbolla** [comment]
The error should be rethrown in render() [here](https://github.com/reactjs/react-redux/blob/f1367df6de7fc5aed4e2434d68038a517208f6da/src/components/connectAdvanced.js#L254)

**Comment by AlexTwine** [comment]
This needs to be fix.  I spent a good amount of time trying to figure out why my debugger wasn't getting hit in the mapState function.  The error should show up in the console.

**Comment by benlakey** [comment]
I was going to look into this but in all my attempts to reproduce the issue I cannot due to the reasons @jimbolla  outlined above. The errors appear to be getting correctly re-thrown inside of the `Connect` component `render()`.

Am I missing something? 

My mechanism for testing was to simply throw an error inside of a string template within `mapDispatchToProps` or `mapStateToProps`.

```js
import Counter from './Counter';
import { incrementAction } from '../actions';
import { connect } from 'react-redux';

const blowup = () => {
  throw new Error('BOOM');
};

const mapStateToProps = (state) => ({
  text: `test ${blowup()}`,
  count: state.count
});

const mapDispatchToProps = (dispatch) => ({
  onClick: () => dispatch(incrementAction())
});

export default connect(mapStateToProps, mapDispatchToProps)(Counter);
```

The correct stuff shows up in a browser because of the re-thrown error:

![screen shot 2018-03-12 at 9 18 33 pm](https://user-images.githubusercontent.com/712322/37322464-f4697f0a-263a-11e8-8494-7c1af174815a.png)

**Comment by zengyang2014** [comment]
Hi @markerikson Why not throw error directly once catch errors in selectors?

```
function makeUpdater(sourceSelector, store) {
  return function updater(props, prevState) {
    try {
      const nextProps = sourceSelector(store.getState(), props)
      if (nextProps !== prevState.props || prevState.error) {
        return {
          shouldComponentUpdate: true,
          props: nextProps,
          error: null,
        }
      }
      return {
        shouldComponentUpdate: false,
      }
    } catch (error) {
      threw error
    }
  }
}
```

**Comment by omnisyle** [comment]
for some reasons try catch block to re-throw error does not work for me either

```javascript
const todoSelector = (state) => {
  return state.todos;
};

const presentTodos = createSelector(
  [todoSelector],
  (todos) => {
    throw new Error("boom");
  }
);
const mapStateToProps = (state) => {
  try {
      return {
        todos: presentTodos(state),
      };
  } catch (e) {
    throw e; // this is still being swallowed by connect if the errors happen inside the selector
  }
}

```

So instead, i have to to this to bubble up the errors

```javascript
const todoSelector = (state) => {
  return state.todos;
};

const presentTodos = createSelector(
  [todoSelector],
  (todos) => {
    throw new Error("boom");
  }
);
const mapStateToProps = (state) => {
  try {
      return {
        todos: presentTodos(state),
      };
  } catch (e) {
    console.error(e); // now this works
  }
}
```

**Comment by Slapbox** [comment]
@markerikson is this believed to be fixed at this point? It seems not to be, or at least -  I have no other theory for why our errors are getting swallowed inside of our `mapStateToProps`.

I've spent an hour trying to pinpoint the exact cause for us, and this issue is my only lead.

**Comment by markerikson** [comment]
@Slapbox : we're multiple major versions and internal rearchitectures past when this issue was closed :)  Could you open up a separate new issue so we can keep track of your question on its own, and if at all possible include either a CodeSandbox showing the problem or a Replay ( https://replay.io/record-bugs ) of this happening?

**Comment by Slapbox** [comment]
Hey @markerikson thanks for the reply! I know I'm super late to the party.

Unfortunately I won't have the time to do anything besides basically copy paste that comment into a new issue (and let me know if I should) - as the solution for us was simply to move that function into `render` (where it should have been anyway.)

**Comment by markerikson** [comment]
Realistically, I'm not going to have time to look at this any time soon.  But I _definitely_ won't ever remember to look at it if there's no new issue filed :)
