### ISSUE TITLE
HMR doesn't work on redux connected component

### ISSUE THREAD

**Issue by liesislukas** [reduxjs/react-redux#809]
Using all new versions of redux and friends. HMR works fine with normal React components but not with connected to Redux store. I have a minimal repo to show this:

https://github.com/liesislukas/react-initial-project

`npm i`
`npm run start:dev`

http://localhost:8080/

UI shows paths to files. HMR shows messages in the console that files changed but no visual update. The goal is to have HMR working with all components without losing the state of components. Inputs in UI modifies the inner state of not-connected components.

**If i comment** 

```
@connect(userSelector, (dispatch) => ({
  userActions: bindActionCreators(userActions, dispatch)
}))
```
at higher order component (UserConnector) of UserVisual **then HMR works fine**

![image](https://user-images.githubusercontent.com/2733862/31776153-52719d30-b4f3-11e7-9fab-a20109eb1478.png)

**Comment by amahrt** [comment]
I'm facing the same issue in react-native.

*package.json dependencies snippet:*
```
{
    "react-redux": "^5.0.5",
    "redux": "^3.7.2",
    "react": "16.0.0-alpha.12",
    "react-native": "0.47.2"
}
```

**Comment by maggo** [comment]
Can confirm that it's not working with `5.0.6`

I tried downgrading as far as `4.4.8` but it wouldn't work. Seems to be an issue with a newer version of webpack-dev-server/HMR or react-hot-loader
