### ISSUE TITLE
Improve mapDispatchToProps factory function documentation

### ISSUE THREAD

**Issue by fongandrew** [reduxjs/react-redux#872]
Some examples were added for factory functions on https://github.com/reactjs/react-redux/blob/master/docs/api.md per https://github.com/reactjs/react-redux/issues/797, but the example for `mapDispatchToPropsFactory` seems off.

Here's the example:

```js
function mapDispatchToPropsFactory(initialState, initialProps) {
  function goToSomeLink(){
    initialProps.history.push('some/link');
  }
  return function(dispatch){
    return {
      addTodo
    }
  }
}
```

The function defines `goToSomeLink` but it's not referenced in any of the return values.

**Comment by fongandrew** [comment]
@markerikson

**Comment by timdorr** [comment]
Yeah, wait...wut. I guess I merged that too soon. I'm not a factory user, so my eyes tend to glaze over at these things. Whoops!
