### ISSUE TITLE
prop-types source is included in dist builds

### ISSUE THREAD

**Issue by nkbt** [reduxjs/react-redux#943]
It would be nice to have source of `prop-types` removed from dist. Especially minified version

This helps: https://www.npmjs.com/package/babel-plugin-transform-react-remove-prop-types

In non-minified build `node_modules/react-redux/dist/react-redux.js`

![image](https://user-images.githubusercontent.com/175264/39558890-ae3d2374-4ed5-11e8-92bf-61bdf4234e8b.png)

In minified build `node_modules/react-redux/dist/react-redux.min.js`

![image](https://user-images.githubusercontent.com/175264/39558900-bb7ea8fa-4ed5-11e8-937a-3123d1ec9b1f.png)

**Comment by gaearon** [comment]
Probably want to throw in https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types in prod mode.

**Comment by timdorr** [comment]
I'm cool with that. I'll check into it for the next release.

**Comment by nkbt** [comment]
Unfortunately `babel-plugin-transform-react-remove-prop-types` does not solve the problem, since it does not remove anything from contextTypes which react-redux uses (and issue is closed now as basically won't fix: https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types/issues/77)

For my library I've done a little hack that works well, but I would be reluctant to recommend it to everyone: 
1. webpack config: https://github.com/in-flux/react-component-router/blob/master/scripts/utils/webpack/common.js#L89-L96
2. actual file: https://github.com/in-flux/react-component-router/blob/master/scripts/utils/webpack/emptyPropTypes.js

**Comment by timdorr** [comment]
This will be fixed once we do our next release.

**Comment by artem-malko** [comment]
Hello @timdorr I know, this is quite old issue, but it should be reopened, as I think. 
Yes, you've removed prop-types from react-redux.min.js, but prop types like:
```
Provider.propTypes = {
  store: PropTypes.shape({
    subscribe: PropTypes.func.isRequired,
    dispatch: PropTypes.func.isRequired,
    getState: PropTypes.func.isRequired
  }),
  context: PropTypes.object,
  children: PropTypes.any
};
```
are still in a file.
Moreover, than I build my app with webpack, all proptypes are in my bundle, cuase they are required in components/Provider.js. And terser or uglifyJs ca not strip it.

What do you  think, if we just wrap prop types to NODE_ENV check like this:
```
if (process.env.NODE_ENV !== 'production') {
  Provider.propTypes = {
    store: PropTypes.shape({
      subscribe: PropTypes.func.isRequired,
      dispatch: PropTypes.func.isRequired,
      getState: PropTypes.func.isRequired
    }),
    context: PropTypes.object,
    children: PropTypes.any
  };
}
```
So, prop-types will be removed from prod build in that case.

**Comment by nkbt** [comment]
@artem-malko there are ways to automatically remove them without polluting code. See my last comment with config examples. You can do it yourself for your prod app build

**Comment by artem-malko** [comment]
@nkbt ok, thx) But I can not understand, why do we need prop-types in prod code?

**Comment by nkbt** [comment]
@artem-malko I know, right! After all that was me who opened the issue :)
