### ISSUE TITLE
how does Redux know which store properties is a component binded on?

### ISSUE THREAD

**Issue by marialovesbeans** [reduxjs/react-redux#957]
Say I'm using a single Redux store for my app. Eg. `<Provider={store}/>`

When the app state changes, how does Redux determine which components should re-render and which not? Does it only rely on the values defined in `mapStatesToProps`? If so, how does Redux know which store properties is a component binded on?

**Comment by markerikson** [comment]
Each connected component instance is a separate subscriber to the store.  Your `mapState` re-runs every time an action is dispatched, and `connect` checks to see if the fields in the returned object are different than the last time.
