### ISSUE TITLE
Connected component will re-render for no reason if its prop is not a primitive

### ISSUE THREAD

**Issue by sylvhama** [reduxjs/react-redux#958]
I've noticed that some connected components will re-render even if their props have not changed. The steps to reproduce are:
- Your redux state must be a non primitive value such as `{}` or `[]`;
- Your connected component must have a props which is non primitive value as well;
- You must dispatch an action.

You can have a look to this [codesandbox](https://codesandbox.io/s/53mkkz28kn) with [react-devtools](https://github.com/facebook/react-devtools)'s Hightlight Updates option to see the third component being updated when clicking on the button.

**Comment by markerikson** [comment]
Your `Test` example is creating a new array instance in its `mapState` function, thus causing the component to re-render every time:

```js
const Test3 = connect(() => ({
  test: []
}))(() => <p>Test3 does re-render when an action is dispatched.</p>);
```

Don't do that :)

It's the same thing if you call `someArray.map()` as well.

See the [Redux FAQ entry on components re-rendering](https://redux.js.org/faq/react-redux#why-is-my-component-re-rendering-too-often), and my post [Practical Redux, Part 6: Connected Lists and Performance](http://blog.isquaredsoftware.com/2017/01/practical-redux-part-6-connected-lists-forms-and-performance/).
