### ISSUE TITLE
MapStateToProps as a class method

### ISSUE THREAD

**Issue by davo11122** [reduxjs/react-redux#959]
Hi everyone.

I suggest to put *mapStateToProps*, *mapDispatchToProps* and *mergeProps* as a class methods for wrappedComponent.

# Motivation
First time I come up with this idea when faced an issue during project unit testing when i was unable to test those 3 functions

```javascript
// My code at that time.
@connect(function mapStateToProps(){/***/},function mapDispatchToProps(){/***/})
class A extends Component{/***/}
```
Here I had 2 options to test functions *mapStateToProps* and *mapDispatchToProps*.

1. Defining our functions atop of class A and exporting from module *which is not a really good solution*
```javascript
export const mapStateToProps = function(){/***/}
export const mapDispatchToProps = function(){/***/}

@connect(mapStateToProps, mapDispatchToProps)
class A extends Component{/***/}
```
2. Defining our functions as class method and put them as an argument in connect
```javascript
@connect(A.mapStateToProps, A.mapDispatchToProps)
class A extends Component{
  static mapStateToProps(){/***/};
  static mapDispatchToProps(){/***/}
  /***/
}
```

With this feature we can just implement our functions in our class *since they are part of our class*
more convient and intuitively.

**Comment by timdorr** [comment]
> Defining our functions atop of class A and exporting from module which is not a really good solution.

Could you explain more why that's not a good solution? This is purely an organizational concern. They don't get any special powers by being put as statics on a class. So other than moving some things around in the same file, I'm not sure what the disadvantage is.

**Comment by davo11122** [comment]
@timdorr thanks for an answer!

You are right this is purely organization concern but it doesn't mean that's not enough for example I believe redux-thunk also just a for organization concern but it still got wide usage and greatest feedback from community.

I think there is several reasons why it's not good.
1. We will need to export 2 varablse from module just for ~nothing~ testing purposes.
2. Those variables will be split from the component in case they are only related to the component.

**Comment by markerikson** [comment]
I've seen wrappers around `connect` that do this.  Personally, I think it's rather pointless.  There's nothing wrong with writing `mapState` as a separate function and exporting it.

While it may technically work, we don't recommend using `connect` as a decorator, and [I recommend against inlining `mapState` into `connect` because it's less readable](https://www.reddit.com/r/reactjs/comments/8rbcze/i_would_love_to_have_your_inputs_on_this_redux/e0pyqtz/).

We definitely have no plans to change the API to support this officially.

**Comment by davo11122** [comment]
@markerikson thanks for your answer.
