### ISSUE TITLE
Please reconsider owning your own typings.

### ISSUE THREAD

**Issue by andrew-buckley** [reduxjs/react-redux#967]
Typescript is becoming more and more prevalent in the development community. Large library maintainers/organizations are starting to realize this and are bringing in typings into their own repositories rather than having thing hang around unmonitored on DT. By doing this, you avoid alienating TS (and JS developers who value typings) because there is much more assurance that the typings that ship with a new release are as stable as the released library. I know this has been revisited a couple times, but I'm asking again, from the bottom of the hearts of the collective React/Redux/TS community, to please reconsider owning the typings for this helpful library. This is a very popular JS library. Redux ships with typings, I think it's a fair request that this library seriously considers doing the same.

Currently there are 71 open issues related to the react-redux typings on DT.

Thanks for considering!

**Comment by markerikson** [comment]
Neither Tim nor I are TS experts (he's used it a bit, I haven't used TS at all), and we don't have the expertise needed to maintain them.  In addition, the last couple of releases we've shipped for Redux and React-Redux that have had typings changes have led to a slew of issues being filed complaining about them, particularly complaints that the changes to typings in Redux-Thunk 2.3 constitute breaking changes.

I can't do anything to maintain those typings, Tim can't do much, and frankly it's too much of a hassle.  We have other things we need to be focusing on.  My impression is that it makes a lot more sense to let the community handle them on DefinitelyTyped so they can be updated at their own pace.

**Comment by andrew-buckley** [comment]
And completely aside from this discussion on whether or not typings will go into this library. I encourage you to give TypeScript a shot! You might fall in love!

**Comment by markerikson** [comment]
I actually think there's definite potential benefits in using either TS or Flow.  But, neither of the apps I build at work are in a position to fully add a type layer on top atm.  I briefly experimented with Flow last year, just long enough to get a feel for what adding it might be like.  However, given our current toolchain and codebase, TS is not a likely option, and I don't have any side projects atm either.  So, no, I probably won't be actually trying to use TS myself any time soon.

As for your previous question: can you point to some of these discussions you're referring to?  This is the first I've heard any of this.

**Comment by andrew-buckley** [comment]
Sure. Some are less directly related than others, but this is what I have read through.

- #433 (2016) and #389 seem to be the first time these were requested both with seemingly positive support.
- #538 which is another attempt at adding typings but it seems to have been closed and reopened in #541 
- #815 which was a continuation of the previous and the conclusion there seemed to be that typings were not important enough so it was closed and that was in Dec 2017.
- #799 which ended in a discussion of of the issues with connect and how it could be helped by having typings. But that too ended with essentially JS is more important at that point in time.
- #877 was just an issue where someone was coming looking for help related to typings. 

I imagine requests for something like this won't stop coming in.

**Comment by markerikson** [comment]
Hmm.  Thanks for collecting those links.

That said, I think these prior comments from Tim and myself still apply:

https://github.com/reduxjs/react-redux/pull/815#issuecomment-350053021
> Other than taking on ownership, I also doubt the benefits of keeping them here. It causes pain when TS moves forward and we don't. Releases are held to our schedule, which doesn't usually align with TS's schedule. I'd argue against adding this burden.

https://github.com/reduxjs/react-redux/pull/815#issuecomment-350077906
> True. I have no connectivity to the TS world. But at the same time, that's an argument for not keeping them here. None of the maintainers here have any experience with TS. We're not able to update them here or on DT. Moving them will not help with update lag.

https://github.com/reduxjs/react-redux/issues/799#issuecomment-370992258
>  I get that typing is a big deal to a lot of people, but our core concern is a library that works as JS code. Redux and React-Redux have a lot of dynamic behavior, and I don't think there's any easy solutions for typing most of that.

To be frank, my personal opinion is that a lot of people spend too much time obsessing over getting typings exactly right.  I understand the desire of having universal solid type coverage for an app, and it's certainly not a _bad_ thing, but to me the time spent going for that last 10% of type coverage seems to be way in excess of the actual benefits.

Anyway, unless @timdorr has greatly changed his stance on this, I don't see us moving towards handling the typings here with the lib.  

My personal priorities as a maintainer for the near future revolve around reworking our implementation to cooperate with async React behavior, not trying to spend hours learning the nuances of TS and Flow.

Thanks for the discussion, and hopefully I've clarified why this isn't something we want to do right now.
