### ISSUE TITLE
Using the 'connect' remounts the wrapped component unnecessarily

### ISSUE THREAD

**Issue by HydraOrc** [reduxjs/react-redux#968]
I have a component called View, which is wrapped with a connect in this way:

```
const mapStateToProps = (state, { page = Map() }) => {
  const view = page.get('view');

  return {
    view: getView(state, view),
    placeholders: getPlaceholdersByView(state, view),
  };
};

export default connect(
  mapStateToProps,
  null,
)(View);
```

The mapStateToProps function is returning the same data and the component is NOT remounted or rerendered from it's ancestors.
Nevertheless, the wrapped component is still unnecessarily remounted (i mean REMOUNTED, not rerendered) when the changes are made to the redux store, which are not even affecting the selectors used in the mapStateToProps above.
This remount occurs only once, but still it messes the state of my children components inside the View.

"react": "16.2.0"
"react-redux": "5.0.7"
"redux": "4.0.0"

**Comment by timdorr** [comment]
Closing until a repro can be provided.

**Comment by edoantonioco** [comment]
I noticed this same problem.
On my mapActionsToProps I have this

`const mapActionsToProps = {

    onUpdateUser: updateUser,
    onUpdateEmail: updateEmail,
}`

So when I need to use for example
`this.onUpdateUser` (to update my user on the store to a new value)

the component remounts again and that mess up my local states.
