### ISSUE TITLE
undefined is not an object (evaluating 'this.props.dispatch')

### ISSUE THREAD

**Issue by JakeHadley** [reduxjs/react-redux#977]
So I'm just starting out with react native, redux, the works. I feel like I've got basic redux under my belt well enough, but I'm getting an error I don't understand. When I click the `changeColor` button on the `DetailsScreen` it throws an error: `undefined is not an object (evaluating 'this.props.dispatch')`. I'm confused because I thought `dispatch()` came free with `connect(mapStateToProps)`. But something is wrong with this and I'm not sure what it is. Any pointers/help would be appreciated.

    ////MapviewScreen.js

    import MapView, { Marker } from 'react-native-maps';
    import React, { Component } from 'react';
    import { View } from 'react-native'
    import styles from '../styles'
    import { connect } from 'react-redux'
    
    class MapScreen extends Component {
      render() {
        const { navigation, color } = this.props
        const initialRegion = {
          latitude: 43.7370,
          longitude: -111.8338,
          latitudeDelta: 0.0922,
          longitudeDelta: 0.0421,
        }
        return (
          <View style={styles.container}>
            <MapView
              initialRegion={initialRegion}
              style={styles.map} >
              <Marker
                coordinate={initialRegion}
                onPress={() => navigation.navigate('Details')}
                pinColor={color} />
            </MapView>
          </View>
        )
      }
    }
    
    const mapStateToProps = (state) => ({
      color: state.color
    })
    
    export default connect(mapStateToProps)(MapScreen)
<br>
    
    ////DetailsScreen.js
    import React, { Component } from 'react'
    import { View, Text } from 'react-native'
    import { Button } from 'react-native-elements'
    import { connect } from 'react-redux'
    import { actionCreators } from '../redux/actionCreators'
    
    class DetailsScreen extends Component {
      changeColor() {
        this.props.dispatch(actionCreators.changeColor())
      }
    
      render() {
        const { checked } = this.props;
        return (
          <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
            <Text>Details Screen</Text>
            <Text>checked: {JSON.stringify(checked)}</Text>
            <Button
              title="Change Color"
              onPress={this.changeColor} />
          </View>
        )
      }
    }
    
    const mapStateToProps = (state) => ({
      checked: state.checked,
      color: state.color
    })
    
    export default connect(mapStateToProps)(DetailsScreen)
<br>    

    ////App.js
    import React, { Component } from 'react';
    import { Provider } from 'react-redux'
    import Drawer from './src/screens/Drawer'
    import { store } from './src/redux/storeCreator'
    
    
    export default class App extends Component {
      render() {
        return (
          <Provider store={store}>
            <Drawer />
          </Provider>
        )
      }
    }
<br>

    ////Drawer.js
    import React, { Component } from 'react';
    import { createDrawerNavigator } from 'react-navigation';
    
    import DetailsScreen from './DetailsScreen'
    import HomeScreen from './HomeScreen'
    import MapScreen from './MapScreen'
    
    export const DrawerNav = createDrawerNavigator(
      {
        Home: HomeScreen,
        Details: DetailsScreen,
        Map: MapScreen
      },
      {
        initialRouteName: 'Map',
      }
    )
    
    
    class Nav extends Component {
      render() {
        return (
          <DrawerNav />
        )
      }
    }
    
    export default Nav

**Comment by pianoman730** [comment]
I got it to not throw the error on this by adding in a `const mapDispatchToProps = (dispatch) => ({
  changeColor: () => dispatch(actionCreators.changeColor())
})`, but now I'm finding that the reducer IS being called, but it doesn't appear that my state is getting back to my map component. I'm assuming that's a different issue and I need to find issues related to that. Any direction would be great.
