### ISSUE TITLE
Revisiting issue - Accessing react component context in mapStateToProps()

### ISSUE THREAD

**Issue by iliran11** [reduxjs/react-redux#981]
I know this accessing react component like this:
`connect((appState, ownProps, ownContext) => { ... })`  
has already been discussed.

i've read the following discussion https://github.com/reduxjs/react-redux/issues/289 which concluded with this statement from @jimbolla :  

> Until the day comes that React has a fully blessed context API, adding support for it is a maintenance liability for React Redux.

However ... [Now React API Context is stable](https://reactjs.org/blog/2018/03/29/react-v-16-3.html#official-context-api).

Is it the right time to request this feature from react-redux maintainers?

**Comment by markerikson** [comment]
No, because the new context API is very different than the old context API.  Instead of a single global namespace, it's now `Provider/Consumer` pairs, and the consumer is used with a "render props" approach.  Nothing for us to do there.

**Comment by iliran11** [comment]
Hi @markerikson 
I read the v6 release notes: 

>  switched from direct store subscriptions in components, to propagating store state updates via createContext

does it actually answer the request of this issue? i'm not quite sure i understood.

**Comment by markerikson** [comment]
Yes, v6 uses `createContext` internally.
