### ISSUE TITLE
Usage of Logical AND over Ternary operator.

### ISSUE THREAD

**Issue by KirankumarAmbati** [reduxjs/react-redux#986]
In files:

**1. mapDispatchToProps.js
2. mapStateToProps.js
3. mergeProps.js**

We can use **Logical AND** instead of **Ternary Operator** to make code more readable and performant.

**Comment by markerikson** [comment]
There shouldn't be any meaningful difference in performance, and there's no real difference in readability either.  Appreciate the PR, but there's no reason to change the code at this time.
