### ISSUE TITLE
Improve documentation for areStatesEqual

### ISSUE THREAD

**Issue by mrbinky3000** [reduxjs/react-redux#993]
I am trying to limit the amount of times react-rexdux connect() fires re-renders. I've looked at the documentation here...

https://github.com/reduxjs/react-redux/blob/master/docs/api.md

... and supposedly there is a way to prevent re-renders by writing your own config option function for areStatesEqual. The problem is, my simple console.log test shows that this option never fires! Not sure what I'm doing wrong. There is not a lot of documentation on this feature, not even one example.

```javascript
export const mapStateToProps = (state, ownProps) => Object.assign({
  isMobileLayout: state.deviceWidthReducer.width < 480,
  postalCode: state.userReducer.postalCode,
  productImageGroup: state.productReducer.productImageGroup,
  productId: '05047234',
}, ownProps);

export default connect(
  mapStateToProps,
  null,
  null,
  {
    pure: true,
    areStatesEqual: (next, prev) => {
      console.log('areStatesEqual?'); // <-- THIS NEVER GETS LOGGED.
      return next.productId === prev.productId;
    },
  },
)(Product);
```
What I'm trying to accomplish:  I don't want connect() to re-render the target component at all if the productId has not changed.

**Comment by timdorr** [comment]
Are you running the render more than once? [It won't run on the first call](https://github.com/reduxjs/react-redux/blob/v5.0.7/src/connect/selectorFactory.js#L87), but will on subsequent calls.

**Comment by markerikson** [comment]
Yep - it's specifically this chunk here:

https://github.com/reduxjs/react-redux/blob/3349bd09c772d0268bef5613c531c10f93f98915/src/connect/selectorFactory.js#L74-L76

**Comment by markerikson** [comment]
As for documentation, the function _is_ documented at https://github.com/reduxjs/react-redux/blob/master/docs/api.md#connectmapstatetoprops-mapdispatchtoprops-mergeprops-options , although not in great detail:

> [`areStatesEqual`] (Function): When pure, compares incoming store state to its previous value. Default value: `strictEqual (===)`

**Comment by timdorr** [comment]
Closing in favor of #1001
