### ISSUE TITLE
Expose wrapped component in connect HOC

### ISSUE THREAD

**Issue by gerbenis** [reduxjs/react-redux#999]
The idea came based on React Router's `withRouter` HOC implementation. The mentioned component exposes wrapped component through a `WrappedComponent` member ([React Router docs sample](https://reacttraining.com/react-router/web/api/withRouter/componentwrappedcomponent)).

This would be useful for writing unit tests as we wouldn't need to use named exports for presentational components. Named exports clash with eslint's `import/no-named-as-default` rule when you try to import container components under the same name.

**Comment by timdorr** [comment]
We already do this: https://github.com/reduxjs/react-redux/blob/master/src/components/connectAdvanced.js#L266 I copied the idea from this project for React Router's withRouter :)

**Comment by gerbenis** [comment]
That's great, didn't notice it! :)
